### ISSUE TITLE
FASTBUILD_CACHE_PATH_MOUNT_POINT

### ISSUE THREAD

**Issue by joshuacox** [fastbuild/fastbuild#1003]
Is it safe to define both 

FASTBUILD_CACHE_PATH_MOUNT_POINT

and 

FASTBUILD_CACHE_PATH

It's a bit vague as to the difference between the two?  If I am on OS X or Linux should they both be defined? And, if so, should they point to the same point, or different mount points?

**Comment by ffulin** [comment]
Apologies for the unclear/missing documentation.

.FASTBUILD_CACHE_PATH (or .CachePath in Settings()) specifies the location of the cache folder on all platforms.

On Windows, this would generally be a path to and SMB share in UNC format.
On OSX and Linux, UNC paths can't directly be used, and the path must be mounted and CachePath set to a folder inside the mounted location.

.FASTBUILD_CACHE_PATH_MOUNT_POINT (or .CachePathMountPoint in Settings()) is an optional path that on OSX and Linux can be set to the location of the mount point to allow FASTBuild to check that the directory is properly mounted. It serves purely as a safety check to allow for properly configured mounts:
```
        if ( cachePathMountPoint.IsEmpty() == false )
        {
            if ( FileIO::GetDirectoryIsMountPoint( cachePathMountPoint ) == false )
            {
                FLOG_WARN( "Caching disabled because '%s' is not a mount point", cachePathMountPoint.Get() );
                return false;
            }
        }
```

**Comment by joshuacox** [comment]
ah that makes sense why I was getting an error about FASTBUILD_CACHE_PATH_MOUNT_POINT not being a mount point when I set it to something like /FASTBUILD/CACHE when I was mounting FASTBUILD as a directory and had brokerage and cache beneath it.  Now that it is its own directory can I leave it as:


```
export FASTBUILD_CACHE_PATH="/unreal/FASTBUILD_CACHE"
export FASTBUILD_CACHE_PATH_MOUNT_POINT="/unreal/FASTBUILD_CACHE"
```

Or does it need to be something like:

```
export FASTBUILD_CACHE_PATH="/unreal/FASTBUILD_CACHE/cache"
export FASTBUILD_CACHE_PATH_MOUNT_POINT="/unreal/FASTBUILD_CACHE"
```

**Comment by ffulin** [comment]
You don't actually need to set FASTBUILD_CACHE_PATH_MOUNT_POINT to anything at all. It only exists as a mechanism to help enforce/check the correct mount point setup. This is useful when you have many developers and want to make sure they mounted the network drive in the correct location.

Normally when it's set, it's set to the location you have mounted the network share and FASTBUILD_CACHE_PATH is usually a sub-directory under that.  So your second example is more what a typical setup looks like.
