### ISSUE TITLE
Stop on error when building multiple targets.

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#1008]
I want to stop as quickly as possible even when building multiple targets. It seems impossible now.

**Comment by ffulin** [comment]
I found the original task tracking this issue: https://github.com/fastbuild/fastbuild/issues/937

I've made the necessary changes to resolve this issue (https://github.com/fastbuild/fastbuild/commit/4fa331fd2b6ec136f0cc16a066ed98a20582b50e), which will be in the next release (v1.13)

The linked issue contains more details of the problem and the implemented fix.

I'll keep this issue open until v1.13 is released.

**Comment by ffulin** [comment]
v1.13 has now been released and includes these improvements.
