### ISSUE TITLE
Error in clang-cl cache

### ISSUE THREAD

**Issue by poljak181** [fastbuild/fastbuild#1015]
Hi!
It seems that I've found a bug while using cache with the **Clang-cl** compiler.
So, I've prepared a minimal reproducible example to demonstrate this error.
I used FastBuild 1.08, Clang version 15.0.7, on Windows.

Steps to reproduce:
1. Unzip the [fastbuild_clangcl_cache_pch_obj.zip](https://github.com/fastbuild/fastbuild/files/13975852/fastbuild_clangcl_cache_pch_obj.zip) into your workspace.
2. Open the **fbuild.bff** file and update the variables at the beginning according to your environment.
3. Open cmd in the directory containing the **fbuild.bff** file.
4. Do not forget to set the **FASTBUILD_CACHE_PATH** environment variable.
5. Run the command **FBuild.exe -cache -cacheverbose -showcmds -clean**. It should be OK.
6. Remove object files from the **out** directory.
7. Run the command **FBuild.exe -cache -cacheverbose -showcmds -clean** again and see something like this: `lld-link: error: could not open 'C:\workspace\test\fastbuild_clangcl_cache_pch_obj/out/main_pch.pch.obj': no such file or directory.`

This is possible fix: [fix_clang_cl_cache.patch](https://github.com/fastbuild/fastbuild/files/13975874/fix_clang_cl_cache.patch)

Pull request: https://github.com/fastbuild/fastbuild/pull/1016

**NOTE:**
There is an ability to break the build even after the fix is applied. If we only remove a.exe and main_pch.pch.obj in step 6 from **out** directory and run the command without the -clean option: `FBuild.exe -cache -cacheverbose -showcmds` we will get the same error as in step 7.
As I understand it, this happens because main_pch.pch still exists, and FastBuild doesn't check the existence of main_pch.pch.obj.

**Comment by ffulin** [comment]
Thanks for the reports and the linked PR. I've added some notes on the PR.

**Comment by poljak181** [comment]
I have updated the PR

**Comment by ffulin** [comment]
I've applied your fix in https://github.com/fastbuild/fastbuild/commit/990be48d701edd058d9a4e878abba280bc131107

This will be in the next release (v1.13). I'll keep this issue open until that version is released.

Thanks again!

**Comment by ffulin** [comment]
v1.13 has now been released and includes this fix. Thanks again for reporting the bug.
