### ISSUE TITLE
FASTBuild Error #1100

### ISSUE THREAD

**Issue by jinyoungbaek98** [fastbuild/fastbuild#1017]
I'm trying to build UE5 using FASTBuild. I have 6 workers(+@) using 10CPUs each. But I got 2 big problems. 

First, when build I'v got message "FASTBuild Error #1100". 
My build command is 'RunUAT.bat BuildGraph -target="Make Installed Build Win64" -script="Engint/Build/InstalledEngineBuild.xml" -clean -set:HostPlatformOnly=true -set:WithDDC=false'

Error log.
###
Detected build type as Windows from 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe' using search term 'Microsoft'
Using path : C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Redist/MSVC\14.38.33130 for vccorlib_.dll (MSVC redist)...
...Add an entry for MsvcCRTRedistVersion in BuildConfiguration.xml to specify a version number
FBuild Command Line Arguments: '-monitor -summary -dist -cacheread -ide -j12 -clean -config "C:\TeamCity\buildAgent\work\b99b0275e940d7\Engine\Intermediate\Build\fbuild.bff" -nostoponerror
C:\TeamCity\buildAgent\work\b99b0275e940d7\Engine\Intermediate\Build\fbuild.bff(122955,1): FASTBuild Error #1100 - Exec() - Target 'C:\TeamCity\buildAgent\work\b99b0275e940d7\Engine\Binaries\Win64\Android\UnrealEditor.modules' already defined.
Exec('Action_5941')
^
\--here
###
I tried to delete all files and rebuild again. But same Error occured.

Second, when I tried to build UE5 in localbuild (not using FASTBuild) builds are all successful. But when I use FASTBuild, build is successful but "Build: 69 Successes, 2 Failures, 32 Latest, 34 Skips". I have no idea with this problems. 

I use 6 workers but build time is the same as when I do not use FASTBuild. I hope you to figure out reasons. 
I wonder if it's because of my own problem or if there's a solution.

**Comment by ffulin** [comment]
It looks as though the Unreal integration you are using is generating an invalid bff file (with conflicting. duplicate or otherwise erroneous targets)

There are several different Unreal integrations - you'll need to ask the author of the integration you are using for help with the problems you are seeing.

**Comment by jinyoungbaek98** [comment]
Thanks for your answer.

But I use Epic Games's Unreal Engine Source code. And there is no change. 
I tried several solutions like change code or use different version of FASTBuild but nothing changed.
I don't know why... just can't use fastbuild in engine build

**Comment by ffulin** [comment]
If you are using an integration that comes with Unreal directly, you'll need to talk to Epic about that and any limitations it may have. I'm not sure what the state of Epic's integration is - I was not involved in it's development.

I'd be happy to support developers of any Unreal integration (Epic or others) to make supporting things easier or to improve FASTBuild so it's easier to support.

Given the error you created this thread for, it seems there is most likely a bug in the Unreal Build Tool's FASTBuild bff generation logic that causes the creation of duplicate targets/config (resulting in error#1100) which would need to be debugged.
