### ISSUE TITLE
Dynamic environment variable without reparsing? (DLL Hot Reload)

### ISSUE THREAD

**Issue by beepdavid** [fastbuild/fastbuild#102]
Hi, I'm currently evaluating fastbuild to replace our game engine build system. I've got everything setup and building ok but for one area.

We support runtime compiling of a game dll module which can be hot loaded while the game is being debugged in visual studio. To do this I need to be able to change the name of the game.pdb file on each dll compilation as visual studio will lock the current one.

I've got this working using and environment import to randomise the name, but doing this causes a reparsing of the .bff to occur and all dependencies to also be rebuilt. I thought this would be ok with a special dll declaration with dependencies removed for the rtc, but it also triggers a full game rebuild when you next come to build and run through visual studio (which is not going to fly)

I can't  see a solution to this at the moment other than the extra .bff dependency work mentioned in #55. Any ideas?

**Comment by ffulin** [comment]
Hello.  The rebuilding when the config file(s) or an imported environment variable changes is an unfortunate limitation of the current implementation.  It's something I'm working towards fixing in the long term, but the re-factor of all the various internals necessary to make this work reliably is a large undertaking.  While the work is well underway, it will be many releases before the work is complete and the feature can be used. :(

However, while I can't offer up an easy/proper fix on the FASTBuild side right now, there are other FASTBuild users who are supporting hot reload of DLLs in a similar way to what you've described.  The way they generally make it work is that:
a) The DLL is compiled to some normal location
b) When the game starts, it copies the DLL and PDB to another folder (keeping the same names)
c) LoadLibrary is called on the copy
d) The game watches the original dll
e) When the DLL is rebuilt, the game unloads the copy, re-copies and loads from the copy again

If I remember the details of how to make this work nicely, I believe a key part of having this working is ensuring the copy dll/pdb name still matches, which necessitates them being in another directory.

Do you think this approach could work for you?

**Comment by beepdavid** [comment]
Hi, thankyou for the detailed reply :) 

I initially thought the pdb location was hardcoded into the dll, but I can see on msdn now that if it missing at this location it will next search in the same folder as the copied dll, so that can work out great!

The copied dll's pdb will still be locked by vs if you are in a debugging season, so I will have to randomise the folder location, but as this is all done game side and non-intrusively to the .bff that is fine.

Our initial use cast for fastbuild was to have a single build setup that can be used for inside visual studio and for the runtime compile, but i'm really impressed by how much snappier building in vs feels as well. Looking forward to some extra unity build features for git users down the road.

Note to anyone else trying out runtime compiling with fast build: the LIBPATH set through vcvarsall.bat is subtly different to what is set from running through visual studio directly. If you have a batch file to call the rtc from inside vs it will be different to what vs sets for NMake use. To get around this we launch vs with the /useenv switch to prevent a rebuild from the path change

**Comment by ffulin** [comment]
Glad to hear this might work for you.

> The copied dll's pdb will still be locked by vs if you are in a debugging season, so I will have to randomise the folder location,

On this note, it might be enough to just alternate between two fixed names?  (Copy1/MyDll.dll & Copy2/MyDll.dll) for example?

**Comment by beepdavid** [comment]
the alternate names would be great, but it seems Visual Studio locks any pdb that has been loaded at least once until it is next restarted (I thought this may get fixed in vs2015, but no..)

**Comment by beepdavid** [comment]
I wanted to add some notes to this in case anyone is reading in the future:

Copying the pdb to a randomised location does indeed work (I'm using the timestamp for a folder name), but there is an issue that the original pdb file cannot remain as this will be loaded first instead of the newly copied one and lock out the next runtime compile. But if you remove it all together, then on the next debugging session if your changes have not produced a new pdb it will be missing for copy. My current solution is to make an extra renamed copy of the pdb and use that if the original is missing.

Reg pdb locking it seems vs2015 only keeps all the pdbs locked until the debugging session is complete, so there is a opportunity to clear out the temp folders in a build step somewhere.

**Comment by rickvanprim** [comment]
I would suggest using /PDBALTPATH to give a slightly name mangled name that it won't find along the way.  Ideally you could change the DLL headers after building, and then just set that value after placing it in the randomized path.  Short of that, just setting "/PDBALTPATH:MyExe_HOTRELOAD.pdb" and then renaming the PDB when you copy it there should work around it finding the original instead of the copy.

**Comment by beepdavid** [comment]
this is great thanks! saves me needing to remove the original pdb for the dll load.

**Comment by ffulin** [comment]
@rickvanprim - Great tip - that's really handy.
