### ISSUE TITLE
LightCache issue with include paths and rsp files

### ISSUE THREAD

**Issue by avudnez** [fastbuild/fastbuild#1023]
We uncovered a case where LightCache does not parse files correctly and thinks every `#include` is inexistant.

On this line, it is passed with `FinalArgs` which in our case is a single argument: the rsp file. This is with distribution, caching and lightcache enabled.
https://github.com/fastbuild/fastbuild/blob/797810f96a6c857d1b4a33af748bfe2eb721b547/Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp#L427

It's then unable to pick up include paths, and will fail to find almost any include.
This then means that the parsing is incorrect, and the dynamic dependencies of the node are empty.
We found out because we use them to print dependency files to communicate with our outer build system (Unreal), and they were only containing a single line: the .cpp file being parsed.

By using `fullArgs.GetRawArgs()` instead, the behavior seems correct.
Is that an actual error, or are we doing something wrong?

**Comment by ffulin** [comment]
This is indeed broken in exactly the way you described. Thanks for reporting this problem!

I've gone ahead and applied the fix along with some tests to cover this case: https://github.com/fastbuild/fastbuild/commit/e04f787d13dd2e16c93bce842f73ded186fb2da4

This fix will be in the next release (v1.13). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.13 has now been released and includes this fix. Thanks again for reporting the bug.
