### ISSUE TITLE
Configuration file supporting Libraby and executable

### ISSUE THREAD

**Issue by og4444** [fastbuild/fastbuild#1033]
Hi,
I want to make a generic bff file that suites all my projects.
I want to have in it something like this:

Executable( '$PROJ_APPLICATION_$.out' )
{
	Print ( 'Building Exe')
	.
	.
	.
}

Library( '$PROJ_APPLICATION_$.a' )
{
	Print ( 'Building Lib')
	.
	.
	.
}

It seems I can't do this cause if both blocks exist It will try build them both.
How can I do such a thing?
Thank you,
Ofir

**Comment by ffulin** [comment]
I see that you are printing things like "Building Exe" in your config, which makes me think you may have misunderstood how the FASTBuild config files (the bff files) work.

The bff files are not a script that is run when you compile. They are a script that defines a bunch of build rules. Later on when you compile, those rules are used to control how to compile. They are only ever evaluated when they change and the rules are kept between builds. When you print things, it's useful for debugging the generation of the build rules, but you won't see those statements come out during a build.

In your example you are defining two build targets - which one will be built depends on what you tell FASTBuild to build.
You are printing out everything you can **potentially** build.

> ** I want to make a generic bff file that suites all my projects.**

There are a few ways to structure the bff files, with different tradeoffs depending on your needs.
It's unlikely that a single configuration file can meet the needs of multiple different and non-trivial projects.

I would generally recommend something like:
a) a set off bff files to define the common build configuration (defining the compiler for example)
b) a root bff file that includes the above and also defines the matrix of build configurations you want (configs: Debug, Release  and platforms: Win32, x64 for example)
c) a bff file per-library or executable that iterates over the array of configs and adds and configuration specific to that library (for example include paths, defines or special case compiler options)

You can make the files in group c) fairly light and reduce boilerplate in two ways:
 - having additional helper logic in other bff files by leveraging [User Functions](https://fastbuild.org/docs/syntaxguide.html#userfunctions). Your example above could be put into a function if you like. Functions do have some limitations but will continue to improve over time.
 -  #include directives as pseudo-functions. These are a bit ugly and would ideally be entirely superseded by more powerful User Functions in the future, but they can be a powerful tool.

You can hoist as much or as little into the common bff files and have as much or as little in the per-project files as suits your needs.

Of course nothing stops you putting all of the above in one bff file if you really want, but for any non-trivial project that will quickly get out of hand.

In case you have not seen it already, these documents may prove to be helpful:
 - [Quick Start Guide](https://fastbuild.org/docs/quickstartguide.html)
 - [Minimal "Hello World" example ](https://fastbuild.org/docs/examples/helloworld_windows.html)

Finally, FASTBuild is built using itself. It contains bff files that roughly follow the structure I mentioned above and includes use of User Functions. It may be more complex overall than you need, as it supports a large number of platforms, build configurations and compilers, but it may prove a useful reference:
 - [Source Code](https://fastbuild.org/docs/download.html)
 
The root fbuild.bff in the root Code directory is probably the best place to start.

**Comment by ffulin** [comment]
I'm going to close this issue as I've answered as best I can for now. Please let me know if you have any followup questions.
