### ISSUE TITLE
.CompilerOptionsC  option

### ISSUE THREAD

**Issue by og4444** [fastbuild/fastbuild#1037]
Hi (@ffulin) , 
I saw in several examples that there is :
.CompilerOptions   - for compiling .cpp files.
.CompilerOptionsC - for compiling .c files.

I don't see any documantation regarding the .CompilerOptionsC .
also it doesn't seem to be used while building.
I made the following configuration:
.BaseCompilerOptions    = '-o "%2" "%1" -c'
	.BaseCompilerOptionsCpp = '-o "%2" "%1" -c'
	
	.BaseCompilerOptions    	+ ' -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 $ARCH_CFLAGS$ -lrt   --sysroot=$CROSS_LINUX_HOME$\$TARGET_SYSROOT$ -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts '
	.BaseCompilerOptionsCpp   	+ ' -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -fexceptions -std=c++11 $ARCH_CFLAGS$ -lrt   --sysroot=$CROSS_LINUX_HOME$\$TARGET_SYSROOT$ -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts '

    .CompilerOptions        = .BaseCompilerOptionsCpp
    .CompilerOptionsC       = .BaseCompilerOptions

but when I build a .c file I get:

Obj: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o
8>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe "C:\GitWS\S4_OCB\efw\Src\ECM\thisNode_ECM.c" -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -fexceptions **-std=c++11** -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts 
8>6> Process Includes:
8> - File: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o
8> - Time: 0 ms
8> - Num : 174
8>7> Obj: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o <LOCAL>
8>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe -o "C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o" "C:\Users\gal\AppData\Local\Temp\.fbuild.tmp\0x3f3eec81\core_7\0D019342\thisNode_ECM.c.i" -c -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -fexceptions -std=c++11 -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts 
8>7> **cc1.exe : warning : command line option '-std=c++11' is valid for C++/ObjC++ but not for C**

Why it doesn't use the  .CompilerOptionsC?

Another question: Why it compile twice ? 
**first time:**
Obj: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o
8>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe "C:\GitWS\S4_OCB\efw\Src\ECM\thisNode_ECM.c" -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -fexceptions **-std=c++11** -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts 
**seconed time:**
Obj: C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o <LOCAL>
8>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe -o "C:\GitWS\S4_OCB\Indigo\generatedFiles\eFW\ECM_Linux\obj\thisNode_ECM.o" "C:\Users\gal\AppData\Local\Temp\.fbuild.tmp\0x3f3eec81\core_7\0D019342\thisNode_ECM.c.i" -c -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -fexceptions -std=c++11 -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts 
8>7> cc1.exe : warning : command line option '-std=c++11' is valid for C++/ObjC++ but not for C

2nd time is with <LOCAL> with file :"C:\Users\gal\AppData\Local\Temp\.fbuild.tmp\0x3f3eec81\core_7\0D019342\thisNode_ECM.c.i"

Thank you for your help

Ofir

**Comment by og4444** [comment]
@ffulin can you please advise?

**Comment by ffulin** [comment]
**> Why it doesn't use the .CompilerOptionsC?**

.CompilerOptionsC is not a property of ObjectList or Library, so any example using that is using it for its own purposes, probably to eventually assign it to .CompilerOptions for any libraries that it wants to compile as C.

It looks like you are trying to compile C code, which means you need to not specify options that are C++ only options (like -std=c++11). If all of your code is C code, you can just set C options. If you have some code in C and some in C++, you'll need to make sure appropriate options are set for each.

**>Another question: Why it compile twice ?**

It's hard to say what's wrong with your setup from the information given, but FASTBuild usually compiles in two passes with gcc: once to preprocess the file, and a second time to do the actual compilation. Normally the first pass would contain -E to activate the preprocessor, but since your example output doesn't have that, I wonder it perhaps you are manually specifying the .PreprocessorOptions and doing so incorrectly (you don't normally need to set those at all).

**Comment by og4444** [comment]
Hi,
Thank you for your reply.
My code has a mix of C & C++ files.
How can I change the CopmilerOption during the build for each file?
Thank you,
Ofir

**Comment by ffulin** [comment]
If you have a mix of C and C++ files in the same folder/library and wish to use C or C++ specific compiler options with either, then you'll need to specify two ObjectList or Library constructs for the files in that folder/library.

For example:
```
ObjectList( 'MyLib-CPP' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.cpp' // (this is actually the default so you could omit this)
    .CompilerOptions = '...' // the options you want for the cpp files
} 
ObjectList( 'MyLib-C' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.c'
    .CompilerOptions = '...' // the options you want for the c files
} 
```
Other options (like specifying the compiler, the output dir and other things which may be needed depending on your needs) have been omitted from the example.

**Comment by ffulin** [comment]
I'm going to close this issue as I've answered as best I can. Please let me know if you have any followup questions.

**Comment by og4444** [comment]
Hi @ffulin ,
Sorry for the late response.
I'm trying your soulution .
I made 2 Object-Lists one for .c files and one for .cpp files.
I gave the Library a list of these 2 Object-lists. but I get an error that the Library doesn't have the .CompilerOptions field.
the .CompilerOptions is defined in each Object-List, but I have just one Library.
How to I solve this issue?
Thank you very much for your help.
Ofir

**Comment by ffulin** [comment]
Each ObjectList should use .CompilerOptions as shown in my example. You put the C++ options in .CompilerOptions for the "MyLib-CPP" and the C options in .CompilerOptions for the "MuyLib-C".

**> I have just one Library.**
A library can be divided into as many ObjectLists as you like to have different command line options for different sets of objects - in this case splitting the C from CPP options (assuming they require different command line options, such as -std=c++17 for the cpp files only).

**Comment by og4444** [comment]
This is what I did, I added .CompilerOptions for each Object-List, but the Library requires an .CompilerOptions as well.
If I take your example:
ObjectList( 'MyLib-CPP' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.cpp' // (this is actually the default so you could omit this)
    .CompilerOptions = '...' // the options you want for the cpp files
} 
ObjectList( 'MyLib-C' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.c'
    .CompilerOptions = '...' // the options you want for the c files
} 

I have a Library:
Library( 'all' )
	{
		.LibrarianAdditionalInputs = {'MyLib-CPP', 'MyLib-C'}
		#import PROJ_OBJS_DIR
		.CompilerOutputPath = '$PROJ_OBJS_DIR$'
		.LibrarianOutput 	= '..\..\$PROJ_APPLICATION$'
	}

I get an error:
FASTBuild Error #1101 - Library() - Missing required property 'CompilerOptions'.

Thanks,
Ofir

**Comment by ffulin** [comment]
An ObjectList compiles a list of objects.
A Library compiles a list of objects and creates a lib archive, potentially merging in other ObjectLists or Libraries in the process.

If you want to create a single .lib file you can change one of your ObjectLists to a Library():
```
ObjectList( 'MyLib-C' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.c'
    .CompilerOptions = '...' // the options you want for the c files
} 
Library( 'MyLib' )
{
    .CompilerInputPath = 'src/MyLib/'
    .CompilerInputPattern = '*.cpp' //  (this is actually the default so you could omit this)
    .CompilerOptions = '...' // the options you want for the cpp files

    .LibrarianAdditionalInputs = { 'MyLib-C' }
    .LibrarianOutput = 'output/mylib.lib'
} 
```

Alternatively you can use my initial example and have no Library() at all, and directly link the two ObjectLists into your final executable or dll. There are some subtle difference with how linking works between consuming object files and libraries which (depending on your codebase) may require one or the other or provide advantages to one approach over the other. If you are unsure of these differences and are porting an existing codebase, it's probably best to match the pattern of that code base.

**Comment by og4444** [comment]
I tried the above, it seems to build correctly the files, but had an error at the end:

Conflicting objects found for: C:\GitWS\....\xxx.o
 Source A  : C:\GitWS\....\xxx.c
 ObjectList: C:\GitWS\...\lib.a
AND
 Source B  : C:\GitWS\....\xxx.c
 ObjectList: lib.a-C
FBuild : error : BUILD FAILED: all

any suggestions?
Thank you,

**Comment by ffulin** [comment]
This error:
```
Conflicting objects found for: C:\GitWS....\xxx.o
Source A : C:\GitWS....\xxx.c
ObjectList: C:\GitWS...\lib.a
AND
Source B : C:\GitWS....\xxx.c
ObjectList: lib.a-C
```
indicates that you have two ObjectLists or LIbraries compiling the same file twice with the same destination. If you can't spot the error by examining your configuration, the [-verbose](https://fastbuild.org/docs/options.html#verbose) and [-showdeps](https://fastbuild.org/docs/options.html#showdeps) arguments may provide some insight.

**Comment by og4444** [comment]
Hi,
This is all the places the conflicted file appears in the verbose output:
Line  459: 3>2> -Build: 0 ms	C:\GitWS\S4_2976\Indigo\generatedFiles\eCommon\SpecialEventParamTypes\common_generated_enum.c
	Line  492: 3>Need to build 'C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o' (first time or dirtied)
	Line 4117: 3>7> Obj: C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o
	Line 4118: 3>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe "C:\GitWS\S4_2976\Indigo\generatedFiles\eCommon\SpecialEventParamTypes\common_generated_enum.c" -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts -I"./ " -I"../../../Indigo/generatedFiles/eiFW/FWSchema" -I"../JerichoEngine/App" -I"../JerichoEngine/App/Components" -I"../JerichoEngine/App/Hal" -I"../JerichoEngine/App/Objects" -I"../JerichoEngine/App/Other" -I"../JerichoEngine/App/Services" -I"../JerichoEngine/App/Subsystems" -I"../JerichoEngine/App/Utils" -I"../JerichoEngine/App/Stab" -I"C://TornadoVerde/target/h/arch/arm" -I"C://TornadoVerde/target/config/all" -I"C://TornadoVerde/target/config/Mcn80321" -I"../SystemCommon" -I"../engineCommon" -I"../JerichoEngine/CANopen/targetspecific" -I"../JerichoEngine/CANopen/local" -I"../JerichoEngine/CANopen/include" -I"../JerichoEngine/CANopen/generated" -I"../JerichoEngine/CANopen/drivers/shar_inc" -I"../dci" -I"../JerichoEngine/mcn3_jetlink" -I"../EventsBasics" -I"../Basics" -I"../Common" -I"../Common/Activities" -I"../Common/Components" -I"../Common/Services/CbcControl" -I"../Common/Management" -I"../Common/Services" -I"../Common/Services/Linux" -I"../Common/HAL" -I"../Services" -I"../Services/Linux" -I"../jinCommon" -I"../../../Indigo/generatedFiles/eiFW/GeneralActions" -I"../../../Indigo/generatedFiles/eiFW" -I"../../../Indigo/generatedFiles/eiFW/MainMotor" -I"../../../Indigo/generatedFiles/eiFW/ChargeRoller" -I"../../../Indigo/sdk/Infra/MWCodeGene/NONGeneratedFiles" -I"../../../Indigo/generatedFiles/eFW/COMM_Linux" -I"../../../Indigo/generatedFiles/eFW/PH" -I"../../../Indigo/generatedFiles/eFW/ECM" -I ...
	Line 4134: 3> - File: C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o
	Line 4137: 3>7> Obj: C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o <LOCAL>
	Line 4138: 3>C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\x86_64-fslcsdk-mingw32\usr\bin\arm-fslc-linux-gnueabi\arm-fslc-linux-gnueabi-gcc.exe -o "C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o" "C:\Users\gal\AppData\Local\Temp\.fbuild.tmp\0x10e85e03\core_7\8E4F70A5\common_generated_enum.c.i" -c -Wno-unused-variable -Wno-unused-function -fstack-check -funwind-tables -ftrack-macro-expansion=0 -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -O3 -lrt --sysroot=C:\LinuxCrossCompilationToolChain\yocto-arm\sysroots\armv7at2hf-neon-fslc-linux-gnueabi -pthread -Wno-endif-labels -Wno-write-strings -Wno-psabi -fmodulo-sched -fmodulo-sched-allow-regmoves -fivopts -I"./ " -I"../../../Indigo/generatedFiles/eiFW/FWSchema" -I"../JerichoEngine/App" -I"../JerichoEngine/App/Components" -I"../JerichoEngine/App/Hal" -I"../JerichoEngine/App/Objects" -I"../JerichoEngine/App/Other" -I"../JerichoEngine/App/Services" -I"../JerichoEngine/App/Subsystems" -I"../JerichoEngine/App/Utils" -I"../JerichoEngine/App/Stab" -I"C://TornadoVerde/target/h/arch/arm" -I"C://TornadoVerde/target/config/all" -I"C://TornadoVerde/target/config/Mcn80321" -I"../SystemCommon" -I"../engineCommon" -I"../JerichoEngine/CANopen/targetspecific" -I"../JerichoEngine/CANopen/local" -I"../JerichoEngine/CANopen/include" -I"../JerichoEngine/CANopen/generated" -I"../JerichoEngine/CANopen/drivers/shar_inc" -I"../dci" -I"../JerichoEngine/mcn3_jetlink" -I"../EventsBasics" -I"../Basics" -I"../Common" -I"../Common/Activities" -I"../Common/Components" -I"../Common/Services/CbcControl" -I"../Common/Management" -I"../Common/Services" -I"../Common/Services/Linux" -I"../Common/HAL" -I"../Services" -I"../Services/Linux" -I"../jinCommon" -I"../../../Indigo/generatedFiles/eiFW/GeneralActions" -I"../../../Indigo/generatedFiles/eiFW" -I"../../../Indigo/generatedFiles/eiFW/MainMotor" -I"../../../Indigo/generatedFiles/eiFW/ChargeRoller" -I"../../../Indigo/sdk/Infra/MWCodeGene/NONGeneratedFiles" -I"../../../Indigo/generatedFiles/eFW/COMM_L ...
	Line 4211: 3>Conflicting objects found for: C:\GitWS\S4_2976\Indigo\generatedFiles\eFW\COMM_Linux\obj\common_generated_enum.o
	Line 4212: 3> Source A  : C:\GitWS\S4_2976\Indigo\generatedFiles\eCommon\SpecialEventParamTypes\common_generated_enum.c
	Line 4215: 3> Source B  : C:\GitWS\S4_2976\Indigo\generatedFiles\eCommon\SpecialEventParamTypes\common_generated_enum.c


it weird because the ObjectList is supposed to build the *.c files and the Library the *.cpp files that means that this specific *.c file should be build only once in the ObjectList and not in both lists.

any idea?

**Comment by ffulin** [comment]
I can't tell from just that output what the problem might be, but the core issue seems to remain the same: you seem to have two objectlists or libraries compiling the same file.

*> If i change the order and put another file first than I get conflict on the other file, that means it not something specific with a file but something with the build configuration.*

If you had two libraries or objectlists building the same files this is what I'd expect.

If you can share more of your bff files it might be possible to spot the issue, but failing that you can try using -showdeps and -verbose to get more information about the problem. you can try building the libraries individually to reduce the amount of spam.

**Comment by ffulin** [comment]
The problem seems to be that you are listing all of the files explicitly in various libraries by doing this:
```
	#include "inputFiles.bff"
```
which is setting .CompilerInputFiles to the same thing in every place you include it.

You then attempt to set .CompilerInputPattern to filter that list, but that filtering is for use in conjunction with options like .CompilerInputPath to filter the list of dynamically discovered files. When you explicitly specify a list of files using .CompilerInputFiles that is always respected.

You can fix this in two ways:

a) (recommended) - remove your hand maintained list of files and set .CompilerInputPath to the directory/directories you want to compile. If the .c and .cpp files are mixed in those directories, continue using .CompilerInputPattern to filter them.

b) if option a) isn't suitable for some reason and you need to hand maintain the list of files to compile, split the list in inputFiles.bff into two:
```
.CompilerInputFilesCPP = { ... }
.CompilerInputFilesC = { ... }
```
and include or define that only once. Then in each Library or ObjectList where you want one or the other, set them as follows:
```
ObjectList( '$PROJ_APPLICATION_$-C'
{
    .CompileInputFiles = .CompilerInputFilesC // Compile C files
    ...
}
ObjectList( '$PROJ_APPLICATION_$.a' )
{
    .CompilerInputFiles=  .CompilerInputFilesCPP // Compile CPP files
    ...
    .LibrarianAdditionalInputs = { '$PROJ_APPLICATION_$-C' } // Merge in C objects
}
```

**Comment by og4444** [comment]
Thanks, now I understand.
I knew that I could make the option B solution, I was trying to avoid it, but it seems that I have no other option.
I will split the list.
Thank you very much for your support.
Ofir
