### ISSUE TITLE
Support for building Chromium

### ISSUE THREAD

**Issue by icew4y** [fastbuild/fastbuild#1056]
Any informaiton about how to leverage fastbuild to distribute build Chromium(Windows/Linux)?

**Comment by ffulin** [comment]
Building Chromium using FASTBuild would require creating build configuration files for FASTBuild to perform the same steps as the build system that is usually used to build Chromium (which I believe is Ninja)

The complexity of this task would depend on how complex the build rules are for Chromium.

**Comment by ffulin** [comment]
I'm going to close this issue as answered, but let me know if you have and follow up questions.
