### ISSUE TITLE
How to generate visual studio project files for fastbuild itself?

### ISSUE THREAD

**Issue by jy02140486** [fastbuild/fastbuild#1057]
I'm using 1.10
run Bin\Windows-x64\FBuild.exe from console directly, and specified some vars(VS2019_BasePath, VS2019_Version, etc.) in External\SDK\VisualStudio\VS2019.bff
somehow it just run this one although I have vs2022 installed on my machine
After it finished, no vc project files generated.
I can find a VSSolution( 'solution' ) in \Code\fbuild.bff that supposed to generate /tmp/VisualStudio/FASTBuild.sln but it seems the VisualStudio folder is never created
but the binaries are generated

what did I miss here

**Comment by jy02140486** [comment]
Figure it out, use argument 'solution'

**Comment by ffulin** [comment]
In general project files can have whatever target name you like. In the case of FASTBuild, the target is named "solution", though would probably be better named "proj" or "projects". Ideally this will be documented in a "how to build FASTBuild from source" guide in the future.
