### ISSUE TITLE
How to setup FASTBuild on my iMac.

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [fastbuild/fastbuild#109]
the website of fastbuild Quick Start Guide just for windows?There isnot for iMac?Thanks !

**Comment by ffulin** [comment]
Hello.  The documentation for OSX and Linux is somewhat lagging behind the Windows documentation, which is something I will improve over time.  Indeed, the Windows documentation is also undergoing updates.

The best advice I can offer right now is to download the source package and take a look at the FASTBuild configuration for building FASTBuild - this contains complete and working configuration for Windows, OSX and Linux.

You can download the source package from:
 - GitHub : https://github.com/fastbuild/fastbuild/releases
 - fastbuild.org : http://fastbuild.org/docs/download.html

**Comment by Shaunchenzhaojin** [comment]
I have downloaded the source package,and open the Bin > OSX-x64 > FBuild. terminal tell me that Failed to open BFF 'fbuild.bff'. Can you offer some solutions? Thx!

**Comment by ffulin** [comment]
fbuild.bff is expected to be in the current directory.  It seems like you are running witht current directory set to Bin/OSX-x64 instead of Code/

You have two options:
a) copy the FBuild exe into the Code folder (recommended)
b) add the FBuild executable path into the system path

In both cases you can then compile with the Code folder as the current directory.

**Comment by Shaunchenzhaojin** [comment]
I try the a) plan, but get the error again. Then I try the b) plan it is the end:-bash: /Users/build/Downloads/dist_v0.90/Code/fbuild: cannot execute binary file. Thanks again!

**Comment by ffulin** [comment]
The "cannot execute binary file" seems to indicate that you set the path incorrectly, perhaps to the linux version by mistake?

For option a) (the copy), just to calrify, you need to:
a) Copy the FBuild executable to Code folder
b) From a command prompt, make the Code folder the current directory
c) run ./FBuild from the command prompt

**Comment by ffulin** [comment]
Hello.  Did you manage to work what was going wrong?

**Comment by Shaunchenzhaojin** [comment]
![image](https://cloud.githubusercontent.com/assets/20035768/17281251/a0d1e022-57cd-11e6-8e10-d0cd9840ac28.png)
I just followed your steps. Then I get the error.

**Comment by ffulin** [comment]
Hello.  It looks like you are trying to execute the bff config file as an executable. You need to invoke the fbuild executable. It will discover the config file automatically when it is in the same directory.

**Comment by ffulin** [comment]
I'm going to close this issue.  Feel free to re-open it if you need more info.
