### ISSUE TITLE
Inconsistency in variable assignment from other variables and explicit values

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#113]
While working on #110 I have stumbled upon this inconsistent behaviour:
```
.TheAnswer = 'fourty two'
.X = 42
.X = 'fourty two'
.Y = 42
.Y = .TheAnswer
```
Here second assignment to .X works fine, changing its type to integer. But second assignment to .Y (which, as one could expect, should produce the same value as in .X) fails with this error:
```
/home/dummyunit/fastbuild/Code/test.bff(5,6): FASTBuild Error #1034 - Operation not supported: 'Int' = 'String'.
.Y = .TheAnswer
     ^
     \--here
```
Is this inconsistency by design? If not, which behaviour is correct: changing variable type or producing an error?

**Comment by ffulin** [comment]
Hello.  The rule so far has been "a variable cannot change type" once created.  I think your work on #110 is ok to consider as exception if we consider empty arrays to be "typeless" until assigned.

Being able to change the type of .X is a bug.  It should fail with the same error as the .Y case.

**Comment by ffulin** [comment]
With the changes you made (which are in v0.91), I believe this issue can now be resolved. Your snippet now results in:
```C++
BFF file 'C:\p4\depot\Code\fbuild.bff' has changed (reparsing will occur).
C:\p4\depot\Code\fbuild.bff(3,6): FASTBuild Error #1034 - Operation not supported: 'Int' = 'String'.
.X = 'fourty two'
     ^
     \--here
```
What do you think?

**Comment by dummyunit** [comment]
Yes, this looks good now.
