### ISSUE TITLE
Why is CONNECTION_LIMIT limited to 15?

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#124]
`#define CONNECTION_LIMIT ( 15 )
`

Is this limit based on something in the code that is known to scale badly with the number of users (e.g. N^2 algorithms); or, is this just an arbitrary number?

I ask because we have the hardware for many more workers, and a very high bandwidth network; so, if the limit is:

A.)  A "nobody should ever need more than 640k of memory" type limit, then I'll just change it. :)

B.) A practical limit, because of some n^2, n^3, or worse algorithms, then it might be worthwhile for us to investigate improving those on our end in order to raise the limit (and, it would be useful to know where the offenders live :)).

Thanks!

**Comment by ffulin** [comment]
The limit on how many workers can be effectively utilized is dependent on factors like how powerful the PC driving the build is and the throughput of the network.

The idea behind the limit of 15 is to avoid degrading build performance by increasing network chatter when we would not be able to service that many workers.

It's an entirely arbitrary limit however (tuned from what I've seen around typical performance observed with typical 8-core PCs and on a gigabit network). It's highly likely it's not optimal for all cases.

You should be able to safely change this value and see how it impacts your build performance. This value could be exposed in the Settings() of the bff, or via an environment variable file in the future if that would be useful.

**Comment by ffulin** [comment]
If you do increase this limit and see some benefits (and are willing to share), I'd love to hear about your results.

**Comment by ffulin** [comment]
I've submitted a change which exposes the worker connection limit via a new .WorkerConnectionLimit property on Settings (https://github.com/fastbuild/fastbuild/commit/f4a02361ffbb2dfe087bac706c5860bad08d6818), allowing it to be increased from the default of 15. This will be in the next release (v0.94)

**Comment by ffulin** [comment]
v0.94 has now been released and includes the new .WorkerConnectionLimit which allows this to be tweaked as desired.
