### ISSUE TITLE
Documentation bug: Executable function and LinkerLinkObjects

### ISSUE THREAD

**Issue by nil-ableton** [fastbuild/fastbuild#125]
The documentation on the website says:
```
  .LinkerLinkObjects       ; (optional) Link objects used to make libs instead of libs (default false)
```

However on FASTbuild 0.90, unless I'm mistaken, the default looks like it's `true`

**Comment by ffulin** [comment]
LinkerLinkObjects is true by default for DLL() and false by default for Executable(). This has been the case as far as I can rememeber. I checked the current source code to be sure and this behaviour is still as documented.

What behaviour have you seen that makes you say it has changed in v0.90?

**Comment by nil-ableton** [comment]
Oh, then I think my mistake came from not carefully comparing Executable() and DLL() nodes.. I simply assumed they had the same default there, and read the documentation for Executable as reference

**Comment by nil-ableton** [comment]
(I have to turn off the LinkerLinkObjects flag for some of our DLLs)
