### ISSUE TITLE
Compiler Flags for Individual Source Files

### ISSUE THREAD

**Issue by fitzymj** [fastbuild/fastbuild#128]
Currently there doesn't appear to be a way to specify compiler options for individual files.  Given the focus on Unity builds, this is somewhat expected, but I still have some scenarios where an individual file needs some specific flags.  E.g., one external cpp needs extra warnings disabled, another needs some specific macros defined during its compilation, or another needs some Android optimization flags.

Apologies if I'm missing something!

**Comment by ffulin** [comment]
Hello.

Having some files in a library that need special compilation settings is a pretty common use-case and is supported by FASTBuild, both with and without unity files.

To begin with, putting Unity aside, you can specify different compilation settings for some unique files by creating an ObjectList for those files, and excluding them from the main Library.
```C++
.SpecialFiles = { 'Code/Library/SpecialFile1.cpp', 'Code/Library/SpecialFile2.cpp' }

ObjectList( 'SpecialFiles-Obj' )
{
     .CompilerInputFiles = .SpecialFiles
     .CompilerOptions    + .SpecialCompilerSettings 
}

Library( 'NormalFiles-Lib' )
{
    .CompilerInputPath              = 'Code/Library/'
    .CompilerInputExcludedFiles     = .SpecialFiles
    .LibrarianAdditionalInputs      = { 'SpecialFiles-Obj' } // link in objs for extra files
}
```
This will build the "special files" with different settings, but still merge the obejct files into the same library.  You can have as many ObjectLists as you need to group the different sets of files.

Now bringing back Unity, it's the same idea, except you create a Unity as well as an ObjectList for each different set of files.  For example:

```C++
.SpecialFiles = { 'Code/Library/SpecialFile1.cpp', 'Code/Library/SpecialFile2.cpp' }

Unity( 'SpecialFiles-Unity' )
{
    .UnityInputPath      = .SpecialFiles
}
ObjectList( 'SpecialFiles-Obj' )
{
    .CompilerInputUnity  = 'SpecialFiles-Unity'
    .CompilerOptions     + .SpecialCompilerSettings
}

Unity( 'NormalFiles-Unity' )
{
    .UnityInputPath              = 'Code/Library/'
    .UnityInputExcludedFiles     = .SpecialFiles
}
Library( 'NormalFiles-Lib' )
{
    .CompilerInputUnity          = 'NormalFiles-Unity'
    .LibrarianAdditionalInputs   = { 'SpecialFiles-Obj' } // link in objs for extra files
}
```

In addition to listing the files explicitly, if your code has a nice structure where the "special files" are named according to some pattern, or they all live in some sub-directory, you can use the various options on Library, ObjectList and Unity to include/exclude them by this pattern or sub-directory instead. Naturally this is easier to maintain.

I hope that makes sense. Let me know if I can clarify anything.

**Comment by fitzymj** [comment]
Ah, that makes perfect sense!  I'd been thinking of ObjectList as a _replacement_ for a Library, along the lines of [CMake's OBJECT Library type](https://cmake.org/Wiki/CMake/Tutorials/Object_Library).  This seems more flexible, though, and of course using it as a component of a Library gets the desired behavior.

Thank you for the quick and thorough response!
