### ISSUE TITLE
Limited Ability to Efficiently Specify Compiler Inputs

### ISSUE THREAD

**Issue by fitzymj** [fastbuild/fastbuild#129]
I'm currently struggling a bit to efficiently handle a file-naming convention of ours.

In a few platform-specific libs, our convention is to handle platform-divergent classes roughly like this:

```
PlatformMgr.h
PlatformMgr_PC.cpp
PlatformMgr_OSX.cpp
PlatformMgr_IOS.mm
<etc.>
```

And occasionally like this:

```
Thread.h
Thread_Posix.h
Thread_Posix.cpp
Thread_Msft.h
Thread_Msft.cpp
```

When platforms are still being ported or don't support a certain feature, we use a `_Stub.cpp` implementation, like this:

```
Keyboard.h
Keyboard_Msft.cpp
Keyboard_OSX.cpp
Keyboard_Stub.cpp <-- used by iOS, Android, etc.
```

I'd like to _try_ to express that pattern somewhat idiomatically, but I can't quite work it out.  Currently the tools available to me seem to be:
- patterns to match within a folder (with option to recurse)
- list of files
- list of files to exclude
- list of folders to exclude
- patterns to exclude (Unity-only, not in Library/ObjectList/etc.)

The exclusions are checked _after_ all the inclusions, so a file in the `.CompilerInputFiles` array can't "override" an exclusion.  This prevents me from doing, say, "add `Thread_*.cpp` as an exclusion pattern on all platforms, then specialize `.CompilerInputFiles` on a per-platform basis to choose the `Thread_*.cpp` implementation I want."  In fact, the only solution I can come up with is to specialize `.CompilerInputFiles` and individually add every non-desired cpp to `.CompilerInputExcludedFiles` for each platform, which is some heavy n^2 code bloat.

I think the smallest change here to make things work for me would be to have `.CompilerInputExcludePatterns` available in Library/ObjectList/etc., and to have `.CompilerInputFiles` evaluated last (or otherwise override exclusions).  Then I could do something like:

```
.PCToolchain = [
   .CompilerInputExcludePatterns = { '*_Posix.cpp', '*_OSX.cpp', '*_Stub.cpp', '*_IOS.cpp', ... }
]

// and then when adding my library
Library('keyboardlib-PC-Debug')
{
   Using(.PCToolchain)
   .CompilerInputFiles + 'KeyboardFeatureUnsupportedOnPC_Stub.cpp'
}
```

The context of all this is that I'm giving FASTBuild a shot on a pretty large established codebase, so I'm doing my best to not rock the boat as I do it and conforming to the conventions we already have in place.  Thanks!  :)

**Comment by ffulin** [comment]
Hello

The list of files explicitly listed .CompilerInputFiles should not be subject to any filtering - they should always be used, the idea being that if you are listing them explicitly, you almost certainly don't want them filtered out.

Based on what you've described, I think you are right that the missing .CompilerInputExcludePattern (to bring it closer to functional parity with Unity) is what you'd need. The good news is that this would be fairly trivial to add - the underlying directory parsing logic (which includes the pattern filtering) is already common between the Unity and ObjectList/Library, so it's mainly just a matter of exposing this new property and passing it to the existing code.

There are two possible work-arounds I can think of right now:
a) Use Unity
 - Pro: Likely to massively speed up your compilation
 - Con: Likely to require code changes (sometimes a few, sometimes many depending on the code-base

b) Use Unity, make all your files writable on disk, and use .UnityInputIsolateWritableFiles
 - Pro: Would do exactly what you want (each file will be built individually)
 - Con: It's pretty hacky (but easily removed when .CompilerInputExcludePattern is added)

After the next release (v0.91) which will be very soon, I will look into adding the missing filtering support (for v0.92). If you wanted to try adding the support yourself before then I could point you in the right direction.

**Comment by fitzymj** [comment]
Great, thanks!  I missed the current behavior of `.CompilerInputFiles`, so I appreciate the correction on that.  I might fork this weekend and try adding that `.CompilerInputExcludePattern` support myself; I'm assuming it's adding some functionality to `DirectoryListNode` to mirror `UnityNode`.

**Comment by ffulin** [comment]
DirectoryListNode is already used by both Unity, Library and ObjectList. Unity is the only one that exposes .UnityInputExcludedPath so if you take a look at how that's getting the property and passing it to DirectoryListNode, we just need to do the same thing in ObjectListNode.

**Comment by fitzymj** [comment]
Just submitted pull request #130 for this; let me know if that looks alright!

**Comment by ffulin** [comment]
I've integrated your changes into the 'dev' branch and also into the Perforce mainline, so they will be in the next version (v0.92).  I'll keep this issue open until that release is completed.
Thanks again!

**Comment by fitzymj** [comment]
Thanks, sounds great!

**Comment by ffulin** [comment]
v0.92 has now been released and contains your enhancements. Thanks again!
