### ISSUE TITLE
Q. about include directory path and variable concatenation

### ISSUE THREAD

**Issue by nil-ableton** [fastbuild/fastbuild#132]
So far in most `fbuild.bff` I've seen compiler options are built from the top down i.e. from a general configuration and detailed in the targets.

In practice on windows this means something like:

```
.CompilerOptions = '/c "%1" /Fo"%2"'
.CompilerOptions + ' $BaseWindowsIncludeFlags$'

(...)

ObjectList('Foo')
{
    .CompilerOptions + ' /ITargetSpecificIncludeDir1'
...
    .CompilerOptions + ' /ITargetSpecificIncludeDirN'
}
```

One problem with this construction however is that base windows include directories come first and therefore resolving a filename "foo.h"

```
#include "foo.h"
```

Might end up opening a system include file.

(You can verify this with this documentation: https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx)

This happened to me recently with a file from curl called `share.h` which is also shipping in MSVC's `VC/include` directory

My only option at the moment is to move the system includes into each target instead of prepending them at the beginning of the `.bff` file, however I'm looking for other options from FASTbuild users.

**Comment by poppolopoppo** [comment]
The following idiom instead might help you :
````
.IncludeDirs = {}
.IncludeDirs + 'c:/Path/To/Visual/Include'
(...)
ObjectList('Foo')
{
    .IncludeDirs + 'TargetSpecificIncludeDir1'
...
    .IncludeDirs + 'TargetSpecificIncludeDirN'
    .CompilerOptions = ''
    ForEach( .path in .IncludeDirs )
    {
        ^CompilerOptions = ' /I"$path$" $CompilerOptions$'
    }
}
````

**Comment by nil-ableton** [comment]
Indeed it seems like it should work

**Comment by ffulin** [comment]
Another option to inject the library specific includes before the general ones is as follows:
```C++
ObjectList( 'Foo' )
{
    .CompilerOptions = '$ExtraIncludePaths$ $CompilerOptions$'
}
```

**Comment by nil-ableton** [comment]
I chose to use that latter idiom

**Comment by rickvanprim** [comment]
One issue you may run into that I found with clang (and presumably GCC), is that system includes (-isystem) always seem to get searched before normal includes (-I), regardless of the order you supply them on the command line.

**Comment by ffulin** [comment]
I certainly had problems with include path specification/search order with GCC, which I was able to resolve by using <> style includes for the problematic cast (in my case a precompiled header include).

For reference, my issue was:
http://stackoverflow.com/questions/34517709/gcc-precompiled-headers-multiple-build-configurations-and-i
And the resolution was:
http://stackoverflow.com/questions/12353429/prevent-gcc-from-searching-the-current-dir-i-option-on-include-search-path

**Comment by rickvanprim** [comment]
My above comment was related to <> includes as I never use the "" ones (to avoid relative paths).  My issue was, `clang -I "A" -I "B" -isystem "C"` will result in a search order of "C, A, B" instead of the "A, B, C" I'd expect from the command line ordering.  Using -I instead of -isystem wasn't an option either, because as I learned, -isystem suppresses any warnings in includes found via those paths, which is necessary for compiling a lot of Windows headers with Warnings As Errors turned on.
