### ISSUE TITLE
master branch (after 0.91 sync) doesn't compile

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#135]
Hello,

Some files are present in the master that create compile errors:
https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/CopyNode.h
https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/CopyNode.cpp

Those are not present in the source zip that you can download http://fastbuild.org/downloads/v0.91/FASTBuild-Src-v0.91.zip

Note that the zip contains a bunch or .bak files...
 Code/Tools/FBuild/Documentation/docs/changelog.html.bak
 Code/Tools/FBuild/FBuildCore/BFF/BFFParser.cpp.bak
 Code/Tools/FBuild/FBuildCore/FBuildVersion.h.bak
 Code/Tools/FBuild/FBuildCore/Graph/TestNode.cpp.bak
 Code/Tools/FBuild/FBuildTest/Data/TestBFFParsing/else_directive.bff.bak
 Code/Tools/FBuild/FBuildTest/Tests/TestBFFParsing.cpp.bak

Thanks!
Lambert

**Comment by ffulin** [comment]
I've fixed up the problems you've identified:
 - stale files are removed from "master"
 - a new source package is uploaded to fastbuild.org with .bak files removed

Also:
 - the v0.91 release on GitHub has been re-created without the stale files

Thanks for letting me know about these problems!

**Comment by ffulin** [comment]
I'm going to close this issue.  Let me know if you spot anything else.  Thanks again for reporting the problems.

**Comment by belkiss** [comment]
Will do, thank you!
