### ISSUE TITLE
-DLL and other args not correctly detected for MSVC

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#142]
I'm building a .dll, and multiple executables which all have to link with the dll. Unfortunately, due to FastBuilds parallel builds it's not finding the import library, due to not being yet generated. Trying to use the dll as input to `.Libraries` results in an error.

This is roughly my setup:

```
DLL('engine')
{
    .LinkerOutput = './_install/bin/engine.dll'
    .Libraries = { 'engine-c', 'engine-asm' }
    .LinkerOptions + ; omitted
}

Executable('game')
{
    .LinkerOutput = './_install/bin/game.exe'
    .Libraries = { 'game-c', 'game-asm' }
    .LinkerOptions + ' -LIBPATH:"./_install/bin"'
                   + ' engine.lib'
}
```

Which works fine, If I manually build the engine first (simply invoking `fbuild engine`) and afterwards the game (`fbuild game`), but not if I try to build all of them via an `all` alias.

Changing the libraries on `Executable('game')` to:

```
.Libraries = { 'game-c', 'game-asm', 'engine' }
```

results in the following error:

```
BFF file 'C:\Users\Arvid\workspace\engine\fbuild.bff' has changed (reparsing will occur).
C:\Users\Arvid\workspace\engine\src\game\fbuild.bff(27,1): FASTBuild Error #1005 - Executable() - Unsupported node type in 'Libraries'. (Node: 'C:\Users\Arvid\workspace\engine\_install\bin\engine.dll', Type: 'Exe')
Executable('game')
^
\--here
```

Any ideas how to properly solve this issue? [The tests seem to hint that it's possible](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildTest/Data/TestDLL/fbuild.bff#L147).

**Comment by Leandros** [comment]
Found the bug! Your parsing code is broken, and does not recognize the `-DLL' switch on MSVC, it only recognizes the '/DLL' switch.

**Comment by Leandros** [comment]
Here is a, partial, patch to fix the issues. It might, or might not work, since there is no explanation on how to build this project.

It still contains one TODO, namely fixing the `GetOtherLibsArg` function to accept proper arguments.


[fix.txt](https://github.com/fastbuild/fastbuild/files/466070/fix.txt)

**Comment by ffulin** [comment]
Hello.  You are indeed right that there are a bunch of args that are not correctly being detected when using - instead of / with the MSVC compiler.
I took a look at the diff you attached, and it seems conceptually solid.  I'll get that integrated and tested.

**Comment by ffulin** [comment]
I wasn't able to apply your change because it didn't compile, so I instead did a pass over all the MSVC args extraction and fixed all the problems.  I've submitted this fix in the dev branch (https://github.com/fastbuild/fastbuild/commit/dbdc9aa460cb32321003d02a988980a9b593fc21).  There were quite a lot of places that were broken, but they should all be fixed.  These fixes will be in the next release (v0.92).

I'll keep this issue open until the next version is released.

Thanks for your help identifying the problem!

**Comment by Leandros** [comment]
Woah, that was fast. Amazing work!

Thanks a lot for making Fastbuild, I've migrated my (arguably quite complex) Make based build system over to Fastbuild in under a day, and reduced the code tenfold and all dependencies on GNU tools (which, unfortunately, suck on Windows).

:+1:

**Comment by poppolopoppo** [comment]
Hi Franta,

Seems like you have broken the argument detection for MSVC with your recent changes : the new code is too permissive and will accepts '/anythingAfterSlashAndBeforeArg' when parsing '/Arg'.

This diff fixes the issue :
````
index 8994fc2..d5ab111 100644
--- a/Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp
+++ b/Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp
@@ -891,6 +891,13 @@ bool ObjectNode::ProcessIncludesWithPreProcessor( Job * job )
         return false;
     }

+    // Length check to early out
+    const size_t argLen = AString::StrLen( arg );
+    if ( ( token.GetLength() - 1 ) != argLen )
+    {
+        return false; // token is too short
+    }
+
     // MSVC Compiler args are case-sensitive
     return token.EndsWith( arg );
 }
````

**Comment by ffulin** [comment]
Good catch - you're totally right. I've fix the bug you found (https://github.com/fastbuild/fastbuild/commit/435ca00a52eeca6f8e4f092cc8b4b0193bfe107f) and the same one in LinkerNode.cpp.  Thanks :)

**Comment by poppolopoppo** [comment]
You're welcome,
So eager to test the bleeding edge features that I got cut ;)

**Comment by ffulin** [comment]
v0.92 has now been released and contains the fixes we talked about. Thanks again for reporting this issue.
