### ISSUE TITLE
Config paths with spaces are not passed with quotes to the subprocess

### ISSUE THREAD

**Issue by liamkf** [fastbuild/fastbuild#146]
Hi there! I've been stumbling my way through getting [msfastbuild](https://github.com/liamkf/msfastbuild) working, which attempts to build Visual Studio projects and solutions with FASTBuild, with various degrees of success getting it to work for some unusual projects... :D

It was noticed in [this bug](https://github.com/liamkf/msfastbuild/issues/3) that spaces in the -config bff path cause the args to not be passed correctly to the spawned process when used with -ide or -wrapper:

Works:
` $>fbuild -config "C:/space bees/fbuild.bff"`
Can't find "C:/space":
` $>fbuild -ide -config "C:/space bees/fbuild.bff"`

It looks like it's down to the configFile not being quoted when it gets passed along. Putting quotes around the file seems reasonable enough, which is what I've done [here](https://github.com/liamkf/fastbuild/commit/ccca403fb01c457c91105772192b15e966d56569). It's obviously not a big change, but I can also make it a pull request after we merge the visualizer changes back into the branch if you'd prefer!

**Comment by ffulin** [comment]
Your diagnosis and fix makes total sense. I'd be happy to integrate that fix as-is immediately if you like. I think it's nice to keep changes as self-contained as possible to keep track of things.

**Comment by ffulin** [comment]
Your https://github.com/liamkf/msfastbuild is pretty intriguing - it's an often requested feature and one of the few areas than Incredibuild outshines FASTBuild currently. I'd pretty much abandoned any hope of creating such a system given the crazy behaviour I've seen in Solution/Project files (things like conditionals tied to the selected project config that are only evaluated on load and not when you switch configs for example). I guess I was thinking of a perfect system, rather than one that might be able to handle enough cases to be useful. It looks like you've made some great progress!

**Comment by liamkf** [comment]
Sounds good! I caught a few places where I wasn't escaping arguments myself along the way.

Re: msfastbuild, yeah I think going for complete coverage of bizarre VS/MSBuild projects that are out there seems a ways off, but even now I think it's usable for most projects. @jairbubbles is doing a good job of kicking the tires. :) We definitely really like FASTBuild (thanks for making it!), and I think getting more people in the door with their existing projects could really help its adoption.

Once I get more of the obvious problems out of the way I'll probably post a few issues with questions/requests here as well. One that readily comes to mind is prebuild dependencies on the library/dll/executable nodes would allow prelink build events, and would also simplify the hacky 'dummy copy' we're doing in our Unreal FASTBuild file.

**Comment by jairbubbles** [comment]
I'm strongly convinced a VS plugin could really improve FB adoption. 

I look forward to the day there will be FastBuild in VS gallery:
"**FAST Build for Visual Studio**
A Visual Studio extension that allows programmer to compile C++ faster **out of the box**. With **distribution and caching**. For **free**.  With the code soure available in case you have a build issue (things which happen with commercial build accelerators)."

Well I guess when this day will come it could quickly be in the top extensions ;-)
And the cool thing is that with all the activity happening right now, this day is like next week :-D

Oh wait it seems FB is not the only to be free:
![2016-09-17 09_15_49-incredibuild extension](https://cloud.githubusercontent.com/assets/15875066/18606695/73817132-7cb7-11e6-8dce-a63992a655e8.png)
Or not:
https://www.incredibuild.com/pricing-and-terms.html
:-D

**Comment by ffulin** [comment]
@jairbubbles - I like your vision of the future :)  If FASTBuild could work out of the box on an existing VS solution in a large portion of cases, that would be nice for a lot of users.
