### ISSUE TITLE
[Question] importing Visual Studio projects

### ISSUE THREAD

**Issue by WojciechMula** [fastbuild/fastbuild#152]
Is there any program which can translate existing Visual Studio projects into FastBuild scripts? We have a great number of projects and doing manual translation would be tedious and error-prone task.

**Comment by liamkf** [comment]
Hi there! It's very early on, but [msfastbuild](https://github.com/liamkf/msfastbuild) might be worth a try for you, even just to generate the bff files to start with... :)

**Comment by WojciechMula** [comment]
@liamkf Thanks, I'm trying it now.
