### ISSUE TITLE
Typo: "No inludes" instead of "No includes"

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#157]
Exactly here: [Report.cpp:662](https://github.com/fastbuild/fastbuild/blob/9528761dbdededc82869878e76c60858614f7dcc/Code/Tools/FBuild/FBuildCore/Helpers/Report.cpp#L662)

**Comment by ffulin** [comment]
I've integrated you fix into the Perforce mainline as well as the GitHub "dev" branch. This fix will be in the next release (v0.92)

I'll leave this issue open until the new version is released.

Thanks for your contribution!

**Comment by ffulin** [comment]
v0.92 has now been released and contains a fix for this. Thanks again!
