### ISSUE TITLE
Do not remove output file of Exec node

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#165]
Currently, when the execution of an `Exec` node fails, it's FASTBuild is only reporting

    >5 Execution failed (error 1) 'C:\Some\Path\To\Log.file'

No problem with this, until you go to the location the log file should be. It's not there. After the `Exec` node is finishing execution, and notice the fail, it's either not writing the logfile or deleting it.

This is quite bad for troubleshooting, if you rely on this build-step and it suddenly fails.

And example of using `Exec` which triggers this behaviour.

```
Exec('foobar')
{
    .ExecExecutable             = './_out/bin/foobar.exe'
    ; Specifying a non-existant file will execute this step every time.
    .ExecInput                  = './_build/this-file-is-not-here'
    .ExecOutput                 = './_out/logs/foobar.log'

    .ExecArguments              = ' -v'
                                + ' ./_build/res/'
                                + ' ./_out/data'
    .ExecWorkingDir             = './'
    .ExecReturnCode             = 0
    .ExecUseStdOutAsOutput      = true

    .PreBuildDependencies       = {
        'foobar'
    }
}
```

**Comment by ffulin** [comment]
FASTBuild follows the general pattern of not leaving behind failed or incomplete files where possible, so it doesn't write the output in this case.

You should see the full stdout and stderr above the "Execution Failed" message. Are you not seeing that?

**Comment by Leandros** [comment]
Turned out there was no output to stdout/stderr, therefore I wasn't seeing anything. Thanks a lot for the information!
