### ISSUE TITLE
String Manipulation inside CompilerOptions

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#167]
Assuming I'm having an `ObjectList` which compiles files, of which the filename is representing an option I would like to pass to the compiler, how would I do that?
Currently I only have the filename, including the newly replaced file-suffix, not without.
Would be great if there were some basic string manipulation functions available, similar to `make`.

**Comment by ffulin** [comment]
At the moment, there are only two build-time substitutions supported in ObjectList (%1 for input file and %2 for output file). A more flexibly "%" syntax would certainly be useful, but implementation of this needs to be carefully considered (as does any syntax change).

Do you have a specific use-case in mind right now?

**Comment by ffulin** [comment]
Closing this old issue as there is nothing specific to action here.
