### ISSUE TITLE
Relative paths when using include and strategies for large applications

### ISSUE THREAD

**Issue by TheClassic** [fastbuild/fastbuild#169]
I'm trying to use fastbuild for a large application comprising many dlls. I would like to have a .bff file for the application that includes one .bff for each library. The .bff files would be colocated with the code for the library. This allows the libraries to be independent entities and multiple applications to use them.

application
|- application.bff
|-library a
  |-library a.bff
|-library b
  |-library b.ff

The problem I'm facing is that paths in each .bff file seem to be evaluated relative to location of the master (including) bff, and not relative to the location of the actual (included) .bff file. In other words, it seems that the paths in a .bff file need to be absolute or at least relative to whatever file includes it. This does not seem scalable. Is there a different and better way of doing what I'm trying to do or is this a potential enhancement for fastbuild? I've created a simple example here:
https://github.com/TheClassic/msfastbuildTests/tree/81abe71a6d3330dd4554959184c1dfa53f7f3e9c/projectReferences

I am aware of .CompilerInputFilesRoot, but that does not seem sufficient for my purposes, as there are potentially other relative paths in any given bff

**Comment by Leandros** [comment]
While I agree, this could be improved, you can easily solve this yourself by creating a variable inside each .bff containing the current location and prepending it to each path.

Example:

**./fbuild.bff**
    
    #include "src/libA/fbuild.bff"
    ; include more libraries
    alias('all') { .Targets = { 'libA' } }

**./src/libA/fbuild.bff**

    .Root = './src/libA'
    ObjectList('libA-src')
    {
      .CompilerInputPath = '$Root$/PathToSrc'
      ; Other options ...
    }

**Comment by ffulin** [comment]
It could be nice to add a way to retrieve the current bff path, which would avoid having to hard code the path in your BFF files. There isn't an existing construct in the syntax to extend for this, so some thought would be required to work out how to implement this nicely.

In the short term, the burden of knowing the current directory could at least be moved outside of the bff file for the library and into the parent file through the use of a variable that you maintain through the include hierarchy.

For example, a main bff like this:
```C++
.CurrentDir = 'Root/'
{
   .CurrentDir + 'Lib1'
   #include '$CurrentDir$/Lib1.bff
}
{
   .CurrentDir + 'Lib2'
   #include '$CurrentDir$/Lib2.bff
}
```
Then the included libraries could use "CurrentDir" as needed without assuming anything about their location.
```C++
// Lib1.bff

Library( 'Lib1' )
{
    .CompilerInputFiles = '$CurrentDir$/Blah'
```
Again, a way to formally support this mechanism would be better, but this could be a reasonable work-around until then.

**Comment by ffulin** [comment]
v0.97 added thebuilt-in _CURRENT_BFF_DIR_ variable but I forgot to resolve this at the time.
