### ISSUE TITLE
Basic flow control

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#175]
I wasn't missing `if` or any other basic flow controls structures, until I now want to define multiple, different types of builds.

Simple flow control, ala:

```
if .BuildType == "debug" {
    ; Do something in debug builds.
} else if .BuildType == "debugrelease" {
    ; Do something in debugrelease builds.
} else if .BuildType == "release" {
    ; Do something in release builds.
}
```

would help a lot. Currently I would have to do this by having multiple defines:

```
#define __DEBUG__
; #define __RELEASE__
; #define __DEBUGRELEASE__
```

which I then uncomment based on what build I desire.
(Alternatively, an `#elif` could also be very helpful)

**Comment by haferburg** [comment]
What's the difference? What's wrong with the solution using `#define`?

And what exactly is `; Do something in debug builds`, what do you want to do? Most of the things one might want to do can be implemented with the `."...$BuildType$..."` syntax.

**Comment by Leandros** [comment]
The `#define` solution is cumbersome and a workaround at best, forcing me to duplicate sections of config. 

Currently I'm mostly setting/changing compiler/linker flags based on buildtype and excluding/including files. 

What I just noticed, though, is that I could dynamically construct the variables based on name.

**Comment by haferburg** [comment]
I was scratching my head once how it is possible that CMake, where string processing should be one of the core strengths, doesn't have string concatenation. But instead of `a=b+c` you have to do `set(a "${b} ${c}")`. It's really a different mind set.

**Comment by ffulin** [comment]
FASTBuild could certainly use some branching/flow-control logic to improve its flexibility, but I don't think that's the right tool for multiple build configurations.

The recommended way to handle multiple build configurations is something along these lines:
```C++
.DebugConfig =
[
     .Config = 'Debug'
     .Defines = '/DDEBUG'
     .Optimizations = ' /Od'
]
.ReleaseConfig =
[
     .Config = 'Release'
     .Defines = '/DRELEASE'
    .Optimizations = '/O2'
]
ForEach(.Config in .Configs)
{
   Using( .Config )

    Library( 'Lib-x86-$Config$' )
    {
         .CompilerOptions = '"%1" /Z7 /nologo /c /W4 /WX'
                                       + ' $Defines$'
                                       + ' $Optimizations$'
    }
}
```
Using this style of configuration it's possible to support many configuration types, platforms or even compiler versions.

**Comment by Leandros** [comment]
Yes, I settled with:

```
.BuildType = 'Debug'

.FlagsDebug = '/DDEBUG'
.FlagsRelease = '/DRELEASE'
.Flags = .'Flags$BuildType$'

.CompilerOptions = '"%1" /Fo"%2" /c'
                 + ' $Flags'
```

Works equally well, and is easy to configure.
