### ISSUE TITLE
.CompilerInputFilesRoot does not seem to work

### ISSUE THREAD

**Issue by TheClassic** [fastbuild/fastbuild#176]
I expect the following input to work. It works if I specify the full path to independent.cpp (which is d:\ClearCaseStorage\msfastbuildTests\projectReferences\independent\independent.cpp). Am I using it wrong?  In addition, removing the trailing slash when specifying CompilerInputFilesRoot causes fbuild to crash (Windows)

```
ObjectList('Action_0')
{
	.Compiler = 'msvc'
	.CompilerOutputPath = "Debug\"
	.CompilerInputFiles = { 'independent.cpp' }
	.CompilerInputFilesRoot = 'd:\ClearCaseStorage\msfastbuildTests\projectReferences\independent\'
	.CompilerOptions = '"%1" /Fo"%2" /c /ZI /nologo /W3 /WX- /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _USRDLL /D INDEPENDENT_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Fp"Debug\independent.pch" /Fd"Debug\vc120.pdb" /Gd /analyze- /errorReport:queue  /FS /TP'
}
```

> d:\ClearCaseStorage\msfastbuildTests\projectReferences>fbuild -clean -config independent\independent.vcxproj_Debug_Win32.bff
> 7> Obj: D:\ClearCaseStorage\msfastbuildTests\projectReferences\Debug\independent.obj
> 7> PROBLEM: D:\ClearCaseStorage\msfastbuildTests\projectReferences\Debug\independent.obj
> independent.cpp
> c1xx : fatal error C1083: Cannot open source file: 'D:\ClearCaseStorage\msfastbuildTests\projectReferences\independent.cpp': No such file or directory
> 7> Failed to build Object (error 0x2) 'D:\ClearCaseStorage\msfastbuildTests\projectReferences\Debug\independent.obj'
> FBuild: Error: BUILD FAILED: all
> Time: 0.052s

This example is available https://github.com/TheClassic/msfastbuildTests/tree/InputFilesRootTest/projectReferences/independent

**Comment by ffulin** [comment]
Apologies for the lack of documentation here that has caused your confusion. .CompilerInputFilesRoot is is special property used to specify the root path to be used when FASTBuild is generating obj filenames from cpp files names. It is normally not needed - it's for the special case where a project contains mutliple source files with the same name and FASTBuild generated conflicting obj names.  It doesn't relate to the folder in which to find the cpp files you list.

Generally, to specify files, you can either:
a) list them relative to the root bff path
b) have FASTBuild discover them by wildcard using .CompilerInputPath

It's strongly recommended that you avoid explicitly listing files and find them with .CompilerInputPath as this means you won't need to edit your build configuration every time you add/remove a file. For your example, that might look like this:
```C++
ObjectList( 'Action_0' )
{
    .CompilerInputPath = 'projectReferences\independent\'
```
If you really do need to list the files explicitly for some reason, you can do this:
```C++
.RootPath = 'projectReferences\independent\'
ObjectList( 'Action_0' )
{
    .CompileInputFiles = { '$RootPath$/independent.cpp' }    
```

> In addition, removing the trailing slash when specifying CompilerInputFilesRoot causes fbuild to crash (Windows)

It definitely should not crash :)  I'll investigate that.

**Comment by ffulin** [comment]
I've extended the tests to add coverage for the CompilerInputFilesRoot property (https://github.com/fastbuild/fastbuild/commit/f9c6a8485e9c20716403db0aa6b60b586f63237c). Sadly, I was not able to reproduce the crash you reported (omitting the trailing slash).  I also tried to use the Action_0 snippet you provided (removing the trailing slash) but I still could not repro the crash you mentioned.

Is there any additional info you can provide about the crash you saw?

Also, did my explanation of the behaviour of .CompilerInputFilesRoot make sense?

**Comment by TheClassic** [comment]
Sorry. When I have some time I'll see if I can provide additional information or steps to reproduce.
