### ISSUE TITLE
Option for FBuildWorker to allow sleeping

### ISSUE THREAD

**Issue by nre-ableton** [fastbuild/fastbuild#183]
It seems that FBuildWorker prevents the system from sleeping, which makes sense as the default behavior in most use-cases. However, for ad-hoc build farms, laptops, etc, it would be nice if this behavior could be overridden in some way so that the system power settings were not affected by FBuildWorker.

**Comment by ffulin** [comment]
I'm definitely open to making the worker play nicely with power settings, though I'm not sure what it is exactly that would be keeping the PC from sleeping as it currently stands (CPU usage?  Listening on the network?)

Ideally it seems the behaviour of the worker would be changed so that if it's idle it doesn't interfere with sleep settings. I'm open to suggestions on how to work out what behavioural change is needed!

**Comment by nre-ableton** [comment]
@ffulin Forgive me, I haven't actually looked at the source of `FBuildWorker` yet and I assumed that this was by design. I have a feeling that network traffic is keeping it alive, but I can't verify that at the moment. I'll play around with `FBuildWorker` and `powercfg.exe` and see why it is preventing sleep.

**Comment by ffulin** [comment]
I tried to make sure that when idle, the FBuildWorker would use close to no CPU, but apart from that I didn't focus any time on the overall behaviour so it's quite possible some tweaks might resolve the problem.

When the worker is set to "When Idle" it will periodically wake from sleep to evaluate system CPU usage (every 100ms) to see if it should work or not. This could be one area to investigate.

On the network side of things, there should only be an active network connection with traffic when builds are in progress.  When no builds are in progress, the worker should just be listening on a port. 

It raises some interesting questions about what the correct behaviour should be.  In any case, if you do look into it, let me know what you find :)

**Comment by nre-ableton** [comment]
Upon further examination, I don't think that FBuildWorker is at fault here. Closing unless I find further evidence to the contrary.
