### ISSUE TITLE
Alias function regression in dev branch ?

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#188]
Since db3b752e3cffd52d2a663430b6f01ce0b3163077 Alias nodes can't target nodes that are not a file, despite being previously allowed.
This is most likely a regression, since the commit is supposed to only expose "PreBuildDependencies" to various nodes.

The problem can be reproduced with this simple BFF : 
````
RemoveDir( 'Purge-A' ) { .RemovePaths = 'A' }

Alias( 'Purge' )
{
    .Targets = { 'Purge-A' }
}
````
Producing this error while parsing : 
````
FASTBuild Error #1103 - Alias() - '.Targets' ('Purge-A') is a 'RemoveDirNode', which does not describe a file.
Alias( 'Purge' )
^
\--here
````

Could you please confirm that this behavior wasn't intended ?

Thanks !

**Comment by ffulin** [comment]
Hello.  This is indeed a regression which impacts Alias() .Targets and also .PreBuildDependencies generally. Coincidentally I noticed this today also.

I've submitted a fix (https://github.com/fastbuild/fastbuild/commit/600564273f56d31928b9f3432cdcbba1d8dc76f2) and added some tests to prevent future regressions. Thanks for reporting it!

**Comment by poppolopoppo** [comment]
Thanks for fixing it ;)
