### ISSUE TITLE
Building arrays by aggregation

### ISSUE THREAD

**Issue by G4m4** [fastbuild/fastbuild#190]
Hello, I've been trying to find out how to build arrays by aggregating elements and can't figure it out.

The typical usage is a follows:
First, this is the vcxproj generation from fbuild.bff in the FastBuild tree:
```
VCXProject( 'UpdateSolution-proj' )
{
    .ProjectOutput              = '../tmp/VisualStudio/Projects/UpdateSolution.vcxproj'
    .ProjectFiles           = { '.\fbuild.bff' }
    .ProjectBasePath            = '.\'

    .GenerateProjectsCommands =
    [
        .ProjectBuildCommand        = 'cd ^$(SolutionDir)\..\..\Code\ &amp; fbuild solution -vs'
        .ProjectRebuildCommand      = 'cd ^$(SolutionDir)\..\..\Code\ &amp; fbuild solution -vs -clean'
    ]

    .ProjectX86Debug        = [ Using( .ProjectX86Debug )       Using( .GenerateProjectsCommands ) ]
    .ProjectX86Profile      = [ Using( .ProjectX86Profile )     Using( .GenerateProjectsCommands ) ]
    .ProjectX86Release      = [ Using( .ProjectX86Release )     Using( .GenerateProjectsCommands ) ]
    .ProjectX64Debug        = [ Using( .ProjectX64Debug )       Using( .GenerateProjectsCommands ) ]
    .ProjectX64Profile      = [ Using( .ProjectX64Profile )     Using( .GenerateProjectsCommands ) ]
    .ProjectX64Release      = [ Using( .ProjectX64Release )     Using( .GenerateProjectsCommands ) ]
    .ProjectX86ClangDebug   = [ Using( .ProjectX86ClangDebug )  Using( .GenerateProjectsCommands ) ]

    .ProjectConfigs = { .ProjectX86Debug, .ProjectX86Profile, .ProjectX86Release,
                        .ProjectX64Debug, .ProjectX64Profile, .ProjectX64Release,
                        .ProjectX86ClangDebug, .ProjectX86ClangProfile, .ProjectX86ClangRelease }
}
```

As we generally already have a .Configs_Windows_MSVC holding relevant variables, hopefully this could be rewritten as:
```
VCXProject( 'UpdateSolution-proj' )
{
    .ProjectOutput              = '../tmp/VisualStudio/Projects/UpdateSolution.vcxproj'
    .ProjectFiles           = { '.\fbuild.bff' }
    .ProjectBasePath            = '.\'

    .GenerateProjectsCommands =
    [
        .ProjectBuildCommand        = 'cd ^$(SolutionDir)\..\..\Code\ &amp; fbuild solution -vs'
        .ProjectRebuildCommand      = 'cd ^$(SolutionDir)\..\..\Code\ &amp; fbuild solution -vs -clean'
    ]

    // How to initialise to the proper type?
    .ProjectConfigs = {}
    ForEach( .Config in .Configs_Windows_MSVC )
    {
        ."Project$Platform$$Config$"        = [ Using( .Project$Platform$$Config$)       Using( .GenerateProjectsCommands ) ]

        // "Array Add"?
        .ProjectConfigs + {  ."Project$Platform$$Config$" }
    }
}
```

At the moment, as far as I know arrays of structs are not immutable but I can't figure how to add elements to them, and above all else I have no idea about how to properly initialise the empty array initially so it holds the right type.
This would allow a nice code reuse as everything is already known at this stage.

**Comment by G4m4** [comment]
Thinking about it, this is a more general issue of programmatically building variables; as this is usually done within a scope such as ForEach(), exposing it to the outer scope is not straightforward.

Is this something you plan to support, or maybe this kind of explicit declaration is a design choice? 
Thanks!

`
.Configs = [ "Debug", "Release" ]
.Platforms = [ "x86", "X64" ]
ForEach( .ConfigName in .Configs)
{
  ForEach( .PlatformName in .Platforms)
  {
    // Define e.g. .ConfigX64Release
    ."Config$PlatformName$$ConfigName$" =
    [
      .Config = .ConfigName
      .Platform = .PlatformName
    ]
  }
}
// .ConfigX64Release is not defined
`

**Comment by poppolopoppo** [comment]
> Variables can be pushed to the parent last used parent scope using the ^ prefix
http://fastbuild.org/docs/syntaxguide.html#scoping

:)

**Comment by G4m4** [comment]
I've seen that indeed but it only works for variables that have already been declared previously (as the example states).

Besides by looking at the parsing code as it is now there is probably another issue, I believe that constructed variables cannot be exposed.
In BFFParser::ParseVariableName(), PerformVariableSubstitutions() is only called in the case of a "regular" variable declaration; if we're trying to expose a variable to the outer scope it doesn't try to build it and fails as the first character of this variable is a quote in our case.

**Comment by ffulin** [comment]
You are correct that in order to use the ^ operator, you need to declare the variable first. The reason for this is that FASTBuild needs to know what scope you the variable should live at.  For example:

```C++
// Should Z end up here?
{
    // or here?
    {
        // or here?

        ForEach(.X in .Y)
        {
            ^Z + .X
        }
    }
}
```

As for your second point, (about it not working for constructed variables), I'm not sure I completely understand what you mean. Any chance you could clarify, or perhaps provide a small example that you expect should work but doesn't? (Then I can tell you if it's a bug or not :) )

**Comment by dummyunit** [comment]
> I have no idea about how to properly initialise the empty array initially so it holds the right type.

Empty arrays are typeless, first element that you add to them determines their type. Here is an example that populates array using a loop (both for strings and structs):
```
.Values = { "foo" "bar" "baz" }

.A1 = {}
ForEach(.X in .Values) { ^A1 + "prefix_$X$" }
ForEach(.X in .A1) { Print(.X) }

.A2 = {}
ForEach(.X in .Values)
{
        .TmpStruct = [ .Val = "$X$_suffix" ]
        ^A2 + .TmpStruct
}
ForEach(.X in .A2)
{
        Using(.X)
        Print(.Val)
}
```

I also recommend looking at the tests for [arrays](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildTest/Data/TestBFFParsing/arrays.bff) and [scope](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildTest/Data/TestBFFParsing/parent_scope.bff) to see other valid syntax.

**Comment by G4m4** [comment]
Thank you for both your answers, it makes the whole syntax much clearer!

For the record this is the kind of declaration I posted earlier, now usable:
```
.ConfigsPlatforms = {}

.Configs = { "Debug", "Release" }
.Platforms = { "x86", "X64" }
ForEach( .ConfigName in .Configs)
{
  ForEach( .PlatformName in .Platforms)
  {
    // Define e.g. .ConfigX64Release
    ."Config$PlatformName$$ConfigName$" =
    [
      .Config = .ConfigName
      .Platform = .PlatformName
    ]
    ^ConfigsPlatforms + ."Config$PlatformName$$ConfigName$"
  }
}
// Here we have .ConfigsPlatforms = { .Configx86Debug, .Configx86Release, .ConfigX64Debug, .ConfigX64Release, }
```
