### ISSUE TITLE
Documentation in repo

### ISSUE THREAD

**Issue by VennGrayDog** [fastbuild/fastbuild#191]
Hi,

Is it possible to put documentation on fastbuild syntax and functions into this depot?
It will be easier to track changes in fastbuild language and also will make possible to access documentation while offline.
Or is it already in downloadable format somethere?

Thanks,
Vitalii.

**Comment by rickvanprim** [comment]
Documentation is in the depot under /fastbuild/Code/Tools/FBuild/Documentation/...

James

**Comment by VennGrayDog** [comment]
Thanks!
