### ISSUE TITLE
Output compilation commands in compile_commands.json

### ISSUE THREAD

**Issue by Ryp** [fastbuild/fastbuild#193]
There are tools to get the compile commands out of fastbuild, like the `-showcmds` or external tools that substitute as a compiler to get the flags used by each source file, but nothing is really built in to do that.

I think this could be a great addition, being used to CMake's `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` that does exactly that, and is compatible with some clang-based tools.

**Comment by ffulin** [comment]
Hello.  This would certainly be possible to add as a feature, although some build steps (those managed internally by FASTBuild) would not be captured. For example, the generation of project files or unity files does not invoke any external tools. Perhaps that's fine, depending on your use-case.

**Comment by Ryp** [comment]
Usually this is useful for knowing what command was used to compile which source file, I don't think generation of sln's or unity objects really fall into that use case, but I could be wrong (or at least this wouldn't be very useful to me). That's what I'm interpreting form http://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by ffulin** [comment]
Support for the compile_commands.json was added in https://github.com/fastbuild/fastbuild/pull/436 and integrated. Version 0.98 contains this new feature (I forgot to close this issue when that version was released).
