### ISSUE TITLE
Include parser won't work with LLVM windows cl.exe

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#206]
While testing LLVM for windows, which comes with an handy wrapper cl.exe able to translate MSVC options for clang, I found that my files had no include dependencies detected by fastbuild.

http://llvm.org/builds/

After a quick debugging it turns out LLVM wrapper ain't outputting CRLF but LF, despite correctly handling /showIncludes. So LLVM is detected as MSCL (as expected since the binary name matches) but the include parser will skip early if it can't find any CR.

**Comment by poppolopoppo** [comment]
I added the pull request #207 which solves this issue.

**Comment by ffulin** [comment]
Good find. This will be a good bug to fix.

**Comment by missmah** [comment]
I wonder if this is tangentially related to the issue I just ran into? Android Clang builds and Emscripten builds don't seem to detect include dependencies properly. Changing a header file which is #included from a source file being built does not trigger a rebuild of that source file with FastBuild.

Related, should I create a pull request for Emscripten support? (sorry for hijack on this question)

**Comment by ffulin** [comment]
@missmah It seems likely that clang builds could be broken in other situations as well.

In terms of Emscripten, I'm not really familiar with it but I'd be open to integrating support for it if that's useful. Perhaps open a new issue if you want to have some back and forth about it?

**Comment by Leandros** [comment]
Clang itself is broken. I've encountered a similar issue on OS X, using clang to build,
I have opened an LLVM bug a few weeks ago, but it seems to be ignored to date: https://bugs.llvm.org/show_bug.cgi?id=31984

**Comment by ffulin** [comment]
@Leandros - Interesting. Is the specific bug in that case because the include is on the very first line?

**Comment by Leandros** [comment]
@ffulin I don't think so, since modifying the attached script by adding multiple more `#include`s / `#define`s before the file still produces the bug.
`-frewrite-includes` is seriously broken in clang. It's not documented anywhere, either. 


```
#!/bin/sh -x

LLVM_BIN=/usr/bin

cat <<EOF > test.c
#define FOO
#define BAR
#include <stdint.h>
#include <stdio.h>
#include <stdatomic.h>
#include <stdlib.h>

int main(void)
{
    volatile atomic_long i = 0;
    return 0;
}
EOF

$LLVM_BIN/clang test.c -std=c11 -E -frewrite-includes > test.e.c
$LLVM_BIN/clang test.e.c -std=c11
```

**Comment by ffulin** [comment]
The fix for this has been integrated and will be in the next release (v0.95)

**Comment by ffulin** [comment]
v0.95 has now been released and includes the fix mentioned above. Thanks again for reporting and fixing this issue!
