### ISSUE TITLE
.SolutionBuildProject isn't working

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#217]
We have some BFF configuration which looks like (below); however, in Visual Studio 2015 R3, the generated solution does not have any projects selected for build under any configurations, so CTRL+SHIFT+B doesn't work. We can manually select projects; but, it was my understanding that .SolutionBuildProject should have done this for us. I would have expected that project (and only that project) to be selected for build under each configuration? Are we missing a step?

```
// Project to compile everything
VCXProject( 'All-proj' )
{
	.ProjectOutput		= '$ProjectsPath$\All.vcxproj'
	.ProjectFiles		= { '.\fbuild.bff' }
	.ProjectBasePath	= '.\'
}
```

```
// Visual Studio Solution
//------------------------------------------------------------------------------
VSSolution( '$VSSolution$' )
{
	.SolutionOutput			= 'Insightful_Dev.generated.sln'
	.SolutionProjects		= { 'All-proj', 'UpdateSolution-proj', }
	.SolutionBuildProject	= 'All-proj'

	// ... continued ...
}
```

**Comment by missmah** [comment]
Okay, on a hunch, I found a workaround:

```
// Project to compile everything
VCXProject( 'All-proj' )
{
	.ProjectOutput		= '$ProjectsPath$\All.vcxproj'
	.ProjectFiles		= { '.\fbuild.bff' }
	.ProjectBasePath	= '.\'
	**.Platform			= 'x64|x86|Android-ARM|Android-ARM64|HTML5|x86Clang' // Needed SolutionBuildProject**
}
```

Adding .Platform with the hash of all the platforms to All-Proj works. And I'll just create a for loop which will automatically hash the platforms together, which works.

The caveat is this:
I needed to create Platforms for each project type and put them inside MSBuild's platform definitions (C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms). And I've done this for VS14, but I haven't done it for VS15 yet, and in this case, VS15 hangs trying to open the configuration manager.

It also means that Configuration x86-Debug only auto-builds in platform x86. Ideally, we would then drop all the permutations of configurations (i.e. x86-Debug, x86-Development,, etc.) in favor of just listing the actual configurations (e.g. Debug, Development) in the configurations drop-down. I wonder whether this will just work, or if there's some gotcha here... will investigate more...

**Comment by ffulin** [comment]
Indeed SolutionBuildProjects should set the active projects. It might be that there is a problem with some of the more exotic "platforms" you are using. In particular, Visual Studio makes it look like the platform string on the solution can be anything, but in reality it only supports very specific strings which I think you noted map to the files in the Platforms folder.

On most projects, I tend to leave the platform as x86 regardless of the actual platform, and bake the platform into the configuration.  This allows a lot more flexibility and avoids the problems with specific props files. The project selection ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/11589403/24229767/7e947790-0f38-11e7-8b50-5761293b1088.png)

**Comment by missmah** [comment]
The workaround worked well - and the exotic platforms are also working well for us - though of course they required additions to MSBuild. But it's nice to have the dropdowns in VS mean what they always meant in non-FastBuild builds. So I'd say this wasn't really a bug - just maybe it wasn't immediately clear what was required to make it work.

**Comment by ffulin** [comment]
It's definitely not ideal that VS treats that platform in this magic way, yet gives the impression that you can name them however you want.

With the two work-arounds (your and mine) I'm thinking that there is nothing more to do. What do you think about closing this issue?

**Comment by missmah** [comment]
Agreed, and agree that this can be closed.
