### ISSUE TITLE
Integer arithmetics

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#22]
Hi,

The following code is not accepted by BFF parser :
````
.Count = 0
.Count + 1
Print( .Count )
````
Output :
`````
fbuild.bff(2,8): FASTBuild Error #1027 - Cannot concatenate <Int> to <Any> for Variable '.Count'.
.Count + 1
       ^
       \--here
````
The code of `BFFParser::ParseVariableDeclaration()` checks that :
````c++
else if ( ( openToken >= '0' ) && ( openToken <= '9' ) )
{
	if ( concatenation )
	{
		Error::Error_1027_CannotConcatenate( operatorIter, varName, BFFVariable::VAR_ANY, BFFVariable::VAR_INT );
		return false;
	}
````
Is there a particular reason to forbid integer concatenation ?

**Comment by ffulin** [comment]
No reason it can't be supported - there simply wasn't a use case for it to date.

Coincidentally, support for:
```C++
Print( .Var )
```
has been added in the Perforce mainline for release in v0.84. As opposed to:
```C++
Print( "$Var$" )
```

**Comment by poppolopoppo** [comment]
Cool, I always find myself writing `Print( .Var )` like you saw :)

Handling integer additions might be good in the future, but I have not a real usage for it : I just tried to count included projects in a .bff file.

**Comment by kylawl** [comment]
I don't want to derail things too much since we're pretty happy with FBuild already. But it seems like more are more procedural features are making their way in. What was the motivation for a custom language over something like Lua/LuaJIT?

**Comment by ffulin** [comment]
There are a few reasons I chose to create a domain specific language.

I wanted to:
 - tailor the syntax to the problem space
 - limit the syntax to things that avoid creating ambiguous or unparallelizable dependencies or even crazier things like non-deterministic dependencies
 - avoid licensing complications with 3rd party libraries or frameworks
 - avoid code size bloat and/or the inability to have a single stand-alone executable
 - be type safe
 - be fast

In the end, especially now as the syntax is nearing some level of maturity (still more to do for sure), I think it's the right long-term choice.

**Comment by kylawl** [comment]
That's fare, 

thanks

**Comment by ffulin** [comment]
Integer arithmetic was implemented as part of https://github.com/fastbuild/fastbuild/pull/117 and will be in the next release (v0.91)

**Comment by ffulin** [comment]
v0.91 has been released which includes this change.  Thanks again for your contribution!
