### ISSUE TITLE
.PreprocessorOptions option is no longer recognized in ObjectList in 0.93

### ISSUE THREAD

**Issue by nre-ableton** [fastbuild/fastbuild#221]
It seems that the `.PreprocessorOptions` option broke in 0.93, and this option is no longer recognized. I suspect that the breakage occurred in commit 372b7ad, but that's just a guess since I don't know the FASTBuild codebase that well. ;) At any rate, I suspect that it was broken in that refactoring and only partially reimplemented using the new reflection system.

**Comment by ffulin** [comment]
It does appear this has broken in v0.93. In the internal refactoring you linked to, it looks as though the option is still recognized by ObjectListNode/LibraryNode, but it's no longer passed to the individual objects as they are created.

**Comment by ffulin** [comment]
I've fixed the regression and added some test coverage to help prevent this in the future. The fix has been submitted in the dev branch (https://github.com/fastbuild/fastbuild/commit/849f8dfc5fe736c66731441ec95bce03cdda59f0) and will be in the next release (v0.94).  I'll keep this issue open until a new version is released.

**Comment by ffulin** [comment]
v0.94 has now been released and includes the fix for this regression.
