### ISSUE TITLE
Restarting of workers occasionally fails builds (error 0x1)

### ISSUE THREAD

**Issue by ClxS** [fastbuild/fastbuild#223]
We've had this occur a few times over the past 6 months:

> 8> Obj: Z:\PROJECTNAME\UE4\Engine\Intermediate\Build\Win64\UE4Editor\Development\Engine\Module.Engine.25_of_37.cpp.obj

...

> -> Obj: Z:\PROJECTNAME\UE4\Engine\Intermediate\Build\Win64\UE4Editor\Development\Engine\Module.Engine.25_of_37.cpp.obj <REMOTE: WORKERNAME>

...

> PROBLEM: Z:\PROJECTNAME\UE4\Engine\Intermediate\Build\Win64\UE4Editor\Development\Engine\Module.Engine.25_of_37.cpp.obj
PROBLEM: C:\Users\FB_WOR1\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1002\Module.Engine.25_of_37.cpp.obj
Module.Engine.25_of_37.cpp
Failed to build Object (error 0x1) 'C:\Users\FB_WOR1\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1002\Module.Engine.25_of_37.cpp.obj'

(FYI, the compiler used is the VS2015 Update 3 cl.exe)

I've checked with the people whose machines caused the error and in each case they restarted their machine around the time the build failed.

Our temporary hack to stop this is to alter the Client to always flag any error which contains "error 0x1" as a system error.

**Comment by ffulin** [comment]
A fix for this issue (https://github.com/fastbuild/fastbuild/commit/7f4189260f676787679f8f9fbb1258fb04b2e6de) will be in the next release (v0.96). I'll leave this issue open until that version is released.

Sorry for the lack of response on this ticket until now!

**Comment by ffulin** [comment]
A version containing a fix for this issue has now been released (v0.96).
