### ISSUE TITLE
Use older glibc on Linux

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#225]
FASTBuild requires a glibc 2.15 or higher, which is often not available for slightly older systems (as an example, Debian 7 only has 2.14, and was only released in 2013).
Likely related to #66.

**Comment by ffulin** [comment]
I'm certainly open to supporting older kernel versions, but I've not seen a way to target older kernel versions from newer versions of Linux. It does seem that statically linking glibc might be a way to increase compatibility, but it's not something I've had a chance to try.

**Comment by Leandros** [comment]
Since I've stumbled upon this again, one rather easy solution would be to statically link musl, instead of dynamically linking glibc (glibc has stopped supporting static linking).

**Comment by ffulin** [comment]
I'm not super excited by the idea of depending on a third party library to avoid this problem. It seems (as per #66, the best fix might be to switch the official builds to an older Linux version. The question then becomes "how far back is reasonable to support/worth supporting?"

**Comment by Leandros** [comment]
I wouldn't consider Musl to be a third-party library. Musl is the standard libc for numerous Linux distributions. It's one of the major contenders to glibc.

**Comment by ffulin** [comment]
> I wouldn't consider Musl to be a third-party library.

Fair enough :) I guess "external" library might be a better way to put it.

**Comment by ffulin** [comment]
Looking into this a little bit more, it seems we only really depend on anything meaningful in glibc 2.6, with the exception of these two functions:

 - memcpy
 - __fdelt_chk

I think both of those dependencies could be avoided with some effort (implementing or --wrap magic for the memcpy and undefining the symbols enabling the "fortify source" runtime checks).

**Comment by Leandros** [comment]
You could get around linking glibc dynamically (or musl statically) by loading `memcpy` via `dlsym`. Since `dlsym` is ignoring all the embedded symbol versioning, you should be able to build on a linux with a newer glibc and still deploy to older glibc's.

**Comment by dummyunit** [comment]
> memcpy
> __fdelt_chk
> I  think both of those dependencies could be avoided with some effort  (implementing or --wrap magic for the memcpy and undefining the symbols  enabling the "fortify source" runtime checks).

I have tried to remove these dependencies and came up with this:
* Dependency on `__fdelt_chk` can be removed by building with `-U_FORTIFY_SOURCE`.
* We can force compiler to link to the old `memcpy` implementation by injecting this line into all translation units: `__asm__(".symver memcpy,memcpy@GLIBC_2.2.5");`

With these changes (plus some minor changes in tests) I was able to run CoreTest and FBuildTest on CentOS 6.5 mentioned in #398. CoreTest run without failures, in FBuildTest only 2 tests have failed: TestBuildFBuild and TestDeepGraph, both use FASTBuild source code and GCC 4.4.6, which comes with CentOS 6.5, can't deal with C++11.

I have pushed these changes into [`glibc_2_6` branch](https://github.com/dummyunit/fastbuild/commits/glibc_2_6) in my fork. If this approach is acceptable a can open a PR for it.

**Comment by ffulin** [comment]
@dummyunit Thanks for taking a look. I'm not particularly worried about the tests compiling or working for the older OS. The ideal state is just that the regular fbuild binary is a little bit more portable.

I took a look at your changes - I'll look into making those in the dev branch - no need to make a PR. Thanks again.

**Comment by ffulin** [comment]
I've changed the way fbuild is compiled (https://github.com/fastbuild/fastbuild/commit/db78492682d8a9619208dc4c8880df5cfe6bb9ab) such that it now only requires glibc 2.6. This change will be in the next release (v0.96). I'll keep this issue open until then.

Thanks again @dummyunit !

**Comment by ffulin** [comment]
A version containing with the described change has now been released (v0.96).
