### ISSUE TITLE
FASTBuild will always rebuild file with #line directives

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#228]
If a file contains `#line` directives, FASTBuild will always rebuild the file. 
The problem is likely related to clang, since it appears to only happen with clang on macOS/Linux. Windows + MSVC doesn't have the issue.

From the `-verbose` logs, it seems like FASTBuild considers the files mentioned in `#line 1 "foo.c"` directives to be dependencies.
You can reproduce the problem by using this file inside a FASTBuild project:

```
#line 1 "missing.c"

int foo = 5;
```

FASTBuild output with verbose will reveal it:

```
-Build: 0 ms    /Users/arvidgerstmann/workspace/private/cc/src/foo.c
-Build: 0 ms    /Users/arvidgerstmann/workspace/private/cc/missing.c
Need to build '/Users/arvidgerstmann/workspace/private/cc/_build/src/foo.o' (dep missing: '/Users/arvidgerstmann/workspace/private/cc/missing.c')
```

`missing.c` doesn't exist, though. It's only mentioned in `#line` (and, in fact, fastbuild will not try to compile it as well).

**Comment by ffulin** [comment]
FASTBuild uses the #line directives seen in the pre-processed output to discover dependency information. If you inject your own #line directives, it will see those as dependencies.

Can you modify whatever process you have that creates these #line directives to have properly formed paths (i.e. that match the behaviour of the compiler)?

**Comment by Leandros** [comment]
The `#line` directives are generated internally by FASTBuild if I use it with `clang`. I can't change that.

**Comment by ffulin** [comment]
FASTBuilds parsing of #line directives either expects paths relative to the working directory, or full paths (the two types I've seen from the supported compilers). I think it would be tricky to differentiate file-relative vs working-dir relative to support the example you've provided without a significant performance hit (we'd have to check files on disk for existence).

Is it possible to alter the behaviour of re2c so it provides full paths or working-dir relative paths?

**Comment by Leandros** [comment]
> Is it possible to alter the behaviour of re2c so it provides full paths or working-dir relative paths?

Yes, I've went with the simple solution of simply disabling the #line directives, which solved it.

**Comment by ffulin** [comment]
Glad to hear you found a solution!

**Comment by ffulin** [comment]
Far too late to address your original issue, but https://github.com/fastbuild/fastbuild/pull/685 should allow you to turn directives back on if you desire. It has been integrated and will be in the next release (v1.00)
