### ISSUE TITLE
MSVC absolute include arguments being stripped by remote workers

### ISSUE THREAD

**Issue by lantictac** [fastbuild/fastbuild#230]
The workaround for #105 appears to have introduced a regression for Recode as it leads to absolute /I args being stripped by remote workers (local compilation preserves the abs includes).

It looks like the fix is to place the continue within the `if ( isFullPath == false ) {}` block, rather than outside of it.

Let me know if you need any further details.

**Comment by ffulin** [comment]
This is a very silly bug - you're right about the continue being in the wrong spot.  This will replace relative includes with full paths, while leaving full paths as-is (instead of accidentally stripping them). Thanks for the bug report!

**Comment by ffulin** [comment]
I've submitted a fix into the dev branch (https://github.com/fastbuild/fastbuild/commit/d835a2c7f66aea794fa83fab0c8b967709baf097). This fix will be in the next release (v0.94). I'll leave this issue open until that version is released.

Thanks for reporting the bug!

**Comment by ffulin** [comment]
v0.94 has now been released and includes the fix for this issue.
