### ISSUE TITLE
.ClangRewriteIncludes option for Compiler is not recognized

### ISSUE THREAD

**Issue by nre-ableton** [fastbuild/fastbuild#232]
The new `.ClangRewriteIncludes` introduced in 0.93 doesn't seem to work. I have tried using this option in the compiler definitions, but I still see `-E -frewrite-includes` at the end of all C++ build commands.

Could this be related to #221?

**Comment by ffulin** [comment]
The bug you linked relates to a property not being correctly copied from the ObjectListNode to each ObjectNode, but in this case, the flag is stored on the Compiler object.

I did a quick sanity check of the code and I don't see any obvious problems. Are you able to paste the Compiler() section from your bff file here so I can see if that yields any clues?

**Comment by nre-ableton** [comment]
So the problem was on my end -- caused by a combination of an error in the BFF file and also using the incorrect version (I still need 0.92 because of the bug in `.PreprocessorOptions` in 0.93). Anyways, I just re-tested this with 0.93 and it seems to be fine. Sorry for the noise!
