### ISSUE TITLE
.ProjectInputPathsExclude broken recently?

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#236]
I've never succeeded at getting `.ProjectInputPathsExclude` to work properly.

Core.bff defines this:
`.ProjectInputPathsExclude   = '$ProjectPath$\CoreTest\'`

And I've tried:
`.ProjectInputPathsExclude = '$MetaProjectName$\r14\'`
`.ProjectInputPathsExclude = '$MetaProjectName$/r14/'`
`.ProjectInputPathsExclude = 'r14/'`
`.ProjectInputPathsExclude = 'r14'`

etc...

Still, the r14 folder and all its subfolders are put into the vcxproj (in this case, taking 19 seconds). If you haven't guessed, this is the ~5gb Android NDK folder. :)

Is anyone else having this issue?

Thanks!
Layla

**Comment by ffulin** [comment]
As far as I know, exclusion is working correctly and has not changed in v0.93. The FASTBuild source code uses this property to exclude the CoreTest files from the Core project for example, and that is working.

Note that the exclusion path (as with all FASTBuild paths) is relative to the root .bff file.

So for example:
```C++
    VCXProject( '$ProjectName$-proj' )
    {
        .ProjectOutput              = '../tmp/VisualStudio/Projects/$ProjectName$.vcxproj'
        .ProjectInputPaths          = '$ProjectPath$\'
        .ProjectBasePath            = '$ProjectPath$\'

        // Exclude Tests
        .ProjectInputPathsExclude   = '$ProjectPath$\CoreTest\'
```

**Comment by ffulin** [comment]
@missmah Did you end up resolving this issue? Please let me know either way so that we can close this issue or investigate further. Thanks!

**Comment by ffulin** [comment]
I'm closing this old issue. Feel free to re-open if you want to continue investigating.
