### ISSUE TITLE
Does FastBuildWorker have a maximum number of cores?

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#237]
Does FastBuildWorker have a hard-coded maximum number of cores? (I'll check the code later, but this just happened):

It works fine on our 64-thread build machine, and lists all 64-cores. Strangely, on our new 72-thread build machine, it only shows half the cores (and defaulted to 4 cores!):

![image](https://cloud.githubusercontent.com/assets/10825214/25584669/f0018fe4-2e64-11e7-8e38-e1017d588f63.png)

**Comment by missmah** [comment]
Just to show that this machine does indeed have 72-threads:

![image](https://cloud.githubusercontent.com/assets/10825214/25584702/0f8542e8-2e65-11e7-8979-eaf9c6c64720.png)

**Comment by missmah** [comment]
Oh the bug gets worse - Even locally, it's only building with half the threads!

![image](https://cloud.githubusercontent.com/assets/10825214/25584782/696fa7f8-2e65-11e7-849f-54d7fdc9d5b5.png)

**Comment by missmah** [comment]
Nevermind, the bug appears to be in Windows somewhere:
The environment variable NUMBER_OF_PROCESSORS = 36

**Comment by ffulin** [comment]
I think the issue comes from it being a multi-socket system. Without explicit code support for multiple physical CPUs, a process can only run one one "NUMA group".

Windows presumably sets NUMBER_OF_PROCESSORS to the number on one physical CPU to prevent applications from over-creating threads if they don't have explicit multi-socket support. In fact, if NUMBER_OF_PROCESSORS was 72, FASTBuild would create 72 threads, but they would all be constrained to the one physical CPU , which would actually degrade overall performance.

It might be possible to add support for multi-socket systems, though I'm not sure how involved that would be.

**Comment by missmah** [comment]
It's curious, though - we have more than 10 multi-socket systems in the office, and this is the first one to show this behavior.

In-fact, our existing build server has 4 sockets and a total of 64 hardware threads, and NUMBER_OF_PROCESSORS reports 64, and FastBuild _seems_ to run okay (performance seems to be about what you'd expect)...

**Comment by ffulin** [comment]
It might be that the 64 logical core limit alone is the issue, rather than the multi-socket (I assumed they were both a factor). i.e. it seems it is purely > 64 CPUs which requires application support, not multi-CPU per-se, as described in this MS whitepaper: https://msdn.microsoft.com/en-us/library/windows/hardware/dn653313(v=vs.85).aspx

**Comment by missmah** [comment]
This is such a disappointing design decision for Windows to have made. It would be better to have a boolean on the Win32 API for whether to 'autoscale' (as compilers should be able to) or to use this explicit node API. But alas, that's neither here nor there since we don't control Microsoft's decisions.

It seems like FastBuild definitely needs > 64 core support one way or another. The simplesimple option may be to allow multiple sub-processes to be launched? So each could scale to 64 cores? But the native way seems more optimal and in some ways less complex (not needing to handle error, message and monitor info passing between multiple processes and all the related complexity)...

Do you have any ideas on the best implementation? And timing for when it might happen? Or ways we might help?

**Comment by ffulin** [comment]
From reading the whitepaper, it's not 100% clear to me whether using CreateRemoteThread to spawn threads on the other processor group would isolate them in their own memory space, or if it's just a potential performance concern. The whitepaper implies that they are isolated, when it talks about dlls being in their own memory space, so if that's true, that would make parallelizing FASTBuild itself across multiple groups a massive change.

I can think of a potentially simpler alternative though:

if FASTBuild just spawned a thread for each logical core, while they would all be restricted to one processor group, the processes they spawn (the compiler for example) presumably would not be. The FASTBuild threads are idle the vat majority of the time, so while this naive approach might not technically be optimal, I think it might actually end up being pretty close. 

We could test this initial behaviour just by setting the NUMBER_OF_PROCESSORS environment variable to be 74 and see what happens.  Best case, the compilers will utilize all cores across both processor groups. Worst case the launched compilers inherit the affinity and we'd need to change the CreateProcess call (which doesn't seem too hard).  In either case, the only remaining work would then be to remove use of the environment variable to detect the number of CPUs.

**Comment by missmah** [comment]
That sounded (and mostly still sounds) like a pretty awesome theory. So I made a batch file where I do:
SET NUMBER_OF_PROCESSORS=72

But, then when I ECHO %NUMBER_OF_PROCESSORS%, I still get 36!

It seems that this environment variable is somehow protected from modification. Looks like I might have to make the change in C++ in fastbuild (e.g. hardcode to 72 temporarily) then run the test.

**Comment by ffulin** [comment]
As a really quick test, you can also run FASTBuild with -j64 (it's capped at 64 as a sanity check) at least that would show if it generally works.

**Comment by missmah** [comment]
I ended up writing the code to fix this in Env.cpp before I saw your message about -j64.

Some preliminary results:

With -j36 [47.7s]:
![image](https://cloud.githubusercontent.com/assets/10825214/25653107/74218e32-2fb9-11e7-9da4-9b3ed30208c1.png)

With 72 threads (via new NUMA-aware auto-detect in Env.cpp) [43.6s]:
![image](https://cloud.githubusercontent.com/assets/10825214/25653169/ae83c126-2fb9-11e7-85c6-b37122a2a0c7.png)

So, a small improvement, but far from the ~50% improvement I would have expected.

Things I noticed:
1. Sometimes the 72-thread version loads all cores to 100% in Task Manager. The 36-core version does not.
2. Sometimes the 72-thread version "stalls" and seems to only load 1 or 2 threads for a few seconds.
  2.a.) This seems to happen most often while building PCHs (even though monitor shows a PCH being built on each core)...
3. The 36-thread version also seems to "stall" to one core while building PCHs, even though monitor shows all cores active. Curious...
4. The same build on a 16-thread Haswell-E machine (same architecture) loads the CPU 100% the whole time with no stalls and takes [1m9s]. Curious to see such higher efficiency on fewer cores.
![image](https://cloud.githubusercontent.com/assets/10825214/25653415/c28cbf82-2fba-11e7-955a-5034626a395f.png)
5. The 16-thread Haswell-E machine using -j8 takes [1m17s]:
![image](https://cloud.githubusercontent.com/assets/10825214/25653480/03fde432-2fbb-11e7-83e5-fd67ebdafbfa.png)
5.a.) It appears that using all the hyper-threads on the system only gains about 10-12% on Haswell-E?

**Comment by missmah** [comment]
Using -j64 on the 72-thread machine improved performance again slightly to [41.8s]:
![image](https://cloud.githubusercontent.com/assets/10825214/25653592/85e1cf68-2fbb-11e7-91bd-05f24081033c.png)

Cores were rarely loaded to 100% and the stalls were still there (quite often). During the stalls, the processor clocks down to idle clocks, and appears to take a second or two to recover afterwards. Without these stalls, it seems like we would save ~10s from the build.

Even a build of 31.8s would be surprisingly slow based on this hardware configuration.

The 16-thread Haswell-E has 4400MHz * 16 =  70,400 AggregateMhz
The 72-thread Haswell-E has 2700MHz * 72 = 194,400 AggregateMhz

In theory, if CPU-bound, the 72-thread machine should be ~2.76x faster. They both have Samsung 960 PRO NVme drives with very high IOPS, and both have quad-channel DDR4. Though the dual-socket system has twice as much available memory bandwidth if threads are distributed across sockets.

I can make a PR for the changes to support the actual number of logical cores in the system via Env.cpp changes. It seems like there are likely still some performance bottlenecks worth sorting out, though...

**Comment by missmah** [comment]
Updating SSD Firmware achieved a time of [39.7s] on 72-threads:
![image](https://cloud.githubusercontent.com/assets/10825214/25654479/2d94b808-2fbf-11e7-9759-a4a93454b65e.png)

**Comment by missmah** [comment]
To answer the question about whether or not the msbuild/clang/etc processes get distributed across NUMA Nodes, the answer is an unequivocal yes. Both nodes spike in utilization in Resource Monitor during a build:

![image](https://cloud.githubusercontent.com/assets/10825214/25655473/f44cfae8-2fc2-11e7-92a3-74dd5a071853.png)

They also both visibly dip together during the "stalls" I mentioned previously.

**Comment by missmah** [comment]
I don't know what changed (I ran a native UE4 build just before running this build), but that build I just pasted the Resource Monitor image of seemed to "stall" less than previous builds, and the total build time was [29.9s] - getting much closer to the 25s theoretical scaling factor of this system versus the 16-thread system (yay!):

![image](https://cloud.githubusercontent.com/assets/10825214/25655521/21ceab1a-2fc3-11e7-86a9-24be1576b5b1.png)

**Comment by missmah** [comment]
Given the scaling is now much closer to the theoretical ideal for this 72-thread machine vs. the 16-thread machine, possibly this Env.cpp change is worth submitting a PR for, after all.

**Comment by missmah** [comment]
Added PR https://github.com/fastbuild/fastbuild/pull/239 :)

**Comment by ffulin** [comment]
Your changes (https://github.com/fastbuild/fastbuild/pull/243) have been integrated into the Perforce mainline and will be in the next release (v0.94). I'll keep this issue open until that version is released. Thankyou once again!

**Comment by ffulin** [comment]
v0.94 has now been released and includes the changes to allow >64 cores for x64 Windows (and >32 cores for x86 Windows)

**Comment by pkxpp** [comment]
> From reading the whitepaper, it's not 100% clear to me whether using CreateRemoteThread to spawn threads on the other processor group would isolate them in their own memory space, or if it's just a potential performance concern. The whitepaper implies that they are isolated, when it talks about dlls being in their own memory space, so if that's true, that would make parallelizing FASTBuild itself across multiple groups a massive change.
> 
> I can think of a potentially simpler alternative though:
> 
> If FASTBuild just spawned a thread for each logical core, while they would all be restricted to one processor group, the processes they spawn (the compiler for example) presumably would not be. The FASTBuild threads are idle the vast majority of the time, so while this naive approach might not technically be optimal, I think it might actually end up being pretty close.
> 
> We could test this initial behaviour just by setting the NUMBER_OF_PROCESSORS environment variable to be 72 and see what happens. Best case, the compilers will be spread across both processor groups. Worst case the launched compilers inherit the affinity from FASTBuild and we'd need to change the CreateProcess call (which doesn't seem too hard). In either case, the only remaining work would then be to remove use of the environment variable to detect the number of CPUs and query the fancier new API.

I have two cpus.And FBuildWorker can read the right logic cores(176).But when compiling, only half cores is using.So I think CreateProcess call maybe in the same processor group.

**Comment by ffulin** [comment]
This is one of those things I can only theorize about since I don't have access to a machine with that many cores (spread over what I assume it more than 2 NUMA nodes?). If you are able to build FASTBuild from source and debug it, with any luck a change could be made to make it work properly.

On a related note, I'd certainly be interested to know how well FASTBuild scales to that many cores.
