### ISSUE TITLE
[First Time User] fbuild detecting only cpp files

### ISSUE THREAD

**Issue by ajeet-virus-bit** [fastbuild/fastbuild#241]
Hi All,

Sorry if it's very naive query, but I really need help.

I downloaded sample implementation from official website. main.cpp 

I was compiling it and all thing was fine. but as soon I changed file extension to ".c" the it throws below error

_

No files found to build 'HelloWorld-Lib'
FBuild: Error: BUILD FAILED: HelloWorld
Time: 0.517s

_

I am using Visual Studio 2005.

Can you please help me in this issue? I am stuck here

**Comment by ajeet-virus-bit** [comment]
My BFF File

// HelloWorld
//------------------------------------------------------------------------------

// Windows Platform (VS 2013 Compiler, Windows 7.1A SDK)
//------------------------------------------------------------------------------
.VSBasePath         = 'C:\Program Files (x86)\Microsoft Visual Studio 8'
.WindowsSDKBasePath = 'C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0'

// Settings
//------------------------------------------------------------------------------
Settings
{
    .Environment    = { "PATH=$VSBasePath$\Common7\IDE\;$VSBasePath$\VC\bin\",
                        "TMP=C:\Windows\Temp",
                        "SystemRoot=C:\Windows" }
}

// X86 ToolChain
//------------------------------------------------------------------------------
.Compiler           = '$VSBasePath$\VC\bin\cl.exe'
.CompilerOptions    = '"%1"'           // Input
                    + ' /Fo"%2"'       // Output
                    + ' /Z7'           // Debug format (in .obj)
                    + ' /c'            // Compile only
                    + ' /nologo'       // No compiler spam
                    + ' /W4'           // Warning level 4
                    + ' /WX'           // Warnings as errors
.Linker             = '$VSBasePath$\VC\bin\link.exe'
.LinkerOptions      = ' /OUT:"%2"'     // Output
                    + ' "%1"'          // Input
                    + ' /WX'           // Warnings as errors
                    + ' /NOLOGO'       // No linker spam
                    + ' /DEBUG'        // Keep debug info when linking
                    + ' /NODEFAULTLIB' // We'll specify the libs explicitly

// Include paths
//------------------------------------------------------------------------------
.BaseIncludePaths   = ' /I"./"'
                    + ' /I"$VSBasePath$/VC/include/"'
.CompilerOptions    + .BaseIncludePaths

// Library paths
//------------------------------------------------------------------------------
.LibPaths           = ' /LIBPATH:"$WindowsSDKBasePath$\Lib"'
                    + ' /LIBPATH:"$VSBasePath$\VC\lib"'
.LinkerOptions      + .LibPaths

// HelloWorld
//------------------------------------------------------------------------------
ObjectList( 'HelloWorld-Lib' )
{
    .CompilerInputPath  = '\input\'
    .CompilerOutputPath = 'Out\'
}

Executable( 'HelloWorld' )
{
    .Libraries          = { "HelloWorld-Lib" }
    .LinkerOutput       = 'Out\HelloWorld.exe'
    .LinkerOptions      + ' libcmt.lib'     // Std Lib (Multi-Threaded, Static, Release)
                        + ' kernel32.lib'   // Kernel functions
}

// All
//------------------------------------------------------------------------------
Alias( 'all' ) { .Targets = { 'HelloWorld' } }

**Comment by ffulin** [comment]
Hello.

The ObjectList and Library use the *.cpp extension by default. You can modify this to find other files as follows:
```
ObjectList( 'MyObjectList' )
{
    .CompilerInputPattern = '*.c'
```

**Comment by ajeet-virus-bit** [comment]
Thanks ffulin
