### ISSUE TITLE
Multiple 'Usings' in the same scope stomp previous using

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#247]
So in a setup like below, I would expect the following to be printed:

[ Foo, Bar, SecondFooBar, ThirdFooBar, FinalFooBar ]

instead I get: 

[ ThirdFooBar, FinalFooBar ]

Is this a bug or are we doing something wrong?

```
.string_array = {}

.FooBar =
[
 .string_array 	+ 'Foo'
				+ 'Bar'
]

.SecondFooBar =
[
	.string_array + 'SecondFooBar'
]

.ThirdFooBar = 
[
	.string_array + 'ThirdFooBar'
]

Using( .FooBar )
Using( .SecondFooBar )
Using( .ThirdFooBar )

.string_array + 'FinalFooBar'

Print( .string_array )
```

**Comment by ffulin** [comment]
Hello.  The behavior of Using you describe is as intended. Think of using as a way to store a bunch of assignments which you can insert later on. If you want to concatenate propeties within structures before use, you can use this pattern:
```
.StructA =
[
   .String = 'Hello'
]
.StructB =
[
   .String = ' there!'
]
.StructC = .StructA + .StructB

Using( .StructC )
Print( .String )
```
This should output:
```
Hello there!
```

**Comment by kylawl** [comment]
Cool, thanks.

Is that struct concatenation behavior with + documented? 

I can't seem to find it.

**Comment by ffulin** [comment]
I thought there was some documentation for that, but it seems there isn't :( I've added some really basic documentation to the Struct section of the Syntax Guide (https://github.com/fastbuild/fastbuild/commit/779c6373dc0b0c6392f651c4eb26e5849d3742a6)

**Comment by ffulin** [comment]
v0.94 has now been released which includes the improved documentation.
