### ISSUE TITLE
Linker error : unresolved external symbol

### ISSUE THREAD

**Issue by kavinnkumarr** [fastbuild/fastbuild#258]
I'm getting below errors , even though i included all the libraries and additional dependencies :
**error LNK2001: unresolved external symbol <function name>
error LNK2019: unresolved external symbol <function name>** 

Any idea on how to fix this?

**Code Snippet:**
.VSBasePath         = 'C:\Program Files (x86)\Microsoft Visual Studio 8'
.WindowsSDKBasePath = 'C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0'

.LinkerOptions      = ' /OUT:"%2"'     // Output
                    + ' "%1"'          // Input
                    + ' /WX'           // Warnings as errors
                    + ' /NOLOGO'       // No linker spam
                    + ' /DEBUG'        // Keep debug info when linking
                    + ' /NODEFAULTLIB' // We'll specify the libs explicitly

.LibPaths           = ' /LIBPATH:"$WindowsSDKBasePath$\Lib"'
                              + ' /LIBPATH:"$VSBasePath$\VC\lib"'
			      + ' /LIBPATH:"$VSBasePath$\VC\PlatformSDK\Lib\AMD64" ' //Addl dependencies
			      + ' libcmt.lib'     // Std Lib (Multi-Threaded, Static, Release)
                              + ' kernel32.lib'
					
.LinkerOptions      + .LibPaths

**Comment by JPLemelin** [comment]
You can use arguments `-showcmds` of fbuild.exe to see the linker command.
With the signature of symbol you will be able to identify which lib is missing.

[What is an undefined reference/unresolved external symbol error and how do I fix it?](https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix)

**Comment by ffulin** [comment]
The snippet you send looks legit generally speaking, so it's likely that you are just missing a dependency on the link line. Note that the /NODEFAULTLIB means you must list everything explicitly. Right now you are only linking the kernel and the C standard library, and while you can definitely create a valid exe with just those (or even less) it's very likely you need more things (like the C++ standard library). If you can provide the link error including the symbol name, I might be able to help more.

**Comment by ffulin** [comment]
@kavinnkumarr Did you end up resolving this issue?  Please let me know so we can close this issue.

**Comment by ffulin** [comment]
Closing old issue.
