### ISSUE TITLE
Handle .sln file directly from fastbuild

### ISSUE THREAD

**Issue by KQ7WysXR24tyHK1S** [fastbuild/fastbuild#263]
Reference: https://github.com/liamkf/msfastbuild

Integrating msfastbuild into fastbuild makes it more flexible.

**Comment by ffulin** [comment]
There are currently no plans to integrate this functionality into FASTBuild. Visual Studio projects are incredibly complicated and don't behave consistently in many cases, so supporting every use-case would require a massive effort.

**Comment by ffulin** [comment]
For now, the plan is to not try to integrate msfastbuild or equivalent functionality into FASTBuild itself. I'm going to close this issue as resolved for now. Feel free to re-open if you need more info.
