### ISSUE TITLE
Website seems to be offline

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#266]
The website seems to be offline.

**Comment by ffulin** [comment]
I took a look when I first got the notification of this, and the site was up for me. I've since tested it from multiple locations on multiple devices without issue. Perhaps there was a transient problem?

**Comment by Leandros** [comment]
Yes, seems to be up again. I did check with an external service if it wasn't just my internet connection, and it was reported as offline, too. Might've just been a temporary hiccup.

**Comment by ffulin** [comment]
Probably a temporary outage somewhere along the way as you say.

I definitely appreciate the heads-up though - good to check it's not offline because I forgot to do something :) !
