### ISSUE TITLE
system() in processes spawned by Exec

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#267]
I wanted to run a Lua script, in a process spawned by the FASTBuild function `Exec`, but I couldn't spawn any child processes with `os.execute()` (which is basically a very thin wrapper over `system()`).

Any ideas why this might happen?

**Comment by ffulin** [comment]
I can't think of any specific reason why this wouldn't work. I don't know of anyone using lua with FASTBuild specifically, but there are users using scripting languages like Python and having no problems launching sub-processes from withing those systems.

The only two things that spring to mind as possibly related are the working dir and the environment. Perhaps those are setup in such a way that is causing problems?

**Comment by ffulin** [comment]
@Leandros Did you end up with a resolution for this issue?

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.
