### ISSUE TITLE
Copy()'ing same file, into different locations

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#274]
If I'm trying to `Copy()` the same file, into different destinations, I'm getting the following error:

```
BFF file 'C:\Users\leandros\workspace\redacted\fbuild.bff' has changed (reparsing will occur).
C:\Users\leandros\workspace\redacted\build\redacted.bff(32,5): FASTBuild Error #1100 - Copy() - Target 'C:\Users\leandros\workspace\redacted\_out\bin\redacted.dll' already defined.
    Copy('redacted-dll-$Arch$')
    ^
    \--here
```

You can circumvent this detection by using `CopyDir()` instead, presumably because it cannot create a dependency graph and must assume it might get dynamically created files. Might slow down the build a little.

**Comment by JPLemelin** [comment]
The name of `Copy` was already used before.

**Comment by Leandros** [comment]
That's indeed the case, unfortunately doesn't fix the problem.

**Comment by ffulin** [comment]
The title of this issue talks about 2 source locations to 1 destination, but the description talks about 1 source and 2 destinations. I presume (given the error) that the title is right and the description is wrong. (Let me know if that's not the case).

FASTBuild doesn't allow you to define two different ways to build the exact same target. This is a deliberate design choice, because:
 - what if they both try to build at the same time? Which one would be copied? Best case the result is undefined
 - this is usually a configuration error (typo on some configuration that should be uniquified per build config for example)
 - if you ask FASTBuild to build something (copy or otherwise), and it was possible to define two ways to do that, which one should it use?

**Comment by Leandros** [comment]
The title was my original assumption, which turned out to be incorrect. The body is correct.

**Comment by ffulin** [comment]
Ah, in that case, you can definitely copy the same source file to two different places via two uniquely named Copy() steps. They need to be unique for the same reason every target needs to be unique: If you asked FASTBuild to "build" that node, it wouldn't be clear which copy it should do if there was more than one defined.

**Comment by Leandros** [comment]
I don't know what is happening, but I can reproduce it on my project, although not yet in an isolated project with just the bug.
I'm trying to copy some dll's into my build folder after the build is complete:

```
ForEach(.Config in .Configs)
{
    Using(.Config)
    Copy('redacted-dll-$Config$')
    {
        .Dest = '_out/$Config$/bin'
        .Source = {
            'extern/Win64/redacted/dll/redacted1.dll'
        }
    }
}
```

and the code above works absolutely perfect, until ...

```
ForEach(.Config in .Configs)
{
    Using(.Config)
    Copy('redacted-dll-$Config$')
    {
        .Dest = '_out/$Config$/bin'
        .Source = {
            'extern/Win64/redacted/dll/redacted1.dll'
            'extern/Win64/redacted/dll/redacted2.dll'
            'extern/Win64/redacted/dll/redacted3.dll'
            'extern/Win64/redacted/dll/redacted4.dll'
        }
    }
}
```

(notice the addition of more files).
It now breaks with the following error message:

```
BFF file 'C:\Users\leandros\workspace\redacted\build\redacted.bff' has changed (reparsing will occur).
C:\Users\leandros\workspace\redacted\build\redacted.bff(32,5): FASTBuild Error #1100 - Copy() - Target 'C:\Users\leandros\workspace\redacted\_out\MSVC-Win32-x64-Debug\bin' already defined.
    Copy('redacted-dll-$Config$')
    ^
    \--here
```

**Comment by ffulin** [comment]
I think you are missing a trailing slash on the .Dest path: _out/$Config$/bin
A trailing slash indicates you are specifying the output folder, rather than the output filename. Perhaps when there are multiple input files, the error could be better.

**Comment by Leandros** [comment]
Yep, that's it! Good catch!
Yes, agreed, the error could be a little more descriptive of the actual problem. Hard to catch.

**Comment by ffulin** [comment]
Let's leave this issue open as a placeholder to improve the error message in that case.

**Comment by Leandros** [comment]
Sounds good!
I just wanted to thank you real quick for your effort building and maintaining FASTBuild. Truly great tool! Thanks a lot! You're awesome! 🎉

**Comment by ffulin** [comment]
Thanks! 😄

**Comment by ffulin** [comment]
I've added a new error (#1400) for the case where there are multiple .Source files, but .Dest is not a path. This has been committed to the Perforce mainline and will be in the next release (v0.95). Additionally, it has been submitted to GitHub: https://github.com/fastbuild/fastbuild/commit/72e2bec3aa89c00a5770d6d69fdb98b36621f6aa

Example:
```C++
C:\test\fbuild.bff(1,1): FASTBuild Error #1400 - Copy() - 'Dest' with multiple 'Source' files should be a path. Missing trailing '/'?
Copy( 'MissingTrailingSlash' )
^
\--here
```

I will leave this issue open until v0.95 is released.

**Comment by ffulin** [comment]
v0.95 has now been released and includes the new error message mentioned above. Thanks for reporting this issue!
