### ISSUE TITLE
Generated .sln should include a BOM for the Microsoft Visual Studio Version Selector to work

### ISSUE THREAD

**Issue by ChuangTseu** [fastbuild/fastbuild#286]
The *Microsoft Visual Studio Version Selector* used to open .sln files with the correct Visual Studio version doesn't work if the .sln files is encoded as simple UTF-8 without the BOM.

See this SO answer for reference: https://stackoverflow.com/questions/2804759/vslauncher-starts-wrong-version/2829550#2829550

I have tested it myself just right now, with a fresh install of Visual Studio 2017, and having Visual Studio 2015 still installed on my PC: now double-clicking the VS2015 .sln files generated by FastBuild opens it with VS2017. Then, manually saving the .sln with encoding UTF-8 with BOM restores the expected and working behavior (assuming the default file opener for .sln is the VS Selector): it opens with VS2015, and as an added bonus the file has a VS14 icon in the Windows Explorer.

**Comment by ffulin** [comment]
I just opened a sln file create by FASTBuild and saved it out from VS2017, and the behaviour I see is that the leading CR/LF FASTBuild writes is stripped, but no BOM is added. If I create a new sln file from VS2017, I see it created with a BOM.

I created the Solution generation for compatibility with an older version of VS, but I don't recall exactly which version :) (I think it was at least 2013, but it might have been 2012 or even 2010). The only concern I have is making sure that we don't break compatibility for exisiting users.  Best case we can just write the BOM if it doesn't break compatibility (with whatever versions of VS currently work). Worst case we can use the SolutionMinimumVisualStudioVersion property to control the behaviour (writing the BOM only if it's > some value).

**Comment by ChuangTseu** [comment]
Almost forgot about that one, a few days ago I got hooked and tried many things to refine my understanding of how the Selector works, here are my observations: https://gitlab.com/ChuangTseu/WikiTseu/wikis/Visual-Studio-Version-Selector:-observations-on-the-solution-format .

Basically, creating a new C++ project/solution from the Visual Studio project creator with VS 2012 up to 2017 yields a .sln file with a leading CR/LF _AND_ the BOM.

But interestingly enough, removing the leading CR/LF _AND_ saving the file WITHOUT BOM makes it work too! (It might even be the default for older than 2010 Visual Studio versions, can't test though).

Conclusion: I guess doing the same thing Visual Studio 11/14/15 does is a safe bet (i.e. a leading newline _AND_ a BOM).

**Comment by ffulin** [comment]
Seems like the CR/LF pair isn't needed for VS2010 (https://github.com/fastbuild/fastbuild/pull/300). I'll integrate that pull request shortly.

**Comment by ffulin** [comment]
I've integrated the fix (https://github.com/fastbuild/fastbuild/pull/300) that removes the rogue CR/LF. This will be in the next release (v0.95). I'll leave this issue open until that new version is released.

**Comment by ffulin** [comment]
v0.95 has now been released and includes the fix mentioned above. Thanks again for reporting this issue!
