### ISSUE TITLE
-report segfaults

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#29]

**Comment by ffulin** [comment]
Can you please provide some more details?
 * What platform are you running on?
 * What version are you running?
 * What is the full command line you are using?
 * If you have a bff file that you've created which can reproduces the crash, are you able to provide it here (or send it to fastbuild@fastbuild.org)?

**Comment by ffulin** [comment]
I guessed from your other ticket that you are running on Linux.

I've reproduced the crash (caused by some functionality not yet implemented on Linux).

Thanks for the report.

**Comment by ffulin** [comment]
I have fixed the bug (Linux and OS X) in the main perforce branch.  The fix will be part of v0.84.
I'll leave this issue open until that version is released.

**Comment by trufae** [comment]
I got the crash on osx. But i guess it was a generic issue. I was testing
it and filling issues without checking the source. I'll do more testing and
such in the following days. I have some ideas to make fb better

**Comment by trufae** [comment]
Thanks

**Comment by ffulin** [comment]
v0.84 has now been released.  Closing this issue.
