### ISSUE TITLE
Change CompilerInputPath to ArrayOfStrings

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#292]
It will be much more convenient to use

**Comment by ffulin** [comment]
FASTBuild doesn't have a property called "ProjectSourcesPath". Could you please tell me exactly which property and which function you are referring to?  (for example .ProjectInputPaths in VCXProject)

**Comment by Domain** [comment]
Sorry for the late reply. It should be CompilerInputPath.

**Comment by ffulin** [comment]
The .CompilerInputPath property (on ObjectList, Library and CSAssembly) can accept a single String or an ArrayOfStrings. (The documentation for all three of the above needs updating to make it clear that this is the case.)

Do you have a case where this is not working as expected?

**Comment by Domain** [comment]
Nevermide, I make a mistake.
