### ISSUE TITLE
Embed progress in to the output string

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#293]
Such as:
-> Obj [ 10.1%] : main.cpp

**Comment by ffulin** [comment]
Some users rely on being able to parse the output from FASTBuild, so I wouldn't want to change the default output behavior. I wouldn't be opposed to adding an option to enabled this - we'd just need to think about how that should interact with the existing -noprogress so it's consistent/logical.

**Comment by ffulin** [comment]
Closing this old issue.

I think we would not want to change the existing behavior (as noted above). For anything that (presumably) wants to parse the output at runtime, something like the -monitor option (or some future improved version of that) is probably a better choice too.
