### ISSUE TITLE
Add -purge flag to remove all intermediate files

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#30]
I was expecting -clean to do this.

This flag should remove all object, executable, libraries and fdb files

**Comment by ffulin** [comment]
While FASTBuild tracks which files it has created in the fdb, this can be deleted by the user, so there is no way to reliably and safely delete all files created during compilation. Additionally, some tools generate side-effect files not known to FASTBuild.

In the dev branch a new RemoveDir() function has been added which allows you to create a "purge" target in your bff. If you generate all your artifacts into a single directory, it's very easy to configure.

This will be in the next release (v0.88). You can see the change here: https://github.com/fastbuild/fastbuild/commit/cd53b8be2d655e608c9ff842c0ea88e74ca6c56d

I'll leave this open until the next version is released.

**Comment by ffulin** [comment]
v0.88 has been release. It contains the RemoveDir() function as described above.
