### ISSUE TITLE
TestDLLWithPCH doesn't pass on 0.94

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#304]
Heya!

The TestDLLWithPCH doesn't pass with the latest release.
It seems the commit introducing the regression is 1cc889e06bee91feba0fcf1bcedf997a931a1f7f.

**Comment by ffulin** [comment]
I'm not able to reproduce this failure. Is there anything special about your setup that might help identify why it fails for you?

**Comment by belkiss** [comment]
Hi!
This seems indeed to be a bug in vs2015, which I use to build FastBuild.
Here is the output of two consecutive launch of cl.exe from the TestDLLWithPCH (I have manually removed /nologo to get compiler version). Note that the second invocation doesn't have the "including file" line, causing the failure:

```
U:\>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" C:\RD\FastBuild\Code\Tools\FBuild\FBuildTest\Data\TestDLL\PrecompiledHeader.cpp /Fo"C:\RD\FastBuild\tmp\Test\DLL\PrecompiledHeader.pch.obj" /Yc"PrecompiledHeader.h" /W4 /WX /Z7 /Fp"C:\RD\FastBuild\tmp\Test\DLL\PrecompiledHeader.pch" /c -DDLL_A_EXPORT  /showIncludes
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

PrecompiledHeader.cpp
Note: including file: c:\rd\fastbuild\code\tools\fbuild\fbuildtest\data\testdll\PrecompiledHeader.h

U:\>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" C:\RD\FastBuild\Code\Tools\FBuild\FBuildTest\Data\TestDLL\PrecompiledHeader.cpp /Fo"C:\RD\FastBuild\tmp\Test\DLL\PrecompiledHeader.pch.obj" /Yc"PrecompiledHeader.h" /W4 /WX /Z7 /Fp"C:\RD\FastBuild\tmp\Test\DLL\PrecompiledHeader.pch" /c -DDLL_A_EXPORT  /showIncludes
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

PrecompiledHeader.cpp
Note: reusing persistent precompiled header C:\RD\FastBuild\tmp\Test\DLL\PrecompiledHeader.pch

```

I quickly tested with vs2017 and the bug seems to be fixed, so if FastBuild goes directly to it, that fix won't be required.

Thanks!

**Comment by ffulin** [comment]
Thanks for investigating this! I think while FASTBuild's tests will be ok if we go straight to VS2017, it seems there is still a bug here for VS2015 users.  For example:
 - do a build
 - delete the fdb
 - do another build
At that point dependency info would be missing and subsequent edits to files included by the PCH would not cause a rebuild as they should.

I think adding this to LinkerNode::DoPreLinkCleanup() would avoid that problem (as well as fixing the test with VS2015):
```C++
    // Work around for VS2015 bug where /showincludes doesn't work if cl.exe
    // thinks it can skip compilation (it outputs "Note: reusing persistent precompiled header %s")
    // If FASTBuild is building because we've not built before, then cleanup old files
    // to ensure VS2015 /showincludes will work
    if ( GetStamp() == 0 )
    {
        deleteFiles = true;
    }
```
We could try to limit it to VS2015 specifically somehow, but this seems low overhead enough to just do all the time. (apart from the test, I think it's not a super common case)

What do you think?

**Comment by belkiss** [comment]
Sounds good! I'll have a try and let you know :) Thanks!

**Comment by ffulin** [comment]
For some reason I started seeing this issue locally and was able to reproduce the bug. I tested the fix I suggested above and it seems to resolve the issue. (https://github.com/fastbuild/fastbuild/commit/60c09e3ea864e0eecc88fc52e4c5a9f1b896d9c3)

As well as the test being flakey, this was a legit bug - i.e. you could be missing dependencies in a clean build if there was a stale .pch lying around. I'm glad we found this.

The fix will be in the next release (v0.95). I'll leave this issue open until this is released.

Thanks again for the report!

**Comment by belkiss** [comment]
Heya!
Sorry this completely slipped my mind. I can confirm that 60c09e3 makes the test pass for me as well.
Thanks!

**Comment by ffulin** [comment]
v0.95 has now been released and the source includes the fix mentioned above. Thanks again for reporting this issue!

**Comment by belkiss** [comment]
Np! :) Thanks for the fix!
