### ISSUE TITLE
Default extensions should depend on host operating system

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#31]
Use .o on unix

**Comment by ffulin** [comment]
This bug has now been fixed in the Perforce mainline. I'll resolve this issue when v0.84 is released (which will contain this fix).

.o is now the default extension on OS X and Linux.  .obj remains the default extension on Windows.

**Comment by trufae** [comment]
Awesome. Thanks

**Comment by ffulin** [comment]
v0.84 has now been released.  Closing this issue.
