### ISSUE TITLE
Unknown variable error message is lacking

### ISSUE THREAD

**Issue by clevijoki** [fastbuild/fastbuild#315]
If you use this fastbuild code:

```
.var1 = 'neato'
.var2 = .'$var1$_burrito'
```

The error that is spit out is this:
```
FASTBuild Error #1009 - Unknown variable.
.var2 = .'$var1$_burrito'
        ^
        \--here
```
This doesn't tell you the most important part, what is the variable name it is trying to find after expansion, e.g. it's really complaining that 'neato_burrito' wasn't found. It would be very useful if that error message looked like:

```
FASTBuild Error #1009 - Unknown variable 'neato_burrito'
.var2 = .'$var1$_burrito'
        ^
        \--here
```

**Comment by ffulin** [comment]
Indeed that error is not very helpful in this case. The error message originates from a time when the .'$var$_xxx' syntax didn't exist, and thus the caret always pointed to the variable and so printing the name was entirely redundant.  As you've noted, that is no longer sufficiently helpful, as per your example.

I think it should be pretty easy to improve the error so the variable name is always shown as you've suggested.

**Comment by ffulin** [comment]
I have improved the #1009 Unknown Variable error (https://github.com/fastbuild/fastbuild/commit/17331829e874fb009da3747de2360d63044b26b1). This will be in the next release (v0.95).

```C++
C:\Test\1009\fbuild.bff(2,9): FASTBuild Error #1009 - Unknown variable '.neato_burrito'.
.var2 = .'$var1$_burrito'
        ^
        \--here
```

I'll keep this issue open until the next version is released.

**Comment by ffulin** [comment]
v0.95 has now been released and includes the enhanced error message. Thanks again for reporting this issue!
