### ISSUE TITLE
Crash on concatenation of two structs with identically named members of incompatible types

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#320]
Found with libFuzzer. Minimal reproducer:
```
.A=[.C={}].B=[.C=2].A+.B
```
When `BFFVariable::ConcatVarsRecurse` tries to concatenate structs it calls itself for each pair of same-named members in both structs. But it never check the result, this results in `nullptr` being pushed into `allMembers` array. Later `BFFVariable::GetMemberByName` iterates through that array, and dereferences that `nullptr` when it tries to compare variable names.

I think this case should result in error message being printed describing the problem (e.g. "can't concatenate array and int").

**Comment by ffulin** [comment]
Thank for the bug report and repro case. I've fixed the bug and added a test (https://github.com/fastbuild/fastbuild/commit/94dba4a4bb7da2a9ce7693caa7de612a13fde90b). FASTBuild will now report Error #1034 about mismatched types for this case.

This fix will be in the next release (v0.95). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.95 has now been released including this fix.
