### ISSUE TITLE
.bff file seems to be a dependency on all tasks

### ISSUE THREAD

**Issue by clevijoki** [fastbuild/fastbuild#327]
If I modify the .bff at all, even to adjust whitespace, it seems to do a rebuild of everything. This makes resolving things like link flag issues on a large project extremely slow, as it has to 'rebuild' every object before getting to the link stage. Even with caching support it is not as fast as if it didn't attempt to do this at all.

It should really just track the command line passed to the individual build tasks, not put a dependency on the .bff IMO.

**Comment by ffulin** [comment]
Full rebuilds being triggered when any part of a bff changes is a limitation of FASTBuild currently. Work is continuing to address this such that only things that change will rebuild. More details can be found here: https://github.com/fastbuild/fastbuild/issues/108

Working to correct linker flags is indeed annoying as it's the worst case for this behaviour. In addition to using the cache to help reduce the pain, another strategy to reduce the pain can be to compile once with -showcmds and then manually invoke the linker adjusting the link args. Once you have it working you can make the appropriate changes to the bff.  It's far from ideal, but might be helpful in some situations.

**Comment by ffulin** [comment]
Closing as (https://github.com/fastbuild/fastbuild/issues/108) covers everything.
