### ISSUE TITLE
Run Makefile from Fastbuild

### ISSUE THREAD

**Issue by artemkin** [fastbuild/fastbuild#334]
Hi there,

I have `3rdparty` folder with a bunch of third-party libraries. I build them using `make`, and don't plan to rewrite makefiles, as they are third-party.

Build command:

```
make -C 3rdparty
```

How can I run it from Fastbuild?

I'm trying to use `Exec` with no success:

```
Exec('3rdparty')
{
    .ExecExecutable = 'make'
//    .ExecInput = ''
    .ExecOutput = '3rdparty/somelib/somelib.a'
    .ExecArguments = '-C 3rdparty'
}

Alias('all')
{
    .Targets = { '3rdparty' }
}
```

Any ideas?

**Comment by ffulin** [comment]
You should be able to run any external executable, but you'll need to set the path appropriately. Assuming make is not in the working directory of FASTBuild, then you'll need to provide a relative or absolute path to the executable.

**Comment by artemkin** [comment]
I specified an absolute path of `make` in `.ExecExecutable`, but it still doesn't work.

```
./fbuild
BFF file '/home/me/sandbox/fbuild.bff' has changed (reparsing will occur).
2> Run: /home/me/sandbox/3rdparty/somelib/somelib.a
```

It seems it is trying to run file specified in `.ExecOutput`, rather than in `.ExecExecutable`.

**Comment by ffulin** [comment]
The Run: prints the target (consistent with everything else) so it's normal to see the .ExecOutput.

A couple of things to try to help diagnose what is going on:
a) How does it fail?  Does Exec() report an error?  If so, what it it? If not, how does it fail or not work exactly?
b) Run with -showcmds will provide information about the full command line and exe being invoked. You can check this to make sure it's exactly what you expect.

**Comment by ffulin** [comment]
@artemkin Did you end up resolving this issue?

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.

**Comment by mikejack07** [comment]
> 



> The Run: prints the target (consistent with everything else) so it's normal to see the .ExecOutput.
> 
> A couple of things to try to help diagnose what is going on: a) How does it fail? Does Exec() report an error? If so, what it it? If not, how does it fail or not work exactly? b) Run with -showcmds will provide information about the full command line and exe being invoked. You can check this to make sure it's exactly what you expect.

The error comes like this:
Failed to spawn process for '< .ExecOutput>'    

Hope this helps.
