### ISSUE TITLE
Cache only storing a small percentage of Object files

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#338]
`Build:          Seen    Built   Hit     Miss    Store   CPU`
`Object     : 5793    4048    1745    0       0       3h:16m 12.075s`

@ffulin Aside from `/Z7` (which we use), I don't know of any reason why the cache would only be Hitting/Storing `1745` out of `5793` object files. My best wild guess is a bug where despite using `.CompilerFamily = 'clang'` for `Android` and `Emscripten`, the part of FastBuild which does caching doesn't recognize the compiler and assumes caching cannot be supported?

Is there any other reason why so few of our object files should be caching? Is there a hidden limit on the maximum cache size?

Thanks!

**Comment by ffulin** [comment]
Assuming the store/hit are the same and you don't see any misses, then it looks like something about your compilation settings is disabling the cache for particular objects of libraries.

The full list of requirements for caching is here (http://fastbuild.org/docs/features/caching.html), but for completeness, things to double-check are:
a) You are using a different compiler for some objects or FASTBuild doesn't detect it as a cache-compatible compiler (.CompilerFamily is only in the dev branch, but if you built your own fbuild exe that should override detection. If you are using v0.94 then this will not have any effect)
b) Debug info as you noted needs to be /Z7
c) /clr must not be used (though using clang that's not an issue)

If it's not one of those 3 things, then the next thing to do is find a specific object that is not being stored/retrieved and look at the full settings used to build that (the command line). If you want, you can paste the command line here (redacted as needed) or if you prefer, send it via direct private support (http://fastbuild.org/docs/contact.html).

If it's not obvious from the command line what is wrong, our next step will be to debug it of course :)

**Comment by ffulin** [comment]
@missmah - Did you end up resolving this? Can this issue be closed?

**Comment by ffulin** [comment]
Closing old issue due to lack of response. We can reopen if this is still an issue you'd like to pursue.
