### ISSUE TITLE
Assert during CompileHelper construction on remote worker

### ISSUE THREAD

**Issue by lantictac** [fastbuild/fastbuild#342]
There's an assert (and potential access violation) when a CompileHelper is constructed on a remote worker:

 	Singleton<FBuild>::Get() Line 54
	ObjectNode::CompileHelper::CompileHelper(bool handleOutput) Line 2043
 	ObjectNode::BuildFinalOutput(Job * job, const Args & fullArgs) Line 2004
 	ObjectNode::DoBuildWithPreProcessor2(Job * job, bool useDeoptimization, bool stealingRemoteJob, bool racingRemoteJob) Line 519
 	ObjectNode::DoBuild2(Job * job, bool racingRemoteJob) Line 276
 	JobQueueRemote::DoBuild(Job * job, bool racingRemoteJob) Line 322
 	WorkerThreadRemote::Main() Line 60
 	WorkerThread::ThreadWrapperFunc(void * param) Line 112
 	ThreadStartInfo::ThreadStartFunction(void * userData) Line 83

```
ObjectNode::CompileHelper::CompileHelper( bool handleOutput )
    : m_HandleOutput( handleOutput )
    , m_Process( FBuild::Get().GetAbortBuildPointer() )
    , m_OutSize( 0 )
    , m_ErrSize( 0 )
    , m_Result( 0 )
{
}
```

The FBuild singleton is never constructed within an FBuildWorker instance (as far as I can tell) hence FBuild::Get() fails with an assert (under a debug build).

**Comment by ffulin** [comment]
Thanks for reporting this. The code is definitely funky, but there is fortunately no access violation because GetAbortBuildPointer() is a static function that returns a static member so even though 'this' is nullptr, it is never dereferenced.  The code is a little silly though, since i should really just be:
```C++
FBuild::GetAbortBuildPointer()
```
which would fix the assertion.

**Comment by lantictac** [comment]
Thanks a lot for the fast response. I didn't see that GetAbortBuildPointer() was static since the assert stopped execution so I never actually tried stepping into it - but I admit I was a little perplexed as to how this hadn't caused an AV within release builds. Now it all becomes clear!

**Comment by ffulin** [comment]
I've fixed up the source code (https://github.com/fastbuild/fastbuild/commit/0b9e54121f68fd957a324f008c4fcbe2b4c59e05). I'll leave this issue open until the next release. Thanks for reporting this!

**Comment by ffulin** [comment]
v0.95 has now been release including this fix.
