### ISSUE TITLE
Exec() node and implicit/dynamic dependencies

### ISSUE THREAD

**Issue by Dragnalith** [fastbuild/fastbuild#344]
I wonder how to inform the Exec node about implicit dependency. For example a source file will depends on header file specified in the source itself, or some asset files will depends other file referenced in the asset file itself.

In my case I am trying to generate reflection data from my C++ sources with a custom tool. But for correct incremental build I need the exec node to be aware of the header files.

I am thinking about patching my fastbuild to make the Exec node being able to read a depfile (like in ninja or make). But before that I want to make sure there is no way today to solve implicit dependencies.

**Comment by ffulin** [comment]
At the moment, Exec() only manages simple input and outputs. ObjectList() on the other hand can manage more complex dependencies.

If you can make your preprocessor behave like any existing compiler (like cl.exe with /showIncludes for instance) you might be able to use ObjectList to get dependency information without modifying FASTBuild.  It's a little inelegant, but not unreasonable:

```C++
Compiler( 'CodeGenTool' )
{
     .CompilerFamily = 'msvc' // Tell FASTBuild this should be treated like cl.exe
     ...

ObjectList( 'CodeGen' )
{
     .Compiler = 'CodeGenTool'

     // Disable Caching and Distribution so /showIncludes will always be used
     .AllowCaching = false
     .AllowDistribution = false
```
Of course, we could extend Compiler, ObjectList or Exec to specify an additional mechanism for dep gathering as well (like your .dep file suggestion).

**Comment by Dragnalith** [comment]
@ffulin Thank you.
Having Exec() being able to deal with implicit dependencies would make FastBuild language agnostic.
But in the mean time it seems your trick is enough to solve my issue. :-)
