### ISSUE TITLE
.response files

### ISSUE THREAD

**Issue by deadwizad** [fastbuild/fastbuild#348]
Not an issue... yet.

Does fastbuild support .response files.

**Comment by ffulin** [comment]
Are you asking if FASTBuild:
a) uses response files for long command lines?
b) if you can use your own manually created response files?

**FASTBuild using response files**

FASTBuild can detect when the command line is too long and the tool being invoked supports response files (like the visual studio cl.exe compiler for example). In that case it will use a response file when invoking the tool.

**Use of your own response files**

If you create your own response files manually and specify those in the args in the FASTBuild config, many things will not work correctly or safely as FASTBuild doesn't consider the contents of the response file in various places it needs to when manipulating the command line or hashing the inputs to the build process.

Was there a different scenario you were worried about?

**Comment by deadwizad** [comment]
You basically answered my question inadvertently buy giving me more information. So thank you for that. 

I've been using, UE4 ( which is a minefield of compiler hacks and such ) they construct their own response files. I've had to demystify those to get our game compiling. 

Out of the box using LIamkf implementation the editor and the tool chain do compile. 
However, if you're a big fan of disabling unity now and then to see which programmer can't use #include  properly ( jokes ), it can fall over just compiling the shader compiler. Especially if you disable shaderdpch as well.

I've managed to fix all of these issues. I've posted two new ones for you to have a look at, but this issue is technically closed.

This tool is amazing and considering its free and how much money i know its already saved a few companies I've worked for. Its nice to have something which helps compile times without being bent over a barrel by incredibuild.

I'm going to clean up the implementation of the FASTBuild.cs i have an get that posted for the community.
I've also managed to get the shadercompiler working using fastbuild as well so i'll post that one in tandem.

I just need to resolve the xbox one issue with distribution and the caching issue.
I'm actively using this now as its part of my build machine setup.
I'd like to help get this into UE4 as a standard tool.

**Comment by ffulin** [comment]
Thank you for your kind words :)

> I'd like to help get this into UE4 as a standard tool.

I think this would be amazing.  The compile times in Unreal seem to be among some of the worst, so if lots of people could benefit by speeding those up, that's be great! I'll do what I can to support any effort to make it easier for Unreal users to use FASTBuild.

I'll go ahead and close this issue. We can work to resolve the distribution and caching questions in the other tickets (I've gone any responded to both of those as well already).

**Comment by RPG3D** [comment]
does Response file supported officially now ?

**Comment by ffulin** [comment]
@RPG3D I'm not really sure what you mean. Can you clarify your question please?

**Comment by RPG3D** [comment]
I mean, Is there some plan to support .response file? this will make it easy to make FastBuild work with UE4

**Comment by ffulin** [comment]
FASTBuild supports the creation of response files for tools that support it. There are no plans to support allowing FASTBuild to use manually created response files.
