### ISSUE TITLE
-cache appears to be incompatible with MSVC /analyze + PCH

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#350]
It appears we may have found another `-cache` + `PCH` bug!

This one is `MSVC` specific (since `VS 2008`, it seems):

When enabling `PCH` on `cl.exe`, specifically in combination with `/analyze`, it appears that the `.pch` file is not the only file which needs to be cached for correct compilation. Apparently, the `.pchast` file also needs to be cached.

Repro steps:
```
1. Do a `cl.exe` build with `/analyze` passed to `cl.exe` and `-cache` passed to fastbuild, which generates a `PCH`
2. Change a header used by the `PCH` to remove a function used in a `.cpp` but not used in the `PCH`
3. Do another build, which should fail because the function is gone.
4. Revert the header so it's the same as in `step #1`.
5. Do another build, which will fail for the same reason as `step #3`, because the `.pchast` wasn't in the cache and didn't get regenerated (so it's now stale).
```

In the short term, it looks like we'll have to disable `/analyze` - but it definitely seems like caching the `.pchast` is something we should integrate into fastbuild.

A generic solution might be to add a way to specify additional dependencies to cache along with some file? (e.g. one input file and multiple output files for the cache?)

If there's already a way to solve this with fastbuild and I'm just not remembering it, or aware of it, that would also be great news!

Thanks!
Layla

**Comment by missmah** [comment]
Maybe `.PCHOutputFile            ; (optional) Precompiled header compilation output`

Could support a list of output files? Then it should be named `.PCHOutputFiles`..

Or maybe `.AdditionalPCHOutputFiles`?

**Comment by gkoreman** [comment]
The generic 'one input file, multiple output files' would be very useful
for other processes as well - for example compiling shaders with debug
flags produces two output files, the compiled shader and the debug symbols.

**Comment by missmah** [comment]
Maybe it could be an ordered list of the hash values of the original cache file, with a different extension that determines which additional file it matches? So that a cache hit would be able to retrieve them all?

Alternatively, instead of files, the hash values could be folder names, and then all the files within the folder have their real filenames so it's easy to pull them back out of the cache to where they go? This would assume they're all in the same relative path, though, as a requirement.

**Comment by ffulin** [comment]
The cache and distributed compilation currently don't work well with /analyze. For now, I recommend setting .AllowDistribution and .AllowCaching for false.

I think we can fix this pretty easily, at least for the cache scenario. The cache already supports (and uses) storing multiple files for a given node - specifically for MSVC both the .pch and the .pch.obj are stored. We can add the additional .pchast file to this bundle.

I have seen some problems with the way /analyze interacts with the preprocessor however, so I think we additionally need to not use the preprocessed output when compiling with /analyze. We can still use it to power the cache and for dependency gathering like we do for /ZW.

Additionally, for regular objects there are some .nativecodeanalysis.xml files that we might need to cache to have complete /analyze functionality.

Distributed compilation is more problematic - as I noted above, when using /analyze the preprocessor behaves differently. I have not fully investigated what it is doing, so it's possible that we could make it work correctly (for instance we might need to strip the /analyze when preprocessing and leave it just for the actual compile). This will need some digging into.

Given the /analyze is significantly slower it would be great to have both of these working as the benefits are significant.

I may be able to find some time in the next few weeks to dig into this.

**Comment by ffulin** [comment]
I have extended the -cache option so that it now stores/retrieves the additional files for msvc when using /analyze.  (The .pchast for precompiled headers and .nativecodeanalysis.xml files for both precompiled headers and normal object files).  This change (https://github.com/fastbuild/fastbuild/commit/35a8c638c2955a02f83b2196d1f653ea560b4004) will be in the next release (v0.95). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.95 has now been release including this fix.
