### ISSUE TITLE
Create compilation database JSON

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#351]
To integrate clang tooling into projects, you need to pass all preprocessor definition flags and include directories to each tool. Having a generated compilation database from your build system can dramatically reduce the effort required. 

The compilation database is, essentially, a json file which contains the path to the file compiled and the compiler flags. The full specification can be found here:

https://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by ffulin** [comment]
I'm not familiar with the use-case for this file, but I took a look at the documentation you linked.

The file itself looks like something which FASTBuild could generate without too much trouble. I imagine we'd add a new Function, such that this could work similarly to Visual Studio or XCode project generation.

It should be noted that if any external tooling wants to invoke any tooling by using these files, it would need to do so in a way that does not modify the actual built files that FASTBuild has generated to ensure it does not cause any problems like unnecessary rebuilds.

**Comment by Leandros** [comment]
The compilation database is mainly used for code completion tools (like [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) to give you code suggestions inside Vim, or the same for Emacs) or clangs tooling (like clang-tidy, to run static analysis). 
The chances that any of those tools is changing any generated files is very low.

**Comment by ffulin** [comment]
A compilation database was added some time ago (in v0.98, Apr 2019) but I missed resolving this issue.
