### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'Files.obj'

### ISSUE THREAD

**Issue by kgrach** [fastbuild/fastbuild#368]
Hi fflulin.

I try to build FastBuild project for Windows, but get link error.

8> Exe: D:\work\Utility\fastbuild_testbuild\tmp\x64-Release\Tools\FBuild\FBuildApp\FBuild.exe
 0.0 % [--------------------] 01s (8/19)    ◘◘◘\
8> LINK : fatal error LNK1181: cannot open input file 'Files.obj'.

I am looking for using Files.cpp/Files.h in source code/bff files,  but can't find.

May be you forgot checkin to repository this file?

Sorry, for my english )))

**Comment by ffulin** [comment]
There is no Files.cpp in the FASTBuild source code. I suspect you have a local configuration error. My best guess is that there are some unescaped local paths in play involving "Program Files" and the linker is getting confused because of those bad args.

If you can provide the following information, I can probably help further:
 - are you building the "master" or "dev" branch?
 - have you made any local changes to the bff files? (like pointing them at your toolchain)
 - can you provide the full link arguments by running FASTBuild with the -showcmds option?

**Comment by kgrach** [comment]
> are you building the "master" or "dev" branch?
>
master

> have you made any local changes to the bff files? (like pointing them at your toolchain)
>
Yes,  I had removed all Linux build refference from *.bff files
I don't have Linux development environment

>can you provide the full link arguments by running FASTBuild with the -showcmds option?
>
I run Fastbuild without arguments. 

How I can specify fastbuild -showcmds option to build only for Windows without local changes into the bff files?

**Comment by ffulin** [comment]
> Yes, I had removed all Linux build refference from *.bff files

It should not be necessary to remove the Linux or OSX configs to build on Windows. You will need to make sure the Windows compiler variable is pointed to where you have it installed. I'm sorry that the instructions for this are lacking :(

> How I can specify fastbuild -showcmds option 

You should just be able to do this on Windows to build just the msvc version of the FBuild exe in debug:
```C++
fbuild FBuildApp-X64-Debug -showcmds
```

I hope that helps.

**Comment by kgrach** [comment]
> fbuild FBuildApp-X64-Debug -showcmds
Yes. It had helped.
Thanks

**Comment by slipstak2** [comment]
I get same error: LINK : fatal error LNK1104: cannot open file 'Files.obj'
We use Visual Studio 2015. There are several /LIBPATH with '/' in the end. Previous fastbuild version(0.92 for example) save it. But in 0.96 all '/' replace on '\'.
But it is not correct command line for link.exe and lib.exe. Should use \\" instead of \" in the end of /LIBPATH.
More here: https://developercommunity.visualstudio.com/comments/69109/view.html

**Comment by ffulin** [comment]
@slipstak2 I think you are experiencing a problem added in v0.96. A description of the problem, a fix and a work-around can all be found here: https://github.com/fastbuild/fastbuild/issues/467

**Comment by banjia0815** [comment]
Get the same error.

c:\Test>fbuild
BFF file 'C:\Test\fbuild.bff' has changed (reparsing will occur).
5> Lib: C:\Test\lib\test1.lib
6> Lib: C:\Test\lib\test3.lib
7> Lib: C:\Test\lib\test2.lib
8> Exe: C:\Test\Out\main.exe
8> LINK :  fatal error LNK1104: cannot open file 'Files.obj'
8> Failed to build Exe. Error: 1104 (0x0450) Target: 'C:\Test\Out\main.exe'

Newbee to the fastbuid here, just a simple test to use the fastbuild(0.99). Really confused with this issue, have no idea what the files.obj means, it should only link to the main.obj imo. I have tried to change the backslashes and quotes but still failed. The Bff file is based on another quick start of fastbuild in someone's blog, the version should be 0.96 with visual studio 2015. I use visual studio 2017 so changed the paths to make lib and obj compile goes well but just cant build exe.

The libpaths is here. 

 .LibPaths           = ' /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\"'
                          + ' /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\"'

Maybe I just forget something?

**Comment by banjia0815** [comment]
Sorry I found maybe there is a relative path problem to cause this error, also it need to change or delete /nodefaultlib in option to make .exe  building succeed.

**Comment by ffulin** [comment]
@banjia0815 : The problem is you are adding this string to the command line directly without surrounding quotes:
```
+ "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\arm64\libucrtd.lib"
```
The linker will interpret this as many unique args, one of which is "Files" which it assumes is a reference to an object file.

**Comment by banjia0815** [comment]
@ffulin Thanks for the reply. At first I  just watched the debug error about what I missed so add the .lib file manually and now make these all to pathes, so it get solved but is not what i thought. Thanks again.
