### ISSUE TITLE
The visual studio generator always appends -summary to the build command

### ISSUE THREAD

**Issue by Ryp** [fastbuild/fastbuild#371]

**Comment by ffulin** [comment]
I'm not really sure what you mean. Do you have a Visual Studio project set to invoke FASTBuild to generate projects?  If so, the command line being used is entirely under your control.

If you mean something else, can you please provide some more information so I can understand the problem a bit better?

**Comment by Ryp** [comment]
Sorry for the lack of description, it's surely a problem on our side. I'll reopen if I can make a compelling repro. Thanks
