### ISSUE TITLE
When building FASTBuild on Windows, I end up with "C:\.fbuild.cache"

### ISSUE THREAD

**Issue by v1ne** [fastbuild/fastbuild#373]
It is not nice to just dump a folder under C:\, IMO. ;)
Instead of hard-coding the path in `Code/fbuild.bff`, FASTbuild should at least put the cache under `$TMP`, I'd suggest.

**Comment by ffulin** [comment]
Thanks for the suggestions. Both the main fbuild.bff for building FASTBuild and the configuration used by the tests would need to be updated.

**Comment by ffulin** [comment]
I've made a change in the dev branch (https://github.com/fastbuild/fastbuild/commit/b58e0ea488094a8f578cb22a7bd0fdd806e1b3d3) that means compiling FASTBuild (and/or running the tests) will no longer pollute the C: drive with a ".fbuild.cache" directory. (The $TMP$ dir will be used instead).

This change will be part of the v0.96 source code release. I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
A version with a change for this issue has now been released (v0.96).
