### ISSUE TITLE
Could I get fbuild binary for CentOS officially?

### ISSUE THREAD

**Issue by BrianMSon** [fastbuild/fastbuild#398]
Could I get fbuild binary for CentOS officially?
I got errors on gcc 4.8.2.

_fbuild: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by fbuild)_

_fbuild: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by fbuild)_

_$ gcc --version_
_gcc (GCC) 4.8.2 20131017 (Red Hat 4.8.2-1)_

Thank you.

**Comment by ffulin** [comment]
What version of CentOS are you using, and what version of glibc does it make available?

(For reference, this is the same issue described here: https://github.com/fastbuild/fastbuild/issues/225)

**Comment by BrianMSon** [comment]
OS version : CentOS release 6.5 (Final)
Required glibc versions : 2.14 and 2.15

I cannot install external library because I'm not super user for this system.

**Comment by ffulin** [comment]
I've made the necessary changes (https://github.com/fastbuild/fastbuild/commit/db78492682d8a9619208dc4c8880df5cfe6bb9ab) such that the next version will only require glibc v2.6. This change will be in the next release (v0.96). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
A version containing a fix for this issue has now been released (v0.96).
