### ISSUE TITLE
Failed to spawn process (error 0x57) to build '...'

### ISSUE THREAD

**Issue by nedwardsnae** [fastbuild/fastbuild#405]
Hi,

Thanks for FastBuild, it's really great. :)

However, we're frequently encountering this spawn process error while building our UE4 game. I built FastBuild locally so that I could debug the issue, and it turns out that a number of the objects we're compiling have arguments lengths of 32767. While this plus the null terminator would result in a string of length 32768 (which is at the limit that the documentation describes), it appears that changing the argLimit check in Args.cpp from <= to < fixes the issue. I'm not sure if the limit described in the docs is an inclusive or exclusive maximum or what. Either way, in this case it looks like FastBuild should be generating a response file in this scenario.

Thanks,
Nick

**Comment by belkiss** [comment]
Hi!
That has been fixed and will be in the next release of FastBuild: https://github.com/fastbuild/fastbuild/pull/369

**Comment by nedwardsnae** [comment]
Thanks! Glad to hear it.
