### ISSUE TITLE
Change in capitalization of executables on Linux

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#420]
During recent BFF simplifications (95607a6b560a8384fa660f1b393a3dea46c0326e) the capitalization of executables on Linux was changed to match the one on Windows and OSX (eg. `fbuild` changed to `FBuild`).
While naming consistency is a good thing, this change will break people's scripts which call the FASTBuild executable.
Of course this issue is minor and is trivial to work around, I just want to ensure that this issue was considered and the this change was intentional.

**Comment by dummyunit** [comment]
This is great, thanks for the answer.

**Comment by ffulin** [comment]
Let's leave this one open to track the work.

**Comment by ffulin** [comment]
Casing of "fbuild" and "fbuildworker" on Linux has been restored: https://github.com/fastbuild/fastbuild/commit/6361b154a15b1b19af5ac0173b9e84e574b7568d

This change will be part of the next source release (v0.97). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.97 has now been released which contains the casing fix when building from source.
