### ISSUE TITLE
C1060: Compiler is out of heap space in remote worker

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#422]
When compile in distributed, the remote worker may run out of memory. 
The C1060 error may be thrown in VC, which will stop the compilation. 
I think this error can be ignored, and the task should be rescheduled to other worker.

**Comment by ffulin** [comment]
Do you see this failure with the x86 compiler, or the x64 one? I would imagine that for the x64 version, it should be all but impossible to have this error. 

If it's the case that it can only happen with the x86 compiler, I'm a little worried about covering up what is a performance problem that I guess would be solved by switching to the x64 compiler. (even if targeting x86 you probably want to use the x64 tool chain).

Alternatively, if "out of heap space" is a condition that can be hit non-determinisitcally on certain machines only, and then proceeds to build ok on another, or it is some generic error where the compiler hits some internal limit (even on x64) then perhaps retrying does make sense.

**Comment by ffulin** [comment]
@Domain - any thoughts on the above comments?

**Comment by Domain** [comment]
I use the x86 compiler, and I cannot switch to x64 version now because of lots of errors and warnings. I can give it a try later.
When I hit this error, it can be solved by restarting the remote machine.

**Comment by ffulin** [comment]
I'm going to close this error as there is nothing actionable on my side. Let me know if you want some more investigation into anything, or if you've discovered anything new and we can re-open this or create a new issue as needed.

**Comment by bburgin** [comment]
For x86 targets, my teams always use the 64-bit version of the x86 cl.exe compiler:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\cl.exe
So as ffulin suggested, I think Domain could use this version of the compiler without needing to change their code. This would avoid the warnings / issues from trying to build for x64. Domain wouldn't need to port their code to x64.

**Comment by dummyunit** [comment]
We recently encountered similar issue with error C1060. In our case though remote worker was really out of memory (somebody started Docker and it consumer 90% of memory). Unsurprisingly switching to 64-bit compiler (14.15.26726\bin\Hostx64\x86) didn't help.

So I would like to reopen this issue and suggest treating error С1080 as a system error (in terms of `ObjectNode::HandleSystemFailures`).

**Comment by ffulin** [comment]
Seems pretty reasonable for FASTBuild to treat this as a "system error" and allow the task to be retried elsewhere. We can make the verbose logging methods include output as needed to help diagnose non-performant builds.

**Comment by ffulin** [comment]
I've made a change so that C1060 is treated as a "system error" and is retried (https://github.com/fastbuild/fastbuild/commit/6190e917a9233afed74c7db51dd2099d158bafc6). This will be in the next version (v0.98). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.98 has now been released and will treat error C1060 as a "system error" so that it will be retried. Thanks for reporting this issue.
