### ISSUE TITLE
Distributed compiling no longer working since latest Windows Update?

### ISSUE THREAD

**Issue by chrisjllamb** [fastbuild/fastbuild#435]
Hello all,

I have been running FASTBuild using distributed compiling for a while now, and have had no problems with it, even through multiple Windows updates.

However, since the latest large update, Some of my machines never get any workers connecting. They are finding the share and the file tokens (which the compiler picks up), but all build items just happen locally. Other machines have no issue, and when I set the ones that don't work up as workers, it finds them and uses them without issue.

Has anybody else experienced this? I'm assuming it's some silly firewall problem

**Comment by ffulin** [comment]
I'm using Windows 10, and at home I have the last large update. I'm not experiencing any problems with distributed compilation.

If you haven't already, you can use -distverbose to see a little more information about what is going on. Specifically, you would see if any connections are being made to your remote workers and if those connections are being dropped. Failing that, it might be something that has to be debugged in your environment.

**Comment by chrisjllamb** [comment]
Found it!

Windows had reset the network to public on some machines, so the firewall was blocking requests to fbuildworker.

Thanks very much for your help :)
