### ISSUE TITLE
Single definition, "Target '[.TestOutput]' already defined."

### ISSUE THREAD

**Issue by StephenPSS** [fastbuild/fastbuild#440]
I'm sure this is a simple syntax error, but I'm trying to run a number of distributed test writing to the same output file and getting the error 

`"fbuild.bff(7,1): FASTBuild Error #1100 - Test() - Target 'D:\depot\UnitTestResults.txt' already defined."
Test('ViewCellPriority')
^
\--here`

Here is the .bff file:

`.TestOutput = 'D:\depot\UnitTestResults.txt'
.TestExecutable = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
Test('OneRingAnalysisTest')
{
 .TestArguments = 'D:\depot\Encoder\Binaries\x64\Release\unitTests.dll /Tests:OneRingAnalysisTest /Platform:x64 /InIsolation'
}
Test('ViewCellPriority')
{
 .TestArguments = 'D:\depot\Encoder\Binaries\x64\Release\unitTests.dll /Tests:ViewCellPriority /Platform:x64 /InIsolation'
}
Alias('all'){.Targets = {'OneRingAnalysisTest', 'ViewCellPriority'}}`

The error occurs on the 2nd Test function call which is intended to use the same output file as the first. According to the documentation the 1100 error code is supposed to show up when multiple definitions use the same alias, but here that alias is only defined once.

**Comment by StephenPSS** [comment]
I should have been more clear in this write-up, that it actually works quite happily with only a single test even though the test dll is run via a wrapper exe. Per your suggestion that tests write to a separate file and then merge the files, they are also happy writing to their individual output files so I'll try that for now. However, would there be problems distributing this with a wrapper exe? Additionally, would using "-clean" force the tests to run even if the ".TestExecutable" hasn't changed?

Thanks for your response!

**Comment by StephenPSS** [comment]
Writing to update that we're abandoning this approach for now as the Test() function is not distributable through -dist, and runs on local cores if -forceremote is enabled.

**Comment by ffulin** [comment]
Just to add to this, the -forceremote is considered a debug option, so other than for testing, you don't realy want to use that.  FASTBuild will already remotely compile everything it can (only running tasks locally if they can't be distributed or if there is nothing else to do locally).
