### ISSUE TITLE
Possible data race between OnReturnRemoteJob and FinalizeCompletedJobs in JobQueue

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#447]
A have got a MemorySanitizer report for RegressionTest_RemoteCrashOnErrorFormatting. It states that uninitialized value is used on [line 306 in JobQueue.cpp](https://github.com/fastbuild/fastbuild/blob/1c42593db528d4552d6896fabcb57e1e1b120993/Code/Tools/FBuild/FBuildCore/WorkerPool/JobQueue.cpp#L368) and that this uninitialized value is a result of deletion of the `Job` object on [line 484 in JobQueue.cpp](https://github.com/fastbuild/fastbuild/blob/1c42593db528d4552d6896fabcb57e1e1b120993/Code/Tools/FBuild/FBuildCore/WorkerPool/JobQueue.cpp#L484). Full report is available [here](https://travis-ci.com/dummyunit/fastbuild/jobs/130966620#L2545).

From looking at state transitions for `Job::m_DistributionState` this seems possible if the following happens:
1. Thread 1 (NetworkThread?) executes `OnReturnRemoteJob`, sees that there is a race with local job (line 358), cancels local job and enters the `Sleep(1)` loop.
2. Thread 2 (WorkerThread?) executes `FinishedProcessingJob`, sees that cancellation of local job was requested (line 585), sets `m_DistributionState` to `DIST_COMPLETED_LOCALLY` and puts the job into `m_CompletedJobs`.
3. Thread 3 (MainThread?) executes `FinalizeCompletedJobs`, grabs this jobs from `m_CompletedJobs`, sees that it is in state `DIST_COMPLETED_LOCALLY` and deletes it.
4. Thread 1 wakes up from sleep and accesses the deleted `Job` object.

I am not familiar with this part of code so I am not sure that this chain of events can really happen, maybe there are other conditions that will prevent that.

**Comment by ffulin** [comment]
This looks like it might be related to this: https://github.com/fastbuild/fastbuild/issues/437

**Comment by dummyunit** [comment]
> FYI, I have tried to address this race condition in the above commit (though it’s not very elegant) and it does not solve #437. It may solve this issue, though.

Sorry for the delay.
I have tested your patch and with a small tweak it fixes this issue. I had to add
```cpp
m_DistributableJobs_InProgress.Erase( it );
```
to the block that handles `DIST_RACE_WON_REMOTELY_CANCEL_LOCAL` in `FinishedProcessingJob`, [here](https://github.com/fastbuild/fastbuild/blob/5cdd2ae5b48e855ca2a1b0b4d40bd1e7b8b7d90a/Code/Tools/FBuild/FBuildCore/WorkerPool/JobQueue.cpp#L599).

**Comment by ffulin** [comment]
v0.98 has now been released and contains the fix for this issue. Big thanks to everyone who helped get this resolved.
