### ISSUE TITLE
Is there any monitor for all activities on available workers?

### ISSUE THREAD

**Issue by thunder-spb** [fastbuild/fastbuild#451]
Hey there!

Is there any dashboard to see all activities on all available workers?

Thanks in advance!

**Comment by ffulin** [comment]
There are a couple of visualizers created by third parties. Links are available here: http://fastbuild.org/docs/download.html

These let you view what workers are active in your current build. There is no way to view the state of workers participating in other builds.

**Comment by ffulin** [comment]
There are no plans to provide monitoring of all builds at the moment.
