### ISSUE TITLE
Missing files in GitHub source release for 0.96

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#460]
BFF files from `External/SDK` directory are missing in the master branch and in the tagged GitHub release for 0.96, so it's impossible to build the source downloaded as archive from GitHub.
Also `.gitignore` from the master branch is missing entries for the missing BFF files, this might be the reason for why they are missing :)

**Comment by ffulin** [comment]
Thanks!  All sorted now.
