### ISSUE TITLE
Wrong path of RC.exe in Windows10SDK.bff

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#463]
It should be:
$Windows10_SDKBasePath$/Bin/$Windows10_SDKVersion$/x86/RC.exe

**Comment by ffulin** [comment]
In my installation, the rc.exe is present in:
 - c:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe
 - c:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe

For my snapshot in source control, I kept them in the same relative directory. I believe this was at version 10.0.14393.0.

What version is the Windows SDK do you have? Microsoft have been moving things around a fair bit, so perhaps this has changed in a more recent version?

**Comment by ffulin** [comment]
I've updated the source to use the latest Windows 10 SDK : 10.0.17763.0 (https://github.com/fastbuild/fastbuild/commit/ce8b111c6afaacc9ecd6757b793230400188ac75). Those paths match as you've described, so the bff has been modified as you suggested. This looks to be the correct layout going forward.

I'll leave this issue open until the next version is released (v0.98) which will contain this source code change.

**Comment by ffulin** [comment]
v0.98 has now been released and the source contains the updated path to rc.exe. Thanks for reporting this issue.
