### ISSUE TITLE
Qt moc support

### ISSUE THREAD

**Issue by iobzo** [fastbuild/fastbuild#465]
when compile qt based project, 'QObject' classes headers should use 'moc.exe' to generate 'moc_xxx.cpp' first， I wonder how to add this step to the .bff file. Thanks.

**Comment by gkoreman** [comment]
I recently set up QT in my own project.

I set up uic, moc, and rcc as compilers
```
	Compiler('QT-uic')
	{
		.Executable = 'ThirdParty\MayaQT\bin\uic.exe'
		.CompilerFamily = 'custom'
	}

	Compiler('QT-moc')
	{
		.Executable = 'ThirdParty\MayaQT\bin\moc.exe'
		.CompilerFamily = 'custom'
	}

	Compiler('QT-rcc')
	{
		.Executable = 'ThirdParty\MayaQT\bin\rcc.exe'
		.CompilerFamily = 'custom'
	}
```
Then I use ObjectList to find appropriate files to process by the three compilers, using a naming convention that seemed to match other QT projects.
```
	ObjectList('$ProjectName$-QT-UIC-Headers')
	{
		.Compiler = 'QT-uic'
		.CompilerOptions = '%1 -o %2 -g cpp'
		.CompilerOutputPath = '$QTCodeGenOutput$'
                .CompilerInputPath = '$ProjectPath$'
		.CompilerOutputPrefix = 'ui_'
		.CompilerOutputExtension = '.h'
		.CompilerInputPattern = '*.ui'
	}

	ObjectList('$ProjectName$-QT-MOC-Cpp')
	{
		.Compiler = 'QT-moc'
		.CompilerOptions = '%1 -o %2'
		.CompilerOutputPath = '$QTCodeGenOutput$'
                .CompilerInputPath = '$ProjectPath$'
		.CompilerOutputExtension = '.generated.cpp'
		.CompilerInputPattern = '*.qt.h'
	}

	ObjectList('$ProjectName$-QT-RCC-Cpp')
	{
		.Compiler = 'QT-rcc'
		.CompilerOptions = '%1 -o %2'
		.CompilerOutputPath = '$QTCodeGenOutput$'
                .CompilerInputPath = '$ProjectPath$'
		.CompilerOutputExtension = '.resource.cpp'
		.CompilerInputPattern = '*.qrc'
	}
```
Then, I made sure to include the output from the ObjectLists (the generated .cpp files) in my Unity for the executable.
```
Unity( '$ProjectName$-Unity-Custom' )
    {
		.UnityInputPath             = '$ProjectPath$\'
		.UnityOutputPath            = '$OutputBase$\Unity\$ProjectPath$\'
		.UnityInputObjectLists		= { '$ProjectName$-QT-MOC-Cpp' '$ProjectName$-QT-RCC-Cpp' }
    }
```
Note that the UnityInputObjectLists doesn't include the output from the 'uic' compiler, since this generates header files which I manually include from other source locations where appropriate.

I hope this helps.

**Comment by iobzo** [comment]
@gkoreman Thanks ,this helps me.

**Comment by iobzo** [comment]
@gkoreman I have another problem，when Fbuilt my project, I press F5 to debug,but VS will build projects again. Is there something wrong with my bff ,or its fastbuild 's problem?

**Comment by gkoreman** [comment]
Hi @iobzo, sorry but I don't have any suggestions to make F5 work as you expect. I would recommend creating a new ticket that focuses on this question.

**Comment by gkoreman** [comment]
One other thing to note: FASTBuild natively supports QT's rcc compiler so you may want to use that directly. I haven't tested this yet, but I would imagine just removing the .CompilerFamily = 'custom' from the rcc compiler in my example above could allow it to auto-detect the rcc compiler and expose additional functionality.

**Comment by ffulin** [comment]
Some projects I'm involved in use Qt with FASTBuild, and the setup is pretty much the same as described here.

> I haven't tested this yet, but I would imagine just removing the .CompilerFamily = 'custom' from the rcc compiler

You can do that, or if for some reason the name of the executable changes in the future, you can also set it explicitly with ```.CompilerFamily = "qt-rcc"```

Note that rcc is the only one supported "natively", as last time I checked, the other tools didn't provide a way to extract dependency information.

**Comment by ffulin** [comment]
@iobzo - Do you have any followup questions in relation to the Qt support?  If not, I'll go ahead and close this ticket.

If you have other questions or problems, a new ticket issue might be the best.

**Comment by ffulin** [comment]
Closing this issue. We can re-open or create new issues if further follow-up is needed.
