### ISSUE TITLE
Allow .bff to indicate minimum supported FBuild release version

### ISSUE THREAD

**Issue by lantictac** [fastbuild/fastbuild#468]
Allowing some way of validating a minimum release version within a bff may help reduce failures when an obsolete FBuild release is on PATH.

Something like:

`
Settings
{
        .MinVersion = 0.96
}
`

**Comment by ffulin** [comment]
I've made some additions to FASTBuild:
 - Two new built in variables: _FASTBUILD_VERSION_ and _FASTBUILD_VERSION_STRING_
 - A new Error() function
 - Support for integer comparisons in If()

The next version of FASTBuild (v0.97) will contain these changes, which when combined allow for behaviour changes based on version. For example:
```C++
.RequiredFASTBuildVersion = 97
If( ._FASTBUILD_VERSION_ < .RequiredFASTBuildVersion )
{
    Error( 'FASTBuild v0.97 or later is required (found $_FASTBUILD_VERSION_STRING_$)' );
}
```
Naturally the new built-in variables won't be defined in older versions, so trying to use them will generate an unknown variable, but that is still an effective way to prevent use of an unsupported version.

I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.97 has now been released which contains the new properties that can be used in the bff.
