### ISSUE TITLE
When generating VCXProj filter files, filters can be wrong

### ISSUE THREAD

**Issue by marc-glaisner** [fastbuild/fastbuild#469]
If I set `.ProjectOutputPath` as a file in a sub-directory of `.ProjectBasePath`, all files contained in the same sub-directory will be seen as if they exist in `.ProjectBasePath`.

For example, if my base directory is `C:\MyProject\` and my output path is `C:\MyProject\Generated\MyProject.vcxproj`.
If I have other files into `C:\MyProject\Generated\` like `C:\MyProject\Generated\GeneratedCpp.cpp`, the vcxproj.filters file created will put `GeneratedCpp.cpp` in `C:\MyProject\`

**Comment by ffulin** [comment]
Thanks for the bug report. This issue has been fixed (https://github.com/fastbuild/fastbuild/commit/d7ce8ee628d1b762a09e664314a4959bd4844da7) and the fix will be in the next release (v0.97). I'll keep this issue open until that version is released.

**Comment by Sigvaard** [comment]
Yeah, filters don't work correctly in 0.96. I had to downgrade to 0.95

**Comment by ffulin** [comment]
v0.97 has now been released which contains the fix for this issue.
