### ISSUE TITLE
Files in VCXProj can have wrong paths if the generated vcxproj is in a sub-directory of its base path

### ISSUE THREAD

**Issue by marc-glaisner** [fastbuild/fastbuild#470]
Let say I have `.ProjectOutputPath` set to `C:\MyProject\_Generated\MyProject.vcxproj` and `.ProjectInputPaths` to `C:\MyProject\`.
If I have files in `C:\MyProject\_Internal\`, their paths in the vcxproj (and vcxproj.filters) will appear as if the `_` as been removed (ie. `C:\MyProject\Internal\`).

It seems the generation of the relative paths doesn't stop at a directory separator.

**Comment by ffulin** [comment]
Thanks for the bug report. This issues has now been fixed (https://github.com/fastbuild/fastbuild/commit/bd2b4b4c474c3b5b9b40463fc116679024f0b415). The fix will be in the next release (v0.97). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.97 has now been released which contains the fix for this issue.
