### ISSUE TITLE
Visual Studio .suo file randomly reset when switching branches

### ISSUE THREAD

**Issue by Rseding91** [fastbuild/fastbuild#471]
I don't have exact steps to reproduce this however as of the 0.96 version switching between different branches random causes the Visual Studio .suo file to be reset.

This resets the loaded/unloaded proejcts and the "Startup Project" (the project built and launched when pressing F5).

**Comment by ffulin** [comment]
FASTBuild doesn't generate or manipulate the .suo file in any way. If you are using git, perhaps git is modifying the file when you change branches?

**Comment by Rseding91** [comment]
We have the entire directory the solution sits in excluded from git. As I said I don't have exact steps to reproduce it happening all I know is it didn't happen before version 0.96 and it has been happening sporadically since. I know that's not much to work off of so if you can't do anything with this maybe others will come around with the same problem.

If I do figure anything else out I'll be sure to leave my findings here.

**Comment by ffulin** [comment]
@Rseding91 Did you end up gaining any new insights into this problem?

**Comment by Rseding91** [comment]
Only slightly. At first I thought it was changing between a bff that had "SolutionBuildProject" as an array and one with a single value but managed to have it happen when just rebuilding the sln using the command line at several points.

The only thing in common seems to be:

* It happens when the sln is rebuild (in our case 'fbuild vs2017-solution') - but not always
* It happens more frequently when the sln hasn't been rebuilt in some time

**Comment by ffulin** [comment]
Although the .suo files are binary, diffing them might yield some insight into what is changing which might give some ideas about what's going on.

**Comment by ffulin** [comment]
@Rseding91 Did you have any luck finding more about what you are seeing?

**Comment by Rseding91** [comment]
It happens at random and it's always when switching branches. I haven't been able to identify anything that triggers it beyond that.

If there was an option to set the startup project through the bff file then it wouldn't matter and I could just use that. I'm not sure if that's even possible though.

**Comment by ffulin** [comment]
> If there was an option to set the startup project through the bff file...

There are some comments implying that it's possible in the other thread (https://github.com/fastbuild/fastbuild/issues/462) but I didn't have a chance to investigate that latest suggestion thoroughly yet.

**Comment by ffulin** [comment]
I'm going to close this issue as without a repro case there is nothing specifically actionable here. The other issue (#462) that covers setting a startup project (which could serve as a work-around) is still open.

**Comment by Rseding91** [comment]
Understood. I still happens but I've never been able to find a cause except "large amounts of stuff changed, it rebuilt".
