### ISSUE TITLE
MSVC FBuild failed to open BFF

### ISSUE THREAD

**Issue by hzm** [fastbuild/fastbuild#482]
The path of fbuild.bff has space,so print "failed to open BFF" in visual studio 2015 output console.But the file "fbuild.bff" is created.I refer to https://github.com/liamkf/Unreal_FASTBuild to make it available in the Ureal Engine 4.The version of fastbuild I am using is v0.96.

**Comment by ffulin** [comment]
I think I need a little more information:
 - Is there anything special about your path?
 - Is the working dir very deep or does it contain spaces?
 - What is the command line FASTBuild is being invoked with?
 - What is the working directory?
 - What is the full text of the error? (redacted if necessary)
 - Is the bff listed in the error, combined with the working directory, the correct path to the file?

**Comment by ffulin** [comment]
Closing due to no reply. Let me know if you still have an issue and we can re-open if needed.

**Comment by ffulin** [comment]
@RPG3D - It looks a like a bug in the Unreal_FASTBuild tool:
```
string FBCommandLine = string.Format("-monitor -summary {0} {1} -ide -clean -config {2}", distArgument, cacheArgument, BffFilePath);

```
in this file: https://github.com/liamkf/Unreal_FASTBuild/blob/61507b3086170f40aff91f60d6ac11f0d3a1f95f/FASTBuild.cs

i.e. the path to the config is not quoted, so it breaks if there is a space in the path. Looks like an easy fix for that tool.

**Comment by RPG3D** [comment]
@ffulin , fix it, thanks.
