### ISSUE TITLE
Add output colors 

### ISSUE THREAD

**Issue by LuisRGameloft** [fastbuild/fastbuild#502]
Hi!!

I did implement output color for fastbuild, something plain text is very difficulty to see compile errors, my implementation is very rudimentary, maybe you have a better solution 

[output_color.zip](https://github.com/fastbuild/fastbuild/files/2531929/output_color.zip)

**Comment by bburgin** [comment]
I suggest using the colout python library, to color your FBuild output to your custom colors:
   https://github.com/nojhan/colout/releases
colout will allow you to colorize arbitrary command line output.
If you write one or more theme files, then you could have colout output ansi color codes around the output text that you want to color.
Just pipe the output of FBuild.exe to colout and pass colout the theme name as a cmd line arg.
If you want more than one theme, add more pipe calls; so one colout call for each theme name.

You could then use:
1. Ansicon on Windows as your cmd.exe, to show the colors when running FBuild on your dev machine
    https://github.com/adoxa/ansicon/releases
2. And the AnsiColor Jenkins plugin, to color the output in Jenkins
    https://plugins.jenkins.io/ansicolor

Other OSes should support color with their default consoles.
I think Windows 10 may even work. I heard that its new console supports colors to some extent.

You could apply this same scheme to other tools, by adding more theme files and calling colout at the appropriate times in your build scripts.

Thoughts?

**Comment by LuisRGameloft** [comment]
Thank for your feedback guys, I appreciate it
