### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by optomux** [fastbuild/fastbuild#506]
Does fastbuild use hashes or timestamps to check for changes in files?
For example build2 uses hashes.

**Comment by ffulin** [comment]
FASTBuild uses file last modification time stamps. This means builds are triggered generally as follows:
 - if node A depends on node B, and node B has a more recent modtime, node A will build

Additionally however, some other cases trigger builds to handle modifications that might be made outside of FASTBuilds control, or when FASTBuild is run for the first time or upgraded:
 - if node A has never been built by FASTBuild before, but it present on disk, it will build, regardless of timestamp (cope with deletion of the .fdb file for example)
 - if node A on disk doesn't match the time recorded at last build (stored in the .fdb) it will build (cope with replacement of file outside of FASTBuild)

In the future, I plan to improve how dependencies are tracked to instead record the mod time relationship of every dependency individually, such that any change to the modtime relationship will trigger a build. This will cater for cases like:
 - timezone or manual time changes
 - daylight savings adjustments
 - revision control systems that have options to set modtime to mean time of remote creation (like p4's +modtime option)
 - some edge case bugs like https://github.com/fastbuild/fastbuild/issues/107

There are no plans to implement hashing of file contents for dependency tracking. FASTBuild uses modtime for performance reasons.

Are you experiencing a problem with rebuilding/not rebuilding, or is this just a general query?

**Comment by optomux** [comment]
No just a general inquiry. Thanks for response!

**Comment by ffulin** [comment]
> However what if the time on the system is wrong? Or get's corrupted.

If the time is wrong *and* you make modifications to source files or perform a build while the time is wrong, then builds may not trigger correctly (for that and subsequent builds). If ever in this bad state, a rebuild would set everything right and would return you to a valid state.

The problem scenarios I mention above are all variants on this scenario, and although unlikely to occur, should all be handled by the planned improvements.

**Comment by optomux** [comment]
Buck - Fast building toolchain from Facebook uses caching (SHA1). 
So apparently there are no performance issues?

Maybe you can add it as a switch. :)

**Comment by ffulin** [comment]
In addition to fast large rebuilds, a core design goal for FASTBuild is for fast incremental build scenarios. Whilst performing a full build, where every file would be read into memory anyway, hashing that data would likely only add a relatively small overhead to the total build time. In incremental build scenarios (making small changes and frequently building), opening and hashing every file would be very expensive in relative terms and would scale very poorly in non-trivial projects. Opening a file and hashing the contents is thousands of times slower than retrieving the file modification time.

For non trivial projects, we are talking about tens of thousands of files, totalling anywhere between hundreds of MiB and several GiB of IO, which would now be the absolute minimum to be performed in every build.

For build systems that do hash all files, a common approach to reducing this cost is to combine it with only re-hashing files when their modification date changes. If FASTBuild was to do that, we'd gain nothing as we'd be relying on the filetime in the same way we already do. Other build systems might be able to use those hashes for cache lookups, but FASTBuild uses an alternative mechanism for that already  (preprocessing) which leverages work it does to support distributed compilation.

With all this in mind, I don't plan to add file hashing support as an option to the basic dependency checking system at this time. It's certainly possible that in the future this might change if the implementation for things like distributed compilation and caching change.

I hope that all makes sense. Let me know if I can further clarify anything.
