### ISSUE TITLE
Optimization options

### ISSUE THREAD

**Issue by optomux** [fastbuild/fastbuild#507]
Implement command line switches to allow custmizations for the following things:

- max-jobs (maximum jobs to create).
- max-stack (maximum stack size in KBytes to allow for newly created threads).
- queue-dept (more for long compilation, less for shorter tests).

**Comment by ffulin** [comment]
Can you please elaborate a little more on what you mean? I don't quite understand what you are asking for, or what the motivation behind these requests are. If you can provide some more information about what aspect of compilation you are trying to improve, and a bit more detail about what you are suggesting, it would help me respond.

In the interim, I'll try to have a guess at what you mean:

**max-jobs:** Do you mean concurrent jobs? The default is one per hardware thread. It can be overridden, though this almost always reduces performance. If you mean the depth of the job queue, this is determined by the target you ask to build. There is no advantage in reducing this (it would only slow the build, particularly for distributed compilation - see below).

**max-stack:** The stack per thread is already very small. What advantage would you see from reducing it further, or what problem do you think this would help address?

**queue-depth:** The depth of the queue is bound by the target you are building and memory usage. Capping this queue further would reduce overall build performance, particularly in distributed scenarios, with no benefit to small compiles (the queue is naturally short if you request only a small build).

**Comment by ffulin** [comment]
@optomux - Do you have any further info you can provide?

**Comment by ffulin** [comment]
I'm going to close this issue for now since no new information has been provided. Let me know if you want to talk about it some more and we can re-open as needed.
