### ISSUE TITLE
Overriding options

### ISSUE THREAD

**Issue by optomux** [fastbuild/fastbuild#508]
Allow overriding compiler/linker/preprocessor options on the fly through command line.

**Comment by ffulin** [comment]
The design of FASTBuild is such that when you have multiple flavors of build, you define all of those flavors in the bff config files. The reason for this is two-fold:

1) It prevents creating invalid or conflicting build targets - i.e. you can't define two builds that output the same files.

2) It allows multiple flavors of build to be run in parallel - i.e. you could build your Debug and Release builds at the same time.

If you can provide a bit more detail about your use-case, I might help me understand what you are looking for.

**Comment by ffulin** [comment]
@optomux - Do you have any further info you can provide?

**Comment by ffulin** [comment]
I'm going to close this issue for now since no new information has been provided. Let me know if you want to talk about it some more and we can re-open as needed.
