### ISSUE TITLE
IO detouring and network file system

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#509]
You have probably already seen the GDC presentation of Rémi Quenin by now :
https://www.gdcvault.com/play/1025444/The-Asset-Build-System-of

The IO detouring solution used by your former colleagues is quite nice :)
This could solve cache/pdb issues even without using the network file system.

But by using the network file system it seems like it could also unlock trickier scenarios, like C++ CLI/UWP/ZW support necessary for XboxOne, and other issues already reported (see https://github.com/fastbuild/fastbuild/pull/214, https://github.com/fastbuild/fastbuild/issues/438, https://github.com/fastbuild/fastbuild/issues/493 for instance).

This is very similar to the network drive mapping solution you already suggested [long time ago](https://github.com/fastbuild/fastbuild/pull/214#issuecomment-288604013), but seems more flexible and also simpler than the VFS solution proposed in https://github.com/fastbuild/fastbuild/issues/359. 

Now I'm sure you already thought over their solution, but I'm curious about your thoughts regarding their work, would you mind discussing a bit about that ?

**Comment by ffulin** [comment]
I actually didn't see that presentation - thanks for the link :) This detouring system implementation is new to me, so I don't have any details on it (other than what I can infer from the slides), though the general approach is familiar to me.

I did think about implementing a hooking/detour solution for FASTBuild in the past, but decided against it for a few reasons, the biggest 3 being the following:

**1) Hooking complexity.** Detours require hooking a lot of functions to work in a completely generic manner - literally hundreds of functions just for basic file and directory IO. On top of that there could be functions to hook to capture other things like registry and environment access. For tools that are completely under out/your control, or at the very least known and testable, it is likely workable/manageable to handle a fraction of those, but as a completely generic solution, it would take a long time to hook all the entry points necessary. This is all doable, but would take a great deal of effort. A missing hook could see really hard to diagnose failures, or worse, random access to the underlying system of the remote machine!

**2) Network latency** - Retrieving files over the network would add latency. A small set of dependencies (like building a single texture) is probably fine (equivalent to the latency FASTBuild already adds), but if we were actually compiling without using the pre-processor to support things like /ZW, we'd add latency to literally thousands of file requests. Naturally, this is solvable with caching input files on the remote host (to the point that it can even be an optimization if files are kept between builds) , but this is a non-trivial piece of work (and our second non-trivial one at that).

**3) Platform specific.** This hooking/detour approach would have to be implemented for each supported platform. Certainly some aspects could be shared (if caching was implemented for instance), but the raw hooking would at a minimum have to be implemented at least twice for Windows and Linux and likely a third time for OSX.

To be clear, I think there is potentially great promise in this approach, and the idea that FASTBuild could generically distribute any work would in the future would be huge. For now though, this I don't feel it's the right time to completely change the approach to distributed compilation.

I think it will be time to revisit some core assumptions about how to handle distributed compilation (and perhaps other things), after FASTBuild has hit v1.0, including at least:
 - feature parity between all platforms
 - full documentation of all features
 - not rebuilding unnecessarily when bff changes
 - robust dependency graph (a few edge case bugs)

**Comment by bburgin** [comment]
Could detouring be implemented outside of FASTBuild, as a separate process layer?
For my sandbox feature, I modified FASTBuild to invoke a sandbox exe.
If the user enables sandboxing, FASTBuild will call the sandbox exe for each compile / test.
If users want detouring, could they make a special sandbox exe that does the detouring for them?

**Comment by ffulin** [comment]
If the detouring is done outside of FASTBuild, then FASTBuild has no way to capture the file dependencies.

**Comment by bburgin** [comment]
Good point. What kind of file dependencies does FASTBuild capture? Can you give some examples?
Perhaps file dependency enumeration could be abstracted away into a plugin dll, like the cache plugin interface you have in FASTBuild today.

**Comment by Dragnalith** [comment]
We are using detouring in our studio for asset build system, so people can build converter without caring about providing dynamic dependencies. We are using [Microsoft Detours](https://github.com/Microsoft/Detours), and on modified version of the "tracebld" sample which is already tracking all the file I/O. Prototyping in our custom build system has been very fast since almost all the code was already written.

But of course it only solve the issue on windows.

On the other hand bazel has the project [sandboxfs](https://github.com/bazelbuild/sandboxfs) for quite the same purpose, but it is only working on Mac and Linux I think.

**Comment by ffulin** [comment]
FASTBuild usually* works by preprocessing locally which flattens the source tree needed to build an object file. This flattened source is used for:
 - extracting #include dependencies
 - sending to remote hosts for distributed compilation
 - hashing as part of the key for cache lookups

* = if caching and distribution is not in used and the msvc compiler is being used, the /showincludes option is used instead as it allows compilation to be done in one pass instead of two, saving some time.

**Comment by ffulin** [comment]
As there is nothing specific to implement, fix or change (at least for now), I'm going to close this issue.

**Comment by g3cko** [comment]
> * = if caching and distribution is not in use and the msvc compiler is being used, the /showincludes option is used instead as it allows compilation to be done in one pass instead of two, saving some time.

If I'm not using dist or cache, can I compile a file in a single pass outside of MSVC (eg, clang)?  Didn't want to open a new post just to ask that.

**Comment by ffulin** [comment]
@g3cko For non-MSVC compilers, the compilation is split into two passes in all cases (even if caching or distribution is not used) as this is how dependencies are extracted.
