### ISSUE TITLE
Using a different configuration file path won't invalidate fbuild.fdb

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#51]
Found an issue with `-config` option :
````
FBuild.exe -config test.bff
````
This will use 'test.bff' and write the dependency graph in 'fbuild.fdb' ([which is static](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/FBuild.cpp#L555)).
Then if the user change the configuration file path :
````
FBuild.exe -config another_test.bff
````
The code will check first 'fbuild.fdb', which is valid since the last execution, and [skip parsing](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp#L92) even if `-config` changed.

I thing that ideally the path to the fdb file should be the same as the configuration file, except for extension.

**Comment by ffulin** [comment]
A related problem is that the fbuild.fdb will not be invalidated if you copy it somewhere, so for example if you make a copy of your entire source tree including the fdb, it will still reference files in the original location.

**Comment by ffulin** [comment]
A change was integrated (https://github.com/fastbuild/fastbuild/pull/104) which uniquifies the fdb name based on the bff name, which resolves this issue.

**Comment by ffulin** [comment]
v0.90 has now been released which includes a fix for this issue.  Thanks again for reporting the problem!
