### ISSUE TITLE
Process argument tokenization on OSX

### ISSUE THREAD

**Issue by nedwardsnae** [fastbuild/fastbuild#510]
Hi!

I've encountered an issue in v0.96 where clang will fail to produce objects due to missing files included by the code being compiled. Running clang in verbose mode, it complains about the include paths I'm specifying:

`ignoring nonexistent directory ""/my/include/path""`

I'm adding the include path like this:

`-I"/my/include/path"`

The path does exist, before I go any further :). In fact, I can copy the command printed by -showcmds and run it fine in the terminal. It seems to be that the arguments which clang receives differ to the ones that FASTBuild says that it is sending. In the message that clang prints above, my include path is being enclosed in an additional set of quotes. Also, when running clang in verbose mode, the include path argument is being shown as this:

`-I "\"/my/include/path\"`

If I remove the quotes from around the include path in the .bff, FASTBuild will happily compile my code. However, this is due to the fact that there aren't any spaces in any of my include directory paths. It seems that clang can't handle an include path in quotes being passed as a single token in argv.

So as a temporary "hack" to fix things for myself, I've modified Process::Spawn to find the first and last quotes (if any) in the argument, and removing them (instead of just doing the BeginsWith/EndsWith checks).

However, I'm not sure if this is just one problem I've encountered which I've managed to patch up, and so there may be additional issues with how the arguments string is tokenized compared to how the system does it, which is resulting in the difference in behaviour.

By the way, I have noticed that this seems to be something which FASTBuild's own bff file appears to work around for Linux and OSX? I should note that I'm working with a UE4 project, and am therefore not writing the BFF by hand, but am just translating the build actions to the BFF.

Hope this helps give enough info about the issue. :)

Thanks,
Nick

**Comment by ffulin** [comment]
It does seem like the arg handling perhaps needs to be a little more elaborate. I think your hacky fix is in the right direction, but some investigation will need to be done into how to get the right behaviour in a way that is as consistent as possible between platforms and working out the best way to handle things like slash escaping.

**Comment by ffulin** [comment]
Various arg parsing fixes have been implemented in https://github.com/fastbuild/fastbuild/commit/36a8b4dbce16c930afcd14210c80a69529ec3ada

One of those fixes was to extend the quote handling logic in process spawning on OSX and Linux to correctly handle quotes "inside" args as well as args completely surrounded by quotes.

These fixes will be in the next release (v1.13). I'll keep this issue open until that version is released.

**Comment by ffulin** [comment]
v1.13 has now been released and includes this fix. Thanks again for reporting the bug.
