### ISSUE TITLE
Question|WorkerConnectionLimit

### ISSUE THREAD

**Issue by axmetishe** [fastbuild/fastbuild#518]
Hi @ffulin 

I've tried to distribute build at maximum and set WorkerConnectionLimit=40 via settings
```
Settings 
{
    .WorkerConnectionLimit = 40
}
```

According to info present on builder nodes via FBuildWorker it seems like there are more than 40 thread build remotely and that's good actually but at workstation I see only 20 threads at max.

Is that because of default -j[x] option behavior and can I set them more than cores count safely in order to fastly consume workers output or this will not increase performance?

Regards.

P.S.
>fbuild -version
FASTBuild - v0.96 - Copyright 2012-2018 Franta Fulin - http://www.fastbuild.org

Workers count: 72

**Comment by ffulin** [comment]
The -jx option is not related to distributed compilation. It controls the number of local threads in the thread pool used for work that can only be performed locally. This should pretty much always be equal to the number of CPU cores on the host (i.e. the default if you don't specify the argument)

I'm not sure exactly what you are looking at, so I'll try to provide some general info about how to understand what is going on wrt distributed compilation.

Let me know if that helps, or if I can provide some more info.

*Understanding in-flight work*

If you look at the progress output @ the command prompt, you can gain a little more insight into what is going on. For example, the line below:
``` 1.5 % [--------------------] 07s (8/30)+(12/52) /```

shows that 8 local CPUs are processing work out of 30 tasks that can only be done locally. In addition to that, we're prepared 52 tasks for distributed compilation, 12 of which are currently being worked on remotely.

In this case, we are not bound on the local machine (as there are 40 additional distributable jobs ready to go).

If the output was to look like this however:
``` 1.5 % [--------------------] 07s (8/30)+(12/12) /```

then it's fairly likely that we are bound on the performance of the local host.

You can potentially use something like the https://github.com/hillin/FASTBuild-Dashboard to gain some visibility if you haven't already.

If you haven't already, you can try using -distverbose to gain a little more insight into how many connections have been made to your workers. This can sometimes be helpful identifying network connectivity problems.

*Bottlenecks*

Things like code structure, use of Unity, the compiler being used, network speed, local IO performance and many other things can all factor into how well distribution works at any given time. It would be fair to say however, that most users run into a situation where the local machine is the bottleneck, and adding no more parallelism can be achieved, regardless of how many workers you add. Typically more than 20 hosts is unlikely to improve performance in most cases and increasing the WorkerConnectionLimit can actually make things worse (as it causes more network chatter) so should be done cautiously.

**Comment by axmetishe** [comment]
Hi @ffulin,
Thank you for your answers.

My bad is that I'm not described the "Lab" environment I've used and the question looks very general.
We have several UE4 projects and more than 20 build configurations for them and we've used https://github.com/liamkf/Unreal_FASTBuild for distributed compilation using FASTBuild.
At some point I've realized that cache used not in optimal way due to specific paths of sources and direct usage of response files from VCToolChain in UnrealBuildTool also task overhead generated by this method which produces one action for one source file with same parameters.
However even such non-optimal compilation gave us huge performance increase - 6 minutes versus 30 minutes for Win64 game build without FASTBuild.

In order to eliminate issues mentioned above I've wrote the FASTBuild toolchain for UnrealBuildTool(can't share sources due to company restrictions at least for now) where I'm not using the response files from VC but generate the BFFs directly without separation by each file, using relative paths. All of this reduce build time with additional 2 minutes when the cache is not fully populated and total compilation disabling when it does and only 1 minute execution for linkage stage. Additionally we've eliminated 4042 link error because modules are consistent now and not duplicated.

We have specific build hosts for these projects. It's a 6 builders with 16-20 cores, 32Gb RAM, 1GBps network(at second quarter will be 10GBps) and RAID0 over Samsung EVO(2000 MBps at sequential write and 300 MBps at random write, 4000 MBps and 500 MBps at read operations) each.

During written toolchain performance testing I'm not cross the upper hardware limit, tasks was greatly parallelized except for linkage and PCH generation operations which must be done locally. Network operations are also were OK - with spikes up to 740Mbps.
![02](https://user-images.githubusercontent.com/12981432/50814602-51e51580-132b-11e9-8dee-618f84a810ba.png)
![04](https://user-images.githubusercontent.com/12981432/50814613-590c2380-132b-11e9-9b80-8d67af7fe391.png)
![05](https://user-images.githubusercontent.com/12981432/50814616-5d384100-132b-11e9-9a1a-6add88001e04.png)
![06](https://user-images.githubusercontent.com/12981432/50814618-60333180-132b-11e9-96a2-19da85b6db2b.png)
![03](https://user-images.githubusercontent.com/12981432/50814619-65907c00-132b-11e9-8d8a-a38c6d6225bb.png)

I've assumed that with such workers amount it will be better if linkage and of course PCH creation operation has a priority for local executors because other operations was distributed and I've increased the amount of local workers up to 40 which gave me another 20 second build time reduction.
Unfortunately I can't use such configuration at production due to simultaneous runs of different builds which possibly reduce overall performance in case any compilation task will be runned locally.

And now I guess my question was - can I somehow run locally only operations which can't be executed remotely?

P.S. We've got huge performance increase with your product already but I guess we must to strive to perfection=)

**Comment by ffulin** [comment]
Thanks for the extra details. It's great to see you getting such big speedups, but of course we all want more :)

When it comes to the local CPU cores, they already prioritize local-only work. They only perform work which could be distributed if there is nothing else to do. There are two different internal queues, and the distributed one is only pulled from when the local one is empty. This means linkage and pch creation is always prioritized locally already.

There are some situations in which we might be better off doing nothing locally so that when a task is returned, you can start it immediately instead of waiting for the distributable task we started to finish. If you want to experiment to see if this is a case you have, you can try using the http://www.fastbuild.org/docs/options.html#forceremote option. That option does come with some problems as described in the documentation I linked, but others have reported it improving overall performance in some scenarios. Perhaps there is a world in which FASTBuild could know when we should favor one behaviour over the other dynamically, or assign different behaviours to different CPUs (like reserving some for local-only perhaps).

Speaking more generally about your performance quest, what we probably need to do is understand where the bottleneck is. Two ways we might be able to gain some insight into that:
a) Use the FASTBuild Dashboard to visualize the overall build timing to see if any bottlenecks are apparent.
b) Build the Profile configuration of FASTBuild from source yourself. This outputs a chrome-tracing compatible json file. This might highlight some unexpected bottlenecks we can target.

Let me know if that helps :)

**Comment by axmetishe** [comment]
Thanks for pointing me to '-forceremote' flag since I've missed it somehow reading documentation.
Unfortunately it gave no any speedup but makes it even force and I guess due to it's cache exclusive nature - https://github.com/fastbuild/fastbuild/blob/199e92be3b58301eb815b9688725b669feb2dfec/Code/Tools/FBuild/FBuildCore/FBuildOptions.cpp#L228
I assume that depending on the build process flow it could increase performance but in most cases cached results will be much faster than distributed compilation.
Why this flag disables cache usage? I guess the task scheduler could take into account cached results and at the same time force remote compilation. Is that because of some kind of race-conditions or scheduler behaviour?

By the way had no chance to run FASTBuild with profiling features yet will reply you about that as soon as possible.

P.S. I've tried to use the FASTBuild Dashboard but console output with '-distverbose' or '-cacheverbose' are more familiar to me=)

Regards.

**Comment by ffulin** [comment]
**> Why this flag disables cache usage?** 

That actually looks wrong to me and I think that should be removed. Given that the cache can be controlled as needed, I think this option should not affect cache settings at all.

As a work-around, so you can run the test while keeping caching, you should be able to just make sure you specify the cache options after -forceremote on your command line so they are enabled anyway.

**Comment by ffulin** [comment]
In the next version (v0.98) -forceremote will no longer modify caching settings (https://github.com/fastbuild/fastbuild/commit/a59e38a38de1c5494e32199bfa9097183e707d63).

I'll leave this issue open until that version is released. I think once that is resolved, there isn't anything else actionable in this issue, but let me know if I missed something.

**Comment by axmetishe** [comment]
@ffulin great, thank you for update. You helped me a lot and of course this request can be closed.

Unfortunately I'm too away from FASTBuild implementation details for now due to different tasks and hope to return to profiling and Android/IOS toolchain implementation in the next three months so it's possible the new questions will be raised=)

Thank again for great product and support.
Regards.

**Comment by ffulin** [comment]
v0.98 has now been released and contains the fix so that -forceremote no longer modifies cache settings.
