### ISSUE TITLE
Using clang 7.0.1 breaks Visual Studio debugging

### ISSUE THREAD

**Issue by KeyserSoSay0** [fastbuild/fastbuild#522]
I was trying to get a windows project working using clang and I couldn't get breakpoints to actually hit in Visual Studio until I noticed that the main fastbuild project uses clang version 5.0.1.  When I switched from 7.0.1 to 5.0.1 is started working, and it breaks again when I switch back.  Just wanted to let people know in case this isn't a known issue (I couldn't find anything about it).

Also of note, I was originally trying to use clang++ as the linker instead of using Visual Studios' link.exe, and it actually almost works in 7.0.1.  The only thing throwing it off is that fastbuild is actually compiling the file in a temp folder like C:\Users\Home\AppData\Local\Temp\.fbuild.tmp\0xc6635309\core_4\94BBC3BD\Test.cpp, and I couldn't find anyway to embed the actual file path in the pdb instead of the temp file path.  Link.exe must handle this somehow that clang doesn't.

**Comment by KeyserSoSay0** [comment]
Oh actually clang++ works as the linker in 5.0.1 too.  So it must just be some change in clang that doesn't handle files in temp dirs.

**Comment by ffulin** [comment]
Might be worth raising an issue in the Clang bug tracker to get to the bottom of what has changed?

**Comment by belkiss** [comment]
Heya!
If you break the execution and double click in the callstack on another line, are you getting "the source file is different from when the module was built"? If so, it seems to be a bug in clang itself that computes an incorrect MD5 for the files when building from preprocessed output, that will end up in the pdb, whereas visual studio seems to clear the value, and in the pdb there's no MD5 at all (we've seen that with the help of cvdump.exe).

About remapping the paths, we use this to the clang command line arguments to get proper remapping when files are built remotely:
`-fdebug-prefix-map="C:\fastbuild-work\.fbuild.tmp"="d:\where\your\code\is`

**Comment by KeyserSoSay0** [comment]
Ah yeah I was definitely seeing different MD5s as well.  I'll try with the prefix-map when I get a chance; although, it sounds like the MD5 issue will likely still break it.  Thanks for the info!

**Comment by KeyserSoSay0** [comment]
Finally got a chance to dig into this again and now I see what you meant about the MD5 now.  It looks like llvm 9 is going to add a "-gno-codeview-ghash" param that seems like it might not emit the MD5 so that it behaves like VS.  Compiling llvm from source on windows ended up being a pain, so I never actually got to test this.

I ended up taking the lazy route and just went to Tools->Options->Debugging->General and disabled "Require source files to exactly match the original version".  Obviously that has downsides, but at least it looks like the next version of llvm might have a real fix.

**Comment by ffulin** [comment]
Thanks for the update with your resolution.

Seems weird that the default behaviour of llvm (without a command line option) would be to make incompatible pdbs. Seems like that option should be on by default.

**Comment by belkiss** [comment]
FYI, reported a bug and attached a fix to the checksum mismatch issue in clang: https://bugs.llvm.org/show_bug.cgi?id=41215
