### ISSUE TITLE
Visual Studio project GUID generation problem

### ISSUE THREAD

**Issue by arttupeltonen** [fastbuild/fastbuild#53]
When a Visual Studio solution is generated, the generated GUIDs in the solution and project files do not match. When opening the generated .sln file, Visual Studio is forced to immediately update the GUID mismatch, resulting in a change in the opened file. This causes problems with version control.

There is a fix for this issue in pull request #52.

**Comment by ffulin** [comment]
I've integrated your fix (#52)[https://github.com/fastbuild/fastbuild/pull/52] for this issue into the Perforce mainline.  It will be in the next release (v0.87)

I'll close this issue when the new version is release.

**Comment by ffulin** [comment]
The fix is now live in the v0.87 release.
