### ISSUE TITLE
Provide a clang-format file

### ISSUE THREAD

**Issue by aganea** [fastbuild/fastbuild#536]
Ditto. It'd be nice if you could provide a clang-format file at the root of the repo, tailored for the formatting style you use on Fastbuild.
Thank you! :)

**Comment by ffulin** [comment]
I have been meaning to try out clang format for a while now, so I thought I'd use this as an opportunity. I got most of the way towards something that matches the desired style, but found it's impossible to have clang format # directives as I want.
i.e.
```C++
#if defined( BLAH )
    #include <xyz.h> // Impossible to have # hug the directive
#endif
```
I could maybe live with the alternatives possible here (have # on left and directive indented), but Clang does not support the following, which is a a deal breaker for me as all the cross-platform code is written to take advantage of this style:
````C++
void Function()
{
    #if defined( __WINDOWS__ ) // Impossible to indent directive in function
        DoWindowsStuff(); // Impossible to indent code relative to directive
    #endif
}```

There are two open issues which would go some way to resolving this:
https://bugs.llvm.org//show_bug.cgi?id=36019
https://bugs.llvm.org//show_bug.cgi?id=36020

Even with those fixed though, I'm not sure it would be exactly what I want.

As far as I can tell, Clang-format is "all or nothing" so it doesn't seem possible to have it respect the current layout of this stuff while applying the other desired formatting.

**Comment by ffulin** [comment]
I stopped investigating at this point, but it is also possible there are other issues.

**Comment by ffulin** [comment]
With the limitations of clang-format I don't think it can be used for the moment, which is a pity. We can re-evaluate again in the future if some of the lacking features are added.
