### ISSUE TITLE
How do we add several paths to .UnityInputExcludePath or .CompilerInputExcludePath

### ISSUE THREAD

**Issue by psallandre** [fastbuild/fastbuild#54]
Hi,
I tried that with no success:
        .UnityInputExcludePath      = ' $ProjectPath$/_NotUsed1'
        .UnityInputExcludePath      + ' $ProjectPath$/_NotUsed2'
One line is Ok, but once I add the second line then none of them are taken into account.
thx,

**Comment by ffulin** [comment]
If you want to add multiple exclusion paths, you need to specify them with the ArrayOfStrings syntax, as follows:
```C++
.UnityInputExcludePath =
{
    '$ProjectPath$/_NotUsed1/'
    '$ProjectPath$/_NotUsed2/'
}
```
The example you gave above is setting a single exclude path with spaces in it, equivalent to:
```C++
' $ProjectPath$/_NotUsed1/ $ProjectPath$/_NotUsed1/'
```

**Comment by psallandre** [comment]
Works great, thx!
