### ISSUE TITLE
the m_CPUUsageTotal is maybe not correct

### ISSUE THREAD

**Issue by tming** [fastbuild/fastbuild#541]
in the function IsIdleInternal() of file "Code\Tools\FBuild\FBuildWorker\Worker\IdleDetection.cpp" , the m_CPUUsageTotal may be not ok, for the kernTime  includes the amount of time the system has been idle 

https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-getsystemtimes 

suggested adjust (golang):
                idledelta     := idle - lastCpuIdle
		kerneldelta   := kernel - lastCpuKernel
		userdelta     := user - lastCpuUser
		totalusage = float64((kerneldelta+userdelta-idledelta)*100/(kerneldelta+userdelta))

**Comment by dummyunit** [comment]
`IdleDetection::IsIdleInternal` doesn't use `GetSystemTimes` directly, it uses a cross-platform wrapper (`IdleDetection::GetSystemTotalCPUUsage`) which subtracts idle time from the kernel time on Windows: https://github.com/fastbuild/fastbuild/blob/79cb4e05bb87bf245e4739b776bfc4695709dafa/Code/Tools/FBuild/FBuildWorker/Worker/IdleDetection.cpp#L161
So the logic seems fine to me.

**Comment by tming** [comment]
yes，the source is ok,  i took it wrong
