### ISSUE TITLE
 optimization suggestion for timeout

### ISSUE THREAD

**Issue by tming** [fastbuild/fastbuild#544]
we used fast build (dist_v0.96) to compile ue4,  our office bandwidth is only 100Mb, and we saw a lot of timeout, so i read the source code, and try to improve it.

My changes all focus on  this directory "dist_v0.96\Code\Tools\FBuild\FBuildCore\Protocol" ,  firstly,  I  changed enum { SERVER_STATUS_TIMEOUT_MS = 30000 }; to { SERVER_STATUS_TIMEOUT_MS = 150000 }  in file Protocol.h,  because 30000  is also the default timeout value for server send data, once server send data timeout, the client will deal the connection as timeout.

secondly, I adjusted the Server.cpp.

server worker will send heart beat by SendServerStatus by function within the following loop,

void Server::ThreadFunc()
{
    while ( m_ShouldExit == false )
    {
        FinalizeCompletedJobs();

        FindNeedyClients();

        SendServerStatus();

        JobQueueRemote::Get().MainThreadWait( 100 );
    }
}

FinalizeCompletedJobs  and FindNeedyClients are two loops to send data, and the timeout value for each send is 30000, so if any send fail, the heart beat will time out too.

my change for this is that, i will call SendServerStatus before each send within FinalizeCompletedJobs and FindNeedyClients, and for this, I split SendServerStatus to tow functions (SendServerStatus and SendServerStatusNoMutex), and the SendServerStatusNoMutex will be called within FinalizeCompletedJobs and FindNeedyClients.

void Server::SendServerStatus()
{
    PROFILE_FUNCTION

    MutexHolder mh( m_ClientListMutex );

    SendServerStatusNoMutex();
}

void Server::SendServerStatusNoMutex()
{
    const ClientState * const * end = m_ClientList.End();
    for ( ClientState ** it = m_ClientList.Begin(); it !=  end; ++it )
    {
        ClientState * cs = *it;
        MutexHolder mh2( cs->m_Mutex );
        if ( cs->m_StatusTimer.GetElapsedMS() < Protocol::SERVER_STATUS_FREQUENCY_MS )
        {
            continue;
        }
        cs->m_StatusTimer.Start();

        Protocol::MsgServerStatus msg;
        msg.Send( cs->m_Connection );
    }
} 

with these changes, it seems better in our case.

**Comment by tming** [comment]
void Server::FinalizeCompletedJobs()
{
    PROFILE_FUNCTION

    JobQueueRemote & jcr = JobQueueRemote::Get();
    while ( Job * job = jcr.GetCompletedJob() )
    {
        // get associated connection
        ClientState * cs = (ClientState *)job->GetUserData();

        MutexHolder mh( m_ClientListMutex );

        // ++ 
        SendServerStatusNoMutex();
        // --

        bool connectionStillActive = ( m_ClientList.Find( cs ) != nullptr );
        if ( connectionStillActive )
     
    ......
}

void Server::FindNeedyClients()
{
     .......
         while ( availableJobs > 0 )
    {
        bool anyJobsRequested = false;

        iter = m_ClientList.Begin();
        for ( ; iter != end; ++iter )
        {
            ClientState * cs = *iter;

            MutexHolder mh2( cs->m_Mutex );

            size_t reservedJobs = cs->m_NumJobsRequested;

            if ( reservedJobs >= cs->m_NumJobsAvailable )
            {
                continue; // we've maxed out the requests to this worker
            }

            // ++ 
            SendServerStatusNoMutex();
            // --

            // request job from this client
            msg.Send( cs->m_Connection );
       .......
}

**Comment by ffulin** [comment]
Thanks for your suggestions. I've been thinking about this aspect of the protocol for some time and I decided to simply remove the heart-beat logic entirely: https://github.com/fastbuild/fastbuild/commit/0271434426b1c27c144f2da838df251ceee11ebc). 

This change will be in the next release (v0.98). I will leave this issue open until that version is released.

**Comment by tming** [comment]
look forward to the next release ：）

**Comment by ffulin** [comment]
v0.98 has now been released and contains the removal of the heart-beat logic.
