### ISSUE TITLE
How to make a "clean" target

### ISSUE THREAD

**Issue by ggnkua** [fastbuild/fastbuild#545]
First of all, thanks for this great tool!

As a part of migrating our build system away from makefiles, we stumbled across the subject's title: people are used to "make clean" to wipe all object files etc. So I tried creating an "Exec" to perform this, but I'm baffled! Here's what I got so far:

```
Exec( "clean" )
{
  .ExecExecutable          = "/bin/rm"  ; Executable to run
  .ExecInputPattern        = "*.o" ; (optional) Pattern(s) to use when finding files (default *.*)
  .ExecInputPathRecurse    = true  ; (optional) Recurse into dirs when finding files (default true)
  .ExecArguments           = "-f"  ; (optional) Arguments to pass to executable
  .ExecInput               = "*.o" ; (optional) Input file(s) to pass to executable
  .ExecOutput              = "test" ; Output file generated by executable
}
```

Basically I would like to recurse all directories and wipe all .o files. However, I can't see the input pattern generating any lists to pass to "rm". Running ```./fbuild clean -showcmds``` gives:

```
BFF file '{...}/fbuild.bff' has changed (reparsing will occur).
1> Run: {...}/test
/bin/rm -f 
WorkingDir: 
ExpectedReturnCode: 0
1> File missing despite success for '{...}/test'
FBuild: Error: BUILD FAILED: clean                             
Time: 0.022s
```

(absolute paths removed using {...}). Obviously I'm doing something wrong, but I can't figure out what! Can anyone assist?

P.S. Ultimately I do have the source files as lists so I could do something like a pattern replace (for example cpp->o) and then feed them to rm, but it seems a bit convoluted to me.

**Comment by ffulin** [comment]
There are a few problems with your config. For completeness, I'll list them here, but I think there is also a better way to do what you want which I'll also detail.

- .ExecInput is a single input, not a wildcard. You don't need to specify that if you have ExecInputPattern
- You aren't passing the list of files to /bin/rm (so you are just running "rm -f". You can use the % 1 to pass the inputs to the executable
 - ExecOutput is not created. You are telling FASTBuild that a file called "test" will be created, but nothing will create that. This is why you have an error.  If the thing you run doesn't generate an output, you can use .ExecUseStdOutAsOutput

I think a better thing for you to use for a case like this is "RemoveDir". It can delete the contents of a directory and supports wildcards (http://fastbuild.org/docs/functions/removedir.html)

A couple of other notes: 
 - Deleting files through either of these mechanisms is not safe to perform in the same pass as then building them (as ordering is not guaranteed). Make sure you perform two separate invocations of fbuild.exe
 - if you actually just want a rebuild, you can use the -clean command line option (i.e. unlike make you don't need to delete all your files to force a clean build) (this avoids the two-pass issues above. You only need to create "clean" targets if you really want to only delete things)

Let me know if that helps.

**Comment by psomadop** [comment]
Thanks for the helpful feedback ffulin!

**Comment by ggnkua** [comment]
Thanks a lot for your detailed reply!

I should have mentioned it but forgot: at the point where I pasted my config above I was really throwing things to fastbuild at random. Sorry to have wasted your time on this.

I'll have a careful read of your reply later and figure this out. Again, thanks a lot :)

**Comment by ggnkua** [comment]
As expected, RemoveDir worked like a charm, so thanks!
