### ISSUE TITLE
Corrupted FDB after blue screen

### ISSUE THREAD

**Issue by ChrisRedacted** [fastbuild/fastbuild#556]
So a guy at our company who happens to have more-than-normal issues with his computer blue screening happened to have it blue screen just after he started a compile.

After re-starting, he could not compile or re-compile all. Fastbuild would die immediately with a return code of -2. I went over to his machine and deleted his FDB file. Then, fastbuild started working. I shudder to think how much time he might have wasted if I hadn't been there, known that this file existed, known what it was for, and suspected that nuking it would solve the problem. I don't know if there's a good way to report that or automatically deal with it? Or at least put in some trouble shooting steps. Or an error report.

**Comment by ffulin** [comment]
Completely coincidentally, I noticed that FASTBuild doesn't emit an error when failing to parse the fdb due to corruption. I fixed this a few days ago (https://github.com/fastbuild/fastbuild/commit/103055eac0fc08976069b45f18e7855ee1d2b56d). This fix will be in the next release (v0.99)

**Comment by ChrisRedacted** [comment]
Wow! Impressive turn-around time! Very cool!

**Comment by ffulin** [comment]
FASTBuild v0.99 has now been released which includes a fix for this issue.
