### ISSUE TITLE
CreateProcess does not support more than 32K chars as parameters

### ISSUE THREAD

**Issue by packadal** [fastbuild/fastbuild#57]
Hi !

I'm helping a bit on the CMake generator for Fsatbuild, and I've run into a problem, where very long command lines fail with Fastbuild.

When linking a large library, the command line can easily exceed 32K (I have 57K right here, and it's not the largest lib in the project) as CMake likes absolute paths better. And even if it used relative paths, this particular command line would be around 36K long.

I googled a bit and it seems there is a way around this:
http://blogs.msdn.com/b/oldnewthing/archive/2003/12/11/56043.aspx

I guess this would be a better way of passing information to the created process.

Best

**Comment by ffulin** [comment]
The 32KiB limit of CreateProcess is an operating system limitation. As far as I'm aware there is no general purpose way to overcome this limit. Overcoming it requires using custom param passing techniques which must be supported by the child process.  The page you link to describes a way to do it if you have access to the linker source code, which is not a general-purpose solution.

The Microsoft toolchain typically supports passing args via a ["response file"](https://msdn.microsoft.com/en-us/library/3te4xt0y.aspx) to overcome this limitation. Where possible, FASTBuild detects that you are using a tool (like link.exe) that supports response files and uses them if the args are > 32KiB.

What linker are you using? If you are using the MS linker, use of response files should be automatic. (If not there might be a bug - the full command line would be helpful here. (Use the [private support](http://www.fastbuild.org/docs/contact.html) email if you are not happy to past that info here.))

If you are using a non-Microsoft linker there are a few possibilities:
 * Look at the documentation to see if it supports response files.  Many linkers that emulate the MS one also support response files. We can easily add detection to FASTBuild for that.
 * See if it supports some other passing mechanism.  We can potentially add detection/support to FASTBuild for that.
 * Use FASTBuild's Unity feature to reduce the number of objects at link time (in addition to massively speeding up your compile times)
 * Create some intermediate libraries to merge your objects together, to reduce the amount of objects/libraries passed on the final link line.

**Comment by packadal** [comment]
I don't have the full linker command at hand, but it's something like "cmake.exe -E link msvc2013 [...]"

I discussed this problem with the main dev of the CMake Fastbuild generator, and he is already looking into response files, so I guess you can safely close this bug.

**Comment by ffulin** [comment]
If cmake.exe supports response files on Windows, we can make sure that FASTBuild uses those when invoking it.  Of course cmake.exe itself will need to make sure it uses response files when invoking link.exe to not have the same problem.

I'll close this issue for now.  Let me know what comes of your discussions and if there is anything to be done on the FASTBuild side.
