### ISSUE TITLE
[OSX][Linux] Race between FBuild and the compiler when writing to the object file

### ISSUE THREAD

**Issue by dummyunit** [fastbuild/fastbuild#595]
I have managed to reproduce locally the TestLocalRace failure that was [happening on Travis](https://github.com/fastbuild/fastbuild/pull/450#issuecomment-491411913). From the `strace` log it seems that the following is happening:
1. `fbuild` starts a remote compilation for an ObjectNode and then a local compilation for the same node.
2. Remote compilation completes and `fbuild` receives the result from network.
3. `fbuild` cancels the local job, which results in SIGTERM sent to the compiler.
4. `fbuild` doesn't wait for the compiler process(es) to exit (judging by the comment in `Client::WriteFileToDisk`) and writes the result of the remote compilation to the destination object file.
5. Compiler (assembler `as` to be precise) receives SIGTERM and `unlink`s the destination object file as part of the [cleanup process](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gas/as.c;h=c7bdf0cd8896c721f22439c46f0e0adfd2b9c5ff;hb=HEAD#l1294).
6. `fbuild` executes the librarian and it fails to open the object file which doesn't exist anymore.

So it seems that `fbuild` should stop writing to object files while local compiler processes are running. Instead it should either wait for them to exit in the thread that handles remote compilation results or write remote results to the files after waiting for compiler processes to exit in the thread that handles local compilation.  
And I suspect that in both cases a blocking implementation of `Process::KillProcessTree` would be required, otherwise we will wait only for `gcc` to exit and not for `as` started by it.

Here is the `strace` log for anyone interested: https://gist.github.com/dummyunit/b03f0190554831228fceba99257e45ce

**Comment by ffulin** [comment]
Thanks for looking into this. The investigation and your notes are very helpful.

When you mention:

**> judging by the comment in Client::WriteFileToDisk**

I assume you mean:

```Also, when a <LOCAL RACE> occurs, the local compilation process might not have exited at this point```. 

The code is talking about a condition that happens becasue of some code in Process::WaitForExit:

```C++
int32_t void Process::WaitForExit()
{
    ....
    if ( m_HasAborted == false )
    {
        // Don't wait if using jobs and the process has been aborted.
        // It will be killed along with the fbuild process if the TerminateProcess has failed for any reason and
        // it is useless to wait for it was anyways we are reporting a failing exit code.
        // Also, This accelerate further more the cancellation.
```

The problem with this code is that it's treating a global build cancel and the cancellation of single task as equivalent. (the m_HasAborted is set in Process::ReadAllData for single task OR global abort). The intention of this code is to let FASTBuild shutdown more quickly on a global terminate. Having said that, cancelling a build completely and rapidly starting a new one exposes us to the same error condition.

I think that this code (checking the m_HasAborted in Process::WaitForExit) is probably unsafe and needs to be removed entirely.

This code in Process:WaitForExit is Windows-only, however. The race condition probably exists there but might be hidden by the WorkAroundForWindowsFilePermissionProblem (which is sadly needed for legitimate windows-specific os-level problems)

On Linux and OS X, local termination seems to always wait for the process the to stop in Process::WaitForExit. It seems that we should already be waiting for the locally terminated task to exit on Linux and OS X before writing the cancelled object. So there is something a bit more subtle going on I think.

**Comment by ffulin** [comment]
This could be reasonably reliably reproduced by running the TestLocalRace in a loop on a VM with few CPU cores and under heavy CPU load. Prior to https://github.com/fastbuild/fastbuild/pull/607 I could reproduce the test failure within 10 attempts. After the fix, the failure was not seen after several hundred iterations.

The fix for this issues will be in the next release (v0.99). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
FASTBuild v0.99 has now been released which includes a fix for this issue.
