### ISSUE TITLE
can I use fast build to build .sln file directly?

### ISSUE THREAD

**Issue by BianChengNan** [fastbuild/fastbuild#597]
after searching on the internet, I didn't find any clue to build **.sln** file with **fastbuild**. I only found that we can convert a **.bff** file to **.sln** file, does **fastbuild** support convert a **.sln** file to **.bff** file, or does **fastbuild** support build **.sln** file directly? thanks for making this wonderful tool.

**Comment by ffulin** [comment]
FASTBuild is a replacement for MSBuild and the .bff files essentially replace the .vcxproj and .sln files. There is no way to generate the .bff files from an existing .sln file.

Once you create a .bff file, FASTBuild can be used to generate .sln files so that FASTBuild can be used from within Visual Studio.

**Comment by ffulin** [comment]
I will close this issue for now, but please let me know if I can provide any more information.

**Comment by BianChengNan** [comment]
> 
> 
> FASTBuild is a replacement for MSBuild and the .bff files essentially replace the .vcxproj and .sln files. There is no way to generate the .bff files from an existing .sln file.
> 
> Once you create a .bff file, FASTBuild can be used to generate .sln files so that FASTBuild can be used from within Visual Studio.

sorry for the late reply, I'm so so so sad to hear that, do you have any plan to support converting .sln -> .bff? I think it will be very useful function. thanks for your reply and thanks for this great tool.

**Comment by fsfod** [comment]
Someone did make a Visual Studio extension for converting and running a sln through FASTBuild https://github.com/liamkf/msfastbuild that might be of interest to you.
