### ISSUE TITLE
miss head file for memset

### ISSUE THREAD

**Issue by tming** [fastbuild/fastbuild#602]
when i compile latest version (0.98) on Mac, it will throw error: /Code/Tools/FBuild/FBuildCore/Protocol/Protocol.cpp:51:5: fatal error: use of undeclared identifier 'memset'

and it will compile ok after I add #include <string.h> in Protocol.cpp

**Comment by dummyunit** [comment]
This was fixed in #551.

**Comment by ffulin** [comment]
Thanks for the bug report. As noted by @dummyunit, this has been fixed in the dev branch.
