### ISSUE TITLE
I can't compile V0.98 version using VS2015

### ISSUE THREAD

**Issue by LuisRGameloft** [fastbuild/fastbuild#611]
Hi Guys , 
I attempt to re-compile FB but I got this warning, that is converted into error

\FB_v98\Code\Tools\FBuild\FBuildWorker\Worker\IdleDetection.cpp(433): error C2220: warning treated as error - no 'object' file generated
\fb_v98\code\tools\fbuild\fbuildworker\worker\idledetection.cpp(427) : warning C6001: Using uninitialized memory '**m_ProcessesInOurHierarchy[](i).m_ProcessHandle'.: Lines: 266, 267, 270, 271, 276, 277, 278, 279, 315, 420, 421, 423, 427, 429, 421, 423, 427
5> Failed to build Object (error 0x2) '\FB_v98\tmp\x64-Release\Tools\FBuild\FBuildWorker\Unity1.obj'

**Comment by ffulin** [comment]
This seems to be a false positive that only occurs with VS2015. If you don't have VS2017 available, you can locally disable static analysis by removing ```/analyze``` from the compilation settings in the main fbuild.bff

Sorry for the inconvenience.

**Comment by LuisRGameloft** [comment]
Ahh OK, no problem, I will attempt to compile using VS2017, I did just notice that detail, 
best regards
