### ISSUE TITLE
Fastbuild Window: how to disable PCH for specific files

### ISSUE THREAD

**Issue by Tan2NT** [fastbuild/fastbuild#613]
Hello,
I'm trying to integrate Fastbuild into my window project. This project contents both .cpp and .c files.
The .cpp files are configured to use precompiled header while the .c files aren't.
I generate the .bff file and config to use pch:

.PCHInputFile = '$Location$/../../source/MyLib/StdAfx.cpp'
.PCHOutputFile = .CompilerOutputPath + '/MyLib.pch'
.PCHOptions = .CompilerOptions
			+ ' /Yc"MyLib/StdAfx.h"'
			+ ' /Fo"%3"'
.CompilerOptions + ' /Yu"MyLib/StdAfx.h"'	

Then I built my project, it generated the error when compiled the .c: 
xxhash.c: fatal error C1853: './obj/x32/Debug/MyLib.pch' precompiled header file is from a previous version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)

The question is: how to configure to disable precompiled header for all the .c files? (I just want this setting for the .cpp files).

Thank a lot!

**Comment by ffulin** [comment]
If you have a set of files in a library and want to build some of them with different settings, you can do that through the use of additional ObjectLists. You can have as many of these as you need, supporting what ever split of files you need.

In your case, if it's just .c vs .cpp files, the split should be quite easy. Here's an example that should be close to what you need (please check all the paths etc are what you need):
```C++
// Common options
.CompilerOptions    = '-c %1 /Fo%2'
.CompilerInputPath  = 'mylib/'
.CompilerOutputPath = 'out/'

// Build .c files without PCH
ObjectList( ''MyLib-CFiles' )
{
    .CompilerInputPattern = '*.c' // Compile .c files
}

// Build .cpp files with PCH
Library( 'MyLib' )
{
    // Compile .cpp files (you can actually omit this since its the default - included here for clarity)
    .CompilerInputPattern = '*.cpp'

    // Configure PCH
    .PCHInputFile  = '$Location$/../../source/MyLib/StdAfx.cpp'
    .PCHOutputFile = '$CompilerOutputPath$/MyLib.pch'
    .PCHOptions    = '$CompilerOptions$ /Yc"MyLib/StdAfx.h" /Fo"%3"'

    // Use PCH when compiling files
    .CompilerOptions + ' /Yu"MyLib/StdAfx.h'

    // Merge the output of the .c ObjectList into this lib
    .LibrarianAdditionalInputs = 'MyLib-CFiles'
}
```

**Comment by Tan2NT** [comment]
Wow, your answer helpfully to me.
Thanks a lot!
