### ISSUE TITLE
[Window] Fastbuild on Visual Studio IDE

### ISSUE THREAD

**Issue by DarkFunny12345** [fastbuild/fastbuild#620]
Hi,

I'm having some issues about using Fastbuild on Visual Studio, I hope you can help me.
I was built successfully on Command Line with bff files was generated. But to able simply debugging, I'm trying to use Visual Studio IDE to building these bff files.
As far as I know, VSProject and VSSolution will be supported generating *.vcxproj (project) files and *.sln (solution) to use Fastbuild for building on Visual Studio IDE. But, I don't know where to add VSProject and VSSolution.

Could you please tell me know how to add VSProject and VSSolution to generating *.vcxproj, *.sln?
And Does Visual Studio have a plugin that supports Fastbuild integration to building for bff file? 

Thank a lot!

**Comment by ffulin** [comment]
When you use FASTBuild and you declare your targets (via ObjetcList, Library or Executable) in your bff files, you usually accompany those with VCXProject each. Then you create a single Solution() that references all of those projects. By building the Solution() target from the command line, the necessary .vcxproj and .sln files will be generated. You can then load this Solution in Visual Studio and build/debug from the IDE as normal.

The references for VCXProject and Solution can be found here:
 - http://fastbuild.org/docs/functions/vcxproject.html
 - http://fastbuild.org/docs/functions/vssolution.html

You may like to look at the FASTBuild source archive for a real-world example of how to use VCXProject and Solution inside a bff file. It can be downloaded here: http://fastbuild.org/docs/download.html

> And Does Visual Studio have a plugin that supports Fastbuild integration to building for bff file?

No Visual Studio plugin is required for compilation from Visual Studio. FASTBuild can generate the project files noted above and those can be directly used.

**Comment by DarkFunny12345** [comment]
Hi Ffulin,
Thank for your support. 

I still have another question, I hope you can answer.  Following your answer:
"When you use FASTBuild and you declare your targets (via ObjetcList, Library or Executable) in your bff files, you usually accompany those with VCXProject each"
So, If using VCXProject, we will have to re-declare all the targets for VCXProject to able generated *.vcxproj with the configs like as the configs of ObjectList in BFF file ==> Structs as below:
---------------------------------------------------------------------------------------------------
ObjectList('CRM_obj_C++-Debug-x64')
{
     // All the configs for this project

     .CompilerOutputPath = '$Location$/obj/x64/Release'
     .Defines = ''
     .IncludeDirs = ''
     .CompilerOptions = ''
}
Library('CRM-Debug-x64')
{
}

VCXProject( '$ProjectName$-proj' )
{
    // the configs same as ObjectList
}
----------------------------------------------------------------------------------------------------
Do I misunderstand what you mean?

Thank you for your time and attention.

**Comment by DarkFunny12345** [comment]
Hi Ffulin,
Thank for your support.

I still have another question, I hope you can answer. Following your answer:
"When you use FASTBuild and you declare your targets (via ObjetcList, Library or Executable) in your bff files, you usually accompany those with VCXProject each"
So, If using VCXProject, we will have to re-declare all the targets for VCXProject to able generated *.vcxproj with the configs like as the configs of ObjectList in BFF file ==> Structs as below:
ObjectList('CRM_obj_C++-Debug-x64')
{
// All the configs for this project

 .CompilerOutputPath = '$Location$/obj/x64/Release'
 .Defines = ''
 .IncludeDirs = ''
 .CompilerOptions = ''
}
Library('CRM-Debug-x64')
{
}

VCXProject( '$ProjectName$-proj' )
{
// the configs same as ObjectList
}
Do I misunderstand what you mean?

Thank you for your time and attention.

**Comment by DarkFunny12345** [comment]
Sorry for the spam,

Wow, awesome Fastbuild.
It seems that need only declare some functions special in VCXproject to able generating *.vcxproj (ex: .ProjectOutput, .ProjectBasePath).   
On Visual Studio, Fastbuild still based-on the bff file of projects + the solution 'fbuild.bff' to able building like as building on Command Line.

And now, everything cleaned.
Thank a lot to you.

**Comment by ffulin** [comment]
Looks like you worked it out. FASTBuild generates project files for Visual Studio which allows VS to run FASTBuild from within the IDE. The compilation is the same as if you invoked from the command line, but of course you can use the debugger and Intellisense like normal.

**Comment by DarkFunny12345** [comment]
Yes, 
everything worked. I will close this question.
Thank you a lot!
