### ISSUE TITLE
[Window] Fastbuild for Universal Windows Platform

### ISSUE THREAD

**Issue by DarkFunny12345** [fastbuild/fastbuild#623]
Hello,

I just applied successfully Fastbuild for Win32 project, and now I'm trying to apply Fastbuild for UWP project, but after I found the documents a long time, it seems that I can't find any the documents for Fastbuild on UWP project. 
So, could you tell me know current Fastbuild is support for UWP project?
If Fastbuild supported UWP project, could you tell me know the differences of BFF file between using for UWP project and Win32 project? 

Thank you a lot!

**Comment by ffulin** [comment]
What will be needed for your project will depend on how you have configured it and what features it requires. Assuming it's a C++ application, you'll likely at least need to use the /ZW but from there I can't really tell you much more.

If you look at the setup of your existing project in Visual Studio, and in particular the build steps and command line args used for each once, it should give an idea what's required.

It should be noted that it's entirely possible you won't be able to get some aspects of your UWP app working. I don't know anyone who is using UWP (with or without FASTBuild). It will probably come down to some experimentation and might depend on how heavily invested in the UWP/WinRT space your application is.

**Comment by DarkFunny12345** [comment]
Hi ffulin,
Thanks for your support!

"It should be noted that it's entirely possible you won't be able to get some aspects of your UWP app working"
=> So, it seems that Fastbuild able to support for UWP project but may also not support for UWP project.

I'm trying to edit bff file that following the configurations of default project on Visual Studio without Fastbuild. And edit some of the environment variables to config for Fastbuild for UWP. But I'm not sure these changes for bff file that right. 
So, could you please give me an example about the configurations within bff file of simple UWP project?

Thanks you!

**Comment by ffulin** [comment]
> could you please give me an example about the configurations within bff file of simple UWP project?
I'm sorry, but I don't have any examples available for UWP projects.

**Comment by DarkFunny12345** [comment]
Hi ffulin,
Thanks for your help!

It seems will be occurred when applying Fastbuild for UWP project.
but I will try to hack-out bff for all project that following the configuration on Visual Studio.

again, thank you for your time and attention,
a nice day to you!

**Comment by DarkFunny12345** [comment]
Hi ffulin,

Sorry for renew this page, because I don't want to create a new page.
I'm having some issues, could you please support me to answer about these issues?

I'm still trying to apply Fastbuild to UWP project, and in my solution of UWP project is containing some features, and I can't find any the documents of Fastbuild for these features:

Example:
GlobalSection(SharedMSBuildProjectFiles) = preSolution
		..\..\..\AAA_lib\SDK\BBB\w10\Release\src\build\**common.vcxitems***{9ada2-301e-470-a299- 
               14ad5d758}*SharedItemsImports = 4		
EndGlobalSection

**common.vcxitems** is a Project Shared Item and some libraries in our project are referencing to this item. So, I will be needed to add some configurations within BFF file to this BFF file able to reference to **common.vcxitems**. 
Could you please tell me know any function of Fastbuild can describe for Project Shared Item?

Thank you a lot!

**Comment by DarkFunny12345** [comment]
Sorry for above spam, I resolved that issue,
I'm using a lib to contains the shared file need reference in Shared Item Project, then will compile this lib like as static lib, then I will use .lib for the libraries necessary.
Thank you :)
