### ISSUE TITLE
[Window] Issues about XAML files in window apps

### ISSUE THREAD

**Issue by DarkFunny12345** [fastbuild/fastbuild#631]
Hi,

I'm trying to apply Fastbuild to a UWP project. but I encourtered some issues about XAML files ( XamlTypeInfo.Impl.g.cpp, XamlTypeInfo.g.cpp)
These XAML files are used to demonstrate the basic programming in windows store app developing, on Visual Studio IDE, MSbuild will auto-generate and auto-compile these XAML files to linking into the executable file via MarkupCompilePass1 and MarkupCompilePass2 task.
But it seems Fastbuild can't auto-generate and auto-compile these XAML files to linking into the executable file.

so, could you please give me any solution or idea to Fastbuild able to resolve this issue?

Thank a lot to you!

**Comment by ffulin** [comment]
Disclaimer: I haven't dealt with .xaml for some time, so please take this info as possibly outdated or wrong:

When I last looked into compiling xaml files directly, I found information that implied that the xaml compiler seemed to be no longer supported, with the functionality it provided being merged into msbuild.

If this is indeed the case, then I think your only option will be to invoke msbuild from FASTBuild when you want to compile this files. This is pretty weird, but perhaps it can work. You would problably need to capture the command line args and other inputs being passed to msbuild for these steps through some small amount of reverse engineering, if those options/command lines are not clearly visible in Visual Studio.

**Comment by DarkFunny12345** [comment]
Hi ffulin,

Thanks for your support, along time to meet you :)

I tried to using MSbuild to compiling only for xaml files, but it seems that MSbuild was integrated the stage to handle xaml files as a part of MSBuild. 
Currently, MSbuild of MSVS2015 is using Microsoft.Windows.UI.Xaml.Build.Tasks.dll for handle the compile xaml process through some tasks as MarkupCompilePass1 & MarkupCompilePass2 inside Microsoft.Windows.UI.Xaml.Common.Targets

I'm trying to find any way to use these tasks (MarkupCompilePass1 & MarkupCompilePass2) like as custom task that to using for generating XamlTypeInfo.g.cpp file because I see Fastbuild only need compiling for XamlTypeInfo.g.cpp, XamlTypeInfo.Impl.g.cpp to .obj files, and then Fastbuild able to linking successfully to an executable 
(for MSbuild: XamlTypeInfo.g.cpp file generated at during the compiling process. XamlTypeInfo.Impl.g.cpp generated before the compiling process, we only need to change anything from .xaml files or .xaml.cpp files)

=> we only need MSbuild to generate that files (XamlTypeInfo.g.cpp, XamlTypeInfo.Impl.g.cpp), then Fastbuild able to make the remaining work.
But it seems that to able generate that files, we have to use a .vcxproj / .proj file to contains xaml files, then using MSbuild to compiling these file to generate XamlTypeInfo.g.cpp, XamlTypeInfo.Impl.g.cpp files, then using Fastbuild to compiling and linking these files

Again, thank you so much!

**Comment by ffulin** [comment]
I don't think there is anything directly actionable on this ticket right now so I'm going to close it. If anything new comes up, we can open a new issue as needed.
