### ISSUE TITLE
Question: Cues to full-build only aliases impacted by some (modified) files.

### ISSUE THREAD

**Issue by francisbolduc** [fastbuild/fastbuild#635]
Hi,

We are looking for a way to optimize our CI process to only full-build/test what have changes and its impacts (instead of rebuilding everything at every push)
FYI, our repo have multiple apps built with fastbuild. And we aren't looking for incremental builds since our VM are spawned at push and destroyed when finished building

Probably using a file that contains all files modified, we are looking to either:
- use/create a command to get aliases impacted by theses changes
- or execute the building/testing process that are impacted by theses modified files

I'm aware how/when fastbuild build files and some limitations (https://github.com/fastbuild/fastbuild/issues/506#issuecomment-439715216 -- I don't know if it has changes much since that comment)

We know it is a complex feature to do but we are looking for cues if dev need be done inside fastbuild or not.

Could it be done by creating fbuild.fdb by putting the current timestamp to all unchanged file nodes and no timestamp to modified files?
Do you foresee some problems using this solution?

Or have you a better idea on how that could be done?

Thanks

**Comment by ffulin** [comment]
If I understand correctly, you want a freshly sync'd machine to be able to build only those targets that would be built if that machine had previously built according to an .fdb taken from another machine?

The state of a build is a combination of what is stored in the .fdb and the files on disk. When it comes to the files on disk, it's not just the source files, but also the intermediate files (object files, libraries, executables and others) that are part of the dependency graph. The core dependency traversal makes no distinction between these files, so even if you replace the timestamp of the source files with a hash, we'd still be missing many other files which would currently trigger a build.

It might be possible to traverse the dependency graph in such a way as to pretend all missing "output" files are up-to-date and emit a list of top-level targets of some type (like tests or executables for example) that recursively depend on any dirtied/missing/newly added "input" files. I think such a traversal mode would be difficult to cleanly implement and difficult to maintain as well as being full of problematic edge-cases.

I don't really have a good suggestion to do exactly what you're asking for. Assuming build-machine affinity/persistence is not possible, the only think close to a solution I can recommend for this is the use of a network cache to accelerate the rebuilds.

I'll keep thinking on this problem and let you know if I have any other ideas. While I don't see a good way to do this, I certainly understand the potential appeal of such a feature.

Of course, let me know if I can elaborate on anything I mentioned.

**Comment by francisbolduc** [comment]
Thanks for your time to answer this not so obvious problem.  😄 
What I fear most is the edge-case problems like you mention.

We have already a network cache on premise, but, most builds are now on cloud. 
To follow your recommendation, I will tried to relocate the network cache nearer to builds at first. I've no doubt that I will see a better result.

Thanks again

**Comment by ffulin** [comment]
I'm going to close this for now. We can reopen or create new issues if anything fresh comes up.
