### ISSUE TITLE
Unable to define custom platform in .VCXProject

### ISSUE THREAD

**Issue by cyberkm** [fastbuild/fastbuild#640]
Hello, I'm unable to define custom platform that is different from Win32 or x64 in the .Platform field for vcxproject config.
When i set it to Win32 or x64 everything works great, but the moment I change it to something else the MSBuild fails.

Example log attached.

```
1>------ Build started: Project: UpdateSolution, Configuration: Debug Win64-Production ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.InvalidPlatform.Targets(21,7): error MSB8006: The Platform for project 'UpdateSolution.vcxproj' is invalid.  Platform='Win64-Production'. This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Platform.
1>Done building project "UpdateSolution.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by cyberkm** [comment]
Never mind, found my problem.
Closing.

**Comment by cyberkm** [comment]
Invested into the problem a little more and found that the solution i found is a little bit problematic, so I'm reopening the issue with a bit more info.
I though that simply adding new platform to visual studio VCPlatforms folder will be enough, but unfortunately it will lead to more problems when my project gonna be used by many devs. There is a huge chance that somebody will forget to add new platforms to the VCPlatforms folder,
I saw that Unreal engine generates new platfrom types without need to modify files in VCPlatforms
So there must be away.
This is the reason I'm reopening the issue, as the custom platform tag indeed doesn't work in fastbuild :)

**Comment by ffulin** [comment]
There are 4 properties that take part in the project configuration matrix. The Config and Platform on the VXLProject, and the Config and Platform on the Solution. It's not very obvious, but while 3 of these can be set freely named as you like, the Platform setting on the VCXProject can only be set to specific value which are supported by Visual Studio (Win32, x64 etc). The exact list of values can be seen in the Visual Studio UI and can depend on whether you've installed additional platform support (for things like the PS4 or Android for example).

The Platform value on the VCXProject controls things like debugging so generally needs to be set to the "real" platform.

I'm not sure if Unreal is doing something special that might allow more flexibility, but I would assume that it either follows the same restrictions, modifies the projects in some way, or adds extra platform support to Visual Studio somehow.

fwiw, even with this restriction, it's possible to have a single solution that supports multiple compiler flavors (like Clang and MSVC), multiple target platforms and multiple build configurations (or a combination of all three). It's also possible to have the Solution Config/Platform drop-down box list exactly what you want, as it can be mapped under the hood to any project configuration.

It's a little hard to go into more specifics, since this can all be managed more than one way. If you could/want to provide some more information, I might be able to suggest something more concrete.

**Comment by ffulin** [comment]
There is nothing actionable on this issue, so I'm going to close it. We can re-open or create a new issue if new information comes to light.

**Comment by benjcarson** [comment]
We're running into what looks like the same issue when trying to add a linux cross-compilation target to our project.  When we load our solution in VisualStudio, it complains with the following error:

```
foo.vcxproj : warning  : Platform 'linux' referenced in the project file 'foo' cannot be found.
```

We have two compilers defined, `MSVC` and `Clang`, with clang setup for cross-compilation to linux (using a custom sysroot):

```
Compiler( 'Compiler-MSVC-x64' )
{
    .Executable = '$VSBinPath$/cl.exe'
    // ...
}

Compiler( 'Compiler-Clang-x64' )
{
    .Executable = '$LinuxClangBinPath$/clang++.exe'  // using custom toolchain, not the version bundled with VS
}
```

We have two configurations we want to support across both of these compilers, `debug` and `release`.  We end up with this list of configs (full compiler & linker switches omitted for brevity):

```
.MSVC_x64_DebugConfig = [
    Using(.MSVC_BaseConfig)

    .ConfigArch      = 'x64'
    .ConfigName      = 'debug'
    .ConfigPlatform  = 'windows'
    // ...
]
.MSVC_x64_ReleaseConfig = [
    Using(.MSVC_BaseConfig)

    .ConfigArch      = 'x64'
    .ConfigName      = 'release'
    .ConfigPlatform  = 'windows'
    // ...
]
.LinuxClang_x64_DebugConfig = [
    Using(.LinuxClang_x64_BaseConfig)

    .ConfigArch     = 'x64'
    .ConfigName     = 'debug'
    .ConfigPlatform = 'linux'
    // ...
]
.LinuxClang_x64_ReleaseConfig = [
    Using(.LinuxClang_x64_BaseConfig)

    .ConfigArch     = 'x64'
    .ConfigName     = 'release'
    .ConfigPlatform = 'linux'
]
.Configs = {
    .MSVC_x64_DebugConfig
    .MSVC_x64_ReleaseConfig
    .LinuxClang_x64_DebugConfig
    .LinuxClang_x64_ReleaseConfig
}
```

We generate our main project like so:

```
    VCXProject( '$ProjectName$-proj' )
    {
        .ProjectOutput     = '$OutputBase$/$ProjectPath$/$ProjectName$.vcxproj'
        .ProjectInputPaths = '$ProjectPath$/source'
        .ProjectBasePath   = '$ProjectPath$/source'

        .DebugConfig = [
            .Platform = 'x64'
            .Config   = 'debug'
            .ProjectBuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide $ProjectName$-windows-x64-debug-all'
            .ProjectRebuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide -clean $ProjectName$-windows-x64-debug-all'
            .LocalDebuggerCommand = '$OutputBase$/$ProjectPath$/windows/debug/client/$ProjectName$.exe'
        ]
        .ReleaseConfig = [
            .Platform = 'x64'
            .Config   = 'release'
            .ProjectBuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide $ProjectName$-windows-x64-release-all'
            .ProjectRebuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide -clean $ProjectName$-windows-x64-release-all'
            .LocalDebuggerCommand = '$OutputBase$/$ProjectPath$/windows/release/client/$ProjectName$.exe'
        ]
        .LinuxDebugConfig = [
            .Platform = 'linux'
            .Config   = 'debug'
            .ProjectBuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide $ProjectName$-linux-x64-debug-all'
            .ProjectRebuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide -clean $ProjectName$-linux-x64-debug-all'
        ]
        .LinuxReleaseConfig = [
            .Platform = 'linux'
            .Config   = 'release'
            .ProjectBuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide $ProjectName$-linux-x64-release-server'
            .ProjectRebuildCommand = 'cd ..\..\ && $FBuildCmd$ -ide -clean $ProjectName$-linux-x64-release-server'
        ]

        .ProjectConfigs = { .DebugConfig, .ReleaseConfig, .LinuxDebugConfig, .LinuxReleaseConfig }
    }
```

Note we have several other VCXProjects in our solution that follow the same pattern.  

Here's our solution definition:

```
VSSolution( 'solution' )
{
    .SolutionOutput = '$OutputBase$/foo.sln'
    .SolutionProjects = { ... }

    .SolutionConfig_Debug = [
        .Platform = 'x64'
        .Config   = 'debug'
    ]
    .SolutionConfig_Release = [
        .Platform = 'x64'
        .Config   = 'release'
    ]
    .SolutionConfig_LinuxDebug = [
        .Platform = 'linux'
        .Config   = 'debug'
    ]
    .SolutionConfig_LinuxRelease = [
        .Platform = 'linux'
        .Config   = 'release'
    ]
    .SolutionConfigs = { .SolutionConfig_Debug, .SolutionConfig_Release, .SolutionConfig_LinuxDebug, .SolutionConfig_LinuxRelease }
    .SolutionBuildProject =  { ... }
}
```

Solution generation works without issue, however when loaded in VisualStudio it emits the error mentioned above.  It seems like we're bumping into the limitations of the platform value on the VCXProject that @ffulin mentions above?

> It's a little hard to go into more specifics, since this can all be managed more than one way. If you could/want to provide some more information, I might be able to suggest something more concrete.

Our goal is to allow devs to build & run Windows debug/release day-to-day, and then compile linux periodically to verify their changes.  Would you be able to provide some suggestions on how to set things up to do so?

Happy to provide more info if it's useful!

**Comment by ffulin** [comment]
I find the way Visual Studio wants this setup to be somewhat unintuitive. Specifically the primary gotcha is that the .Platform on the vcxproj cannot be any arbitrary string. It must match specifically installed platforms, which by default are something like ARM, Win32 or x64. In some cases third parties can add extra ones, like "ORBIS".
I think, but I'm not certain, that it's the folders that exist here (and the files within them) that dictate what is valid:
```
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Platforms
```
This means that while things such as the .Config, SolutionConfig and .SolutionPlatform can be set arbitrarily, the .Platform is restricted and if you have two "x64" platforms, like Windows and Linux for example, you need to disambiguate them via the .Config.

I put together an example, which is a greatly simplified version of what is in the FASTBuild source, that might be helpful:
```
// Projects
//----------------------------------------
// .Platform must be specific strings as shown in VS Configuration Manager
// .Config can be arbitrarily set
.Config_Linux_x64_Debug     = [ .Config = 'Linux-Debug'     .Platform ='x64' ]
.Config_Linux_x64_Release   = [ .Config = 'Linux-Release'   .Platform ='x64' ]
.Config_Windows_x64_Debug   = [ .Config = 'Windows-Debug'   .Platform ='x64' ]
.Config_Windows_x64_Release = [ .Config = 'Windows-Release' .Platform ='x64' ]

VCXProject( 'project' )
{
    .ProjectConfigs = { .Config_Windows_x64_Debug
                        .Config_Windows_x64_Release
                        .Config_Linux_x64_Debug
                        .Config_Linux_x64_Release }
    .ProjectOutput = 'out/project.vcxproj'
}

// Solution
//----------------------------------------
.SolutionConfig_Linux_x64_Debug =
[
    // Name for selection in VS drop down (can both be arbitrary)
    .SolutionPlatform = 'Linux-x64'     .SolutionConfig = 'Debug'

    // Map to Project config (must match a valid VXCProject config combo)
    .Config = 'Linux-Debug'             .Platform ='x64'
]
.SolutionConfig_Linux_x64_Release =
[
    .SolutionPlatform = 'Linux-x64'     .SolutionConfig = 'Release'
    .Config = 'Linux-Release'           .Platform ='x64'
]
.SolutionConfig_Windows_x64_Debug =
[
    .SolutionPlatform = 'Windows-x64'   .SolutionConfig = 'Debug'
    .Config = 'Windows-Debug'           .Platform ='x64'
]
.SolutionConfig_Windows_x64_Release =
[
    .SolutionPlatform = 'Windows-x64'   .SolutionConfig = 'Release'
    .Config = 'Windows-Release'         .Platform ='x64'
]

VSSolution( 'solution' )
{
    .SolutionConfigs = { .SolutionConfig_Linux_x64_Debug
                         .SolutionConfig_Linux_x64_Release
                         .SolutionConfig_Windows_x64_Debug
                         .SolutionConfig_Windows_x64_Release }
    .SolutionProjects  = { 'project' }
    .SolutionOutput = 'out/solution.sln'
}

Alias( 'all' ) { .Targets = 'solution' }
```

**Comment by benjcarson** [comment]
This is great, thank you!
