### ISSUE TITLE
"Failed to store fileId xxx for manifest " Problem on Mac

### ISSUE THREAD

**Issue by James-Z** [fastbuild/fastbuild#645]
Hi,
After updating the latest version of Mac. I got a weird problem.

- Mac version: macOS Mojave
- FBuildWorker and FBuild version: master branch. manually compiled.

"int open(const char *pathname, int flags, mode_t mode)" [(link) ](http://man7.org/linux/man-pages/man2/open.2.html)doesn't work in "FBuildWorker" anymore.
It could create folders, but can't write any file. the "open(...)" function always return "-1".
meanwhile I create a testing xcode project to test "open(...)" in the same folder with the same file name and the same parameters, it's all the same but YES!, the "open(...)" function in xcode project is working well. I really have no idea about that.

---
### Update
If FBuildWorker logs: `Failed to store fileId #number for manifest 0x20e.......` on the remote side.
That should be a **FireWall** problem.
1. Turn off the Mac firewall.
2. Kill the process named "FireWall" in the background, if there is.

**Comment by ffulin** [comment]
I'm a little confused by you saying "updating to latest version of mac". Do you mean the latest version of FASTBuild for mac?  Or the latest version of OSX (which is Catalina)?

The current status of FASTBuild is that it's used extensively in production on Mojave without any issues (both the official v0.98 release and latest from the "dev" branch). I'm not aware of any issues like the one you have described on Mojave.

FASTBuild on Catalina is as-yet untested.

Taking a wild guess, I would suspect that you may have a permissions problem. Perhaps you are trying to create files somewhere you don't have access rights. This working inside XCode could also be explained by XCode running with elevated privileges (which I believe it does for debugging)

Since you are compiling your own executable of FASTBuild, if you are able to check the errno when the open() fails, that might tell us what's wrong (if it's set to EACCESS for example)

**Comment by James-Z** [comment]
Hi,
Finally, I found some things.
After updating the latest version of XOS, `NSTemporaryDirectory(...)` changed the path of UE4 shader pre-compile files from `/tmp/xxx` to `/var/xxx/`, there's really need a hat-off to our lovely Apple.inc, changed without any notice, and looks like [no one knows about what happend](https://cocoadev.github.io/NSTemporaryDirectory/).

Sorry about the complaint and this dumb question.

**Comment by ffulin** [comment]
Thanks for the update - it'll be helpful to have this info here in case anyone else encounters this issue.

**Comment by James-Z** [comment]
Hi,
This issue comes back after I update to the latest version of xcode.
ALWAYS LOG "Failed to store fileId 248 for manifest 0x20e......."

FBuild and FBuildWorker are compiled from the version 0.99 source code.

**Comment by ffulin** [comment]
I still suspect that you are alternating between running FASTBuild inside and outside of XCode, and some folders are being created with elevated permissions or different ownership inside XCode which then prevents things working correctly when running outside of XCode.

My theory could be proven if you try the following steps:
 - run FBuildWorker in XCode for the first time and everything is ok
 - you run FBuildWorker outside of XCode and it fails
 - you delete all the temp directories FBuildWorker creates
 - you run FBuildWorker outside of XCode and it works

If this is the problem, it's entirely possible that FASTBuild is not creating the temporary directories and files with the correct permission settings. (FileIO.cpp and FileStream.cpp contain several TODO:MAC comments related to file/folder permissions)

**Comment by James-Z** [comment]
I didn't run FBuildWorker or FBuild inside XCode, even they were not compiled by XCode.
I downloaded the Source Code from GitHub and put the "FBuild" under the "/Code/" folder which has a "fbuild.bff", then run the command "./FBuild".
FBuildWorker could create folders under "/tmp", transport the UE4 ShaderCompilerWorker to "/tmp/_fbuild.tmp/worker/toolchain.xxxxxxxx/Engine/Binaries/Mac/" of the remote computer correctly, BUT when it encounters the "*.txt" like "RenderShader.hlsl" or "readMe.txt", it will have the problem.

**Comment by ffulin** [comment]
So far we've talked about:
 - OSX version (one version ok, one not?)
 - running the same cmd line from XCode or not?
 - running via FBuildWorker or perhaps not?
 - compiling shaders for Unreal?

I'm now confused as to exactly what is going on. Can you please clarify what is working and what is not?

**Comment by James-Z** [comment]
* OSX version is 10.15.1
* FBuild or FBuildWorker dose not running with xcode. CMD only
* Xcode version is 11.2(11B52)
* We have four mac-mini environments is same, I deploy FBuildWorker for each.
* yes, compiling shaders of Unreal4

✔ When I run with cmd `./FBuild` only the local mode, it works well. 
❌ But run with `./FBuild -forceremote`, the FBuildWorker on the remote mac will log _"Failed to store fileId 248 for manifest 0x20e......."_

**Comment by James-Z** [comment]
Hi, ffulin,
There's a process named "FireWall" running in the background on Mac, even I turn off the firewall in Preference.
That made me a little bit upset. Now it's work! Compiling 10,000 shaders of Unreal4 just 15 mins around.
