### ISSUE TITLE
Dealing with 'Stale' entries in the brokerage

### ISSUE THREAD

**Issue by ca-johnson** [fastbuild/fastbuild#646]
We use fastbuild in the cloud, with instances that have short lives.
This causes the number of entries in our brokerage to accumulate over time as machines use a particular hostname for less than 1 day

We havn't noticed any major consequences so far, but do you expect this to cause regressions in performance? 

What would you recommend for cleaning up entries for machines that are no longer available in the brokerage?

**Comment by bburgin** [comment]
See https://github.com/fastbuild/fastbuild/pull/636

Once this PR is accepted, you should be able to write a script that periodically removes older machine files from your brokerage path.

**Comment by bburgin** [comment]
@DavidCurtiss wrote a script. I posted it here:
https://gist.github.com/bburgin/b42f3a26a2e5661d2366dcdd2283b715

**Comment by ca-johnson** [comment]
Awesome, thanks!
