### ISSUE TITLE
Considering fastbuild but have some questions

### ISSUE THREAD

**Issue by bitflipper42** [fastbuild/fastbuild#650]
Hello!

- Is it possible to use just the caching side of Fastbuild without modifying our build system (we have used CMake for many years and have a lot of logic there)
- I couldn't find anything explaining how to do out of source tree builds.  Is it possible?
- I couldn't find any instructions on how to build Fastbuild itself.  Any pointers?

CI builds for our product is taking about 1 hour...we need to shorten that.
Thanks!

**Comment by ffulin** [comment]
Hello

**> Is it possible to use just the caching side of Fastbuild without modifying our build system (we have used CMake for many years and have a lot of logic there)**

The caching and distributed compilation functionality of FASTBuild requires you configure your build using FASTBuild. There is no generic distribution/caching mechanism. FASTBuild uses your compiler in this process and must now how it is invoked to understand what can be cached/distributed and to schedule the build accordingly.

**> I couldn't find anything explaining how to do out of source tree builds. Is it possible?**

I'm not really sure what you mean. Can you elaborate?

**> I couldn't find any instructions on how to build Fastbuild itself. Any pointers?**

Sadly this documentation is currently lacking and is something I plan to improve. Additionally, there are plans to simplify/automate this process.

To compile locally, you need to:
a) Obtain the source (unzip the archive from fastbuild.org or clone the GitHub repo)
b) Place the fbuild executable for your platform in the Code folder
c) (Windows only) If on Windows, update the VS2017.bff in External to point to the specific version installed (if not the same)
d) invoke fbuild from the command line with Code as the working dir
e) (Optional) Generate Visual Studio or XCode project files with "fbuild solution" or "fbuild xcode" respectively

**Comment by ffulin** [comment]
I'm going to close this issue for now. Let me know if you have anymore questions, or it I can elaborate on the answers I've given.

**Comment by bitflipper42** [comment]
Apologies I didn't get back to this.

I now understand why I would need to replace my build system with fbuild to get the benefits.  It cannot be used as a generic compiler replacement like other build caching systems.

What I was referring to as "out of source tree build" is the ability to leave the source code untouched and generate all build files and generated objects in a folder totally outside the source tree...if the source is in c:\source I would like to generate the solution, objs and exe in c:\buildfiles and leave the source tree (C:\Source) untouched.  
Is there a way to do this?

Thanks for this awesome product!  I like the overall idea and the steady stream of releases, we may decide to put the time and effort into replacing all those cmake files we have and translate them to Fastbuild. (Assuming we can do an out of source build)

**Comment by bitflipper42** [comment]
I wanted to leave here all the modifications I had to do to get it to compile in Windows VS 2019, in case it may be helpful for someone else.

in External\SDK\VisualStudio\VisualStudio.bff:
Disabled VS2017, enabled VS2019 in the #defines.

in External\SDK\VisualStudio\VS2019.bff:
Modified first two line to read:
.VS2019_BasePath         = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional'
.VS2019_Version          = '14.23.28105'

in SDK\Windows\Windows10SDK.bff:
modified the first two lines to read
.Windows10_SDKBasePath          = 'C:\Program Files (x86)\Windows Kits/10'
.Windows10_SDKVersion           = '10.0.18362.0'

in SDK\Clang\Windows\Clang7.bff:
modifed first line to read:
.Clang7_BasePath = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm'

With the above modifications it was able to generate the solution with "fbuild solution"

There were a couple of compilation errors related to mismatched sign (unsigned int vs int), but it may be different for you.

After fixing the compilation errors it was able to build all 6 configurations in the solution, so I was able to build using both native Ms compiler and with clang in VS2019 as well.

I was able to modify, recompile  and debug fbuild.  This is key for us since it means we could troubleshoot any issues with newer IDEs/compilers.

Also, @ffulin  in the process of building it I discovered ".ProjectOutput" variable, which is what I was looking for to be able to generate and build outside the source tree.  All my questions are now answered.

Now I just hope we can translate all the functionality we have in the CMake scripts into Fastbuild scripts.

Thanks!

**Comment by ffulin** [comment]
Regarding "out of source" builds; thanks for clarifying. I understand exactly what you mean now :)

To elaborate/clarify a bit further:

FASTBuild is completely independent of Visual Studio. You can compile without even having Visual Studio installed, as long as you have a compiler. The low-level nature of FASTbuild's config files means you can tell the compiler/linker/etc exactly where you want your output files. You can therefore of course have output files completely separate from the source files. This is certainly the normal/recommended way to do things.

Although not required, FASTBuild can generate Visual Studio projects. These are not used for compilation - they are purely for browsing/intellisense, to allow launching FASTBuild in a convenient way and to run/debug your built executables. FASTBuild still drives all the compilation and anything you setup in the FASTBuild config is respected when compiling from VS.

The .ProjectOutput option is only used to tell Visual Studio where to put it's own "other" temporary files (such as the Intellisense database and some log files). It doesn't relate to the compiler/linker intermediate or temporary files at all.

I hope this makes sense. Let me know if I can elaborate/clarify anything :)
