### ISSUE TITLE
100% Cache Hits using a networked cache location but almost zero network receive activity

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#652]
Haven't fully investigated this yet, but I just did a build on one of our build servers where it reported a 100% cache hit rate, but had almost no network receive activity (the cache is remotely located on another server).

@ffulin Do you have any ideas on where to start an investigation into this?

Thanks! Will report more as I investigate.

**Comment by missmah** [comment]
Reproduces on the latest `fastbuild 0.98` merged into our branch from `fastbuild/master` last night.

The build is faster using caching, so something must be happening. But, there's not nearly enough actual network traffic for what would seem to be needed/expected.

My best guess is that somebody is somehow doing something very intelligent about not fetching objects over the network whose hashes haven't changed since the last time the cache hit on those objects. AFAIK, `FastBuild` doesn't have this kind of logic, which would leave the OS (`Windows Server 2019`)?

I'd be pleasantly surprised if the OS is safely doing something that intelligent... I'll keep searching for the answer...

**Comment by missmah** [comment]
Possibly this is related to parts of the `SMB3` protocol...

**Comment by ffulin** [comment]
FASTBuild reads/writes from the cache path using normal file IO. It doesn't treat any particular path in any special way and doesn't have any additional (local) caching.

The only exception to this is if you implement a custom cache plugin, in which case you of course have full control over caching IO behavior (and could cache locally as well for example). Naturally, I would assume that's not the case here :)

I'm not very familiar with the details of SMB, so I'm afraid I can't really comment on whether it has any special sauce that might be in play here.

**Comment by ffulin** [comment]
I don't think there is anything for me to action in this issue, so I'm going to close it. We can re-open or create a new issue if new information comes to light.
