### ISSUE TITLE
support for older linux platforms

### ISSUE THREAD

**Issue by packadal** [fastbuild/fastbuild#66]
The currently distributed binary only supports Linux platforms with GCC 4.9 (CXXABI_1.3.8 required).

This excludes Centos7 which has GCC 4.8.

Is there a way the distributed binary can target a lower CXXABI ?

If this is bothersome for you, I could otherwise write CMakeLists for the purpose of bootstrapping to a lower CXXABI.

Thanks

**Comment by ffulin** [comment]
Hello. There's no specific ABI version requirement fro FASTBuild itself, so in general using an older ABI should be fine. From what I can tell, this might be possible using the same gcc version as now to generate the binary, but specifying the --enable-kernel compiler option to target the older ABI. If that's the case, I don't imagine there should be any problem lowering the version to improve compatibility.

Do you know which version of CXX ABI is required for Centos7?

**Comment by packadal** [comment]
It uses GCC 4.83, so fropm the [doc page](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)  it should be `GCC 4.8.3: GLIBCXX_3.4.19, CXXABI_1.3.7`.

However if there are no constraints, enabling compatibility with Centos6 (which will be fully supported until Q2 2017) would be nice. 
Centos6 uses GCC 4.4.7, and the doc says it has the same ABI as 4.4.2 : `GCC 4.4.2: GLIBCXX_3.4.13, CXXABI_1.3.3`.

Thanks !

**Comment by ffulin** [comment]
I've tried to use the --enable-kernel compiler option but no matter what version I specify, I can't get it to compile. For example:
```C++
--enable-kernel=2.4.32
```
results in this error:
```C++
cc1plus: error: unknown pass kernel specified in -fenable
```
I couldn't find any useful information on the Internet about this error.

I think I'm on the right track, but I'm not sure how to make it work from here.

**Comment by packadal** [comment]
Hi,

from what I've read the `--enable-kernel` flag is not the way to go, its purpose is to use newer kernel system calls or older ones, and does not relate directly to the glibc. Sorry I dod not catch this earlier, I should have paid more attention.

From [what I read](https://sourceware.org/ml/libc-help/2011-04/msg00032.html), the recommended solution is to build gcc against the old glibc, and use this gcc to create the executable.

This seems like quite a bit of work, so I tried throwing together a few CMakeLists to build FastBuild, which worked quite nicely.
I created a Pull Request with the CMakeLists in case anyone needs them (but once there are binaries targetting a lower glibc I highly doubt that will be necessary).
If you want I can create the binaries on a CentOS6 and send those to you.

**Comment by ffulin** [comment]
Ideally I'd like to make sure that all new releases have reasonably wide compatibility if possible, so if an older distro is supported it would be ideal to be able to compatible out of the box for that distro. 

I can see two options:
 - Switch my final build VM to an older distro
 - Attempt to get static link the libstdc++

The former is probably the simplest, but it also prevents use of more recent compiler versions which is a shame.

I did a bit of research into the latter, and it seems it might be a workable solution: statically linking the libstdc++ seems like it should work (as described here: http://www.trilithium.com/johan/2005/06/static-libstdc/ )

**Comment by packadal** [comment]
Sadly, distributing Linux binaries is not a simple problem.

If you static link the libstdc++ you still have to use the enable-kernel flag, otherwise there might be syscalls that are not supported on the target machine.

If you switch your final build VM to an older distro, there is always the possibility of using a newer compiler.
For instance in the case of centos, there is the package [devtoolset](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/) to easily install GCC 4.7.

IMHO this is the best support/effort ratio, and more than good enough.
