### ISSUE TITLE
Add Reordering to Tracing's Callback Dispatcher

### ISSUE THREAD

**Issue by ohoughton** [fastbuild/fastbuild#662]
This is a relatively minor issue.

I'd like to draw attention to the following code from DispatchCallbacksOutput in Tracing.cpp -- when dispatching callback functions for output, the dispatcher will conclude upon the first callback which wants a message suppressed, rather than concluding after all callbacks.
```cpp
for ( auto cb : m_CallbacksOutput )
{
    if ( (*cb)(message) == false )
    {
        m_InCallbackDispatch = false;
        return true; // callback wants msg supressed
    }
}
```

While I understand this is currently intentional (or at least code is designed around it at the moment, as the interaction between the callback in FLog and the callback in the fbuild tests would suggest), it seems difficult to make use of other callback functions beyond those already in use.  Any callback function added after a build was started will never be reached (due to the FLog callback function always returning false).  The callback array cannot be reordered except by removing and re-adding the functions, and when we would want to reorder we typically don't have access to the functions to remove them.  Could we add some form of priority, or the ability to add a callback to a specific position in the callback array?

The other option would be to adjust the callback dispatcher such that it only returns true or false after executing all callbacks.  This seems like the at-a-glance most logical execution path for the method, but it would require a decent amount of changes to the way the existing callbacks interact, so it's probably inadvisable.

**Comment by ffulin** [comment]
The current design is indeed intentional - the idea is that callbacks are registered in order of priority and can "consume" the output.

Can you tell me a bit more about the use-case you have for adding another callback? That might help understand what the right course of action is.

**Comment by ohoughton** [comment]
Honestly, I was looking at adding callbacks in tests.  On further consideration, I don't view this as important enough to change, so I'm going to close this.
