### ISSUE TITLE
how to generate .exe file from the source code?

### ISSUE THREAD

**Issue by shaojunping** [fastbuild/fastbuild#663]

**Comment by ohoughton** [comment]
The owner has a quick rundown in a similar issue, which I have copied and pasted below. 

To compile locally, you need to:
a) Obtain the source (unzip the archive from fastbuild.org or clone the GitHub repo)
b) Place the fbuild executable for your platform in the Code folder
c) (Windows only) If on Windows, update the VS2017.bff in External to point to the specific version installed (if not the same)
d) invoke fbuild from the command line with Code as the working dir
e) (Optional) Generate Visual Studio or XCode project files with "fbuild solution" or "fbuild xcode" respectively

**Comment by ffulin** [comment]
Thanks @ohoughton

**Comment by ffulin** [comment]
@shaojunping I think the info kindly provided by @ohoughton answers your question, so I'm going to close this issue for now. Let me know if you need any more info.
