### ISSUE TITLE
How to get attention on older, refactored and maintained PR?

### ISSUE THREAD

**Issue by lucianm** [fastbuild/fastbuild#664]
Hi @ffulin,

last time I've got some feedback from you on https://github.com/fastbuild/fastbuild/pull/291 was March 1st, since then I even found time to refactor my PR according to your suggestions, I even developed an external addon-module to retrieve project type Guids in the meantime. It all works well actually, maybe you want to have a look, maybe you want us to discuss it? I'd really hope this enhancement won't miss the next release.

With best regards,
Lucian Muresan

**Comment by ffulin** [comment]
I'm sorry it's taken so long to resolve this PR. As you can probably see there is quite a backlog. When mixing this with limited time, prioritizing bug fixes over new features, it means that anything that needs some iteration can take quite some time to resolve.

I've taken a look at the current state of the PR and detailed the state of things here: https://github.com/fastbuild/fastbuild/pull/291#issuecomment-559209430

Hopefully we can resolve the remaining things and get this in the next release.

**Comment by lucianm** [comment]
Hi @ffulin ,

thank you for the feedback, I can fully understand the situation, as I'm quite often facing myself similar ones. I just felt after our latest conversations in the PR where you suggested I should ask for guidance when I felt to and in the end after going through a first draft of an implementation addressing all those points we previously discussed, that for sure others will open up (your new comment kind of proves that, too ;-), I had myself questions, but now some of them might be obsolete or I'd have to reformulate. Well, I really felt this needs to be discussed about, so thank you, I'm closing the issue and will comment in the PR.
