### ISSUE TITLE
FASTBuild doesn't track outputted PDB files

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#673]
Hi!

I found an issue with the way FASTBuild handles dependency tracking for DLL/Executable: these node track the compiled executable and its inputs, but since FileNode can only tracks one output file they can't also track the associated PDB which is also potentially outputted by the node.

So FB knows how to produce the dll/exe, but **not the pdb**.
And more importantly, FB doesn't see at all the pdb file: if it's deleted it won't invalidate the target.

A simple way to reproduce the issue:
````
Compiler('MSVC-14.16.27023-Win64')
{
    .Root = 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64'
    .Executable = '$Root$/cl.exe'
    .ExtraFiles =
    {
        '$Root$/c1.dll'
        '$Root$/c1xx.dll'
        '$Root$/c2.dll'
        '$Root$/1033/clui.dll'
        '$Root$/msobj140.dll'
        '$Root$/mspdb140.dll'
        '$Root$/mspdbcore.dll'
        '$Root$/mspdbsrv.exe'
        '$Root$/mspft140.dll'
        'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Redist/MSVC/14.16.27012/x64/Microsoft.VC141.CRT/msvcp140.dll'
        'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Redist/MSVC/14.16.27012/x64/Microsoft.VC141.CRT/vccorlib140.dll'
        'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Redist/MSVC/14.16.27012/x64/Microsoft.VC141.CRT/vcruntime140.dll'
    }
}

ObjectList('Test-Obj')
{
    .Compiler = 'MSVC-14.16.27023-Win64'
    .CompilerInputFiles = { 'Test.c' }
    .CompilerOutputPath = 'Output/'
    .CompilerOptions = '/c /Z7 /MD /Zo /I . /I "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/INCLUDE" /I "C:/Program Files (x86)/Windows Kits/10/include/10.0.17134.0/ucrt" /I "C:/Program Files (x86)/Windows Kits/10/include/10.0.17134.0/shared" /I "C:/Program Files (x86)/Windows Kits/10/include/10.0.17134.0/um" /I "C:/Program Files (x86)/Windows Kits/10/include/10.0.17134.0/winrt" /DWIN32=1 /D_WIN32_WINNT=0x0601 /DWINVER=0x0601 /TC /W0  /Fo"%2" "%1"'
    .CompilerOutputExtension = '.cpp.obj'
    .AllowCaching = false
    .AllowDistribution = true
}

Executable('Test-Exe')
{
    .Linker = 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe'
    .Libraries = { 'Test-Obj' }
    .LinkerOptions = '/Out:"%2" /MANIFEST:NO /NOLOGO /DEBUG /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:CONSOLE /FIXED:No /NXCOMPAT /OPT:NOREF /OPT:NOICF /INCREMENTAL:NO /LIBPATH:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/lib/x64" /LIBPATH:"C:/Program Files (x86)/Windows Kits/10/lib/10.0.17134.0/ucrt/x64" /LIBPATH:"C:/Program Files (x86)/Windows Kits/10/lib/10.0.17134.0/um/x64" /NODEFAULTLIB:"LIBCMT" /NODEFAULTLIB:"LIBCPMT" /NODEFAULTLIB:"LIBCMTD" /NODEFAULTLIB:"LIBCPMTD" /NODEFAULTLIB:"MSVCRTD" /NODEFAULTLIB:"MSVCPRTD" /NODEFAULTLIB:"LIBC" /NODEFAULTLIB:"LIBCP" /NODEFAULTLIB:"LIBCD" /NODEFAULTLIB:"LIBCPD" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" "netapi32.lib" "iphlpapi.lib" "setupapi.lib" "dwmapi.lib" "imm32.lib" /PDB:"Output/Test.pdb" "%1"'
    .LinkerOutput = 'Output/Test.exe'
}
````
We then build the executable, outputing both Test.exe & Test.pdb: 
````console
$ ./FBuild Test-Exe
1> Obj: Test\Output\Test.cpp.obj
2> Exe: Test\Output\Test.Exe
FBuild: OK: Test-Exe
````
I can check then that FB does know about Test.exe, but not about Test.pdb:
````console
$ ./FBuild Output/Test.exe
FBuild: OK: Output/Test.exe
$ ./FBuild Output/Test.pdb
Unknown build target 'Output/Test.pdb'
````
And if I delete Test.pdb, leaving Test.exe untouched, Test.exe won't be invalidated:
````console
$ rm Output/Test.pdb -f
$ ./FBuild Output/Test.exe
FBuild: OK: Output/Test.exe
````

I remembered this old issue: #326, where the single output file limitation was already discussed, but it seems to have broader implications.

Note that I tried adding the pdb to PreBuildDependencies:
````
Executable('Test-Exe')
{
    .Linker = 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe'
    .Libraries = { 'Test-Obj' }
   // ...
    .PreBuildDependencies = { 'Output/Test.pdb' }
}
````
I thought it wil complain about missing 'Output/Test.pdb' when building 'Test-Exe', but the missing file was completely ignored.

I think FASTBuild should track the PDB file timestamp/existence to avoid this problem, 

But could you please give your thoughts about this problem please ?

Thanks!

**Comment by ffulin** [comment]
FASTBuild doesn't track "secondary" files. It might be possible to tell FASTBuild about secondary files like pdbs in the future, but there isn't a good way to represent this within the dependency right now. 

Thankfully, for the most part, this limitation doesn't really cause any problems and/or has easy work-arounds in the cases I've seen.

**The Deletion Case**

In the deletion case, if you want the pdb to be regenerated, you can delete the exe as well. The exe and pdb will be regenerated.

**The Dependency Case**

If you want something to depend on the pdb, let's say for example a step that copies the pdb to another folder, you can use .PreBuildDependencies as follows:

```C++
Executable( 'exe' )
{
    // All the normal exe creation stuff, assuming this creates
    // Output/exe.exe and Output/exe.pdb
}

Copy( 'copy-pdb' )
{
    .PreBuildDependencies = 'exe' // Depend on the exe, knowing that the pdb is a side-effect
    .Source = 'Output/Exec.pdb'
    ...
}
{code}

---

Do you have a case where this is problematic in some new way or can't be worked around?

**Comment by poppolopoppo** [comment]
Thank you for your detailed response,

The issue issue was found inside our integration with Unreal : it deleted a pdb file without deleting the associated dll before starting the build, and then made sure it was rebuilt after compiling. But the target was clean since the dll was ok, so the pdb was never generated and thus build failed irremediably (and it was happening after each successful build).

Turns out the main cause was a dependency declaration problem on Unreal side, and the pdb issue was avoided after fixing it (we use a custom node to inject back FASTBuild dependencies parsing inside UnrealBuildTool).

Like you said this limitation wasn't a problem until an external program messed with FASTBuild assumptions, but it still feels wrong to don't have dependency tracking for PDB files (and other secondary output files). 

Maybe FASTBuild could track multiple output files by spawning a new FileNode dependency for each, with a weak dependency to the target ? If explicitly updated after each execution of the target, those FileNodes shouldn't invalidate it unless secondary output files are modified ?

**Comment by ffulin** [comment]
It would be ideal to have FASTBuild understand all these additional outputs, but it can't be achieved with the current dependency graph implementation. What I think would be required is a new mechanism to tied nodes together as "siblings", so that the "out of date" state for any is triggered for all, but there isn't a good way to implement that right now.   (Weak dependencies already exist as a concept, but don't really help solve this problem)

It sounds like you resolved your original issue, so I'll go a head and close this issue for now.

**Comment by john-blackburn** [comment]
Just to add my $0.02, the FASTBuild language is superb but the use of `.PreBuildDependencies` is a bit of a black art. I appreciate FASTBuild only allows one output file (compilers have one input, one output; linkers and EXEC have many inputs one output etc). But within that it should be possible to remove the need some `.PreBuildDependencies`. 

For instance in the (fairly) common case where header files are created by a custom compiler and then consumed by the CPP compiler via `#include`, FASTBuild knows the CPP depends on the H and it can see how the H was created by the custom compiler so why is `.PreBuildDependencies` needed there?

So anything that could reduce the need for `.PreBuildDependencies` would be make it more intuitive with fewer gotchas.

**Comment by ffulin** [comment]
> For instance in the (fairly) common case where header files are created by a custom compiler and then consumed by the CPP compiler via #include, FASTBuild knows the CPP depends on the H and it can see how the H was created by the custom compiler so why is .PreBuildDependencies needed there?

In the first build, FASTBuild doesn't know that a particular cpp file includes a particular header file. It must invoke the preprocessor to discover those dependencies. The preprocessor requires that the header already exists in order to be able to parse it.

This is just the simplest case. Real-world use-cases tend to also be far more complex (headers including other headers, or the relationship not being 1:1).

I think PreBuildDependencies are a necessary and sensible mechanism for such a use-case.

I do agree however, that other cases which currently have to be handled with PreBuildDependencies (like operating on PDB files) are far from ideal.
