### ISSUE TITLE
FASTBuild can get confused when compiling a compiler then using it on an ObjectList with multiple configs

### ISSUE THREAD

**Issue by john-blackburn** [fastbuild/fastbuild#676]
I am trying to build a shader compiler (EXE) and then use it to compile shaders in an ObjectList. It seems there are problems when I have more than 1 configuration (debug and release) and so more than one shader compiler: eg ShaderCompiler_debug.exe and ShaderCompiler_release.exe. 

Here is a simplified version of my BFF

```
.msvcPath='C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64'

Settings
{
   .AllowDBMigration_Experimental=true
}

.Compiler ='$msvcPath$\cl.exe'
.CompilerOptions='/nologo /EHsc /O2 /c /Fo"%2" "%1"'

.Librarian='$msvcPath$\lib.exe'
.LibrarianOptions='/nologo /out:"%2" "%1"'

.Linker='$msvcPath$\link.exe'
.LinkerOptions='/nologo /out:"%2" "%1"'

.cfgs={'debug','release'}

ForEach (.cfg in .cfgs)
{
  
  ; --------------------------------------------------------
  ; ShaderCompiler
  ; --------------------------------------------------------

  ObjectList('ShaderCompiler_obj_$cfg$')
  {
     .CompilerInputFiles = 'ShaderCompiler.cpp'
     .CompilerOutputPath = 'obj_$cfg$'
  }
  
  Executable('ShaderCompiler_$cfg$')
  {
     .LinkerOptions + ' /SUBSYSTEM:CONSOLE'
     .Libraries={'ShaderCompiler_obj_$cfg$'}
     .LinkerLinkObjects=false
     .LinkerOutput='ShaderCompiler_$cfg$.exe'
  }

  ; --------------------------------------------------------
  ; Define the ShaderCompiler itself based on above EXE
  ; --------------------------------------------------------
    
  Compiler("ShCompiler_$cfg$")
  {
    .Executable='ShaderCompiler_$cfg$'
    .CompilerFamily="custom"
  }
  
  ; --------------------------------------------------------
  ; Create Shader headers
  ; --------------------------------------------------------
  
  ObjectList('shaderheaders_$cfg$')
  {
     .Compiler='ShCompiler_$cfg$'
     .CompilerOptions='%1 %2'
     .CompilerInputPath='shaders'
     .CompilerInputPattern='*.fx'
     .CompilerOutputPath='shaderheaders'
     .CompilerOutputExtension='_fx.hpp'
  }
}
```
When I run in debug mode all is well
```
C:\Users\john.blackburn\Documents\compile_compiler>fbuild -clean shaderheaders_debug
Database version has changed (clean build will occur).
3> Obj: C:\Users\john.blackburn\Documents\compile_compiler\obj_debug\ShaderCompiler.obj
12>Exe: C:\Users\john.blackburn\Documents\compile_compiler\ShaderCompiler_debug.exe
8> Obj: C:\Users\john.blackburn\Documents\compile_compiler\shaderheaders\foo_fx.hpp
FBuild: OK: shaderheaders_debug
```
But if I run in release mode:
```
C:\Users\john.blackburn\Documents\compile_compiler>fbuild -clean shaderheaders_release
6> Obj: C:\Users\john.blackburn\Documents\compile_compiler\obj_release\ShaderCompiler.obj
10>Exe: C:\Users\john.blackburn\Documents\compile_compiler\ShaderCompiler_release.exe
1> Obj: C:\Users\john.blackburn\Documents\compile_compiler\obj_debug\ShaderCompiler.obj
7> Exe: C:\Users\john.blackburn\Documents\compile_compiler\ShaderCompiler_debug.exe
9> Obj: C:\Users\john.blackburn\Documents\compile_compiler\shaderheaders\foo_fx.hpp
FBuild: OK: shaderheaders_release
```

FASTBuild builds _both_ the debug and the release shader compiler. It then uses the _debug_ shader compiler to compile the shaders! If I use -showcmds, the last command above was
```
C:\Users\john.blackburn\Documents\compile_compiler\ShaderCompiler_debug.exe C:\Users\john.blackburn\Documents\compile_compiler\shaders\foo.fx C:\Users\john.blackburn\Documents\compile_compiler\shaderheaders\foo_fx.hpp
```
i.e. it uses the debug compiler even though I specified release.

**Comment by ffulin** [comment]
Every target defined in FASTBuild has to be unique. In your example, you are specifying the same output location for the compiled shaders in both of your configurations:

```C++
.CompilerOutputPath='shaderheaders'
```

This creates an unresolvable ambiguity - i.e. if you want to build "shaderheaders\foo_fx.hpp" FASTBuild cannot know whether you want the Debug or Release version.  It would also prevent you building both Debug and Release configs in parallel.

To resolve this, you can either:

**a) Have a unique output dir per-config** i.e. append the $cfg$ as a sub directory and update the include paths for downstream consumers to match
OR
**b) Build your shaders in a specific config only** i.e. regardless of the config used for the rest of compilation (i.e. share the generated headers between configs)

I was surprised you didn't get an error about this, and looking into it, it seems as though the "Conflicting objects found" logic in ```ObjectListNode::CreateDynamicObjectNode``` is assuming that if the source file is the same, there is no conflict, but this is not a reliable enough check (the arguments, executable and other settings should also be checked)

**Comment by john-blackburn** [comment]
Thanks very much. I didn't realise output files had to be unique. My intention was when I build the  shaderheaders_release ObjectList it would overwrite eg foo_fx.h with a new foo_fx.h created by release. But now I see FASTBuild does not allow this. (other build systems would be OK with this)

I will use strategy (a) which is the cleanest solution, though it does mean changing the source code to do it (I'm migrating from MSBuild which does seem to allow non-unique output files). 

Yes, it would be better for FASTBuild to emit an error in this case rather than acting "strangely" but this is not really a bug. Thanks again for your help.

**Comment by ffulin** [comment]
I've improved the conflicting obejct detection to catch this case (https://github.com/fastbuild/fastbuild/commit/1196e945f3cce97218d13933c91b26de3dd3c469) and added test coverage as well.

It will now emit an error along the lines of the following:
```C++
Conflicting objects found for: C:\p4\depot\tmp\Test\ObjectList\ConflictingObjects\file.obj
 Source A  : C:\p4\depot\Code\Tools\FBuild\FBuildTest\Data\TestObjectList\ConflictingObjects\A\file.cpp
 ObjectList: ObjectList-Release
AND
 Source B  : C:\p4\depot\Code\Tools\FBuild\FBuildTest\Data\TestObjectList\ConflictingObjects\A\file.cpp
 ObjectList: ObjectList-Debug```

This change will be in the next release (v1.00)

**Comment by john-blackburn** [comment]
Excellent! Thank you very much.
