### ISSUE TITLE
Mem block issues

### ISSUE THREAD

**Issue by bburgin** [fastbuild/fastbuild#678]
**Issue 1:**
I had to add this if statement to SmallBlockAllocator::Free:
//------------------------------------------------------------------------------
bool SmallBlockAllocator::Free( void * ptr )
{
    if ( s_BucketMemoryStart == MEM_BUCKETS_NOT_INITIALIZED )
    {
        return false; // Not a bucket allocation
    }

Since sometimes a large (non-smallblock) alloc and free happens before the s_BucketMemoryStart is initialized. Is this the proper fix for this issue?

**Issue 2:**
Sometimes, I hit this assert in MemPoolBlock::Free() using debug fbuild:
#ifdef DEBUG
    ASSERT( m_NumActiveAllocations > 0 );
#endif

I did some debugging using the windbg time travel debugger (ttd.exe):

BUCKET_MAX_ALLOC_SIZE = 256, but when SmallBlockAllocator::Alloc( size_t size, size_t align )
is called with size 3275, then it returns with nullptr before calling block.Alloc()
Then, the parent method instead calls _aligned_malloc().

Then in SmallBlockAllocator::Free( void * ptr ),
FBuild!SmallBlockAllocator::s_BucketMemoryStart is 0x000002826e2f0000
MemPoolBlock::MEMPOOLBLOCK_PAGE_SIZE is 0x10000
FBuild!SmallBlockAllocator::BUCKET_MAPPING_TABLE_SIZE is 0x0000000000000c80
but ptr is 0x000002826e2e5208

so in,
const size_t pageIndex = (size_t)( ( (char *)ptr - (char *)s_BucketMemoryStart) / MemPoolBlock::MEMPOOLBLOCK_PAGE_SIZE );

pageIndex = (0x000002826e2e5208 - 0x000002826e2f0000) / 0x10000
which results in pageIndex = 0

then in if (pageIndex > BUCKET_MAPPING_TABLE_SIZE)
if (0 > 0x0000000000000c80)
is false
so the code thinks it is a small block allocation when it is not.

It later asserts in:
MemPoolBlock::Free()
#ifdef DEBUG
    ASSERT( m_NumActiveAllocations > 0 );
#endif

What is the proper fix for this issue? I do not understand the memory classes well enough to know.

Thank you.

**Comment by ffulin** [comment]
A bug was introduced into the SmallBlockAllocator during a recent pass of static analysis cleanup. I've fixed the regression here: https://github.com/fastbuild/fastbuild/commit/e6d81c5f06dfa36516b1779309a898191c6a0c93

All of the issues you are seeing seem to result from that. No code changes should be required if you grab that fix, but let me know if you see any more issues.

**Comment by bburgin** [comment]
Thanks for the quick fix.
