### ISSUE TITLE
HasEnoughDiskSpace returns false when access to a drive is restricted

### ISSUE THREAD

**Issue by ClxS** [fastbuild/fastbuild#68]
For security reasons we have FBuildWorker running under a special domain user, and removed this users read permissions for the D: drive. This results in HasEnoughDiskSpace Worker.cpp failing, as GetDiskFreeSpaceExA(...) returns false when access is denied.

My solution to this was to simply remove the second part of that if, but a more detailed way to check if it's something actually wrong with the drive might be needed.

**Comment by ffulin** [comment]
Seems reasonable to skip/ignore drives we can't query for free space.

**Comment by ffulin** [comment]
A fix has been implemented in the Perforce mainline. This will be in the next release (v0.88). I'll leave this issue open until that version is release.

Inaccessible drives are now ignore during free-space checks.

**Comment by ffulin** [comment]
v0.88 has now been release and includes a fix for this issue.
