### ISSUE TITLE
[Feature Request] Add an option to allow overwrite in Copy()

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#683]
I want to copy the final exe to the same assets location in debug and release build. I won't build them at the same time.

**Comment by ffulin** [comment]
If you define two ways to copy a file to the same location and then ask FASTBuild to "build" that copy, then it has no way to know which one you actually want to copy. This is why every target must be unique.

There is a way to achieve what you want however, which is to use a script, batch file or external tool to do this final copy without FASTBuild having to know about it. Something like this:
```C++
// Common properties
.ExecExecutable = 'c:\windows\system32\xcopy.exe' // The external tool
.ExecArguments = '%1 Deploy\myExe.exe' // Both copy to the same place

// Tell FASTBuild to consider the exec's stdout as the output instead of the copy target
.ExecUseStdOutAsOutput = true;  

Exec( 'Copy-Debug' )
{
    .ExecInput = 'Debug-Exe'
    .ExecOutput = 'tmp/copy-debug.log' // Unique log file for Debug
}

Exec( 'Copy-Release' )
{
    .ExecInput = 'Release-Exe'
    .ExecOutput = 'tmp/copy-release.log' // Unique log file for Release
}
```

**Comment by Domain** [comment]
Thanks. I will give it a try.
