### ISSUE TITLE
Substitution isn't supported anymore on includes

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#687]
Include paths are no more substituted since a17139c2b03c10bf26d05dc1754562fc2386fc5f, which refactored preprocessor parsing:
* _before_: https://github.com/fastbuild/fastbuild/commit/a17139c2b03c10bf26d05dc1754562fc2386fc5f#diff-6247b87ab27be0a3d63c4e2958930272L789 :
````cpp
    // unescape and substitute variables
    AStackString<> include;
    if ( PerformVariableSubstitutions( stringStart, iter, include ) == false )
    {
        return false;
    }
````
* _after_: https://github.com/fastbuild/fastbuild/commit/a17139c2b03c10bf26d05dc1754562fc2386fc5f#diff-c75805f6312c6cfcca86dda715f7f8ccR861
````cpp
// NOTE: Substitutions are not supported on includes
````

I understand that moving preprocessing away from the parser did make it impossible to support the old behavior with the new code. 

This idiom is now broken unfortunately:
````
.PoorMansDynamicDispatch = 'MyHelper'
#include "Functions/$PoorMansDynamicDispatch$.bff
````

I'm still looking for a lazy workaround, 
but it may be finally time for **user functions** https://github.com/fastbuild/fastbuild/issues/316 ;)

Did you already made plans toward this ?

Thanks!

---
(Glad you separated lexing from parsing btw, code is now way cleaner/maintanable 👍)

**Comment by ffulin** [comment]
As you probably saw, the parsing code was getting quite unmaintainable and contained quite a few edge case bugs. Implementing it as a single pass originally was a mistake in hindsight. Ironically, I made that choice originally for speed, but actually the new two pass implementation is significantly quicker :)

Breaking this "feature" of expanding strings inside include paths is a necessary evil to allow the code to be maintainable in the future while adding some of the missing features to the language.

I only saw one use case for it so far (in a codebase I work with) which was along the lines of:
```C++
.Libraries = {
                'LibraryA'
                'LibraryB'
                'LibraryC'
              }
ForEach( .Library in .Libraries )
{
    #include "$Library$/$Library$.bff"
}
//  ... do other stuff with .Libraries
```
which was replaced with:
```C++
.Libraries= {}
#include "LibraryA/LibraryA.bff"  // Each include adds itself to .Libraries ...
#include "LibraryB/LibraryB.bff"
#include "LibraryC/LibraryC.bff"
//  ... do other stuff with .Libraries
```
so each thing was still canonically listed only once.

Your case seems different, but I don't think I fully understand your example, as you can still use #include to expand in=place as a sort of macro, just like in C++, which is what it seems to be like. For example:
```C++
.LibraryName = 'LibraryA'
#include "LibraryTemplate.bff" // something that uses .LibraryA still works as before
```
Maybe you can explain your use-case a bit more and perhaps I might be able to suggest some work-arounds?

>  it may be finally time for user functions

This is still something I'd like to add, and something I have plans for. Cleanup work like the stuff I just did will make all of these kinds of things easier in the future.

**Comment by ffulin** [comment]
As noted, though this is an unfortunate break in backwards compatibility, it is a necessary change. I'm going to close this issue, but let me know if you want to discuss any specific use-cases that might have relied on this.
