### ISSUE TITLE
Dependency graph visualization

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#691]
I was wondering if it's possible to generate a visual of dependency graph? Something like `cmake --graphviz=graphviz/graph .` I imagine all data needed is stored somewhere inside Fastbuild model.

**Comment by ffulin** [comment]
FASTBuild can emit dependency information using the [-showdeps](https://fastbuild.org/docs/options.html#showdeps) option.

This outputs in a text format, so not quite as nice as a graphviz visualization, thought that would also be possible (and at a brief glance of the "dot" file format, probably not very difficult)

**Comment by claimred** [comment]
> FASTBuild can emit dependency information using the [-showdeps](https://fastbuild.org/docs/options.html#showdeps) option.
Thanks! I'll look into it. Though it seems it shows every 3rd party dependency header present, a lot of boost header files for instance. Is it possible to narrow it down to targets only?

**Comment by ffulin** [comment]
-showdeps will show the complete hierarchy of dependencies for the specified target (or 'all' if not specified). There isn't currently a way to limit it any further.

**Comment by ffulin** [comment]
I'm going to close this question as answered. Let me know if I can provide any more details.

**Comment by ffulin** [comment]
The next version of FASTBuild (v1.04) will contain a new -dot[full] command line option that allows for the generation of DOT format graph visualizations. For example:
![image](https://user-images.githubusercontent.com/11589403/103490297-c692a380-4dcf-11eb-8acd-6d48064e4411.png)
