### ISSUE TITLE
Precedence issue in error tests?

### ISSUE THREAD

**Issue by bburgin** [fastbuild/fastbuild#692]
Can you help me with this test failure from the most recent build? It looks like the Error_1500_CompilerDetectionFailed is taking precedence over the Error_1100_AlreadyDefined error.

 - Test 'ConflictingFiles3'

/home/travis/build/fastbuild/fastbuild/Code/Tools/FBuild/FBuildTest/Data/TestCompiler/conflict3.bff(4,1): FASTBuild Error #1500 - Compiler() - Compiler detection failed. Unrecognized executable '\home\travis\build\fastbuild\fastbuild\Code\Folder\A'.

Compiler( 'Compiler' )

^

\--here

-------- TEST ASSERTION FAILED --------

/home/travis/build/fastbuild/fastbuild/Code/Tools/FBuild/FBuildTest/Tests/TestCompiler.cpp(223): Assert: GetRecordedOutput().Find( "Error #1100" )

-----^^^ TEST ASSERTION FAILED ^^^-----

 - Test 'ConflictingFiles3' *** FAILED ***

_Originally posted by @bburgin in https://github.com/fastbuild/fastbuild/pull/485#issuecomment-582626665_

**Comment by bburgin** [comment]
Seems like these files are getting passed the duplicate file check:
conflict3.bff:
...
    // These would both end up in the root, so that should fail
    .ExtraFiles     = { 'OtherFolder1/B',
                        'OtherFolders/B' }

Question: What makes the files both end up in the root?
I think the relative paths for these files are unique because relative path is calculated from the working dir downward.
So in CompilerNode.cpp, PathUtils::GetRelativePath( m_ExecutableRootPath, extraFiles[ j ].GetNode()->GetName(), relPathB );
is called and then if ( PathUtils::ArePathsEqual( relPathA, relPathB ) )
compares:
..\OtherFolder1\B to ..\OtherFolders\B
which are unique.

Thoughts?

**Comment by ffulin** [comment]
It looks like you've changed the behavior of either ArePathsEqual or GetRelativePaths in the ToolManifest.

.ExtraFiles in the Compiler() (managed by the ToolManifest helper class) have a very specific behavior (https://fastbuild.org/docs/functions/compiler.html):

> For distributed compilation, the specified files will also be synchronized to the remote machine. The relative location of the source files controls how they will be mirrored on the remote machine. Files in 'ExtraFiles' in the same directory or in sub-directories under the primary 'Executable' will be placed in the same relative location on the remote machine. **'ExtraFiles' in other folders will be placed at the same level as the executable.**

TestCompiler::ConflictingFiles3 is testing this case.

**Comment by bburgin** [comment]
Thanks. I reinstated the tool manifest logic. The build is passing now.
