### ISSUE TITLE
Fastbuild and .tlb/.tlh

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#694]
We are experiencing a minor setback while compiling windows project that contains files that use #import <file.tlb> directives. The thing is, files like that can't be compiled with '/MP' flag if I understand correctly. First cl pass processes a file & generates .tlh header which is used for other files. Multiprocess compilation runs into issues when it tries to compile something which is not there yet. What would you recommend as a workaround? Special ObjectList for every files with #import?

**Comment by lucianm** [comment]
We ran into these kind of problems with MSXML. We had to get rid of the `#import` directives, [as Microsoft themselves are recommending now](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms765540%28v%3dvs.85%29), then you have compilation and linking under control, there is no more magic generating of .tlh files out of the `#import <msxml6.dll>` directive, which had to cause sporadical access violations on the same file being generated by multiprocess compilation in the same location, we had long server builds failing whenever they liked to do so because of this. With MSXML6 there were headers and .lib available in the Windows SDK, even if the API was slightly different than the one from automatically generated .tlh, it was worth putting some effort in refactoring the code a bit for solving the issue.
I do not know if with your `#import <file.tlb>` something similar is possible though, but this may be pointing you at something to look for...

**Comment by claimred** [comment]
🤔 @lucianm Thanks! I'll look into it. 

Have you encountered midl.exe by any chance? We have a setup of generating multiple things using midl like `midl.exe file.idl /iid "file.c" /h "file.h" /proxy "file_p.c" `, I am contemplating writing an external script but it would be nice to use FBuild for all things.

**Comment by lucianm** [comment]
Yes, I have.

I defined it as a compiler:
```
Compiler( 'MIDL-Compiler' )
{
	.Executable			= '$WIN_SDK_PATH$\midl.exe'
	.CompilerFamily		= 'custom'
	.AllowDistribution	= false
}
// MIDL Compiler
//------------------------------------------------------------------------------
.MIDLCompiler =
[
	.Compiler					= 'MIDL-Compiler'
	.CompilerOutputExtension	= '.tlb'
	.CompilerOptions	= ' $BaseIncludePaths$ /W1 /nologo /char signed /Oicf /robust'
]
```

Then, in my target I'm making sure to create an output directory before invoking it, something like this:
```
.Configs = { .X64DebugConfig, .X64ReleaseConfig, .X86DebugConfig, .X86ReleaseConfig }
	ForEach( .Config in .Configs )
	{
		.PS_OutputPath = '$OutputBaseDir$\$Platform$\$Config$\$TargetName$PS'
		Exec( 'Mkdir-$TargetName$PS-$Platform$-$Config$' )
		{
			.ExecExecutable	= '_Globals\_fbuild\_mkdir.cmd'
			.ExecArguments	= '"%2"'
			.ExecOutput		= .PS_OutputPath
		}
		ObjectList( '$TargetName$-Lib-$Platform$-$Config$' )
		{
			.PreBuildDependencies = { 'Mkdir-$TargetName$PS-$Platform$-$Config$' }
			Using( .MIDLCompiler )
			.CompilerInputFiles	= '$TargetName$/Source/$TargetName$/$TargetName$.idl'
			.CompilerOutputPath	= '$OutputObj$/$TargetName$/'
			.CompilerOptions	+ ' /I $TargetName$\Include\Exports'
								+ ' /D $MidlDefines$ /env $PlatformMidl$'
								+ ' /out"$PS_OutputPath$" /h "$TargetName$_i.h"  /iid "$TargetName$_i.c"  /proxy "$TargetName$_p.c"'
								+ '  /tlb "%2" "%1"'
		}
     }
```

mkdir.sh contains just the line `if not exist %1 mkdir %1`

I have to admit, I only have one such target, but it builds for 4 different platform/config pairs enumerated in .Configs, and each of them generate output in their own directories. But this is pretty much under control, the other stuff, when `#import <some_magic_mushroom.dll>` starts generating *.tlh/.tlb somewhere it happens to want to, will easily clash when FASTBuild will parallelize the jobs.

In the end, I'm not sure if I was telling is of any help in writing such MIDL targets in a reusable fashion.

**Comment by claimred** [comment]
Nice! Thanks again. 

> I have to admit, I only have one such target

Yeah, my problem arises from the fact that there is a folder with *.idl files and I don't see a way to automatically provide a prefix from idl file for /iid, /h & /proxy options.

Tried forcing .CompilerOutputExtension to empty value and use it later on but it doesn't work like that. 
```
 .CompilerOutputExtension` = ''

 .AdditionalOptions + ' /iid ^"%2.c^""'
 .AdditionalOptions + ' /h ^"%2.h^""'
 .AdditionalOptions + ' /proxy ^"%2_p.c^""'

 .CompilerOptions = .AdditionalOptions
```

**Comment by ffulin** [comment]
Sorry I missed this issue when it was first created. It seems like perhaps you have a viable set of work-arounds, but I'm not 100% sure.

On a related note, there is a proposal for concurrently groups/limits in https://github.com/fastbuild/fastbuild/issues/722 that might be away to solve the case where we need only one instance of a thing to be running at a time, but still want the build in-general to be as parallel as possible.

**Comment by claimred** [comment]
We've sort of followed @lucianm advice by putting .tlh file under version control and got rid of #import directives in favor of #include ones, fixed the /mp issue for now.

**Comment by ffulin** [comment]
Thanks. With that in mind, I'll go ahead and close this issue.

For completeness, it should be noted that FASTBuild does not use /MP (and will strip it from any command lines you specify). /MP is incompatible with various options, some of which FASTBuild requires. Instaad, FASTBuild controls the process spawning itself. The end result for this specific issue is likely the same however.

**Comment by claimred** [comment]
>For completeness, it should be noted that FASTBuild does not use /MP 

Sorry, yeah. I used "/mp" as a shortcut for multiprocess compilation in general, whether from actual `cl.exe /mp` or FASTBuild process spawning. On our old msbuild.exe build setup we had '/MP-' on projects that use #import directives.
