### ISSUE TITLE
WriteToCache() not called for local builds?

### ISSUE THREAD

**Issue by bburgin** [fastbuild/fastbuild#695]
When an ObjectNode can be distributed (canDistribute is true) but isn't built remotely
(due to no available workers), then it seems that ObjectNode::WriteToCache() is never called for the object.

Specifically, ObjectNode::DoBuildWithPreProcessor2() is never called and so WriteToCache() is never called.
Do you concur? Is this expected behavior?

I ask because it seems that builds that complete locally should be cached.

**Comment by ffulin** [comment]
Looking at the code, the seqeunce of events when a local core builds a distributable job (whether racing a remote job or note) should be as follows:
 - WorkerThread::Update calls JobQueueRemote::DoBuild
 - JobQueueRemote::DoBuild calls ((Node *)node )->DoBuild2
 - DoBuild2 calls DoBuildWithPreProcessor2

Assuming the compile succeeds, at the end of DoBuildWithPreprocessor2 we have:
```C++
    // record new file time
    if ( job->IsLocal() )
    {
        // record new file time
        RecordStampFromBuiltFile();

        const bool useCache = ShouldUseCache();
        if ( m_Stamp && useCache )
        {
            WriteToCache( job );
        }
    }
```

So as long as the job is cacheable, it should be stored to the cache.

There doesn't seem to be test coverage of this case, but it should be relatively easy to add to ensure it's working correctly.

**Comment by bburgin** [comment]
Thanks for the function list. I stepped through it with a debugger.
The WriteToCache() calls do happen, but much later than I expected.
For the case where there are workers but none available, the remote queue is left untouched until all the preprocessor steps have run:

/*static*/ bool WorkerThread::Update()
{
    // try to find some work to do
    Job * job = JobQueue::IsValid() ? JobQueue::Get().GetJobToProcess() : nullptr;
    if ( job != nullptr )

Could we modify the Update() method to check if the number of workers available is zero and then see if we can do a job from the remote queue? This would help the remote queue to be serviced earlier and the object cache files to be available earlier for these remote queue jobs.
Then other devs' builds or subsequent builds would run faster, since they would have cache files to use.

As it is now, if the user stops the build anytime before the preprocessor steps are complete, then they don't get cache files for the remote queue jobs. And on a subsequent build, all the preprocessor steps have to run again for these jobs.

Such a modification to Update() would also help the build order to be more consistent for this case where there are no available workers. The execution of remote and local jobs would get interleaved, instead of all the remote jobs running after all the preprocessor and local jobs run.

Thoughts?

**Comment by ffulin** [comment]
> Could we modify the Update() method such that on every iteration, check if the number of workers available is zero and then see if we can do a job from the remote queue? 

FASTBuild locally does things in the following order:
 - prepares distributable work
 - performs work that can only be done locally
 - consuming distributable work locally

This order of operation is deliberate. If locally we consumed the distributable jobs earlier we would:
a) have no distributable work ready when workers connect or become available
b) remove parallelism between local-only work and distributable work

> As it is now, if the user stops the build anytime before the preprocessor steps are complete, then they don't get cache files for the remote queue jobs. 

The cache is checked *before* the jobs are added to the distributable queue. So if the item can be retrieved from the cache, it will be. 

> [this] would also help the build order to be more consistent ... where there are no available workers. ...

The order of operations varies across builds. Previous build timing is used to better order subsequent builds. Consistency of build order is not a goal of the system - faster builds are the goal.

> remote and local jobs would get interleaved, instead of all the remote jobs running after all the preprocessor and local jobs run.

Distributable jobs don't all run at the end of a build. They run as dependencies dictate, prioritizing distributed work to be done remotely to free up local CPU cores for work that can only be done locally.

**Comment by bburgin** [comment]
Thanks for the clarifications.

> The cache is checked _before_ the jobs are added to the distributable queue. So if the item can be retrieved from the cache, it will be.

I meant that the writes to the cache for the remote jobs don't happen until all the preprocessor jobs complete. So if the build errors or is aborted before these writes happen, then there are no cached obj files for these remote jobs to use on the next build. Thus, no progress has been made towards writing to the cache for this case. And the next build must run all the preprocessor steps again before it can even have a chance to write the remote job objs to the cache.

You mentioned that the FASTBuild system is optimized for build speed, but for this case I think it is only optimized for the initial build speed, not incremental builds.
Is the initial build speed the only goal of the system?
Does your build speed goal extend to incremental build speed?

**Comment by ffulin** [comment]
> I meant that the writes to the cache for the remote jobs don't happen until all the preprocessor jobs complete.

A compiled object will be written to the cache as soon as it is completed (returned from a remote host or compiled locally).  The number of outstanding distributable jobs doesn't change or defer that.

Until the object is compiled, (locally or remotely) there is nothing that can be written to the cache. The preprocessed output is not cached - only the final objects are cached. The only way to make it writable to the cache is to build it locally, which is making a speculative call that it won't be effective to distribute compilation. That might be the right call in certain cases, but I think it's not the right call in most cases.

I can see a potentially worst-case scenario of starting a distributed build, and having no workers available for the entire build, and cancelling (or failing) a build after a bunch of work is prepared, but before any useful work is done. While I think you can easily identify a build like that after the fact, there isn't really a way to predict that outcome in advance, so FASTBuild works based on the assumption that there will be workers available and that the build will not be cancelled or fail so quickly.

> Is the initial build speed the only goal of the system?

The goal of FASTBuild is to accelerate as many cases as it can. The starting point is to chose logic and behavior that helps the largest amount of cases the largest amount of the time. Where a tradeoff is needed or possible, whether we'd favor local iteration or full builds, would be chosen depending on the frequency and magnitude of the tradeoff. It might be reasonable to make full builds slower to the benefit of incremental builds, but the reverse might also be true.

All other things being equal, I would probably favor local iteration or incremental builds, where such a thing can be determined.

What is a "full" or "incremental" build, while trivial to identify after the fact, isn't something that can be easily determined before-hand, and the "working out what needs building" and "building" happen at the same time. Many decisions have to be made speculatively, and while FASTBuild tries to use the context it has to be smart when deciding what to do, sometimes it has to essentially guess. Sometimes those guesses will be identifiable as wrong after the fact.

Note that the logic I've described so far also contains more nuance than I've described. (Locally modified files isolated from unity have a variety of tweaks applied to how they are handled to name just one example).

----

None of this is to say that the current system is perfect, nor is it to say that it can't be improved. It is however far more nuanced than it might first appear, and it's difficult to improve some cases without making others worse.

**Comment by bburgin** [comment]
Thanks for the explanations.
It seems that the ideal solution would be to cache preprocessor work for the next build, rather than change the priority of work in the WorkerThread.cpp. I am closing this issue.

**Comment by ffulin** [comment]
> It seems that the ideal solution would be to cache preprocessor work for the next build,

This could definitely benefit some situations. Some thought would need to go into how that could be persisted to disk in a sensible way and how storage for that (potentially rather large data) could be managed.

An aspiration long-term goal is to eliminate the use of the compiler preprocessor entirely for both caching and distributed compilation. A custom preprocessor could be much faster, could de-duplicate redundant work between object files (or even between builds) and could be implemented in a way that supports remote use of precompiled headers.

The (Experimental) LightCache is a first step towards that - it avoids using the preprocessor and de-duplicates redundant work, yielding as much as a 10x reduction in the time it takes to generate the cache "key". A full preprocessor for distributed compilation use is a *lot* more work however, so that's some way off. (The LightCache also has at least 2 bugs :) )
