### ISSUE TITLE
Linking fails due to too long argument-list

### ISSUE THREAD

**Issue by ndob** [fastbuild/fastbuild#70]
Environment used: Windows 7, Visual Studio 2013

The problem appears with long argument lists, that are somewhat near the maximum command size (32767) boundary. The problem is that the total command length exceeds the boundary in certain cases, when the need for a response file is deducted wrongly.

Need for response file is deduced by the length of arguments provided for the linker. This deduction should also take into account the length of linker-command itself. In addition there are two slashes and a white space [added in Process::Spawn](https://github.com/fastbuild/fastbuild/blob/master/Code/Core/Process/Process.cpp#L125-L132), which adds further three characters to total length.

Following snippet demonstrates and fixes the immediate problem with linking process, but it seems that there are other call sites that use the same logic (LibraryNode, CSNode, ObjectNode). Additionally this fix is only for Windows, so probably a more general fix needs to be implemented (maybe let Process::Spawn() handle the response file logic?).

Problematic deduction:
[Code/Tools/FBuild/FBuildCore/Graph/LinkerNode.cpp](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/LinkerNode.cpp#L111)

Snippet:
```
const uint32_t MAX_COMMANDLINE_CHARS = 32767;
// Magic corresponds to number of characters added in Process::Spawn(), when __WINDOWS__ is defined.
const uint32_t MAGIC = 3;
const uint32_t totalCommandLength = m_Linker.GetLength() + fullArgs.GetLength() + MAGIC;

const bool useResponseFile = (totalCommandLength > MAX_COMMANDLINE_CHARS) && (GetFlag(LINK_FLAG_MSVC) || GetFlag(LINK_FLAG_GCC) || GetFlag(LINK_FLAG_SNC) || GetFlag(LINK_FLAG_ORBIS_LD) || GetFlag(LINK_FLAG_GREENHILLS_ELXR) || GetFlag(LINK_FLAG_CODEWARRIOR_LD));
```

**Comment by ffulin** [comment]
Thanks for reporting this edge-case bug.

Indeed the logic is not correctly accounting for the exectuable name and the quotation of the exe name that is necessary to cope with paths with spaces in them.  Conceptually the fix needed is what you've shown. 

I'll work on getting a fix for that in place that covers all the users of response files.

(This logic is Windows-specific, since only windows compilers generally utilize response files since they are only necessary to work around the length limits in the Windows API.)

**Comment by ffulin** [comment]
I've submitted a fix for this in the Perforce mainline. The fix will be in the next release (v0.88)

I turned out to need quite a rework in order to be robust in all cases: there were quite a few egde-case bugs which the rework will address.

Thanks again for reporting the bug!

**Comment by ndob** [comment]
Great, thanks!

**Comment by ffulin** [comment]
v0.88 has now been release and includes a fix for this issue (as well as some other command line length edge cases).
