### ISSUE TITLE
FASTBuild CPU limit UI behaves strangely with high-core-count CPUs.

### ISSUE THREAD

**Issue by peterwoytiuk** [fastbuild/fastbuild#709]
On a Ryzen 2990 (32 physical cores/64 logical), the FBuildWorker UI will initially only let you set the CPU limit to 43 CPUs (67.2%) - as shown in the attached screenshot the dropdown shows from 32 cores to 43 cores.  If you select 43 cores, close the UI and then reopen the UI, the dropdown's items will change to show 43-54 cores.  If you select 54 cores, close and reopen the UI, the items will again change to show 53-64 cores and only then can you select 64 CPUs (100%).  This is not intuitive.

![FASTbuildWorker-0 99-CPU-Limit](https://user-images.githubusercontent.com/56612898/75598789-5569bd80-5a53-11ea-9b92-43694d6efb8f.png)

**Comment by peterwoytiuk** [comment]
Here's the screenshot after completing the close-and-reopen steps a couple of times.
![FASTbuildWorker-0 99-FullCPU-Limit](https://user-images.githubusercontent.com/56612898/75598873-315aac00-5a54-11ea-9ca6-4a9df58e9c1a.png)

**Comment by ffulin** [comment]
Thanks for reporting this. I'm not sure how I never noticed it :)  This have committed a fix (https://github.com/fastbuild/fastbuild/commit/d78b4f3bde8aee2bd373f8c2c879adf73a132541) which will be fixed in the next release (v1.00).

I'll leave this issue open until that version is released.

**Comment by peterwoytiuk** [comment]
Thanks for the quick turnaround!

**Comment by ffulin** [comment]
v1.00 has now been released. It includes the fix for this issue.
