### ISSUE TITLE
Parent scope ^ doesn't work with local variables

### ISSUE THREAD

**Issue by kylawl** [fastbuild/fastbuild#71]
I'm not sure if I'm doing this wrong or if this is a bug but following yields an error.
```
.ParentScopeArray = {}
{
	.LocalVariableString 	= 'hello'
	^ParentScopeArray 	+ { .LocalVariableString }
}
```
```
Error:
FASTBuild Error #1026 - Variable '.LocalVariableString' not found for concatention.
		^ParentScopeArray 		+ { .LocalVariableString }
		                  		^
		                  		\--here
```

**Comment by ffulin** [comment]
That syntax you have used is valid and I've reproduced the bug locally. I'll investigate what is going on.

Thanks for reporting this!

**Comment by kylawl** [comment]
:+1:

**Comment by ffulin** [comment]
I've narrowed down the problem further. It's specific to the concatenation of Arrays.
A work around in the short term is:
```C++
.ParentScopeArray = {}
{
    .LocalVariableString    = 'hello'
    ^ParentScopeArray   + .LocalVariableString
}
```

**Comment by kylawl** [comment]
Ah right, thanks. 

That example is a distilled down version of what we're doing but we don't actually need to concat arrays in this case anyway (there is only 1 item).

**Comment by ffulin** [comment]
This bug has been fixed in the Perforce mainline and will be part of the next release (v0.88). I will leave this issue open until that version is released.

**Comment by ffulin** [comment]
v0.88 has now been release and includes a fix for this issue.
