### ISSUE TITLE
vs2019 sln header is not correct

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#714]
Heya!

The sln header changed in vs2019, now the expected header is:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
```

FastBuild writes `# Visual Studio 16`, which makes the sln not being recognized as a vs2019 one by the Visual Studio Version Selector, and the icon being blank in the file browser.

**Comment by ffulin** [comment]
Seems like it's be fairly straightforward to modify SLNGenerator::WriteHeader to emit the slightly different format for version 16 or later.

**Comment by belkiss** [comment]
Yes, I didn't have the time to fix it in the code, but wanted to log it, in case someone beats me to it :)

**Comment by ffulin** [comment]
Visual Studio solution generation has been updated to write the new format header when the version is 16 or greater (2019+) (https://github.com/fastbuild/fastbuild/commit/23bd49f2002a06fe52f4d6162a721e4f55af01a3). This change will be in the next release (v1.03). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.03 has now been released and contains a fix for this issue.
