### ISSUE TITLE
Question: would you be open to adding a __has_include feature?

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#715]
Heya!

Would you be open to the idea of adding the possibility to do a file existence check before including a bff? Similar to the `#if exists(MY_ENV_VAR)`

This would allow us for instance to include a file that decides which vs version to use, without having to manually change any bff file, like here https://github.com/fastbuild/fastbuild/blob/1ae7e7e10e574fc416b1a1fd3ed1a476c0ef255f/External/SDK/VisualStudio/VisualStudio.bff#L6

The code could become something like:
```
#if exists("VisualStudio_override.bff")
    #include "VisualStudio_override.bff"
#endif

// check if the user chose a version, and if not keep current default
#if !USING_VS2015
    #if !USING_VS2017
        #if !USING_VS2019
            //#define USING_VS2015
            #define USING_VS2017
            //#define USING_VS2019
        #endif
    #endif
#endif
```

Side-node: #ifs don't support &&...

Thanks!

**Comment by ffulin** [comment]
I've been thinking about the automated compiler discovery a lot, and while doing that, I implemented #if file_exists. One I finished, I realized it probably wasn't what I actually want (I think an IfFileExists() function might be better) so I shelved it to give it some more thought.

In general, I think moving away from # directives and supporting more complex Functions is the way to go, but I think #if file_exists can be useful in the short term at the very least. With that in mind, I've submitted the change (https://github.com/fastbuild/fastbuild/commit/aa753f02ad212f1d84f66151604f8f133cfbcfb6).

This will be in the next release (v1.00):
```
#if file_exists("file.bff")
#endif
```

It's not limitted to checking for bff files. It can check for the presence of any file.

I'll leave this issue open until v1.00 is released.

**Comment by ffulin** [comment]
> Side-node: #ifs don't support &&...

That's right. The #if support is very basic. It will likely evolve in the future, but I want to carefully consider how much we want to encourage use of preprocessor directives in general.

**Comment by belkiss** [comment]
Excellent! Thank you!

About automating compiler discovery, we are divided, some things can't easily be detected...
I will definitely share what we come up with thanks to this addition.

Cheers!

**Comment by john-blackburn** [comment]
@belkiss You probably already know but FASTBuild's preprocessor is not the same as the C preprocessor . `#if` is the equivalent of C's `#ifdef`. `#if !` is equivalent to `#ifndef`. You can `#define` macros but you can't give them a value: they are simply defined or undefined. So you can check if a macro is defined but you can't check what value it has. This is the same as in C# I think.

It would be rather nice to have
`#if foo && bar`

which would be equivalent to C's
`#if defined(foo) && defined(bar)`

But I'd rather see work done on regular `if` (compare against literals for example)

**Comment by ffulin** [comment]
There will probably be extensions to the #if syntax in the future (&& support being a useful and reasonable possible example), but for the most part, the direction going forward is to extend the "regular" part of bff parsing to solve for missing functionality. Improving If (for things like direct comparison with literals) is a good example of such an improvement.

**Comment by ffulin** [comment]
v1.00 has now been released. It includes the new file_exists directive.
