### ISSUE TITLE
Why isn't it possible to set brokerage path from the inside of bff file?

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#718]
That way broker path could be trivially synchronized between clients using VCS. Am I missing something?

```
Settings
{
  .Environment = 
  {
    "FASTBUILD_BROKERAGE_PATH=\\mybrokerage"
  }
}
```

**Comment by john-blackburn** [comment]
I'm pretty sure the `.Environment` you set only affects subsidiary processes that FASTBuild calls (eg compiler, linker). FASTBuild itself will not pay attention to it.

**Comment by ffulin** [comment]
@john-blackburn is correct. The .Environment is used to control the environment of processes launched by FASTBuild (to help ensure consistent builds between machines).

It would be reasonable to add a .BrokeragePath property to Settings() as long as it behaved consistently with other properties that are exposed (like .CachePath vs FASTBUILD_CACHE_PATH for example)
