### ISSUE TITLE
Running -showtargets with -wrapper returns FBUILD_WRAPPER_CRASHED

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#719]
Hi,

I stumbled on a small issue while running this command:
````
FBuild.exe -showtargets -wrapper
````
It will always succeed, but with the return code value -7 (FBUILD_WRAPPER_CRASHED),
and it seems to be the default value set in the code in Main.cpp:
````c++
int WrapperMainProcess( const AString & args, const FBuildOptions & options, SystemMutex & finalProcess )
{
    // Create SharedMemory to communicate between Main and Final process
    SharedMemory sm;
    g_SharedMemory.Create( options.GetSharedMemoryName().Get(), sizeof( SharedData ) );
    SharedData * sd = (SharedData *)g_SharedMemory.GetPtr();
    memset( sd, 0, sizeof( SharedData ) );
    sd->ReturnCode = FBUILD_WRAPPER_CRASHED;
````

Thanks for your hard work !

**Comment by ffulin** [comment]
Thanks for the bug report. This has been fixed (https://github.com/fastbuild/fastbuild/commit/51cc61dce0289e68777efe3f094be11e5e1d55f1). This change will be in the next release (v1.00). I'll keep this issue open until that version is released.

**Comment by ffulin** [comment]
v1.00 has now been released. It includes the fix for this issue.
