### ISSUE TITLE
Unexpected Shared Network Cache Misses

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#727]
Hi @ffulin,

I've hit an unexpected (to me) case with the cache. We've been using cache via `SMB3 with a UNC Network Path` for quite some time, with `> 50 nodes`. The nodes are able to store and retrieve cache entries successfully.

But, what I unfortunately haven't tested for quite some time was whether the cache entries are actually being shared between nodes (vs. each node storing and retrieving it's own exclusive copy).

I assumed the entries were being shared, and I know that at some point (far in the past) I did verify that it worked and entries were properly shared; but, I have direct evidence of multiple cases tonight where it is not occurring at the moment.

1. If I build from `C:\dev` and then build again from `D:\dev`, I just verified the cache entries to be exclusive.

2. If I build from two different machines, even if both machines use `D:\dev`, it seems that the entries are also exclusive.

This is with `v0.99` with some modifications (but none having to do with the cache).

This is also with the `LightCache` enabled.

Is this behavior expected? Was there a point in the recent releases when the behavior of the cache with respect to this may have been changed?

**Comment by missmah** [comment]
I'm going to start ruling out potential differences between the machines vis-a-vis case `#2`.

What would be very helpful would be a way to generate a report for all the cache lookups of the input data that gets hashed, and then the cache entry/hash.

This way, two machines could generate two reports, which could then just be diffed using a diff tool to find out exactly where the differences in cache behavior are coming from (e.g. whether it's a path issue vs. different code issue, etc.)

I'm guessing this tool does not exist? :) If it does not exist -- do you have any pointers on where to start with implementing it?

Thanks,
Layla

**Comment by ffulin** [comment]
Here's some information that will hopefully help you figure out what's going on. Let me know if I can elaborate on anything.

**LightCache**

The light cache is experimental and has bugs, including some recently discovered ones related to dependency gathering, which could prevent correct caching. This feature should not be used in production environments until it is promoted to "not experimental". This may not have anything to do with what you are seeing, but you should disable this feature, at least temporarily, to ensure it's not the cause.

**What is required for caching**

The cache requires the following to match between machines:
 - pre-processed (flattened) source code
 - command line options
 - compiler binaries
 - pre-compiled header (if used)
 - cache version (currently version 'A')
 - using, or not using LightCache

The pre-processed source code and command line options usually contain full paths, both of which impact the output (debug information and __FILE__ directives for example) and thus the paths between machines must match. 

(There is an experimental (incomplete) option in the next version (.[UseRelativePaths_Experimental](https://github.com/fastbuild/fastbuild/commit/ca966069920f28157bc10311c0fa888bdb1225ca)) which may end up allowing path agnostic caching, though from experiments done so far, it seems this will work well with GCC and Clang, but may have limitations/trade-offs with MSVC)

**Debugging cache misses**

You can use [-cacheverbose](https://fastbuild.org/docs/options.html#cacheverbose) to see what cache keys are being generated on two different machines. When combined with -cache, -cacheread or -cachewrite this will output additional information in the following format:
```
12>Obj: C:\p4\depot\tmp\x64-Debug\Tools\FBuild\FBuildCore\FBuildCore_Unity3.obj
 - Cache Miss: 35 ms 'E90519265A1719FA_3AC8C650_6C30067E14AB4880-0000000000000000.A'
					   
12>Obj: C:\p4\depot\tmp\x64-Release\TestFramework\TestFramework_Unity1.obj
 - Cache Store: 157 ms (Store: 150 ms - Compress: 1 ms) (Compressed: 25684 - Uncompressed: 51916) 'BA4252DC6B561582_97907E3A_6C30067E14AB4880-0000000000000000.A'
		   
10>Obj: C:\p4\depot\tmp\x64-Profile\Core\Core_Unity1.obj <CACHE>
 - Cache Hit: 81 ms (Retrieve: 73 ms - Decompress: 1 ms) (Compressed: 452262 - Uncompressed: 1044600) 'FD9B691EF509B98D_3409CAAE_6C30067E14AB4880-0000000000000000.A'
```

Each line contains the cache keys, which are comprised of hashes of the inputs I mentioned earlier, formatted by the following function:
```C++
// GetCacheId
//------------------------------------------------------------------------------
/*static*/ void ICache::GetCacheId( const uint64_t preprocessedSourceKey,
                                    const uint32_t commandLineKey,
                                    const uint64_t toolChainKey,
                                    const uint64_t pchKey,
                                    AString & outCacheId )
{
    // cache version - bump if cache format is changed
    static const char cacheVersion( 'A' );

    // format example: 2377DE32AB045A2D_FED872A1_AB62FEAA23498AAC-32A2B04375A2D7DE.7
    outCacheId.Format( "%016" PRIX64 "_%08X_%016" PRIX64 "-%016" PRIX64 ".%c",
                       preprocessedSourceKey,
                       commandLineKey,
                       toolChainKey,
                       pchKey,
                       cacheVersion );
}
```

By comparing the cache keys from two machines you expect to match, you can see which components differ.

**Comment by missmah** [comment]
`TR4`, `C:\`:
```
19>Obj: C:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
 - Cache Miss: 0 ms '4666AF78AF9E50EC_2D4F64E6_AA27963E0354195B-0000000000000000.A'
```

`TR4`, `D:\`:
```
15>Obj: D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
 - Cache Miss: 4 ms 'D011FEB3B3F53800_37868A95_AA27963E0354195B-0000000000000000.A'
```

`PC1`, `D:\`:
```
72>Obj: D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj <CACHE>
 - Cache Hit: 41 ms (Retrieve: 1 ms - Decompress: 7 ms) (Compressed: 1841385 - Uncompressed: 5006879) 'D011FEB3B3F53800_7B5C9CFF_AA27963E0354195B-0000000000000000.A'
```

**Comment by missmah** [comment]
`TR4`, `C:\`:
```
24>Obj: C:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
 - Cache Miss: 0 ms '4666AF78AF9E50EC_2D4F64E6_AA27963E0354195B-0000000000000000.A'
24>Obj: C:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
C:\FastBuild\External\VS14.0\VC\bin\amd64\cl.exe /Zc:forScope /Zc:rvalueCast	/Zc:auto /Zc:implicitNoexcept /std:c++14 /DIVR_CPP17_EXPERIMENTAL_COMPILER_IS_SUPPORTED "C:\dev\Build\Output\Unity\3rdparty\bullet3\src\BulletDynamics_1.cpp" /Z7 /nologo /c /W4 /WX /Zc:wchar_t /Zc:inline /Zc:strictStrings /we4062 /we4263 /we4265 /we4296 /we4555 /we4619 /we4640 /we4826 /we4836 /we4905 /we4906 /wd6302 /wd6255 /wd4324 /cgthreads4 /fp:fast /D_CRT_STDIO_ISO_WIDE_SPECIFIERS /D"WIN32_LEAN_AND_MEAN" /D_WIN32 /D__WINDOWS__ /D "_WINDOWS" /D"_WINSOCK_DEPRECATED_NO_WARNINGS" /analyze:stacksize 1048576 /Fo"C:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj" /I"./" /I"C:\FastBuild/External/VS14.0\VC\include/" /I"C:\FastBuild/External/Windows10/Include/10.0.16299.0/ucrt" /DWIN64 /DRELEASE /MD /Ox /Oy /Oi /GS- /GF /GL /Gy /Gw /GR- /Gm- /DIVR_META_PROJECT_NAME=3rdparty /DIVR_PROJECT_NAME=libbullet3 /DIVR_BUILD_CONFIGURATION_Profile=1 /DIVR_BUILD_CONFIGURATION_NAME=Profile /DIVR_BUILD_PLATFORMTARGET_NAME=x64 /DIVR_INTERNAL_BUILD=1 /DIVR_BUILD_AUDIENCE=INTERNAL /D_HAS_EXCEPTIONS=0 /D_UNICODE /DUNICODE /D_USRDLL /D_WINDLL /I"C:\dev" /I"C:\dev\thirdparty" /I"C:\dev\Build\Configuration" /DIVR_IS_PLUGIN_BUILD=1 /DIVR_PLUGIN_NAME=3rdparty /wd4003 /wd4005 /wd4018 /wd4100 /wd4127 /wd4189 /wd4201 /wd4244 /wd4245 /wd4267 /wd4296 /wd4316 /wd4389 /wd4456 /wd4457 /wd4458 /wd4459 /wd4463 /wd4505 /wd4701 /wd4702 /wd4703 /wd4706 /wd4800 /wd6340 /wd6323 /wd28182 /wd6001 /wd6011 /wd6246 /wd6001 /wd6385 /wd6386 /wd6031 /wd6387 /wd6054 /wd6244 /wd6287 /wd6326 /wd6289 /IC:\FastBuild/External/Windows8.1/include/shared /IC:\FastBuild/External/Windows8.1/include/um /IC:\dev/3rdparty/bullet3/src /IC:\dev/3rdparty/Khronos/OpenCL/include /DIVR_DISABLE_PLUGINCORE_CODE /DIVR_DISABLE_LOAD_LIBRARY_CODE /DIVR_DISABLE_IVRCOMBASE_LIBRARY_CODE /DIVR_DISABLE_IVRPLUGINBASE_LIBRARY_CODE 
```

`TR4`, `D:\`:
```
9> Obj: D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
 - Cache Miss: 0 ms 'D011FEB3B3F53800_37868A95_AA27963E0354195B-0000000000000000.A'
9> Obj: D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj
C:\FastBuild\External\VS14.0\VC\bin\amd64\cl.exe /Zc:forScope /Zc:rvalueCast	/Zc:auto /Zc:implicitNoexcept /std:c++14 /DIVR_CPP17_EXPERIMENTAL_COMPILER_IS_SUPPORTED "D:\dev\Build\Output\Unity\3rdparty\bullet3\src\BulletDynamics_1.cpp" /Z7 /nologo /c /W4 /WX /Zc:wchar_t /Zc:inline /Zc:strictStrings /we4062 /we4263 /we4265 /we4296 /we4555 /we4619 /we4640 /we4826 /we4836 /we4905 /we4906 /wd6302 /wd6255 /wd4324 /cgthreads4 /fp:fast /D_CRT_STDIO_ISO_WIDE_SPECIFIERS /D"WIN32_LEAN_AND_MEAN" /D_WIN32 /D__WINDOWS__ /D "_WINDOWS" /D"_WINSOCK_DEPRECATED_NO_WARNINGS" /analyze:stacksize 1048576 /Fo"D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj" /I"./" /I"C:\FastBuild/External/VS14.0\VC\include/" /I"C:\FastBuild/External/Windows10/Include/10.0.16299.0/ucrt" /DWIN64 /DRELEASE /MD /Ox /Oy /Oi /GS- /GF /GL /Gy /Gw /GR- /Gm- /DIVR_META_PROJECT_NAME=3rdparty /DIVR_PROJECT_NAME=libbullet3 /DIVR_BUILD_CONFIGURATION_Profile=1 /DIVR_BUILD_CONFIGURATION_NAME=Profile /DIVR_BUILD_PLATFORMTARGET_NAME=x64 /DIVR_INTERNAL_BUILD=1 /DIVR_BUILD_AUDIENCE=INTERNAL /D_HAS_EXCEPTIONS=0 /D_UNICODE /DUNICODE /D_USRDLL /D_WINDLL /I"D:\dev" /I"D:\dev\thirdparty" /I"D:\dev\Build\Configuration" /DIVR_IS_PLUGIN_BUILD=1 /DIVR_PLUGIN_NAME=3rdparty /wd4003 /wd4005 /wd4018 /wd4100 /wd4127 /wd4189 /wd4201 /wd4244 /wd4245 /wd4267 /wd4296 /wd4316 /wd4389 /wd4456 /wd4457 /wd4458 /wd4459 /wd4463 /wd4505 /wd4701 /wd4702 /wd4703 /wd4706 /wd4800 /wd6340 /wd6323 /wd28182 /wd6001 /wd6011 /wd6246 /wd6001 /wd6385 /wd6386 /wd6031 /wd6387 /wd6054 /wd6244 /wd6287 /wd6326 /wd6289 /IC:\FastBuild/External/Windows8.1/include/shared /IC:\FastBuild/External/Windows8.1/include/um /ID:\dev/3rdparty/bullet3/src /ID:\dev/3rdparty/Khronos/OpenCL/include /DIVR_DISABLE_PLUGINCORE_CODE /DIVR_DISABLE_LOAD_LIBRARY_CODE /DIVR_DISABLE_IVRCOMBASE_LIBRARY_CODE /DIVR_DISABLE_IVRPLUGINBASE_LIBRARY_CODE 
```

`PC1`, `D:\`: -- couldn't find the `Obj:` command here?
```
40>Obj: D:\dev\Build\Output\x64-Profile\3rdparty\bullet3\src\BulletDynamics_1.obj <CACHE>
 - Cache Hit: 17 ms (Retrieve: 2 ms - Decompress: 11 ms) (Compressed: 1841385 - Uncompressed: 5006879) 'D011FEB3B3F53800_7B5C9CFF_AA27963E0354195B-0000000000000000.A'
```

**Comment by ffulin** [comment]
If using -showcmds, the command line won't be shown for a cache hit (since the compiler invocation was skipped), but it will be shown earlier for the preprocessing operation (it's possible the LightCache prevents this as that skips compiler invocation - I'd have to check the source code to be sure).

Based on the most recent output, TR4 from C: has a has a different paths, and thus the "source" and "command line" do not match the other cases and you have a cache miss as expected.

For TR4 D: and PC1 D: the source code matches, but you seem to have a command line difference. You'll need to examine the -verbose output from the PC1 D: cache generation operation (not the cache hit). It should be earlier in the log (light cache disabled to be sure as noted above)

**Comment by missmah** [comment]
@ffulin Yes, edited my message while you were writing yours :) Got the "diffable" output I needed and quickly solved it -- it was a removed `/analyze` command locally, which I had forgotten about during the time this 2nd machine had been out-of-commission.

Hopefully this thread will be helpful to others in the future. Thanks again for the help!

**Comment by missmah** [comment]
And, to clarify for others who run into this issue in the future, as @ffulin said, if you're using the `LightCache`, you need to delete the cache before running this experiment, or else you won't get the `command-line` for the machine which was getting cache hits.

**Comment by missmah** [comment]
Out of curiosity, though, for a case where the `preprocessed source` differs (rather than the command), how would you recommend getting that? Just use the command line that was passed to FastBuild via `-showcmds` and add `/E` to the command line?

**Comment by ffulin** [comment]
You don't need to delete anything from the cache, and I don't think that helps triage anything.

The general way to triage, given two machines is:

On machine A, perform a write-only operation:
```C++
fbuild.exe <target> -cachewrite -showcmds -clean
```

Then on machine B, perform a read-only operation:
```C++
fbuild.exe <target> -cacheread -showcmds -clean
```

Normally, that will print both sets of commandlines for each operation.

It's possible (as I said I'd need to check the source behaviour) that LightCache doesn't emit the command line for preprocessing in the cache hit case at all. That makes sense because the large speedup comes from skipping that invocation, but in a situation like this, that info might be useful. I will need to give it some thought.

**Comment by ffulin** [comment]
> where the preprocessed source differs ... how would you recommend getting that? ... use the command line ... via -showcmds and add /E to the command line?

Pretty much, though when using -showcmds, the first invocation will already have /E (or -E) as that's what FASTBuild uses, so you can just use that directly and pipe it to a file.

**Comment by missmah** [comment]
That is correct about `LightCache`, which is why I deleted it to get the data I needed in my case.

And just tried that -- again, possibly because of `LightCache`, there was no first invocation with `/E`, so I added it manually.

Fixing the issue with the `/analyze` command mentioned above did cause cache hits to appear. But only `20` hits. Still around `130` misses, for this configuration.

Looking at the first miss, everything was now equal *except* the `preprocessed source`.

Interestingly, using `/E` and looking at the diff, the source looks identical but for line numbers.

Starting somewhere in the middle of the file, all of the line numbers are `off-by-one` between the two diffs.

Possibly I accidentally added a spurious newline to a common header? I'll do some `git status` checking to see if I can hunt that down...

Anyway, thanks again, and again, hopefully this thread is helpful to someone else in the future. Perhaps we could formalize the commands/info into a "Shared Cache Debugging" Wiki?

**Comment by ffulin** [comment]
If by "delete LightCache" you mean disable the option in your bff, then that makes sense. If you mean literally delete files from the network cache file system, then that's unnecessary. It sounded like you were saying the latter. It's only important in so far as it could be confusing for anyone following in your footsteps.

> Perhaps we could formalize the commands/info into a "Shared Cache Debugging" Wiki?

I think a counterpart to the "[Distributed Compilation Troubleshooting](https://fastbuild.org/docs/troubleshooting/distribution.html)" page is what I'd go with.

**Comment by ffulin** [comment]
> And just tried that -- again, possibly because of LightCache, there was no first invocation with /E, so I added it manually.

Thanks for the confirm. That makes sense.

**Comment by missmah** [comment]
Is that something that is in source control and/or that I can help write? Or something you want to handle?

Thanks again for all the help!

**Comment by ffulin** [comment]
For completeness, the main reason why I suggest not using the LightCache for now is this PR: https://github.com/fastbuild/fastbuild/pull/716

I have not accepted that PR yet because I think there might be deeper issues and I have not had the time to investigate properly yet.

**Comment by ffulin** [comment]
> Is that something that is in source control and/or that I can help write? Or something you want to handle?

The documentation/fastbuild.org website (which are the same thing) are versioned inside github, the root of which is here: https://github.com/fastbuild/fastbuild/tree/dev/Code/Tools/FBuild/Documentation . 

PRs are gladly accepted to improve the documentation, if that's something you're interested in making a start. I guess some of the detail I provided in my initial response would make a good start to help people troubleshoot.

**Comment by missmah** [comment]
Thanks for the context of PR: #716 

I can't promise it, because I'm about to head to bed now, and I don't know what fires will get in my way tomorrow -- but I'll put it on my `TODO` list, in-case I end up with a few spare minutes I can devote to it (as I'd certainly like to!)

Have a great night!

**Comment by missmah** [comment]
@ffulin here's my first draft stab at the documentation: https://github.com/fastbuild/fastbuild/pull/729

I think you'll probably need to take it from here, or give me pointers on the `TODO`(s), or recruit someone else to fill those parts in, as I don't feel qualified to elaborate on them yet. But, hopefully this is a good starting point, and maybe it can even be merged with some cleaned-up version of the `TODO`s, as it's still likely more helpful than not.

**Comment by ffulin** [comment]
Cheers!
