### ISSUE TITLE
LightCache crashes with read access violation exception

### ISSUE THREAD

**Issue by lucianm** [fastbuild/fastbuild#728]
Hello,

after almost happily using `.UseLightCache_Experimental = true` in a production environment for 4 months now, FASTBuild crashes out of the blue, lately especially on our build servers made me dig a little bit more into it, I ended up running our rather large project build in the debugger with the very latest FASTBuild sources. It happens randomly, every time at building some other target, but it's gotten me to the point that I reverted the LightCache activation.

I also found an indication others had some maybe similar problems: 

> `.LightCache` helps immensely though but it crashed from time to time, tried couple of weeks ago. 
_Originally posted by @claimred in https://github.com/fastbuild/fastbuild/issues/723#issuecomment-605876454_

Nevertheless, at least I tried to narrow down the problem a bit, and this is what I found in the debugger (sorry it's only 2 screenshots for now):
![2020-04-09 11_28_38-FASTBuild (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/602101/78881892-b4115680-7a57-11ea-8816-80350df16209.png)
![2020-04-09 11_29_20-FASTBuild (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/602101/78881925-bd022800-7a57-11ea-8a6e-0d213430b872.png)

Looks like a race condition to me, it seems that `def` is no longer a valid pointer, the container over which the iteration is performed might have been modified at the same time, hope that helps identifying what's wrong.

**Comment by ffulin** [comment]
A few bugs have been uncovered in the LightCache. There are at least two known issues:
 - a crash (very likely the one you are seeing)
 - incorrect key generation, resulting in (best case) cache misses or (worst case) incorrect results

There are some PRs for these issues, but one of them I believe is incorrect and I'm uncertain about the other one. I hope to find some time to investigate these problems soon.

For now, I recommend not using LightCache in a production environment.

**Comment by ffulin** [comment]
Thanks again for the bug report. I've been able to add tests that 100% repro this crash and have confirmed that the fixes in (https://github.com/fastbuild/fastbuild/pull/716) resolve the problem. These fixes have been integrated and will be in the next release (v1.00)

I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.00 has now been released. It includes the fix for this issue.
