### ISSUE TITLE
Get 1028 code error when generate XCode project with XCodeBuildToolArgs

### ISSUE THREAD

**Issue by allenwalker31** [fastbuild/fastbuild#731]
Hello, I try generating xcodeproj from FASTBuild. When I add  **.XCodeBuildToolArgs = '-ide -cache -summary $(FASTBUILD_TARGET)'** same as document, I get error code 1028: Cannot find '$' to end variable substitution.
.XCodeBuildToolArgs = '-ide -cache -summary $(FASTBUILD_TARGET)'
	                                            ^
	                                            \--here
How should I config for XCodeBuildToolArgs and avoid this error?

**Comment by ffulin** [comment]
When you want to use $ literally (rather then denoting the start of a variable substitution), you can escape it with ^:
```C++
.XCodeBuildToolArgs = '-ide -cache -summary ^$(FASTBUILD_TARGET)'
```

I took a look at the documentation for this option and saw it was lacking this which makes it somewhat confusing. I've updated the documentation for the next release (https://github.com/fastbuild/fastbuild/commit/4b6d7273713c2f63f5592dd9921eaaf785bd3b15).

**Comment by allenwalker31** [comment]
Thank you, I generated xcodeproj with XCodeBuildToolArgs now
