### ISSUE TITLE
A case for extending #if

### ISSUE THREAD

**Issue by ggnkua** [fastbuild/fastbuild#732]
Hello,

I'm in the process of porting a rather large project over to fastbuild, and like the subject says, I've been taking hits when it comes to using #if with something more complex than one variable. However, my cases are not super crazy, mostly along the lines of:

`#if aaa & bbb`
`   ...`
`#endif`

or

`#if aaa | bbb`
`    ...`
`#endif`

The first one I can work around with a nested #if, no biggie. But the second really hurts as I have to copy the insides of the #if twice and have two separate #if one below the other. This gets messy rather quick.

Now, I took the liberty and writing some code that seems to work fine with the above cases, or any arbitrary combination of logical AND, OR, NOT. I can make an effort to produce a pull request for you but I'd like to know your thoughts on this first in order to not waste much time on this. By sheer luck I came across [a previous post of you discussing the matter ](https://github.com/fastbuild/fastbuild/issues/715#issuecomment-602077915), and I agree that going overboard with extending #if will not yield anything practical, but is for more academic use.

Just for reference, here is the test .bff that seems to work ok with my code:

```
#define aaa
#define bbb
#define ccc
#if aaa & bbb
    Print('AND test #1 ok')
#endif
#if aaa & bbb & ccc
    Print('AND test #2 ok')
#endif

#if ccc | ddd
    Print('OR test #1 ok')
#endif
#if ddd | ccc
    Print('OR test #2 ok')
#endif
#if ccc | ddd | aaa | bbb
    Print('OR test #3 ok')
#endif

#if aaa & !ddd
    Print('AND ! test #1 ok')
#endif
#if !ddd & !aaa
    Print('AND ! test #2 ok')
#endif
    
#if !eee | !ddd
    Print('OR ! test #1 ok')
#endif
#if aaa | !ddd
    Print('OR ! test #2 ok')
#endif
#if !ddd | aaa
    Print('OR ! test #3 ok')
#endif

;Should produce syntax error
#if | ddd
    Print('| at the start - should not reach this!')
#endif
#if & ddd
    Print('& at the start - should not reach this!')
#endif
```

Looking forward to your reply!

**Comment by ffulin** [comment]
I think it'd be nice to extend #if to support OR and AND and I'd be open to a PR to that end. 

A couple of thoughts that spring to mind about this:
 - I think we'd want to use && and || as the operators like C/C++ (as opposed to & and |)
 - Your example bff looks like a pretty good start at some test cases. Would be great to extend that into a test for the new functionality (you probably saw it already, but TestBFFParsing.cpp is a good example of various ways to test something like thi
 - We'd want to make sure that mixed && and || works sensible, particularly with respect to precedence order which should similarly work like C/C++

**Comment by ggnkua** [comment]
Hello,

> I think it'd be nice to extend #if to support OR and AND and I'd be open to a PR to that end.
> 
> A couple of thoughts that spring to mind about this:
> 
> * I think we'd want to use && and || as the operators like C/C++ (as opposed to & and |)

Okay, I don't care too much about syntax so no objections there, I used single character symbols to make it easier to code :) But I'll give it a shot

> * Your example bff looks like a pretty good start at some test cases. Would be great to extend that into a test for the new functionality (you probably saw it already, but TestBFFParsing.cpp is a good example of various ways to test something like this)

Nope, didn't notice that file at all, I'll have a look.

> * We'd want to make sure that mixed && and || works sensible, particularly with respect to precedence order which should similarly work like C/C++

I'm not really up to speed with that. But I think that a left-to-right parsing of an #if statement wouldn't contain any ambiguities? Also, I didn't implement parentheses handling to avoid going into the crazy town of recursion or keeping weird states.

Anyway, I'll get started towards a PR while I wait for your clarifications!

**Comment by ggnkua** [comment]
I just checked out the dev branch on git as I've been writing code against the v0.99 source release and saw that there are considerable changes in the code. I'll give it a shot and see what happens. Also I should say that I never made a PR in my life so this will be a bit awkward for me!

**Comment by ggnkua** [comment]
#733

**Comment by ggnkua** [comment]
So here's the promised PR. I hope you agree with what I did in principle. There are a few things I didn't know how to deal with, such as:

* I wasn't sure where to put that enum at the top of the function so I left it there for now.
* Although I added tests I'm not sure exactly what happens on errors as the current dev build doesn't produce any errors printed on my win10 console. I imagine this is a bug but right now I can't do much more than what I did

**Comment by ffulin** [comment]
> But I think that a left-to-right parsing of an #if statement wouldn't contain any ambiguities?

I agree we can live without support for braces, but we can't ignore precedence rules.

Consider the following C code:
```C++
#define A 1
#define B 1

#if A || B && C
    int Func() { return 0; } // This will be compiled
#endif
```
because precedence rules result in this evaluation:
```C++
#if A || (B && C)
    int Func() { return 0; } // This will be compiled
#endif
```
while a simple left to right comparison would evaluate as:
```C++
#if (A || B) && C
int Func() { return 0; } // This will not be compiled
#endif
```

**Comment by ggnkua** [comment]
All fair comments (also on the PR). Also, I mostly expected that I got pretty much everything wrong since I really don't have a feel for the code base!

I'll have another go at it in about 3 days - it's Easter holidays here and have things to do!

**Comment by ggnkua** [comment]
Hello again,

So I've altered my PR to respect operator precedence, updated the tests and things seem to be fine. From my side I only have two open questions now:

- Use of enum class as noted [in this thread](https://github.com/fastbuild/fastbuild/pull/733#discussion_r412011969)
- Fastbuild's error philosophy. In Error.cpp I notice that error numbers go from 1000 to 1060 (with a few gaps), then jump to 1100, then to 1200 etc. My inclination would be to use the 1000-1099 range since the #if errors are in there. But which number do I pick? Just the next available? etc etc

Thanks

**Comment by ffulin** [comment]
Keeping the enum as you have it makes sense given what you've said in the other thread.

For errors, general parsing errors are in the 1000-1049 range, so if you need to add a new erro, that's probably the place for it.

**Comment by ggnkua** [comment]
All right, I've added errors as well. I think that's all then. The PR is at your disposal for review!

**Comment by ggnkua** [comment]
Hello, any news on this?

**Comment by ffulin** [comment]
This changes has been integrated and will be in the next release (v1.02). I'll leave this issue open until that version is released. Thanks for your contribution!

**Comment by ffulin** [comment]
v1.02 has now been released which includes this new functionality. Thanks for helping to improve FASTBuild!
