### ISSUE TITLE
FBuildWorker Protocol

### ISSUE THREAD

**Issue by Swoogan** [fastbuild/fastbuild#734]
I am interested in getting statistics about how many cores are available at any given time across the worker pool. I can get the names of the machines from the broker path, but I'm curious about the FBuildWorker protocol and if I could make a call to all machines that would report back their status (ie: how many cores they have generally available and if said cores are idle or busy with fbuild work)?

Any information you could provide would be appreciated.

**Comment by ffulin** [comment]
In the next version (v1.00) the brokerage tokens contain some information about the configuration of each worker. Perhaps this information is what you are after?

```C++
Version: v1.00
User: Franta
CPUs: 12/24
Mode: dedicated
```

**Comment by Swoogan** [comment]
After reading the code, I think my assumption was wrong. I thought the machines in the broker path were are all the machines running FastBuildWorker and then when fbuild had work, it would query those machines for availability. However, it appears they add and remove the broker token based on their availability. Is this correct?

What you listed would be helpful, but would still not tell me the total number of machines running FastBuildWorker, if my new understanding is correct.

**Comment by ffulin** [comment]
*> However, it appears they add and remove the broker token based on their availability. Is this correct?*

That's right. Only machines that have some chance of accepting work have tokens in the brokerage path. There isn't any way currently to query machines who are running FBuildWorkers but are disabled/prevented from doing work entirely.

The current implementation is a deliberate choice to:
 - only require a single directory listing of the brokerage frolder to get the list of available workers
 - avoid connecting to workers who cannot accept work (reducing overall network connections)

**Comment by Swoogan** [comment]
Those are perfectly valid reasons. Thanks for the information.
