### ISSUE TITLE
Fastbuild timeout

### ISSUE THREAD

**Issue by zorofee** [fastbuild/fastbuild#737]
Hi everyone, I met a problem when compiling UE4 shaders : my remote worker always time out ,  I don't konw if its related to the file path.  And where can I get the log files？ 

![image](https://user-images.githubusercontent.com/13816313/81789336-685e3b00-9536-11ea-92b9-4ba183ad6978.png)

![image](https://user-images.githubusercontent.com/13816313/81789304-5a101f00-9536-11ea-87e9-0866b01cbb1c.png)

**Comment by zorofee** [comment]
I wonder what kind of path should be used in .ExtraFiles or .Executable ,  relative or absolute?And why?

**Comment by ffulin** [comment]
All paths passed to functions (like Compiler, Executable etc) are relative to the root path (the working directory you run FASTBuild from, which is usually where the fbuild.bff file is)

Full paths are usually a bad idea for all the usual portability reasons, but generally are handled correctly. It's quite possible that using full paths in the compiler files is not handled correctly during distribution though.

For distributed compilation, the logs are returned to the host and emitted like any other output when a job completes or fails. In the case of a worker timeout, the remote worker has become unresponsive. For debugging, you may be able to run a worker remotely in -console mode to get some more information on the remote end.

**Comment by zorofee** [comment]
> All paths passed to functions (like Compiler, Executable etc) are relative to the root path (the working directory you run FASTBuild from, which is usually where the fbuild.bff file is)
> 
> Full paths are usually a bad idea for all the usual portability reasons, but generally are handled correctly. It's quite possible that using full paths in the compiler files is not handled correctly during distribution though.
> 
> For distributed compilation, the logs are returned to the host and emitted like any other output when a job completes or fails. In the case of a worker timeout, the remote worker has become unresponsive. For debugging, you may be able to run a worker remotely in -console mode to get some more information on the remote end.

Thank you so much!  I run with "-console", and see the failed info :"Failed to store fileId 1885 for mainfest 0x2947738c5cdabe7e" , I do not quiet understand. Could you give me any suggestion?

**Comment by ffulin** [comment]
>  I also set the ".CachePath =.\cache" but didn't see any cache directory or files , in which case can generate cache files in FB ? And where is the path related to?

The .CachePath has no effect on remote workers.  The .CachePath is for the host machine and is usually pointed to a network location - i.e. the cache is usually used for sharing compilation results between machines, though it can be useful to have a local cache in some instances.

For basic information about caching, you can look here: https://fastbuild.org/docs/features/caching.html

Some troubleshooting documentation for caching should be in the next release. You can preview the PR here: https://github.com/fastbuild/fastbuild/pull/729

**Comment by zorofee** [comment]
> > I also set the ".CachePath =.\cache" but didn't see any cache directory or files , in which case can generate cache files in FB ? And where is the path related to?
> 
> The .CachePath has no effect on remote workers. The .CachePath is for the host machine and is usually pointed to a network location - i.e. the cache is usually used for sharing compilation results between machines, though it can be useful to have a local cache in some instances.
> 
> For basic information about caching, you can look here: https://fastbuild.org/docs/features/caching.html
> 
> Some troubleshooting documentation for caching should be in the next release. You can preview the PR here: #729

 Thx so much  :)

**Comment by ffulin** [comment]
As of v1.01, FASTBuild (FBuild.exe and FBuildWorker.exe) esupports longer path length limits with Windows 10 (if enabled in the registry as per https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation). This might provide a way for you to solve this problem if otherwise shortening the directory structure is not possible.

**Comment by ffulin** [comment]
I think there is nothing remaining that is actionable on the FASTBuild side for this ticket, so I'm going to close this for now. We can re-open or raise new issues as needed if that's not the case.
