### ISSUE TITLE
Question: post-stamp step that changes the executable

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#739]
Heya!

I have a few post-build steps that need to run after the executable stamping, which will affect the executable file: I'm actually extracting the debug info from a linux executable so they are in a separate file, and stripping the exe after (like described here https://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target).

The issue is that because the executable file has changed, running fastbuild again after the build finished successfully once will relink the executable, since fastbuild thinks that it changed.

Is there a way to add additional "stamping" steps, or to mark a step as affecting the output file so fastbuild treats it accordingly?
As a workaround I can put all those in a bash script that would be run as stamping steps, but that's a little sad...

Thanks for your inputs!

**Comment by ffulin** [comment]
Currently, only one "stamping" step is supported directly. I've considered extending this to support multiple steps, and this could be a reasonable extension and fairly easy to implement. The only complexity is backwards compatibility/syntax.

Currently, I know of 3 ways to handle situations like this:

**1. Invoke multiple commands, chained via bash or cmd.exe.**

This is what FASTBuild does on Linux to extract debug info:

```C++
            #if __LINUX__
                .LinkerStampExe             = '/bin/bash'
                .ExtractDebugInfo           = 'objcopy --only-keep-debug $LinkerOutput$ $LinkerOutput$.debug'
                .StripDebugInfo             = 'objcopy --strip-debug $LinkerOutput$'
                .AddDebugLink               = 'objcopy --add-gnu-debuglink $LinkerOutput$.debug $LinkerOutput$'
                .LinkerStampExeArgs         = '-c "$ExtractDebugInfo$ && $StripDebugInfo$ && $AddDebugLink$"'
            #endif
```

**2. An external batch file/script**

This is the option you mentioned. Ultimately, it's very similar to 1), but I find 1) a little nicer as it allows the details to still remain in the bff.

**3. Link to an intermediate output**

You can link to a "tmp" file and then chain operations via additional Exec commands. This is the most flexible, in that each Exec step can provide a lot of control over each step (including merging steps for example) but has the downside of filling the disk with multiple copies of things.

**Comment by ffulin** [comment]
I'm going to close this issue as answered. Please let me know if you have any follow up questions.

**Comment by belkiss** [comment]
Thanks! Sorry for the delay, will probably use option1 for now but will have a though about ways to change fastbuild to handle multiple postbuild steps that change the exe, maybe an additional property in the step.
