### ISSUE TITLE
Deadlock when posting WM_QUIT via the FASTBuild Dashboard

### ISSUE THREAD

**Issue by MrPeteypoo** [fastbuild/fastbuild#740]
Hi, I've been doing some fixes and enhancements to the Dashboard and one of those fixes was to ensure when we kill the worker (due to an update) or when we close the Dashboard, the worker should close cleanly too.

Using [SendMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage) I tell FBuildWorker to `WM_QUIT`. Instead of closing cleanly and setting itself as unavailable it freezes a majority of the time.

I hooked up my debugger and found that although `WM_QUIT` is handled and `m_WantToQuit` is set to `true`, the polling of messages is stopped and `WorkerWindow::Work` returns to `Worker::Work` on the main thread. The main thread then calls `return Thread::WaitForThread( m_WorkThread );`. 

During this time, `m_WorkThread` may try to call `Worker::UpdateUI` and eventually we get down to `OSListView::SetItemText` where [SendMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage) is called. This function is defined to wait until the message has been processed, but as we're no longer processing messages this will never happen and FBuildWorker will never exit cleanly.

I'll fork FASTBuild and try to fix the issue but your input would be much appreciated of the best way to fix this without unwanted side effects.

**Comment by MrPeteypoo** [comment]
I implemented this change and it seems to work. It feels a little hacky, if you have a better suggestion let me know :)

https://github.com/MrPeteypoo/fastbuild/commit/438de0a9b11286d28aeee15bd7d51d39d0b04a34

**Comment by ffulin** [comment]
Thanks for looking into it. I think this will need some more detailed investigation, as your change feels a bit like covering up the problem rather than a true fix. That makes me concerned that there are other issues. Additionally, the behavior of the message pump on OSX is quite different to Windows and needs to be considered.

**Comment by MrPeteypoo** [comment]
Yeah I can't test Mac myself and can't test Linux easily either. The fundamental issue comes from the the worker expecting messages to be processed before it can complete. There's multiple places for example where it uses SendMessages to update the UI and these functions explicitly require messages to be processed otherwise they don't return.

It could be that this is a Windows-exclusive problem but I haven't been able to confirm that as I'm working on the Dashboard which is only on Windows.

**Comment by ffulin** [comment]
I've implemented a fix for the deadlock (https://github.com/fastbuild/fastbuild/commit/03c93257fa013884d32741196758e431df1acfc0). This will be in the next release (v1.02). I'll leave this issue open until that version is released. Thanks for reporting the problem!

**Comment by ffulin** [comment]
v1.02 has now been released which includes a fix for this issue. Thanks for reporting the bug!
