### ISSUE TITLE
Allow "pass by reference" for user functions

### ISSUE THREAD

**Issue by mkujawa** [fastbuild/fastbuild#744]
Passing a variable to a function always copies it into the new scope right now.  It would be very handy to be able to modify the struct that's passed in.  If only return values were supported as a way for a function to generate state, then it is more difficult to modify several different things at once (like a pair of arrays)  and potentially very expensive copies are avoided (imagine having a giant, deep, array of structs of etc etc, and this function wants to add another to it.)

Just for some brainstorming, here is one potential syntax:
```
function TestFunc( &ref1 .value2 )
{
    .MyValue = [ .values { 1, 2, .value2 } ] 
    ^ref1 + .MyValue
}

.MyStruct = [ ]
TestFunc( &.MyStruct 3 )
```

I'm using the `&` at both the parameter definition and the call site, similar to how C# uses the `ref` keyword.  I have the call site still using the `.` or `^` to indicate what scope to get the reference from, and to clarify that it's getting the value of a variable and not a function; but I don't think this is strictly necessary.  I then opted to use the "parent scope" syntax to dereference, since functions currently don't have any parent scope.  This has the effect of giving TestFunc very selective, explicit parent scope.

This could be taken even further if references are allowed to be stored into variables, an alternative to the current dynamic variable construction.  A dereference syntax would be needed, possibly `^(.MyRef)` to follow the example set above, but that's not as intuitive a result here.  Perhaps `.(.ref1)` or `^(.ref1)` is preferable in both uses.

(I initially mentioned this in https://github.com/fastbuild/fastbuild/issues/742, but am creating this to narrow the focus and provide enhancement tracking.)

**Comment by ffulin** [comment]
I would not rule out the possibility of adding this at some point in the future, but there are no plans to do so right now and I think other improvements to the language/syntax will address many of the needs this would in ways that are easier for users to understand, maintain and debug (return values being the first and most obvious example).

In the interests of trying to reign in the backlog, I'm going to close this issue for now. It can be re-evaluated again in the future of course.
