### ISSUE TITLE
Support function pointers

### ISSUE THREAD

**Issue by mkujawa** [fastbuild/fastbuild#746]
This is where I really expect user functions to shine.  It allows several things:
1) In a large build system with many projects, each project can specify settings like "project type", and these variables can be used to look up an array of function pointers that are then used to generate the function calls that define the project to fastbuild
2) when combined with https://github.com/fastbuild/fastbuild/issues/744 you can create an object-oriented system in the way that LUA or ActionScript do 

A possible syntax:
```
function TestFunction(  .a .b )
{
  Print( .a )
  Print( .b )
}

.MyStruct = [ .Func = &TestFunction ]
Using( .MyStruct )
{
    .Func( "hello" "world" )
}
```

**Comment by ffulin** [comment]
This could certainly be an interesting feature, but there are no plans right now to add this functionality.

In the interests of trying to reign in the backlog, I'm going to close this issue for now. It can be re-evaluated again in the future of course.
