### ISSUE TITLE
Problems upgrading from 0.94

### ISSUE THREAD

**Issue by Swoogan** [fastbuild/fastbuild#747]
When I attempt to upgrade from 0.94 to 1.0 I get the following errors:

```
./fbuild -config fbuild.bff -nostoponerror proj
fbuild_Configuration.bff(103,5): FASTBuild Error #1004 - Compiler() - Empty string not allowed for property 'Environment'.
    Compiler( "Compiler-X" )
    ^
    \--here
```

The documentation states:

> .Environment - String or ArrayOfStrings - (Optional)

Given that it's optional, I don't understand why it's complaining. In spite of that, I added 

    .Environment = 'abcd'

which got rid of the error. I didn't know what value to use because the documentation doesn't explain what an "environment" is in this context. It's sort of written in a style where if you know what it means, it makes sense, but if you don't, it doesn't really explain anything.

After that, I get this error:

```
./fbuild -config fbuild.bff -nostoponerror proj
fbuild_Generators.bff(26,5): FASTBuild Error #1500 - Compiler detection failed. Unrecognized executable 'NugetPackage\Microsoft.Net.Compilers.1.3.2\tools\csc.exe'.
    CSAssembly('AnAssembly')
    ^
    \--here
```

I tried using the version 2.0.1 and 3.6.0 nuget packages, but neither work. With this regression, I'm dead in the water.

Given these issues, I thought that I might have more success upgrading to a revision closer to the one I'm using, namely 0.95, but I got the following error:

```
./fbuild -config fbuild.bff -nostoponerror proj

Some.bff(20,5): FASTBuild Error #1004 - DLL() - Empty string not allowed for property 'Libraries'.
    DLL( "$Lib$-$Platform$-$Config$-DLL" )
    ^
    \--here
```

In fact, all versions from 0.95 - 1.0 gave me errors. I read all of the changelogs, but I wasn't able to find any breaking changes that would indicate the cause of these problems.

Any ideas how I can move forward? I'm trying to upgrade because distribution is no longer working reliably and I would like the improved `-distverbose` logging so that I can (hopefully) fix the issue.

**Comment by ffulin** [comment]
Wow, you are almost 3 years behind :)  I think it makes sense to jump straight to the latest version. I think we can easily resolve your issues.

I've listed the solutions and an explanation of each scenario below.

Let me know if you run into any other problems.

**> Empty string not allowed for property 'Environment'.**

v0.98 added the ability to set a custom set of environment variables for your Compiler (and a few other things). It seems you have set an empty .Environment String globally that is now being seen by this new option.

The reason it complains, even though the property is optional, is that the underlying property is an ArrayOfStrings which allows assignment of a string for convenience. The subtle difference is that an Array of strings with one empty string in it is different from an empty ArrayOfString.

There are two possible fixes here:
a) remove or scope the global .Environment that is leaking into the Compiler scope
OR
b) set the .Environment to an empty array inside you Compiler():
```C++
    .Environment = {}
```

> the documentation doesn't explain what an "environment" is in this context. It's sort of written in a style where if you know what it means, it makes sense, but if you don't, it doesn't really explain anything.

The documentation certainly could use some improvement in many places. It continues to improve over time but there is much to be done.

> Compiler detection failed. Unrecognized executable

Prior to v0.95, FASTBuild would attempt to detect the compiler, and when it failed, would silently fall back to generic compilation with limitted dependency tracking. This could result in difficult to track down problems. To make these situations more obvious, FASTBuild will now fail with the error above in those cases. To accept that only limited dependency tracking will occur, you can set the following in your .Compiler definition:

```C++
.CompilerFamily = 'custom'
```

This works well for the ObjectList/Library case, but it's a bit weird that this error is generated from CSAssembly. FASTBuild could probably be improved to handle this case automatically by detecting the C# compiler automatically.

**Comment by Swoogan** [comment]
I have attempted to add the compiler family, however it has no effect.

```
{
    .Compiler           = 'NugetPackage/Microsoft.Net.Compilers.1.3.2/tools/csc.exe' 
    .CompilerFamily     = 'custom'
    .CompilerOptions    = '/target:library /out:%2 %1 /reference:"%3" /debug /pdb:%2'
    .CompilerInputPattern = '*.cs'

    //------------------------------------------------------------------------------
    
    CSAssembly('AnAssembly')
    {
        .CompilerOutput     = 'path/to/an/assembly.dll'
        .CompilerInputPath  = 'Code'
        .CompilerFamily     = 'custom'
    }
```

Note: I have `.CompilerFamily` at two scopes. I've tried all three combinations of placement, none have any effect. The documentation implies that `CompilerFamily` is not an option for `CSAssembly`, like it is for the `Compiler` function.

**Comment by ffulin** [comment]
Sorry, I thought you had your C# compiler already defined in a Compiler() function. You need to do this:
```C++
Compiler( 'CSharpCompiler' )
{
    .Executable        = 'NugetPackage/Microsoft.Net.Compilers.1.3.2/tools/csc.exe' // Whatever your path is
    .CompilerFamily    = 'custom'
}

CSAssembly( 'Thing' )
{
    .Compiler          = 'CSharpCompiler'
```

**Comment by ffulin** [comment]
I've made a small improvement so that csc.exe will be automatically detected as a C# compiler, removing the need to set it as a "custom" compiler. This also allows you to continue to directly reference the compiler in the ObjectList (no need to define an explicit Compiler()).  This change (https://github.com/fastbuild/fastbuild/commit/64ffe3a1e17bb56c77b77e2ac5e6eb65250dfb6c) will be in the next release (v1.01)

**Comment by ffulin** [comment]
v1.01 has been released and includes the fix mentioned above
