### ISSUE TITLE
ObjectList chaining and outdated codegen artifacts

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#748]
I've ran into a couple of issues with things like moc.exe or midl.exe. Basically what I have is this:

```
ObjectList('ObjectList1')
{
  .Compiler = 'moc' 
  .CompilerInputFiles = { '1.moc', '2.moc', '3.moc' }
  .CompilerOutputPrefix = 'moc_'
  .CompilerOutputExtension = '.cpp'
} // 1.moc, 2.moc, 3.moc -> moc_1.cpp, moc_2.cpp, moc_3.cpp

ObjectList('ObjectList2')
{
  .PreBuildDependencies = 'ObjectList1'

  .Compiler = 'cl' 
  .CompilerInputPattern = '*.cpp'
 } // moc_1.cpp, moc_2.cpp, moc_3.cpp, 4.cpp, 5.cpp -> obj
 
```
Now, suppose I receive removal of 2.moc from the upstream, yet I still have moc_2.cpp generated from previous runs, nobody knows that it should be deleted, and ObjectList2 will still try to compile it resulting in a compile error. 
 
 What am I missing here? Maybe it's possible to directly chain one ObjectList into another?

**Comment by ffulin** [comment]
The way you have it setup is currently the only way to directly chain one ObjectList into another, and there isn't a way to avoid the problem you've encountered.

A mechanism could be added to make this use-case robust. We'd add a .CompilerInputObjectList property to ObjectList() to allow explicit chaining.

In the short term, you might be able to use what i use for moc files at least, which is to use Unity() in the middle, which does have such a chaining mechanism.

The basic setup is this:
```C++
// Generate the .moc files
ObjectList( 'Moc-Generate' )
{
    .Compiler = 'moc' 
    ... etc ...
}

// Create a Unity file for the moc files
Unity( 'Moc-Unity' )
{
    .UnityInputObjectLists  = 'Moc-Generate'
    ... etc ...
}

// Compile the Unity
ObjectList( 'Moc-Compile' )
{
    .CompilerInputUnity = 'Moc-Unity'
    ... etc ...
}
```

When an object is added or removed, the Unity is correctly rebuilt, and as it's used as an input directly, the final ObjectList only compiles what is required.

(There is the side-benefit of improved compile times through the use of Unity as well.)

**Comment by claimred** [comment]
@ffulin Thanks for the advice! Unity object list chaining will help in our case. 

Speaking of midl.exe I noticed another thing about it. It generates .h files just like uic.exe mentioned here https://github.com/fastbuild/fastbuild/issues/465

Suppose I have a target with uic object list prebuild dependency. 
```
ObjectList( '$ProjectName$-uic' )
{
  .Compiler = 'uic'
  .CompilerInputPattern = '*.ui'
  .CompilerOutputPrefix = 'ui_'
  .CompilerOutputExtension = '*.h'
  ...
} // 1.ui -> ui_1.h, 2.ui -> ui_2.h

ObjectList( '$ProjectName$' )
{
  ...
  .PreBuildDependencies = $ProjectName$-uic
}
```
Now, I delete 1.ui, try to build $ProjectName$ target and that happens:
```
fbuild $ProjectName$ -verbose -showcmds
...
4> Obj: ui_1.h
uic.exe -o ui_1.h 1.ui
4> Error: opening file 1.ui while loading source file for transport
```
For some reason FASTbuild still tries to build .h file, fbuild.exe $ProjectName$ -clean or deleting .fdb solves the issue.

It feels like there is something special about codegenerating header files?

**Comment by ffulin** [comment]
For the uic case you mention, I think there might be something additionally in play, like a stale cpp file that references the header, which in turn references the .ui file. You may be able to use -showdeps to understand where the dependency is coming from.

**Comment by ffulin** [comment]
I've implemented a new .CompilerInputObjectLists property on ObjectList which allows ObjectLists to be chained together (https://github.com/fastbuild/fastbuild/commit/83f541c992e237865586bfd444bea5c26e6c913c). This should avoid issues with stale files/dependencies and avoids the need to use the Unity workaround (though that can still be used for cases where it brings other benefits). This will be in the next release (v1.02). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.02 has now been released which includes the new functionality.
