### ISSUE TITLE
Is fdb a sqlite database? If it is, what's the password?

### ISSUE THREAD

**Issue by pythonperl** [fastbuild/fastbuild#755]
I wanna checkout the final compiler command generated by FB. 
I guess it was stored in fdb file so I try to open it by sqlitespy, but password required.

thank you.

**Comment by ffulin** [comment]
The .fdb is a custom binary file. It doesn't contain the final command lines used to invoke the compiler, but rather the information necessary to build the command line at runtime.

If you want to see the command lines being used for a given build, the best two options are:

a) use the -[showcmds](https://fastbuild.org/docs/options.html#showcmds) command line option. This will print the full command line used for each item being built

OR

b) use the -[compdb](https://fastbuild.org/docs/options.html#compdb) command line option. This will print a json file in the Clang compilation database format

**Comment by pythonperl** [comment]
Thank you for the rapid reply.

**Comment by ffulin** [comment]
I'll close this issue for now. Please let me know if you have any followup questions.
