### ISSUE TITLE
Unity files isolation and git vcs

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#766]
If I understand correctly `.UnityInputIsolateWritableFiles` is supposed to work with Perforce only. On the other hand, according to this PR https://github.com/fastbuild/fastbuild/pull/220 `.UnityInputIsolateListFile` is a more generic solution that requires a bit of work.

Just to make sure, I should write something like `.Exec( 'git-status' ) {}`, use it as .PreBuildDependency, gather modified files from it and pass it down to `.UnityInputIsolateWritableFiles`. Am I getting this right?

**Comment by ffulin** [comment]
A pre-build dependency as you've described should work. Alternatively, invoking git yourself beforehand would also be fine if that's practical in your build setup. (For example you could easily invoke git first from visual studio by having multiple commands in the .ProjectBuildCommand.

It would be nice in the future to have a better integration that just works, which would probably involved invoking git and parsing the output.

**Comment by ffulin** [comment]
I'm going to close this issue as answered for now. Let me know if you have any followup questions.
