### ISSUE TITLE
New built-in variable to retrieve the path to the FastBuild executable being run?

### ISSUE THREAD

**Issue by belkiss** [fastbuild/fastbuild#775]
Heya!

I was wondering if it would make sense to add a new built-in variable that would return the path to the current fastbuild executable.
My use case would be the solution generator for instance like here: https://github.com/fastbuild/fastbuild/blob/79d1410bc58db3d21560db7d3206b25ef65231b7/Code/fbuild.bff#L279

We would use it instead of writing `fbuild`.

Thanks!
Lambert

**Comment by ffulin** [comment]
This seems like a good additional feature - makes sense to me.

**Comment by ffulin** [comment]
A new variable (_FASTBUILD_EXE_PATH_) was made available in v1.09 but this issue slipped through and wasn't closed at that time.
