### ISSUE TITLE
List all targets command switch

### ISSUE THREAD

**Issue by cyberkm** [fastbuild/fastbuild#78]
It will be really nice to have somekind of `fbuild --list-build-targets`
command switch that will enumerate all build targets one can build

**Comment by ffulin** [comment]
This would certainly be possible. The option would need to iterate the dependency graph has table and build a list of all Alias nodes. It could then (sort and) print them out.

Note: This pull request (which gives hints when you mis-type) may be of interest: https://github.com/fastbuild/fastbuild/pull/69
That will almost certainly be in the next version (v0.89)

**Comment by cyberkm** [comment]
Ok, i just created a pull request, with new -targets switch. I really not sure that sorting them will be benefit.

**Comment by ffulin** [comment]
Whether sorting is useful likely depends on how many targets you have. In a large codebase, it's not uncommon to have hundreds of Aliases.

**Comment by ffulin** [comment]
FASTBuild v0.89 has been release which includes your pull request, thanks!  (Option is now -showtargets)
