### ISSUE TITLE
Compile error when enabling PROTOCOL_DEBUG_ENABLED

### ISSUE THREAD

**Issue by mhoulier** [fastbuild/fastbuild#784]
Hi,

I enabled locally `PROTOCOL_DEBUG_ENABLED` and it triggers a static assert in Protocol.cpp : 

> "msgNames item count doesn't match NUM_MESSAGES"

It seems the "ServerStatus" entry ( see https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Protocol/Protocol.cpp#L38 ) is obselete as Protocol::MessageType::MSG_SERVER_STATUS was removed some time ago
(see https://github.com/fastbuild/fastbuild/commit/0271434426b1c27c144f2da838df251ceee11ebc#diff-ccd2ddd9575f469ddb599008059d8b6e).

Should I do a Pull Request with the removal or do you prefer to fix it directly yourself ?

Thanks.

**Comment by ffulin** [comment]
Thanks for letting me know. I'll make the fix to save you the trouble of making a PR. I'll resolve this when that's done.

**Comment by ffulin** [comment]
I've submitted the fix (https://github.com/fastbuild/fastbuild/commit/d9645aaaf3412ad6773bcea135eae71278835e8e) to the dev branch. This will be part of the next version (v1.03). I'll leave this issue open until that version is released.

Thanks again for letting me know about this problem.

**Comment by ffulin** [comment]
v1.03 has now been released and the source contains this fix.
