### ISSUE TITLE
New option to allow remote worker on host

### ISSUE THREAD

**Issue by mhoulier** [fastbuild/fastbuild#785]
Hi,

for debugging purposes, I wanted to use a remote worker on the same host machine as the main FBuild, so I modified WorkerBrokerage.cpp to allow including the host name machine as a possible remote worker.

I only hardcoded it locally, but I wanted to know if you think this a feature you would want to include and expose through a command line option?
If so, I'll see to do a first draft for a pull request.

Thanks.

Maxime H.

**Comment by ffulin** [comment]
You should be able to use the .Workers property on Settings() to explicitly list your local machine as follows:
```.Workers = { '127.0.0.1' }```
The host should only be filtered when discovered via the network brokerage location.

**Comment by mhoulier** [comment]
I only knew about the brokerage feature to discover available workers, somehow I missed the setting in the bff file.
I see that this is setup like that in some Fastbuild tests.
I will add a debug option to our UE4 integration so that the local host setting gets added to the generated bff file.

Thanks!
