### ISSUE TITLE
DispatchCallbacksDebugSpam() is breaking callback re-entry check

### ISSUE THREAD

**Issue by mhoulier** [fastbuild/fastbuild#786]
Hi,

Having `PROTOCOL_DEBUG_ENABLED` defined, FBuild uses `DEBUGSPAM()` to output protocol debug log, but I believe the debug spam code is not used anywhere else by default and only active in debug builds, which explains why I am probably the only one to execute this code recently while running Fastbuild tests.

`Tracing::Callbacks::DispatchCallbacksDebugSpam()` never sets **_m_InCallbackDispatch_** back to **_false_** on return, which prevents further logs to be recorded.

This was preventing `TestCache::ConsistentCacheKeysWithDist()` from succeeding when searching for "Cache Store" and "Cache Hit" in the recorded log.

Let me know if you want a pull request or not.

Thanks

Maxime H.

**Comment by ffulin** [comment]
You're right that DEBUGSPAM is rarely used. It's mostly designed to be transient during debug and is usually not even committed. The TCP_DEBUG is a rare exception.

I didn't look at the code, but what you noted sounds like a bug as you have described it. I'd certainly be open to a PR to fix this.

**Comment by ffulin** [comment]
A change to fix this (provided by you :)) was integrated and will be part of the next release (v1.03). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.03 has now been released and the source contains this fix.
