### ISSUE TITLE
FASTBuildMonitor

### ISSUE THREAD

**Issue by qinghua713-zhou** [fastbuild/fastbuild#788]
After installing fastbuildmonitor according to the method provided in the following address“https://github.com/yass007/FASTBuildMonitor”, I found that fastbuildmonitor cannot be opend on vs2013, but can be seen in the Tools tab of vs2013. What's the problem?

**Comment by ffulin** [comment]
FASTBuild monitor is a 3rd party tool for use with FASTBuild. Bug reports and questions for FASTBuild monitor should be directed to the authors via the github page you linked above.

**Comment by qinghua713-zhou** [comment]
@ffulin  thanks!  I will contact the author .
