### ISSUE TITLE
In ListDependenciesNode::EmitOutputMessage(), missing new line character in log

### ISSUE THREAD

**Issue by mhoulier** [fastbuild/fastbuild#795]
Hi,

"DepList: '%s' -> '%s'" is missing '\n'.

I'll make a pull request asap.

Thanks,

Maxime H.

**Comment by ffulin** [comment]
Thanks for the fix. I've integrated your change. It will be in the next release (v1.03). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.03 has now been released and contains this fix.
