### ISSUE TITLE
What is the plan for support complex expression in Function If?

### ISSUE THREAD

**Issue by Xorcerer** [fastbuild/fastbuild#799]
Hi Guys,

I am willing to help, but I would like to know the plan (if any) before starting.

Here is my proposal, adding support of vary boolean computation to the If function.

Forms
```
    bool-exp = true | false
             | bool-variable
             | ! bool-exp
             | bool-exp &&/|| bool-exp
             | number-exp ==/!=/>/>=/</<= number-exp
             | string-exp ==/!= string-exp
    number-exp = number-literal | number-variable
    string-exp = string-literal | string-variable
```

Case 1
`
If( .StringVariable1 == "StringValue" )
`

Case 2
`
If( .BoolVariable2  && ( "StringValue" == .StringVariable2 ) )
`

There are two approaches.
1. Calculate the result while parsing the If header (`const BFFTokenRange & headerRange`)
2. Generate an Abstract Syntax Tree, then calculate the result when needed.

Option 2 is more flexible and is my favourite but Option 1 looks straight forward.

Any feedback is welcomed.

**Comment by ffulin** [comment]
Support for more complex expressions are planned, but there is currently no timeline for implementing them. Direct use of literals and compound expressions (as per your two cases) are both desirable.

My approach would be to calculate the result while parsing the condition (your first suggestion), probably with some use of recursion to evaluate the conditions. I think an AST, while powerful, would be unnecessary here. With the right structure, the evaluation functions could potentially be used in more complex extensions to the language later on.

A couple of related thoughts/info that might be useful:

The current list of supported operators is documented here: https://fastbuild.org/docs/functions/if.html  Note that this includes some operators you didn't mention above (like "in", "not in" operators and >/>=/</<= for strings for example)

To whatever degree it's practical, I would like to require braces around non-unary and non-binary operators to enforce explicit precedence.

TestIf.cpp is where all core tests related to the If parsing currently live, but they use an older style of test where each test is a file on disk. Newer tests, as seen in TestBFFParsing.cpp use TEST_PARSE_OK/TEST_PARSE_FAIL helper macros to allow the config to be directly inlined into the test cpp.

**Comment by Xorcerer** [comment]
Hi @ffulin , here is the commit with the feature and corresponding unitttests.
https://github.com/Xorcerer/fastbuild/commit/32a2a34b9c6baaafd1b6d2ac375793a6923d08db

It is tested against Windows + MSVC.

I am going to test my changes against
* Windows + clang
* OS X
* Linux
then update the documentation, as the checklist of the PR template required.

Before that, would you like to take a look at the commit in case I missed anything or didn't do it the right way?

I am not a fan of mega commits, but I just could not split the changes into small meaningful pieces.

**Comment by Xorcerer** [comment]
A summary for the commit.

* First of all, the implementation is 100% backward-compatible with the original implementation, except two error messages.
* The syntax design is strictly to your comment: "To whatever degree it's practical, I would like to require braces around relational (<, >= etc) and equality (==, != etc) operators to enforce explicit precedence." e.g.
```C++
    TEST_EXP_TRUE( "", "(!!true)" );
    TEST_EXP_TRUE( "", "(!(!true))" );

    TEST_EXP_TRUE( "", "('String' == 'String') && (1 == 1)" );
    TEST_EXP_TRUE( "", "('String' == 'Hello') || (1 == 1)" );
    TEST_EXP_TRUE( "", "true && (false || true) || ((1 == 2) && ('abc' != 'def'))" );
``` 
* Added std::initializer_list support for Array. (I noticed that the project does not like std lib, so if you don't like it, I will re-implement the feature with variadic-template. Use-cases:
```C++
static const Array<Operator> BoolOperators
{
    Operator::OP_EQUAL,
    Operator::OP_NOT_EQUAL,
    Operator::OP_AND,
    Operator::OP_OR,
};
```
* I have brought the idea of TEST_PARSE_OK/TEST_PARSE_FAIL and write another set of helper macros for If function, which focusing on the header of If. Use-cases:
```C++
    TEST_EXP_TRUE( ".Bool = true", ".Bool" );
    TEST_EXP_TRUE( ".Bool = true", ".Bool != false" );
    TEST_EXP_TRUE( ".Bool = true", "false != .Bool" );
    TEST_EXP_FALSE( ".Bool = true", ".Bool != .Bool" );

    TEST_EXP_TRUE(R"(
        .True = true
        .False = false
    )", ".True && true || .False" );
```
* A recursive way to parse the header block. This part is the major work of the commit. I have explored two ways to write the recursive parser.
    1. "Divide and Conquer": Divide the header block into small sub-blocks by braces, use a new iterator for each sub-block. It was the first idea came to my mind and the readability and error handling is expected better. The error/bug in the sub-blocks won't leak and impact the parent block. The solution requires two passes to the tokens, one for dividing the tokens, another one for doing the actual boolean calculation in blocks.
    2. "One pass": Use a single iterator across the whole block. The `Parse<...>` functions should carefully maintain the state of parsing. , Each call from one `Parse<...>` function to another `Parse<....>` function is considered a state transition.
I tried the first way but I found that I needed a dict/map to save the pairing of braces for further lookup (there were a few complicated work around), then I turned into the second way.

**Comment by Xorcerer** [comment]
Two updates to error messages.

Update 1
=======
For
```
.Int in .ArrayOfStrings
```
Originally returns
```
"Property '.Int' must be of type <ArrayOfStrings> or <String> (found <Int>" 
```
Now returns
```
"Unexpected operator"
```
The reason for this update is that, when the parser gets the `.Int`, it does not expect operator `in`, an error will be raised and the parsing will be halted.

Update 2
==========
For
```
.Bool1 >= .Bool2
```
Originally returns
```
"Operation not supported: 'Bool' >= 'Bool'"
```
Now returns
```
"Unexpected operator"
```
The same reason as the above update, a bool should not be the left-hand-side of `>=`, the parsing will be halted immediately.

**Comment by ffulin** [comment]
Your change for this feature (https://github.com/fastbuild/fastbuild/commit/743203e24a192ee24dc79a3cb516db3665b47ebb) has been integrated and will be in the next release (v1.05). I'll leave this issue open until that version is released.

Thanks for helping to make FASTbuild better!

**Comment by ffulin** [comment]
v1.05 has now been release, which includes this new functionality.

Thanks for helping to make FASTBuild better!
