### ISSUE TITLE
Not so serious, backslash in some links to fastbuild.org on releases page

### ISSUE THREAD

**Issue by lucianm** [fastbuild/fastbuild#8]
Hi Franta,

first of all, I'm so glad you're working to further improve FASTBuild, which is already so brilliant, and that you found the time to host the sources on github. Seems it will pay off, you've already got forkers to contribute :-).

Just wanted to point at the links to fastbuild.org on your releases page here on github, those contained in "See fastbuild.org for:", seems they're broken, because they contain a backslash.

Other than that, keep up the good work, and, btw, I already succeeded in seducing few colleagues at work into using FASTBuild at least for inofficial, development builds of a large project :+1: .

Best regards,
Lucian

**Comment by ffulin** [comment]
Hi Lucian

Thanks for letting me know about this! I've fixed the links.

Regards

- Franta
