### ISSUE TITLE
Some Problems met while Integrating FASTBuild into UnrealBuild Tools

### ISSUE THREAD

**Issue by chengjiaozyl** [fastbuild/fastbuild#805]
During a period of learning, i intergrated fastbuild into unrealbuildtool(ubt). However, i have some questiones about fastbuild, and some problems need to be solved.
The first question is that it did not work while the default compiler is visual studio 2019. However, it worked well on visual stuido 2017 on the same machine. The vs2019 version is the latest version and the fastbuild version is v1.02. The error is showed below:
~~~
c1xx: fatal error C1356: unable to find mspdbcore.dll
Failed to build Object. Error: 2 (0x02) Target: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\.fbuild.tmp\0x00000000\core_1027\Module.Core.10_of_14.cpp.obj'
~~~
May it be caused by the environment on the worker computer? If so, what i should do is to set vs2019 on my all worker computers?  That is a problem.... Besides, the compiler defined in my bff file is given below.
~~~
Compiler('WindowsObjCompiler') 
{
	.Root = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64'
	.Executable = '$Root$/cl.exe'
	.ExtraFiles =
	{
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\c1.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\c1xx.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\c2.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\mspdbsrv.exe',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\mspdbcore.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\mspft140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\msobj140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\mspdb140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\msvcp140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.28.29325\x64\Microsoft.VC142.CRT\vccorlib140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\vcruntime140.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\msvcp140_1.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\tbbmalloc.dll',
		'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\1033\clui.dll',
	}
}
~~~

I am sure these .dll files exist on the local computer. And with same source codes, it built succesffully on the same computer when i uninstalled vs2019 and installed vs2017.

The second question is that whether link action, which generates dll,lib,exe file can be distributed. There are two problems when i try to use fastbuild to execute link actions.
1. all the link actions were finally executed locally.

2. when the link actions were executed by fastbuild, the errors and warnings were output:
~~~
LINK : error LNK2001: unresolved external symbol: mainCRTStartup/WinMainCRTStartup
LINK : fatal error LNK1158: cannot run“mt.exe”
LINK : warning LNK4001: no object files specified; libraries used
~~~
i solved the LNK2001 error by add option /NOENTRY, this worked while linking dll/lib but didnot work while linking exe.
the LNK1158 was solved by delete the origin options /MANIFEST and /MANIFESTINPUT:D:\UE-CI\UnrealEngine\Engine\Build\Windows\Resources\Default-Win64.manifest when it wrote .linkeroptions.
Errors did not occur while building, but the generated dll or lib files could not use.

i wonder whether fastbuild can be used to distribute link actions and how i can use fastbuild to do so.

some info is attached below.
```
DLL('Action_298') ; ShaderCompileWorker-ApplicationCore.dll
{
	.Linker = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe'
	.LinkerOutput = 'D:\UE-CI\UnrealEngine\Engine\Binaries\Win64\ShaderCompileWorker-ApplicationCore.dll'
	.LinkerOptions = '/MANIFEST:EMBED /MANIFESTINPUT:D:\UE-CI\UnrealEngine\Engine\Build\Windows\Resources\Default-Win64.manifest /NOLOGO /DEBUG /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:CONSOLE /FIXED:No /NXCOMPAT /STACK:12000000 /DELAY:UNLOAD /DLL /PDBALTPATH:%_PDB% /OPT:NOREF /OPT:NOICF /INCREMENTAL:NO /ignore:4199 /ignore:4099 /DELAYLOAD:"d3d12.dll" /DELAYLOAD:"DBGHELP.DLL" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" /NODEFAULTLIB:"LIBCMT" /NODEFAULTLIB:"LIBCPMT" /NODEFAULTLIB:"LIBCMTD" /NODEFAULTLIB:"LIBCPMTD" /NODEFAULTLIB:"MSVCRTD" /NODEFAULTLIB:"MSVCPRTD" /NODEFAULTLIB:"LIBC" /NODEFAULTLIB:"LIBCP" /NODEFAULTLIB:"LIBCD" /NODEFAULTLIB:"LIBCPD" "%1" /OUT:"%2" /IMPLIB:"D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\ApplicationCore\ShaderCompileWorker-ApplicationCore.suppressed.lib" /PDB:"D:\UE-CI\UnrealEngine\Engine\Binaries\Win64\ShaderCompileWorker-ApplicationCore.pdb" /ignore:4078 /NOENTRY'
	.Libraries = 
	{
		'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\delayimp.lib',

	}
	.Libraries2 = 
	{
		'D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\Core\SharedPCH.Core.ShadowErrors.h.obj',

	}
	.LinkerAssemblyResources = 
	{
		'D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\Default.rc2.res',
	}
}
``` 

```
Library('Action_0') ; UE4Editor-CoreUObject.lib
{
	.Compiler = 'WindowsLibCompiler'
	.CompilerOptions = '/NOLOGO /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:WINDOWS /DEF /NAME:"UE4Editor-CoreUObject.dll" /IGNORE:4221 /NODEFAULTLIB "%1" /OUT:"%2" /NOENTRY /c'
	.CompilerOutputPath = 'D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\CoreUObject'
	.Librarian = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\lib.exe'
	.LibrarianOptions = '/NOLOGO /errorReport:prompt /MACHINE:x64 /SUBSYSTEM:WINDOWS /DEF /NAME:"UE4Editor-CoreUObject.dll" /IGNORE:4221 /NODEFAULTLIB "%1" /OUT:"%2" /NOENTRY'
	.LibrarianAdditionalInputs = 
	{
		'D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\CoreUObject\PCH.CoreUObject.h.obj',
	}
	.LibrarianOutput = 'D:\UE-CI\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\CoreUObject\UE4Editor-CoreUObject.lib'
}
```

Hope your reply soon~ Thank you very much. If any other info needed, please tell me.

**Comment by chengjiaozyl** [comment]
Some info about question-1....the sample.bff.txt is the bff file used to pass to fastbuild, the image is the result run from batch.
[sample.bff.txt](https://github.com/fastbuild/fastbuild/files/5742085/sample.bff.txt)
![1](https://user-images.githubusercontent.com/41104072/103137087-de4b9700-4700-11eb-8666-6b35104685f8.png)

**Comment by chengjiaozyl** [comment]
Some info about question-1....the sample.bff.txt is the bff file used to pass to fastbuild, the image is the result run from batch.
[1.txt](https://github.com/fastbuild/fastbuild/files/5742090/1.txt)
![Uploading 1.png…]()

**Comment by ffulin** [comment]
> c1xx: fatal error C1356: unable to find mspdbcore.dll

Visual Studio 2019 added dependencies on several new dlls over the course of several updates. The most recent version added a dependency on msvcp140_atomic_wait.dll for example. Which ones you are missing will depend on the version you have installed.

You can take a look at FASTBuild's own [vs2019.bff](https://github.com/fastbuild/fastbuild/blob/dev/External/SDK/VisualStudio/VS2019.bff) to see which dlls are required as of 16.8.3:
```
    .Root       = '$VS2019_ToolchainPath$/bin/Hostx64/x64'
    .Executable = '$Root$/cl.exe'
    .ExtraFiles = { '$Root$/c1.dll'
                    '$Root$/c1xx.dll',
                    '$Root$/c2.dll',
                    '$Root$/msobj140.dll'
                    '$Root$/mspdb140.dll'
                    '$Root$/mspdbcore.dll'
                    '$Root$/mspdbsrv.exe'
                    '$Root$/mspft140.dll'
                    '$Root$/msvcp140.dll'
                    '$Root$/msvcp140_atomic_wait.dll' // Required circa 16.8.3 (14.28.29333)
                    '$Root$/tbbmalloc.dll' // Required as of 16.2 (14.22.27905)
                    '$Root$/vcruntime140.dll'
                    '$Root$/vcruntime140_1.dll' // Required as of 16.5.1 (14.25.28610)
                    '$Root$/1033/clui.dll'
                    '$Root$/1033/mspft140ui.dll' // Localized messages for static analysis
                  }
```

>  ....link action, which generates dll,lib,exe file can be distributed

Only compilation can be distributed and creating libraries and linking is always performed locally. There are no plans to support distributed linking as it would not benefit most scenarios given the often massive amount of data that would need to be transferred (as much as many GiB) before linking could start and that linking typically occurs at the end of compilation, where local CPUs would typically be idle anyway. 

Interestingly, the latest VS2019 (16.8.3) has some significant link time speedups (I saw ~2x speedups).

**Comment by chengjiaozyl** [comment]
fastbuild works after adding the extra dll files listed in vs2019.bff. Thank you very much. And As for link actions, i wonder whether it can be achived technically to deliver link actions to remote computers if ignoring the net tranform limitation and the amount of the data. I used to compile UE4 with IncredibleBuild, and i found it seems to deliver link actions to remote computer . However, i found most of these link actions actually were executed locally, just like fastbuild did.

**Comment by chengjiaozyl** [comment]
> > c1xx: fatal error C1356: unable to find mspdbcore.dll
> 
> Visual Studio 2019 added dependencies on several new dlls over the course of several updates. The most recent version added a dependency on msvcp140_atomic_wait.dll for example. Which ones you are missing will depend on the version you have installed.
> 
> You can take a look at FASTBuild's own [vs2019.bff](https://github.com/fastbuild/fastbuild/blob/dev/External/SDK/VisualStudio/VS2019.bff) to see which dlls are required as of 16.8.3:
> 
> ```
>     .Root       = '$VS2019_ToolchainPath$/bin/Hostx64/x64'
>     .Executable = '$Root$/cl.exe'
>     .ExtraFiles = { '$Root$/c1.dll'
>                     '$Root$/c1xx.dll',
>                     '$Root$/c2.dll',
>                     '$Root$/msobj140.dll'
>                     '$Root$/mspdb140.dll'
>                     '$Root$/mspdbcore.dll'
>                     '$Root$/mspdbsrv.exe'
>                     '$Root$/mspft140.dll'
>                     '$Root$/msvcp140.dll'
>                     '$Root$/msvcp140_atomic_wait.dll' // Required circa 16.8.3 (14.28.29333)
>                     '$Root$/tbbmalloc.dll' // Required as of 16.2 (14.22.27905)
>                     '$Root$/vcruntime140.dll'
>                     '$Root$/vcruntime140_1.dll' // Required as of 16.5.1 (14.25.28610)
>                     '$Root$/1033/clui.dll'
>                     '$Root$/1033/mspft140ui.dll' // Localized messages for static analysis
>                   }
> ```
> 
> > ....link action, which generates dll,lib,exe file can be distributed
> 
> Only compilation can be distributed and creating libraries and linking is always performed locally. There are no plans to support distributed linking as it would not benefit most scenarios given the often massive amount of data that would need to be transferred (as much as many GiB) before linking could start and that linking typically occurs at the end of compilation, where local CPUs would typically be idle anyway.
> 
> Interestingly, the latest VS2019 (16.8.3) has some significant link time speedups (I saw ~2x speedups).

fastbuild works after adding the extra dll files listed in vs2019.bff. Thank you very much. And As for link actions, i wonder whether it can be achived technically to deliver link actions to remote computers if ignoring the net tranform limitation and the amount of the data. I used to compile UE4 with IncredibleBuild, and i found it seems to deliver link actions to remote computer . However, i found most of these link actions actually were executed locally, just like fastbuild did.

**Comment by ffulin** [comment]
I think it's technically possible to distribute linking, but I've not seen a situation in which it would make things better.

Are you seeing a situation that you think might be improved by distribution of linking?

**Comment by aganea** [comment]
@ffulin ThinLTO would benefit from distribution, like Google does, there's mentions here: https://www.youtube.com/watch?v=VAMvr1rXmg8

**Comment by ffulin** [comment]
> Since ThinLTO is distributable by design, 

That's quit interesting. Given a link operaiton is a single node in the dependency graph, and distribution in FASTBuild is currently tied to the node-level, some thought would need to go into how this might be implemented.

**Comment by aganea** [comment]
We'll have someone work on this starting in May, if you don't do it until then. But essentially ThinLTO can be executed in several steps: 1. pre-link and discover dependencies (this is quite fast). 2. distribute dependencies 3. final link after gathering all artefacts. I would imagine step 1. would need, after completing, to insert new dynamic nodes in the graph, to allow step 2. to execute.

**Comment by ffulin** [comment]
I'm going to close this issue as both questions have been resolved.
