### ISSUE TITLE
Compiler.html: the VS2019 section lists 2017 variables

### ISSUE THREAD

**Issue by peterwoytiuk** [fastbuild/fastbuild#807]
In looking at the recent change to support VS2019 16.8.3, I noticed that in the Documentation/docs/functions/compiler.html file the "Visual Studio 2019" section starting at line 250 has a couple of variables/entries pertaining to VS2017.   

Link: https://github.com/fastbuild/fastbuild/commit/8709731399e674a547447c0e52d65a81c8f8cd42#diff-82a828e3844f373b42626d353efd6d63c6a4ffa84fbc05d6ec36afe868196d1f

**Comment by ffulin** [comment]
Thanks for letting me know! It's been wrong for quite some time!

I've fixed the error here: https://github.com/fastbuild/fastbuild/commit/708a910446fa47c9131c66405f56ea519ed0a3fe

This fix will be in the next release (v1.04). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
FASTBuild v1.04 has now been released. It contains this documentation fix.

Thanks again!
