### ISSUE TITLE
Question about distributed build tasks not being tightly packed

### ISSUE THREAD

**Issue by ologon** [fastbuild/fastbuild#808]
Hi, I have a question regarding FASTBuild distributed builds. 
I have only two PCs in my network (one local, one remote), and when I run distributed builds everything runs fine,
except that FASTBuild doesn't seem to be using the remote PC optimally.

This is how remote builds look in FASTBuildMonitor:
![FastBuildMonitor](https://user-images.githubusercontent.com/30046703/104024339-525c6380-5206-11eb-909d-a74cda691748.PNG)

As you can see, there are quite of bit of holes in between where the remote cores are idle (the holes above are about 30seconds ~1 minute long). FASTBuild seems to be sending a "batch" of build tasks of about the same number of the cores in the remote machine and it won't send another batch of tasks until the previous batch is completely finished. Is this intendend behaviour? Is there anything I can do to make it dispatch remote tasks more aggressively? The remote worker is set to "Always work for others".

In comparison, the local build tasks are tightly packed:
![local](https://user-images.githubusercontent.com/30046703/104023062-74ed7d00-5204-11eb-8325-1c4a655840ce.png)

**Comment by eclazi** [comment]
Maybe time in between is the remote machine sending back the compiled artifacts?

**Comment by ffulin** [comment]
This sort of thing can be difficult to diagnose without understanding more about the structure of your code.

This pattern in the images you sent tends to indicate the host machine is a bottleneck in the build process. This can be for a few reasons and it's hard to diagnose from the information provided.

At a guess it seems your host can't provide the worker with data quickly enough, but I don't think that entirely explains the pattern you're seeing, which implies some sort of bottleneck in the dependencies (some tasks that can only be performed locally).

----

The next version of FASTBuild (v1.04) will have two features that help investigate cases like this, to help people dig in on their own as well as being able to provide more information about what's going on in a build.

**a) Build profiling**
A new -profile command line option makes FASTBuild output a chrome-tracing compatible json when the build finishes. This trace shows local and remote work and can often highlight bottlenecks.
In some ways it's similar to the trace above, but it's more accurate as the network protocol has been updated to provide extra context back to the host

**b) Dependecy graph visualization**
A new -dot command line option makes FASTBuild output a DOT format .gv file which can be used to visualize the dependency graph

If you are in a position to build this version from source, that might be helpful to you. If not, the next release should not be too far away (weeks, not months)

----

The next version of FASTBuild (v1.04) also contains some improvements to distributed compilation performance. I can't say whether that will help this case from the information given though.

**Comment by ffulin** [comment]
> Maybe the time in between is the remote machine sending back the compiled artifacts over the network?

@eclazi - The compilation and network transfer are overlapped. Each worked over-requests work so that it's well fed.
Naturally the network bandwidth can be a bottleneck, but I don't think the pattern shown implies that.

**Comment by ologon** [comment]
@ffulin @eclazi 
Thanks for the quick response and the useful information.
I should maybe specify that I'm using Visual Studio 2017's compiler and the bff project consists of a single ObjectList + Executable.

I will try building FASTBuild from source and further investigate this issue as suggested :)
It's definitely odd as if for example one obj build in the "batch" takes much longer than the others, FASTBuild will dispatch a new batch the same instant that obj completes.

**Comment by claimred** [comment]
I saw a similar pattern on one of our codebases. If I recall correctly the problem was a relatively weak host, bad network connection, and, most importantly, a huge precompiled header. The host couldn't feed workers properly because it spent all its time preparing jobs i.e. preprocessing that huge PCH over and over again to send tasks to workers. We got rid of the precompiled header and `-dist` compilation evened out.

Here is a thread about it https://github.com/fastbuild/fastbuild/issues/696#issuecomment-587042636

**Comment by ologon** [comment]
@claimred 
Thanks for the info. 
My codebase has a PCH which is pretty big as well. I will try getting rid of it and see if anything changes.

**Comment by ffulin** [comment]
If there is a single object list with a pch, the pch would only cause a bottleneck at the start of the build.

The pattern you are seeing (multiple "slices" of build) is very strange. I can't think of anything that would explain that behavior as in the image you attached, it's so consistent in the way it's sliced. It's almost as something is occurring periodically, like a network stall or background process on the machine.

One thing to note is that the visualizer you are using is trying to regenerate the details of which remote threads built what, which means that it's possible it's actually displaying incorrectly. The -profile feature of the next version will show an accurate representation.

**Comment by ologon** [comment]
@ffulin 
I see, thanks! I've tried switching from my wireless router home network to directly wiring the two PCs via ethernet,
and the distribution got a lot better (almost no holes), so my home network/router appears to be the problem.

**Comment by ologon** [comment]
I’m closing this issue as everything looks ok now on the wired network. Thanks for the help!

**Comment by eclazi** [comment]
I have found that used `-j` to leave 1 core free can improve situations like this. I haven't really looked into it in much detail but that's the config I run with.
