### ISSUE TITLE
Code formatter for .bff

### ISSUE THREAD

**Issue by ompadu** [fastbuild/fastbuild#810]
How about getting some extra mileage out of that nice .bff files lexer in FASTBuild and adding a code formatter?

**Comment by ffulin** [comment]
Do you mean a code formatter for c/c++? The lexer/parser is nowhere near smart enough for that :)

Or do you mean a clang style formatter for the bff itself?

Or something else entirely?

**Comment by ompadu** [comment]
A clang-format like style formatter for bff itself.

**Comment by ffulin** [comment]
The BFF parser right now doesn't retain enough information to be able to re-emit the BFF in a lossless manner. As an example, all the comments are discarded. It would likely be possible to retain the necessary information with some changes, though some care would be needed to ensure the parser is still performant.

I think this is an interesting idea, but it isn't something I'd be likely to explicitly prioritize. I'll keep it in mind when making future changes to the parser though.

I wonder if clang-format could be configured in a way that yields a useful result for bff parsing?

**Comment by ffulin** [comment]
I don't currently have any plans to work on this, so I'm going to close this issue for now.
