### ISSUE TITLE
Brokerage tokens show raw IP addresses instead of names

### ISSUE THREAD

**Issue by claimred** [fastbuild/fastbuild#816]
We noticed this in 1.04 after updating, "22.windows" folder contains raw IP addresses, "21.windows" contains tokens named as computers. Not sure if it has something to do with Hyper-V thing because we have it enabled here and there.

Is this a bug? Was just a bit easier to understand what's going on. 🤔

**Comment by ffulin** [comment]
This is a deliberate change. By writing the IP address, we avoid clients needing to perform name resolution (which can be expensive, particularly if it times out).

The file written to the brokerage contains additional information, include the hostname if needed.

**Comment by ffulin** [comment]
I'm going to close issue. Let me know if you need any more info.
