### ISSUE TITLE
Compilation database is using friendly compiler name instead of compiler executable path

### ISSUE THREAD

**Issue by wrdn** [fastbuild/fastbuild#819]
FastBuild v1.04 is exporting the friendly compiler name to the compilation database instead of the compiler executable path, the executable path was used in v1.03 and earlier.

E.g. in 1.04 the database includes "Compiler-GCC9" instead of "/usr/bin/x86_64-linux-gnu-gcc-9"

This appears to have changed in CompilationDatabase.cpp at commit 61b2cc08af52540b4b4e878ccca9b8e7e27d0b73

According to the LLVM docs ( https://clang.llvm.org/docs/JSONCompilationDatabase.html ) the command element "must be a valid command to rerun the exact compilation step for the translation unit".

Originally I found this when trying to use include-what-you-use and finding it didn't recognise the clang-cl compiler options until I added "--driver-mode=cl" to the IWYU options.

**Comment by ffulin** [comment]
Thanks for reporting this bug. I've submitted a fix and extended the tests to cover this functionality more thoroughly: https://github.com/fastbuild/fastbuild/commit/39cb7e9f17257ca98a55ea8ac566f56911d5af2c

This fix will be in the next release (v1.05). I'll leave this issue open until that version is released.

**Comment by wrdn** [comment]
Good to hear, many thanks! :)

**Comment by eclazi** [comment]
What is the severity of this issue? Is it best to avoid 1.04 and wait until 1.05?

**Comment by ffulin** [comment]
@eclazi The severity will depend on whether you use the -compdb command line argument to generate a JSON file for use by external tools.

If you depend on this feature, the updated version is likely unusable until the next release.

If you don't use this feature, then no other functionality is impacted.

**Comment by eclazi** [comment]
Ah ok, thought it might effect the caching.

**Comment by ffulin** [comment]
v1.05 has now been release, which includes a fix for this issue.

Thanks again for reporting the problem.
