### ISSUE TITLE
default value for #import in case the envar doesn't exist

### ISSUE THREAD

**Issue by shooshx** [fastbuild/fastbuild#82]
Using #import, if the given environment variable doesn't exist, the parsing of the .bff fails. this makes #import less useful than it could have been since if I use it anywhere, I now have to make sure this variable is always defined and I can't even do a simple ./FBuild in the .bff folder. 
A reasonable solution is to add a second space delimited, optional argument to #import that would be the default value, in case the given name doesn't exist. this is similar to python's dict.get()
**pro**: gives maximum flexibility
**con**: some might find it a weird syntax 
Another alternative is that #import just sets the variable to an empty string, 
**pro**: no syntax change, simpler concept
**con**: less powerful 
**con**: break backward compatibility as far as error handling is concerned.
let me know what you prefer and I'll code it.

**Comment by kovarex** [comment]
I would also like to support it. The first variant.

**Comment by ffulin** [comment]
I've been thinking about this, and I think adding an optional keyword as follows would be the way to go:
```C++
#import optional ENV_VAR
```
**If ENV_VAR exists**, the behaviour is the same as without the optional keyword.

**If ENV_VAR does not exist:**
 - if previously declared in the bff, it would remain unchanged (so you can have a default value overridden by an ENV_VAR)
 - if not previously declared, it would create and empty string

What do you think?

**Comment by shooshx** [comment]
That sounds perfect.
Hopefully in the next few days I'll have time to be working on both this and the -define issue

**Comment by kovarex** [comment]
This might be different topic, but it would be nice to be able to make conditional code depending on the import value. For example, I have visual studio 2013 and 2015 configurations in the build file, 
Visual studio 2015 configuration uses this import:
#import VS140COMNTOOLS
While visual studio 2013 configuration uses this import:
#import VS120COMNTOOLS
The default/optional value will solve the problem that it didn't work when just one of the versions was installed, but it still won't solve, that the other configuration will still be available. If I could define preprocessor value depending on the existance of environment variable, I can use it to control what configurations to define.

**Comment by Manuzor** [comment]
:+1:
I'm looking for the same thing as @kovarex. It would be very useful to make some environment variables optional, possibly even having the ability to react on whether they exist or not.

I'm thinking
```
#if !VS140COMNTOOLS
#if !VS120COMNTOOLS
"Unable to find VS2015 or VS2013"
#endif
#endif
```

**Comment by ffulin** [comment]
I've been thinking about this, and I think the following syntax would likely be the way to go:
```C++
#if !exists(ENV_VAR)
```
This would also extend to something like this:
```C++
#if !exists("folder/folder/file.exe")
```
I think this would provide the necessary flexibility for supporting several compiler versions where that's desirable. 

With a little more syntactic sugar (#else and #error), we could end up with something like this:
```C++
#if exists("External/SDKs/VS2013.4/bin/cl.exe")
   .MSCompiler = "External/SDKs/VS2013.4/bin/cl.exe" // Use checked in toolchain if available
#else if exists(VS140COMNTOOLS)
   #import VS140COMNTOOLS
  .MSCompiler = "$VS140COMNTOOLS$/bin/cl.exe" // Fallback to installed VS2015
#else if exists(VS120COMNTOOLS)
   #import VS120COMNTOOLS
   .MSCompiler = "$VS120COMNTOOLS$/bin/cl.exe" // Fallback to installed VS2013
#else
   #error "Could not find compiler"
#endif
```

**Comment by Manuzor** [comment]
Seems good to me! Looks like what a C/C++ programmer would expect. But, will you be able to use the value of a `#define` within the `exists()` statement?

```
#define EXTERNAL "External/"
#if exists(EXTERNAL "SDKs/VS2013.4/bin/cl.exe")
// ...
#end
```

I'm not sure about actual use cases, but I can imagine people trying to leverage something like this.

**Comment by ffulin** [comment]
**> But, will you be able to use the value of a #define within the exists() statement?**

Perhaps unintuitively, you would be able to do this:
```C++
.External = "External/"
#if exists( "$External$SDKs/VS2013.4/bin/cl.exe" )
```
This is because (unlike C/C++) directives and normal parsing (for better or worse) are done in the same pass in FASTBuild.

**Comment by ffulin** [comment]
I have integrated https://github.com/fastbuild/fastbuild/pull/178, so #if exists functionality can now be used to conditionally import optional environment variables:
```C++
#if exists(ENV_VAR)
   #import ENV_VAR
#endif
```

**Comment by kovarex** [comment]
Thank you for the support!

**Comment by ffulin** [comment]
v0.93 has now been release which includes this change.
