### ISSUE TITLE
Quadratic behavior in the Dependency class

### ISSUE THREAD

**Issue by aganea** [fastbuild/fastbuild#825]
Since Fastbuild 1.04, I'm seeing a scaling issue with `Node::m_DependenciesToThisNode`. I saw it happening on startup, after I updated a .bff and Fastbuild needed to modify its DB. And also during compilation. I was compiling a 'NoBlob' target that Sharpmake generates (we had that before `-nounity` ever existed). There are approx. 20,000 CPP to compile and >50,000 inputs touched by the compilation.

This is during startup, after changing a .bff (it remains stuck there for a while, I ended up killing fbuild.exe):
![fastbuild_on2](https://user-images.githubusercontent.com/37383324/112029616-d472dd80-8b0f-11eb-9375-e861c783f455.PNG)

This is when compiling with cache enabled (here 100% cache hits).
It starts building fine, then after a little bit there's a "pause" for 25 sec, where it's stuck in this loop:
![fastbuild_on2_dependency](https://user-images.githubusercontent.com/37383324/112029812-0126f500-8b10-11eb-97ef-4fc93dda164a.PNG)

I'm running on a Cascade Lake 48C/96T machine on Windows 10 version 20H2.

**Comment by ffulin** [comment]
m_DependenciesToThisNode doesn't exist anywhere in the FASTBuild source.

The destructor of Dependency is also a no-op (doesn't call FindAndErase)

Seems like this is a local change you have?

**Comment by aganea** [comment]
Or right, sorry it's part of a change I meant to send you ;-) I'll guess it needs a bit more polishing first.
