### ISSUE TITLE
/clr:xxx object files are distributed but should not

### ISSUE THREAD

**Issue by distee-ubi** [fastbuild/fastbuild#828]
C++/Cli objects must not be distributed, but are distributed when `/clr:xxx` is given instead of `/clr`.
Encountered when compiling with `/clr:netcore`.

Reason:
In `ObjectNode.cpp` the test `IsCompilerArg_MSVC( token, "clr" )` returns false with token `clr:netcore` when it should return true.

Easily fixed, still will not provide a MR. Sorry!

**Comment by ffulin** [comment]
Thanks for the report. This does indeed look like a fairly quick fix (switch to using IsStartOfCompilerArg_MSVC instead) and adding a test should also be easy to prevent regression in the future.

**Comment by ffulin** [comment]
I've made the necessary fix and added some appropriate tests (https://github.com/fastbuild/fastbuild/commit/a72f2d1b72d3b23ced5250c393f4f6d430a78273)

This change will be in the next release (v1.05). I'll keep this issue open until that version is release.

Thanks for reporting this issue!

**Comment by distee-ubi** [comment]
Btw, I am a fastbuild fan. Big thanks for creating it!

**Comment by ffulin** [comment]
v1.05 has now been release, which includes a fix for this issue.

Thanks again for reporting the problem.
