### ISSUE TITLE
Is there a method to configure the CustomBuild for ProjectFileTypes in VCXProj?

### ISSUE THREAD

**Issue by marius-luca-87** [fastbuild/fastbuild#831]
In some of my VCXProj targets I include *.natvis files that have the "Item Type" configured as "Custom Build Tool".
`<CustomBuild Include="test.natvis" />`

I tried using the ProjectFileTypes to change the "Item Type":
```
.Natvis = [
  .FileType = 'Document'
  .Pattern = '*.natvis'
]
.ProjectFileTypes = { .Natvis }
```
The generated output was:
```
<CustomBuild Include="test.natvis">
  <FileType>Document</FileType>
</CustomBuild>
```

The output I was hoping to achieve was:
```
<Natvis Include="test.natvis">
  <FileType>Document</FileType>
</Natvis>
```

Is there currently a method to configure the CustomBuild section to use Natvis or any other VS supported type?

**Comment by claimred** [comment]
Not sure if that's of any help in your case but we ended up passing .natvis files [directly](https://docs.microsoft.com/en-us/cpp/build/reference/natvis-add-natvis-to-pdb) to the linker and it works.

```link.exe ... /DEBUG /NATVIS common.natvis```

**Comment by marius-luca-87** [comment]
Thanks for info!
That is a viable alternative but won't fix the case where we are iterating on the .natvis file and have to relink instead of just restart the debugger.

**Comment by ffulin** [comment]
Can you tell me a bit more about the problem you are having? I'm using .natvis files and simply having them in the projects as they are works correctly for debugging. Editing them while debugging also updates in the watch window in real time. I'm using VS2019, though I believe it worked the same with 2017.

**Comment by ffulin** [comment]
@marius-luca-87 Is it possible you're using an older VS version, which might behave differently? Or is there something else unique about your setup?

**Comment by marius-luca-87** [comment]
On a clean install the .natvis files are picked up automatically without having to configure the CustomTool so the issue was on my machine. If configuring the "FileType" is of no interest for anybody this issue can be closed.

**Comment by ffulin** [comment]
For now it seems there's no need for custom configuration of the Include, so I'll close this issue as you suggested.
If we discover there is some benefit to changing the Include for .natvis files (or other files) we can re-evaluate. It might also be that we're simply change FASTBuild to use specific different Includes by default so the user doesn't need to configure anythuing.
