### ISSUE TITLE
Sometimes there are frequent timeouts when compiling remotely

### ISSUE THREAD

**Issue by TOBEALISTENER** [fastbuild/fastbuild#833]
![timeout](https://user-images.githubusercontent.com/35261598/116202071-c3e7ff80-a76c-11eb-998c-4b074ba0287a.png)

As shown in the figure, it occasionally pops up during my compilation, much to my annoyance.

I suspect the problem has something to do with FastBuild ensuring a smooth network connection. I'm looking for something to do with it. Please help me if you know something about it.

**Comment by TOBEALISTENER** [comment]
I'm sorry to see your comment so late because I was enjoying Labor Day a few days ago.Also here I wish you a happy holiday!
Thank you for your answers.

I'm using the V1.04 version of FastBuild and combining it with UE4, and it does work for the most part.
I used the -distverbose parameter to check the situation, and modified part of the FastBuild source code to get the error code. 
I got socket error: 10053 10054, and got an explanation from Microsoft:
![image](https://user-images.githubusercontent.com/35261598/117237060-aa297500-ae5c-11eb-9b69-0436d3527f77.png)
There seems to be a problem with the local network. I am looking for a solution in this area. If you can help with this, please let me know.

**Comment by TOBEALISTENER** [comment]
Okay, I think I've got the problem.
The IT technician plugged the gigabit network cable into the 100-megabit network card interface, causing the network to be in a state of frequent interruption and reconnection.
It seems that FastBuild's network connection mode relies on a stable network.
Such a problem can be a disaster for the maintenance staff!

**Comment by ffulin** [comment]
Thanks for the update on your resolution of this problem.

*> It seems that FastBuild's network connection mode relies on a stable network.*

FASTBuild uses simple TCP/IP connections and doesn't have any special requirements for network connectivity on top of that. It generally just pushes all the data to the socket with standard retry logic to handle full send/receive buffers.

It's entirely possible that behavior could be improved to reduce the impact of such slow network connections, but it's probably not worth spending much time investigating that given that ultimately you'd want to just fix the slow network anyway.

**Comment by TOBEALISTENER** [comment]
> **FASTBuild uses simple TCP/IP connections and doesn't have any special requirements for network connectivity on top of that. It generally just pushes all the data to the socket with standard retry logic to handle full send/receive buffers.**

Yes, I found the TCP connection Settings for FastBuild and found that it sets the timeout to either 10ms or 100ms (sorry I didn't explore that further).

When the network cable is plugged into the wrong interface, it will restart the network card at a certain period of time (for example, restart every 10 minutes, each restart takes 5 or 6 seconds or more). I guess it shows a timeout because the network was disconnected for longer than the transmission time.

Note, however: **TCP connections are not broken, frequent network problems only affect the efficiency of the transfer of remote files.**

The above is just my speculation, because I still have a lot of things to do, so I didn't spend too much time on the code after solving the frequent timeout problem. 

I'm very glad that you can explain my speculation, thank you for your help.

**Comment by ffulin** [comment]
FASTBuild sets the socket timeouts to allow it better control over shutdown (to avoid waiting for the normally very lengthy default socket timeouts). Though it may set timeouts as low as 10ms for a socket, and an operation like a send() would timeout after that time, the send is continually retried for a much longer higher-level timeout (around 30 seconds). So these timeouts should not cause connection loss.

I guess it's possible though, and only some investigation and experimentation with your 100mpbs setup would allow us to know for sure. However, given that gigabit or better is generally required for adequate performance anyway, and you've now got that setup, it'd be hard to imagine this would be a good use of time trying to improve the 100mbps case.
