### ISSUE TITLE
Whether the job defined in Exec Function can be built remotely, how it works.

### ISSUE THREAD

**Issue by chengjiaozyl** [fastbuild/fastbuild#834]
I attempt to comiple shader in ue4 with fastbuild, and it works. But i found many jobs were actually built locally. Thus i try to read source codes, the version is v1.04.  I have read the codes about ObjectListNode and ObjectNode class, and know how ObjectList Function works. So i think Exec function may work similarly. It seems my thought is wrong because i found the DoBuild Interface overridden in ExecNode is simply spawning a process locally to finish the job. Now i am confused. Could u please help me to know whether a job defined in Exec Function in a BFF file can be built remotely, and whether this job will be transferred into a Exec Node, and finally call ExecNode::DoBuild to finish this job.

The job defined in  BFF file is attached below.
```
ForEach( .BATCH_ID in .ALL_BATCHES )
{
Exec( 'ShaderBatch-$BATCH_ID$' )
{
  .ExecExecutable = '$SystemRoot$/System32/cmd.exe'
  .ExecOutput = '$BFF_DIR$timestamp2/$BATCH_ID$'
  .ExecArguments = '/D /S /C "copy NUL timestamp1\$BATCH_ID$ && copy NUL timestamp2\$BATCH_ID$"'
  .ExecWorkingDir = '$BFF_DIR$'
  .ExecAlways = true
  .PreBuildDependencies = 'ShaderBatch-Compile-$BATCH_ID$'
}
}
```
And the interface ExecNode::DoBuild() is 
```
/*virtual*/ Node::BuildResult ExecNode::DoBuild( Job * job )
{
    // If the workingDir is empty, use the current dir for the process
    const char * workingDir = m_ExecWorkingDir.IsEmpty() ? nullptr : m_ExecWorkingDir.Get();

    // Format compiler args string
    AStackString< 4 * KILOBYTE > fullArgs;
    GetFullArgs(fullArgs);

    EmitCompilationMessage( fullArgs );

    // spawn the process
    Process p( FBuild::Get().GetAbortBuildPointer() );
    bool spawnOK = p.Spawn( GetExecutable()->GetName().Get(),
                            fullArgs.Get(),
                            workingDir,
                            FBuild::Get().GetEnvironmentString() );

    if ( !spawnOK )
    {
        if ( p.HasAborted() )
        {
            return NODE_RESULT_FAILED;
        }

        FLOG_ERROR( "Failed to spawn process for '%s'", GetName().Get() );
        return NODE_RESULT_FAILED;
    }

    // capture all of the stdout and stderr
    AString memOut;
    AString memErr;
    p.ReadAllData( memOut, memErr );

    // Get result
    int result = p.WaitForExit();
    if ( p.HasAborted() )
    {
        return NODE_RESULT_FAILED;
    }
    const bool buildFailed = ( result != m_ExecReturnCode );
    
    // Print output if appropriate
    if ( buildFailed ||
        m_ExecAlwaysShowOutput ||
        FBuild::Get().GetOptions().m_ShowCommandOutput )
    {
        Node::DumpOutput( job, memOut );
        Node::DumpOutput( job, memErr );
    }

    // did the executable fail?
    if ( buildFailed )
    {
        FLOG_ERROR( "Execution failed. Error: %s Target: '%s'", ERROR_STR( result ), GetName().Get() );
        return NODE_RESULT_FAILED;
    }

    if ( m_ExecUseStdOutAsOutput == true )
    {
        FileStream f;
        f.Open( m_Name.Get(), FileStream::WRITE_ONLY );
        if ( memOut.IsEmpty() == false )
        {
            f.WriteBuffer( memOut.Get(), memOut.GetLength() );
        }

        f.Close();
    }

    // record new file time
    RecordStampFromBuiltFile();

    return NODE_RESULT_OK;
}
```

**Comment by ffulin** [comment]
Only ObjectNode (as defined via ObjectList() ), can be distributed. The ObjectList must also reference a Compiler() which supports distribution.

In general, FASTBuild can distribute work with compilers it explicitly knows can support it (like cl.exe, clang.exe etc). For custom compilers, such as a shader compiler, it may be possible to use "SimpleDistributionMode" as described here (https://fastbuild.org/docs/functions/compiler.html)

**Comment by ffulin** [comment]
I'm closing this issue since the question has been answered. Let me know if you have any further questions and we action them as needed.

**Comment by chengjiaozyl** [comment]
> I'm closing this issue since the question has been answered. Let me know if you have any further questions and we action them as needed.

Thanks for your answer, i have no questions now.
