### ISSUE TITLE
ExtraFiles in Compiler definition cannot have files with the same name (but different path)

### ISSUE THREAD

**Issue by RCL** [fastbuild/fastbuild#836]
When ExtraFiles contain paths like

/foo/bar/defs.h
/baz/defs.h

this results in an error "Target 'defs.h' already defined". The problem is however that we need both those files (which are distinct files located in different places).  Is there a solution I'm missing?

Thank you in advance!

**Comment by ffulin** [comment]
How files are treated depends on whether the source is relative to the compiler or not. Files relative to the compiler will keep their relative destination. Files from unrelated directories will be places at the root. (details here: https://fastbuild.org/docs/functions/compiler.html) Could that be what's goin on here?

If you can provide a more complete example of your setup, that might be helpful in triaging this problem.

**Comment by RCL** [comment]
Thank you for the prompt reply. 

We use Compiler() to define our custom tool that compiles the shaders for a number of platforms using the compiler from their respective SDKs. ExtraFiles thus includes all the potential dependencies (not just dll, but also e.g. config files or other parts of those underlying SDKs that the tool calls into) that we wanted to be replicated to the remote FASTBuild workers, because we would like to avoid the assumption that the SDKs of the same version are installed on all workers.

From the description you provided it seems that what we're trying to achieve is impossible, at least under Windows. The dependencies can be located on different letter drives, and we were passing absolute paths to them - there's no way to provide a relative path to them in a general case. Looks like we instead should leave it to the user to make sure that the workers are running a homogeneous environment and provide messaging from the error messages when it's not the case.

Thank you!

**Comment by ffulin** [comment]
If the tools are setup in a way that requires they be located in specific absolute paths, then indeed this won't work. FASTBuild is not able to virtualize the entire filesystem this way.

I usually recommend that developers submit all of their toolchains and dependencies to source control for build-reproducibility reasons. When doing this, all paths can be relative to the depot/branch root, which then works well with distributed compilation as it's able to reproduce the same relative structure. Perhaps that could work for you in your case.

If you control the workers and can guarantee they are all setup consistently, then you can also rely on the installation as you suggested. I'd try to avoid this if possible, but it can certainly work if you are okay with the risks/tradeoffs.

**Comment by ffulin** [comment]
Based on the comments I don't think there is anything actionable remaining in this issue so I'm going to close it. We can create new issues for any bugs or enhancements that might be useful in the future.
