### ISSUE TITLE
The function max is recognized as a macro definition

### ISSUE THREAD

**Issue by yuhongchi** [fastbuild/fastbuild#839]
I defined a function
::google::protobuf::int32 max() const;
when I use unity files, it will compile with
::google::protobuf::int32 ((() > ()) ? () : ()) const;
so how do I fix this problem?

**Comment by ffulin** [comment]
This is almost certainly caused by one of your cpp files including Windows.h, which by default defines min and max macros:
```C++
#ifndef max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
#endif
```
You can avoid this behavior by defining NOMINMAX either before including Windows.h, or on the command line with -DNOMINMAX

You may have avoided this problem so far by luck.
