### ISSUE TITLE
could't hit breakpoint

### ISSUE THREAD

**Issue by yuhongchi** [fastbuild/fastbuild#841]
If I opened -dist. Static library could't hit breakpoint,only dynamic library or application can work.
how can I fix this problem?

**Comment by ffulin** [comment]
It is very likely that you don't have your command line options related to debug information setup correctly.

If you can provide some more information, such as a repro case, I might be able to help you identify the problem.

**Comment by ffulin** [comment]
I'm closing this issue due to lack of information. If you can provide some more information, I may be able to help.
