### ISSUE TITLE
Add Remote CPU to FASTBuild Report

### ISSUE THREAD

**Issue by evg656e** [fastbuild/fastbuild#844]
Now Remote CPU field is present in the summary, but missed in the HTML report, which seems inconsistent.

**Comment by evg656e** [comment]
I can provide a fix. The only question is where to add this field now? Into Overview table right after CPU Time (this could potentially break the parsing of the report for those who now rely on the order of the rows in the table)? To the end of the table (does not match the order in the summary)? Make a separate record outside the table, or even a new table (seems overkill for a single field)?

**Comment by ffulin** [comment]
I think it's ok to change the layout/formatting and style of the generated html report. It's not designed or intended to be machine readable. So I think adding it to or changing the table in a way that feels consistent with the -summary seems like a good way to go.

**Comment by ffulin** [comment]
I've integrated your improvement and this will be part of the next release (v1.06). I'll leave this issue open until that version is released. Thank you for helping to improve FASTBuild!

**Comment by ffulin** [comment]
v1.06 has now been released.
