### ISSUE TITLE
bug on FBuildCoordinator.bff about backslashes

### ISSUE THREAD

**Issue by t31k3** [fastbuild/fastbuild#862]
```
$egrep "[.]ProjectPath" $(egrep "objcopy" ../* -rI -c |grep -v :0 |tr ":" " "|awk '{print $1}')
../Code/Tools/FBuild/FBuildCoordinator/FBuildCoordinator.bff:    .ProjectPath        = 'Tools\FBuild\FBuildCoordinator'
../Code/Tools/FBuild/FBuildApp/FBuildApp.bff:    .ProjectPath        = 'Tools/FBuild/FBuildApp'
../Code/Tools/FBuild/FBuildWorker/FBuildWorker.bff:    .ProjectPath        = 'Tools/FBuild/FBuildWorker'
```
as you can see, this is a problem on linux (the paths ends like ".../ToolsFBuildFBuildCoordinator/..."), and the other 2 files are correct.
So I think this needs to be patched:
`../Code/Tools/FBuild/FBuildCoordinator/FBuildCoordinator.bff:    .ProjectPath        = 'Tools/FBuild/FBuildCoordinator'`

PS.: compiling FastBuild itself is working on ubuntu20.04: https://gist.github.com/t31k3/3a42714058e4ae6439d597937b6172a9

**Comment by ffulin** [comment]
FBuildCoordinator.bff doesn't exist in FASTBuild. Thit must be part of some other project.

**Comment by t31k3** [comment]
you are right! it is a new file created by the UnrealEngine 4.27.0 FastBuild diff patch!
thx!
