### ISSUE TITLE
Error in linux build (JSON.cpp #pragma once)

### ISSUE THREAD

**Issue by septag** [fastbuild/fastbuild#863]
I'm trying to compile the main branch on linux (clang 10.0), but I'm getting this error:

```
/home/sepul/Projects/fastbuild/Code/Tools/FBuild/FBuildCore/Helpers/JSON.cpp:3:9: error: #pragma once in main file [-Werror]
    3 | #pragma once
```

however, commenting that line solves the problem.

**Comment by ffulin** [comment]
This is unintended and has already been fixed in the dev branch. If you want to build the stable current release you can remove it s you have done. Alternatively, you can build the 'dev' branch instead.

The next release (v1.06) will of course contain this fix as well.

**Comment by ffulin** [comment]
v1.06 has now been released. The source snapshot contains this fix.
