### ISSUE TITLE
Question: How to cross-compile for arm64 raspberry PI

### ISSUE THREAD

**Issue by septag** [fastbuild/fastbuild#864]
I'm fairly new to FastBuild, and I wanted to try it out on RapberryPI devices. 
How can I cross-compile fbuild and fbuildworker for rpi4 on a linux host ?

Thanks

**Comment by ffulin** [comment]
If you have a cross-compiler that runs on Linux but can target Raspberry Pi, then you can either:
a) add a new build configuration for Raspberry Pi
b) modify the existing build configuration  to target Raspberry PI

Option b) is likely a little easier if you just want to experiment.
The main changes required are:
a) point the linux.bff at the compiler
b) modify the command line args to add the appopriate "arch" options (and any other options needed)

Depending on what is supported by the system headers, other code changes may be needed, but I would assume not much would need to change.

**Comment by ffulin** [comment]
I'm going to close this issue. Let me know if you have any follow up questions.
