### ISSUE TITLE
Different behavior btw local and dist

### ISSUE THREAD

**Issue by christophe-calmejane** [fastbuild/fastbuild#867]
Hi,

I'm facing an issue that I can't diagnose.
On a project, I've a file that compiles fine with fbuild in local mode, but as soon as I activate `-dist` it fails with a compilation warning (from the code itself, some double defined macro). The only way for this warning to pops is if compilation flags/defines are different.
I unfortunately cannot share the whole project, and couldn't reproduce with a simple test, so do you have any idea on how to debug this, or what is different when using distributed compilation?

I compared the command lines and the only difference I could spot was the last parameter:
* `/E` in distributed
* `/showIncludes` in local

This alone cannot explain the behavior difference.

Any ideas?

Compiling on windows with VS2019

**Comment by claimred** [comment]
Do you use precompiled header when compiling the file in question? Try turning them off, FASTBuild deals with pch [differently](https://github.com/fastbuild/fastbuild/issues/179#issuecomment-268305640) for local and remote tasks.

**Comment by christophe-calmejane** [comment]
No I don't.

**Comment by christophe-calmejane** [comment]
But after a few more tests (few hours actually), it looks like it might not be related to fbuild but to visual studio compiler.
If I run my command line manually in a shell, trying to compile the file, it works. If I add /E (and redirect to a file), I get the macro redefinition error... so weird!

**Comment by christophe-calmejane** [comment]
Ok I think I got it.
Take the following fbuild file (text partially removed):
```
// CMAKE generated file: DO NOT EDIT!
// Generated by "Fastbuild" Generator, CMake Version 3.20

// This file contains all the build statements

// =============================================================================
// Helper variables

.FB_INPUT_1_PLACEHOLDER = '"%1"'
.FB_INPUT_2_PLACEHOLDER = '"%2"'
.FB_INPUT_3_PLACEHOLDER = '"%3"'
// =============================================================================
// Settings

Settings
{
  .Environment = 
  {
    // ENV REMOVED FOR PRIVACY
  }
  .CachePath = 'D:\dev\3rdparty\fbuild-cmake-testcase\_build_fb\fbuild.cache'
}
// =============================================================================
// Compilers

Compiler('Compiler-CXX')
{
  .Root = 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86'
  .Executable = '$Root$/cl.exe'
  .CompilerFamily = 'msvc'
  .ExtraFiles = 
  {
    '$Root$/c1.dll',
    '$Root$/c1xx.dll',
    '$Root$/c2.dll',
    '$Root$/atlprov.dll',
    '$Root$/msobj140.dll',
    '$Root$/mspdb140.dll',
    '$Root$/mspdbcore.dll',
    '$Root$/mspdbsrv.exe',
    '$Root$/mspft140.dll',
    '$Root$/msvcp140.dll',
    '$Root$/msvcp140_atomic_wait.dll',
    '$Root$/tbbmalloc.dll',
    '$Root$/vcruntime140.dll',
    '$Root$/vcruntime140_1.dll',
    '$Root$/1033/clui.dll',
    '$Root$/1033/mspft140ui.dll'
  }
}
.Compiler_CXX = 'Compiler-CXX'
.Compiler_dummy = 'Compiler-CXX'

/////////////////////////////////////////////
// Target definition: TestWarning

{
  .TargetOutCompilePDBPath = '"D:/dev/3rdparty/fbuild-cmake-testcase/_build_fb/CMakeFiles/TestWarning.dir/TestWarning.pdb"'
  .TargetOutDir = '"CMakeFiles/TestWarning.dir"'
  .TargetOutPDBPath = '"TestWarning.pdb"'
  .TargetOutputImplib = '"TestWarning.lib"'
  ObjectList('CXX_ObjectGroup_TestWarning--1')
  {
    .Compiler = .Compiler_CXX
    .CompilerOptions = '  /nologo /TP -DNOMINMAX /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /W4 /WX -std:c++17 /Fo$FB_INPUT_2_PLACEHOLDER$ /Fd$TargetOutCompilePDBPath$ /FS -c $FB_INPUT_1_PLACEHOLDER$'
    .CompilerOutputPath = 'CMakeFiles/TestWarning.dir/'
    .CompilerOutputExtension = '.obj'
    .CompilerOutputKeepBaseExtension = true
    .CompilerInputFiles = 
    {
      '../testwarning.cpp'
    }
  }
  Executable('TestWarning')
  {
    .Linker = 'D:\dev\3rdparty\cmake\_build\bin\Release\cmake.exe'
    .LinkerOptions = ' -E vs_link_exe --intdir=$TargetOutDir$ --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests -- C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\link.exe /nologo $FB_INPUT_1_PLACEHOLDER$  /out:$FB_INPUT_2_PLACEHOLDER$ /implib:$TargetOutputImplib$ /pdb:$TargetOutPDBPath$ /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console   kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib '
    .LinkerOutput = 'TestWarning.exe'
    .Libraries = 
    {
      'CXX_ObjectGroup_TestWarning--1'
    }
    .LinkerLinkObjects = false
    .LinkerType = 'auto'
  }
}
```

And take the following source files (maybe there is no need for 2 files)

testwarning.cpp:
```
#include "testwarning.hpp"
int main()
{
	return 0;
}
```
testwarning.hpp
```
#pragma once
#pragma warning (push, 0) // disable all warnings
#define NOMINMAX
#pragma warning (pop)
```

If you compile locally, everything is OK, if you force compilation on a remote (`-forceremote`) then it fails.
For some reason, cl.exe seems to ignore pragma push macro when `/E`is used.

I don't know if there is something that can be done on fbuild side. The preprocessed file is correctly generated though, so maybe we can still send it to the remote and see if there is a compilation error?
I'll create a ticket on visual studio support.

**Comment by christophe-calmejane** [comment]
Ok, good news (sort of) : https://developercommunity.visualstudio.com/t/pragma-warningdisable-4668-not-working-when-genera/561735

So, not sure fbuild can do anything about it. If so, close this ;)

**Comment by ffulin** [comment]
As you've noted, FASTBuild utilizes the pre-processor for distributed compilation. From time to time, bugs like this one are discovered in the MSVC compiler. FASTBuild contains work-arounds for some of these bugs, but I think the nature of this bug means a work around in FASTBuild is likely impractical. (Of course if you have an idea for this I'd be open to it)

With that in mind, it looks like the options to work around this are:
a) change the source code to avoid this problem
b) disable the problematic warning on the command line (as per the issue you linked), for the library or problematic cpp files
c) disable distributed compilation for the problematic library or cpp files

I can imagine that depending on your codebase or needs, one or more (or all) of those might be impractical of course.

**Comment by christophe-calmejane** [comment]
The problematic compiler error is deep inside a 3rd party library so, yes, not an easy task :)
For my use case, I'll probably limit the warning level for this single file or something like that.
I also do agree that there is not much we can do inside fbuild (that would hurt it's capabilities or consistency), so I guess it's best to work around another way.

Since this particular MSVS issue is still not fixed, if some of you have a couple minutes to upvote the linked ticket it would help (microsoft is fixing issues based on `popularity`).

At least let's hope my report will help some other reader searching for a similar issue. I think we can close it now. Thanks a lot.
