### ISSUE TITLE
Active Code analysis

### ISSUE THREAD

**Issue by max01598** [fastbuild/fastbuild#869]
Hello, How are you ? :) 
I'm currently using Fastbuild in a professional context, and I want to enable the code analysis. Idi multiple tries but I did not succeed. Can you tell me if it's possible ?
Thank
Have a good day !

**Comment by ffulin** [comment]
Static analysis generally doesn't require anything special other than the options to enable it for your compiler (/analyze for example).

Some static analysis is incompatible with certain FASTBuild feature (for example, MSVC /analyze is incompatible with distributed compilation). FASTBuild will usually detect these cases an act accordingly.

Finally, the FASTBuild source contains an MSVC static analysis configuration that you might be able to use as a reference.

I hope that helps!

**Comment by max01598** [comment]
Thanks for your help :) 
I didn't understand this sentence : "Finally, the FASTBuild source contains an MSVC static analysis configuration that you might be able to use as a reference."
Could you tell me more ?

**Comment by ffulin** [comment]
**> "Finally, the FASTBuild source contains an MSVC static analysis configuration that you might be able to use as a reference**

If you download the source code for FASTBuild (from GitHub or https://fastbuild.org) you can example the .bff files that FASTBuild uses to compile itself. There is an MSVC Static Analysis build configuration.

**Comment by ffulin** [comment]
I'm going to close this issue as answered. Please let me know if you need some additional information.
