### ISSUE TITLE
Is it possible to disable the "preprocessor only" step and do a single-operation build (with Clang)?

### ISSUE THREAD

**Issue by jorgenpt** [fastbuild/fastbuild#872]
I was looking at the code and I couldn't figure out if there was a set of options / switches that could be used to disable the "preprocessor only" step -- we're building with Clang.

I'm interested in this because I'd like to be able to use clang's `-ftime-trace` to time the entire build, including the processing, in one operation.

Barring that, is it possible to configure options for the compiler that are *not* used in the preprocessor compile, only the final compile? `CompilerDriverBase::ProcessArg_PreprocessorOnly` seems to only strip some specific options, so there's no user control over what options are only passed to the final compile.

**Comment by ffulin** [comment]
Currently FASTBuild splits processing into two passes and this behavior is a key part of dependency extraction, distributed compilation and caching. It's therefore not currently possible to operate in a mode where those are done together.

The CompilerDriver can be used to control which arguments are used in which phase of processing. The CompilerDriverBase interface defines the optional virtual functions that each driver can use. These allow args to be stripped in various cases.

The GCC/Clang driver (CompilerDriver_GCCClang) performs such stripping in ProcessArg_PreprocessorOnly for several things. It seems reasonable to extend to this case.

**Comment by jorgenpt** [comment]
Ok! I will see if https://github.com/fastbuild/fastbuild/pull/871 gets merged, then. Thank you!
