### ISSUE TITLE
Missing csproj support?

### ISSUE THREAD

**Issue by grahamboree** [fastbuild/fastbuild#881]
I have a C# project that I'd like to integrate into an existing fastbuild workflow.  Compiling with `CSAssembly` works great but I'd also like to generate a csproj for IDE support.  Currently it seems like only vcxproj generation is supported.

For a simple hello world C# program in `Program.cs` I'd ideally like to be able to generate an appropriate csproj with something along the lines of: 
```
.Compiler = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe'

CSAssembly('hello')
{
    .CompilerOptions = '/t:exe /out:%2 %1'
    .CompilerOutput = 'bin\hello.exe'
    .CompilerInputFiles = {'Program.cs'}
}

VCSProject('hello_proj')
{
    .ProjectName = 'hello'
    .ProjectFiles = { 'Program.cs' }
    .ProjectOutput = 'hello.csproj'
    .ProjectBasePath = '.'
    .ProjectBuildCommand = 'cd ^$(SolutionDir) &amp; fbuild -ide -dist -cache ^$(ProjectName)'
}

.sourceFolder = [
    .Path = 'Source'
    .Items = { 'Program.cs' }
]

VSSolution('hello_sln') {
    .VisualStudioVersion  = '16.0.31613.86' // VS2019
    .SolutionOutput       = 'hello.sln'
    .SolutionProjects     = {'hello_proj'}
    .SolutionFolders      = { .sourceFolder }
    .SolutionBuildProject = 'hello_proj'
}

Alias('All') {
    .Targets = {'hello', 'hello_proj', 'hello_sln'}
}
```

The current workaround (as touched on [here](https://github.com/fastbuild/fastbuild/issues/290#issuecomment-337620752)) is to manually create a separate sln and csproj specifically for IDE usage.  This is quite clunky since the manually-updated sln and fastbuild CSAssembly need to both be maintained in lock-step and can get out of sync in a number of ways.  

Curious if this is on the roadmap and/or if you'd be receptive to a PR to support this?  Seems like table stakes for supporting C#.

**Comment by ffulin** [comment]
FASTBuild's support for C# is limited. FASTBuild is somewhat constrained by the limitations of Visual Studio and it's reliance on tying C# code to .csproj files for some IDE functionality (like UI editing) while tying the invoking of external build tools to "makefile" projects.

For C# projects that don't need any IDE functionality, a normal vcxproj can be used and compilation can be taken care of by CSAssembly. For things that need IDE functionality, hand authoring a csproj is usually the way to go, with the sln being configured so as to pass compilation between the two systems. It should be possible to have FASTBuild generate a sln file that works in this scenario, perhaps already or maybe with some small changes.

In terms of having FASTBuild generate csproj files, I'm not entirely sure how that would work. In your example there would now be two different ways to compile 'Program.cs'. It's unclear to me how those would interact or what the implications of that might be.

**Comment by ffulin** [comment]
Closing this as answered. Let me know if you have and follow up questions or if i have misunderstood your questions.
