### ISSUE TITLE
Host machine seen as member of the worker pool for its own builds

### ISSUE THREAD

**Issue by Auriform** [fastbuild/fastbuild#891]
Since 1.04, the hosts are  identified by their ip instead of their hostname (mentioned in #816). Before a machine starts a distributed build, it shouldn't consider itself to be part of the worker pool. However, to remove itself from the worker pool, it checks against the hostnames instead of the ips, leaving the current machine as part of the worker pool. This introduces a big performance penalty, because the machine sends requests to itself via the network interface.
In my tests, (windows only) the distributed builds were slower than the local visual studio builds.
Specifically, the problem lies in WorkerBrokerage.cpp, inside function FindWorkers, end of the function:
`if ( workerName.CompareI( m_HostName ) != 0 )` <-- should check against ip now.

**Comment by ffulin** [comment]
Thanks for reporting this. The local build should not send jobs to the worker on the same machine.

Updating the logic you mentioned to use the local IP as you've suggested would be a good fix in the very short term. In the longer term, a more complex fix might also be needed as there may be multiple IPs present in some cases and the worker may be configured in the future to use specific IPs other than the "primary" or "default" one. It might be necessary to check all local IPs for example.

**Comment by ffulin** [comment]
This issue was fixed in v1.09 (the internal logic for checking if a worker and host was corrected), but it was not closed at that time. Closing the issue as part of general issues cleanup.
