### ISSUE TITLE
sendfile will transfer at most 0x7ffff000 (2,147,479,552) bytes

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#892]
https://man7.org/linux/man-pages/man2/sendfile.2.html

sendfile() will transfer at most 0x7ffff000 (2,147,479,552)
bytes, returning the number of bytes actually transferred.  (This
is true on both 32-bit and 64-bit systems.)

The original Linux sendfile() system call was not designed to
handle large file offsets.  Consequently, Linux 2.4 added
sendfile64(), with a wider type for the offset argument.  The
glibc sendfile() wrapper function transparently deals with the
kernel differences.

Applications may wish to fall back to [read(2)](https://man7.org/linux/man-pages/man2/read.2.html)/[write(2)](https://man7.org/linux/man-pages/man2/write.2.html) in the
case where sendfile() fails with EINVAL or ENOSYS.

**Comment by Domain** [comment]
https://stackoverflow.com/questions/22373528/sendfile64-only-copy-about-2gb

**Comment by ffulin** [comment]
Thanks for closing the issue. I must have missed it in my sweep when releasing v1.06 (which contains the fix)
