### ISSUE TITLE
Proposal to create Value Types for internal data and to have a unified way to evaluate expressions

### ISSUE THREAD

**Issue by Xorcerer** [fastbuild/fastbuild#901]
### FAQ
Is this proposal going to change the behaviours on the user side?
**No.**

Does this proposal impact the performance?
**No.**

Does this proposal impact BooleanExpParser?
No, at least not for now, because they are of the different spaces.

#### 1. To remove duplicated logic
In #745, as per @ffulin
> Since FASTBuild v1.0, work has been done to make the bff parsing code easier to maintain. Part of that was to de-duplicate how values are parsed in various places, but some duplication of logic still exists. I think further consolidation of some of this code is likely required before function return values could be sensibly implemented. (An explcit "rvalues" like concept may be needed for example).

So this is a precondition for #745.

### Design

I would like to implement a value type for each data type. e.g. 
* `BFFValueInt` for Integer
* `BFFValueString` for String
* `BFFValueNilArray` for an untyped array
* `BFFValueArrayOf<String>` for ArrayOfString
* `BBFValueStruct` for Struct
* ...

All the value type are subclass of BFFValue,
and BFFVariable is merely a holder of a BFFValue
**Note:** for backward-compatible, the public methods/hehaviours of BFFVariable will stay unchanged for now

And then define operations between value types.
Note: for now, luckily, all the binary ops are left associative and equal priority
#### Option 1
```C++
// Signature
bool Eval(OpType op, const BFFValue & lhsValue, const BFFValue & rhsValue, BFFValue & outValue);
// There is a multiple dispatch happen within the `Eval()`
// The Match and Pattern are merely pesudo classes
switch (Match(op, lhsValue, rhsValue)) {
    case Pattern<OpConcat, String, String>::value:
         return EvalConcat(static_cast<const BFFValueString&>(lhsValue), static_cast<const BFFValueString&>(rhsValue), outValue);
    case Pattern<OpSubtract, String, String>::value:
        //...
    default:
        // log error
        return false;
}

// Use case.
BFFVariable var;
bool result = Eval(OpAdd, lhsValue, rhsValue, var.GetValue());
```

#### Option 2
```C++
// Signature:
bool BFFValueString::Eval(OpType op, const BFFValue rhsValue, BFFValue& outValue);
// There is a multiple dispatch happen within the `BFFValueString::Eval()`
// The Match and Pattern are merely pesudo classes
switch (Match(op, lhsValue, rhsValue)) {
    case Pattern<OpConcat, String>::value:
         return EvalConcat(static_cast<const BFFValueString&>(rhsValue), outValue); // It is safe to use static_cast<> here.
    case Pattern<OpSubtract, String>::value:
        //...
    default:
        // log error
        return false;
}

// Use case.
BFFVariable rhsVar;
BFFVariable var;
bool result = lhsValue.Eval(OpAdd, rhsVar.GetValue(), var.GetValue());
```

**Comment by Xorcerer** [comment]
A patch with all the tests parsed under Linux build.
[#Xorcerer/fastbuild/branches/add-value-types-to-parser](https://github.com/Xorcerer/fastbuild/tree/add-value-types-to-parser)

**Comment by Xorcerer** [comment]
# Comparison of mplementations in abstract

## Data Structure
### Before
`BFFVariable` holds all kinds of values directly.
### After
`BFFVariable` holds an instance of `BFFValue`
* BFFValueOfBool
* BFFValueOfInt
* BFFValueOfString
* BFFValueOfStruct
* BFFValueOfArrayOfStrings
* BFFValueOfArrayOfStructs

## Calculation
### Before
Raw values (ints, bools, arrays, and etc.) are calculated in multiple places, the processes are not consistence. 

### After
All operations between two value objects (`BFFVariables` and `BFFValue`) are defined and unified in one place.
e.g. for <Array of Strings> + <String>
1. There is a `BFFValueOfArrayOfStrings`, a `BFFValueOfString` and an operator `+` (Concatenation).
2. Look up the definition of the process with all the three factors.
3. Treat the `BFFValueOfArrayOfStrings` and the `BFFValueOfString` as immutable and get the result.
4. Pass the result to the caller.
https://github.com/Xorcerer/fastbuild/blob/8a579158e84437df0ebaa6ce2339753265febf6c/Code/Tools/FBuild/FBuildCore/BFF/BFFValue.cpp#L370
```C++
        // Inside the virtual method of BFFValueOfArrayOfStrings.
        // .ArrayOfStrings + "String1"
        case Pattern<BFFValueOperators::CONCATENATION, BFFValueOfString>():
        {
            StackArray<AString> finalValues;
            finalValues.SetCapacity( Get().GetSize() + 1 );
            finalValues = Get();
            finalValues.Append( GetValue<BFFValueOfString>( rhsValue ) );
            outValue = FNEW( BFFValueOfArrayOfStrings( finalValues ) );
            return true;
        }
```

## Example: For concatenation of `Array<AString>`s
## Before
1. create an `Array<String>`
2. add the elements of the left-hand side array, 
3. then add the elements on the right-hand side while parsing the tokens.

## After
1. Gets the `BFFValue` instance for the left-hand side array
2. Parses and creates a `BFFValue` instance for the right-hand side array.
3. Join two instances together through the unified process.

**Comment by Xorcerer** [comment]
Still working on more tests before the PR.

**Comment by Xorcerer** [comment]
I am thinking of adding some `.natvis` files for those value types.

**Comment by ffulin** [comment]
Thanks for your detailed thoughts.

The parsing code and related structures (BFFVariable etc) are a core part of FASTBuild and need to be modified very carefully. A large change to all parsing is unlikely to be accepted due to the difficulty in testing and the risk it brings.

As you pointed out, some operations on variables are still handled inconsistently and there is value in fixing that before adding more features to the code. I'd recommend small targeted improvements towards this end that can be easily integrated and tested with reduced risk. I think it's possible to transform the code slowly this way.

Additionally, I think the changes you mention to the BFFVariable are not necessary for such a change but are a separate body of work. Trading the "union" current implementation for a virtual one is likely to have some tradeoffs that will impact performance (perhaps positively or negatively in different scenarios). I'd suggest the slow consolidation of functionality be done without significantly changing the BFFVariable class in the short term.

Finally, I'd like to caution against heavy use of templates in any changes. Templates are avoided in the codebase except where essential. I don't think their use is critical to what you've described.

**Comment by Xorcerer** [comment]
Thank you for the reply in such detail.

Let me start over in small steps.

There are six types in the code.

* Bool
* Int
* String
* Struct
* ArrayOfStrings
* ArrayOfStructs

I would like to start with `Bool` and `Int`. e.g. Booleans are calculated in three places.
* `BFFParser::ParseNamedVariableDeclaration`, an assignment.
* `BFFParser::StoreVariableToVariable`, an assignment
* `BFFVariable::CancatVars`, an OR within a concatenation of two structs

If you like the approach in the first PR, I will apply it to all the data structures.

**Comment by ffulin** [comment]
As per previous comments, there is value in targeted fixes to reduce special cases in the expression evaluation logic, but a large overhaul doesn't seem necessary. I'm going to close this issue for now. Other changes and improvements can be discussed/evaluated as needed in the future.
