### ISSUE TITLE
How to use Fast build in Mac OS

### ISSUE THREAD

**Issue by jungsic1023** [fastbuild/fastbuild#903]
I downloaded the OS X file But cannot open FBuild file in OSX-x64 folder.

error -> File cannot open. File is not UTF-8 Text Encoding ~~Blah Blah

How do I open it?
Then how do I set it up?

**Comment by ffulin** [comment]
Given the provided information, this question has been answered as best as possible. Please let me know if you have any clarifying questions and we can re-open if necessary.
