### ISSUE TITLE
Adding structs containing arrays of structs

### ISSUE THREAD

**Issue by aponomarev1408** [fastbuild/fastbuild#904]
FASTBuild emmits error when adding structs where one of the structs contains empty array and another one contains an array of structs.

Code to reproduce:
```
.SomeStruct = []

.Foo = 
[
	.Array = {}
]
.Bar = 
[
	.Array = { .SomeStruct }
]

.Result = .Bar + .Foo
```

Error:
```
FASTBuild Error #1034 - Operation not supported: 'ArrayOfStructs' + 'ArrayOfStrings'.
.Result = .Bar + .Foo
               ^
               \--here
```

Tested on Windows with FASTBuild v1.06

**Comment by ffulin** [comment]
This issue was fixed in v1.09 but this bug slipped through and wasn't closed when that was released.
