### ISSUE TITLE
Potential infinite loop in fbuildworker linux version

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#907]
My fbuildworker just run >100% CPU forever. No build is running.
Maybe I will build a debug version to reproduce this when I have time.

**Comment by ffulin** [comment]
Is the worker actually using CPU time? Is it 100% of one core, or 100% on all cores?
What version of the FBuildWorker are you using?

**Comment by Domain** [comment]
I see it in top command. I use systemd to run it as a daemon. After several builds, it runs 100% of one core forever until I restart it.

**Comment by ffulin** [comment]
What version of the FBuildWorker are you using?

**Comment by Domain** [comment]
v1.06 with some changes. I'll investigate if it's because of this local change: 32e36d3b71fd3c1ef792356fe21b3731ef08ecd3

**Comment by ffulin** [comment]
Doesn't seem like that change could be responsible, unless there is some very weird side effect.

If you are able to obtain a callstack next time it occurs that'd be very helpful.

btw - The dev branch contains a very recent fix for a bug where the client could send corrupt data to the worker. This could result in a worker doing all manner of potentially bad things. If you haven't already, I recommend building your version against the dev branch.

**Comment by Domain** [comment]
This issue is very weird. The CPU usage is creasing slowly, from 1% to 100% in days, and never goes down. I try to debug it, and it seems just busy waiting at pthread_join. And distributed compiling is not working at all. I have attach a profile file in #887.

**Comment by ffulin** [comment]
That is very strange, but it is perhaps an interesting clue to the cause of the problem.

My best guess is that either there is a resource leak of some kind (memory or threads for example) or perhaps some unbounded growth of an internal structure causing degraded performance over time.

**Comment by Domain** [comment]
https://serverfault.com/questions/738097/high-cpu-caused-by-pthread-cond-wait-or-nanosleep
<pre>
strace: Process 334205 attached with 59 threads
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 74.66   15.783751       47256       334       170 futex
 15.34    3.242634        1636      1981           select
  8.35    1.765134       37556        47        46 restart_syscall
  1.55    0.328306         173      1893           clock_nanosleep
  0.05    0.009804        1960         5           write
  0.01    0.003112          53        58           madvise
  0.01    0.003031        3031         1           rename
  0.01    0.002214         201        11           close
  0.01    0.001483          67        22           munmap
  0.00    0.000162          13        12           lstat
  0.00    0.000062          62         1           mmap
  0.00    0.000058          58         1           openat
  0.00    0.000011          11         1           chdir
  0.00    0.000009           9         1           flock
  0.00    0.000007           7         1           fstat
  0.00    0.000007           7         1           rt_sigaction
------ ----------- ----------- --------- --------- ----------------
100.00   21.139785                  4370       216 total
</pre>

**Comment by Domain** [comment]
Upgrade to newest version, issue not found.

**Comment by ffulin** [comment]
That's great news - thanks for updating the ticket!
