### ISSUE TITLE
compile_commands.json - definitions with spaces get split and creates a strange entry

### ISSUE THREAD

**Issue by tru** [fastbuild/fastbuild#913]
If you have a define like: `/DMY_DEFINE="hello world"` and then run fastbuild with `compdb` you'll get an entry in compile_commands.json that is: 

`[..., "/DMYDEFINE=\"hello", "world\"", ...]`

This should be:

`[..., "/DMYDEFINE=\"hello world\"", ...]`

**Comment by ffulin** [comment]
This appears to be a duplicate of: https://github.com/fastbuild/fastbuild/issues/741

There are some comments on that issue explaining the complexities of this problem space.
