### ISSUE TITLE
Option to choose folder/drive that Remote Worker use when compiling

### ISSUE THREAD

**Issue by pShota** [fastbuild/fastbuild#917]
Hi there,

the speed of distributed compilation is awesome, but we can only deploy FBuildWorker.exe on some special machines with limited storage on C drive,  It would be nice to have an option/setting to change the copy files location.

Thank you
Philip

**Comment by ffulin** [comment]
The worker uses disk storage for:
* synchronizing the toolchain/compiler. These can accumulate over time currently if you change the compiler a lot.
* writing temp files and compiler output. These are deleted as soon as they are no longer needed.

The overall usage should be relatively small (usually a few GiB only), but if you are *very* constrained, for space, or have some unusual usage patterns, you should be able to control the location of these files by setting the [FASTBUILD_TEMP_PATH ](https://fastbuild.org/docs/environmentvariables.html#FASTBUILD_TEMP_PATH) environment variable.

Would that be usable in your situation?

**Comment by pShota** [comment]
yes, the machines we using have very little space.
I will try that later on, thanks for reply!

**Comment by pShota** [comment]
I use that variable and successfully moved the fastbuild temp folder to another drive, I close this ticket now thank you.
