### ISSUE TITLE
Can connect to worker but fbuild reports 'cannot create child process' for all remote compiles

### ISSUE THREAD

**Issue by cosmoselodie** [fastbuild/fastbuild#924]
hey, i'm trying to use fastbuild in unreal engine 4.27.2.  it looks like my remote worker is seeing the connection just fine.  Like when i try to build, I see the worker UI say "1 connection", and it seems like both machines can write/read from the broker directory just fine.

  When i go and build, every object that gets farmed to the worker dies like this:

Failed to build Object. Error: 4294967295 (0xffffffff) Target: 'C:\Users\carl\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1008\Module.ElodieApplicationState.gen.cpp.obj'
Got Result: Filmacom2000 - C:\dev\mainbb\Blueberry\Game\Plugins\ElodieApplicationState\Intermediate\Build\Win64\UE4Editor\Development\ElodieApplicationState\Module.ElodieApplicationState.cpp.obj
PROBLEM: C:\dev\mainbb\Blueberry\Game\Plugins\ElodieApplicationState\Intermediate\Build\Win64\UE4Editor\Development\ElodieApplicationState\Module.ElodieApplicationState.cpp.obj
PROBLEM: C:\Users\carl\AppData\Local\Temp\.fbuild.tmp\0x00000000\core_1002\Module.ElodieApplicationState.cpp.obj
ERROR: Unable to create child process

This excerpt has -distverbose -verbose on.  There's more logs but they don't look relevant to the issue (like lots of /I arguments)  Every other file that fail pretty much looks this coupled with the

I'm currently working with FASTBuild 0.99 (i believe this is the version that ships with unreal, it's what's in our tree anyway).  On the remote workstation i downloaded the x64 fastbuild 0.99 and ran the worker.  In my case both of my workers are windows 10 machines.

I've googled for a couple hours and scoured the website.  I don't know what I'm doing wrong.  Any help is appreciated.

**Comment by cosmoselodie** [comment]
ah ha - i figured it out.  We're using unreal and unreal requires a forked fastbuild (or it did as of 0.99).  I was trying to use a non-forked 0.99 build from your website and that naturally wasn't playing well with the alternative fastbuild in our tree.  I didn't set that up so i didn't know.  okay, nothing to see here - thanks all!

**Comment by ffulin** [comment]
Thanks for posting the update/solution to your problem to potentially help others.
It's a bit of a shame the Unreal integration is using an almost 3 year old version - it's missing many optimizations and bug fixes.
