### ISSUE TITLE
Compiling Linux Kernel using FastBuild

### ISSUE THREAD

**Issue by mikejack07** [fastbuild/fastbuild#930]
Hi,
I have a a project that is somewhat similar to Linux source code. It has a MakeFile that handles the configuration and compilation part similar to Linux source code. I want to use FastBuild to distribute the build of my project and hence first trying to compile Linux source code using FastBuild. My fbuild.bff file looks like this:

Exec('lin')
{
    .ExecExecutable = 'C:\Users\Mkj\linux-5.19.8'
    .ExecOutput='C:\Users\Mkj\LinC\libr.o'
    .ExecArguments= '-C lin'
}

Alias('all'){
    .Targets={ 'lin' }
}

However, there is an error on running FBuild.exe, which says:

C:\Users\Mkj>FBuild.exe
BFF file 'C:\Users\Mkj\fbuild.bff' has changed (reparsing will occur).
2> Run: C:\Users\Mkj\LinC\libr.o
2> Failed to spawn process for 'C:\Users\Mkj\LinC\libr.o'
FBuild: Error: BUILD FAILED: all
Time: 0.007s

All file locations are set correctly and FastBuild works perfectly fine for demo projects that I have built to have an experience of how things work in FastBuild.

Can anyone help me out by guiding me on how to just compile Linux source code by using the Linux built-in make file in FastBuild?
Thanks.

**Comment by ffulin** [comment]
Compiling the Linux Kernel from source using FASTBuild will require you write new FASTBuild config files (.bff files) to replace the makefiles.

You could have FASTBuild invoke make, but they wouldn't really achieve anything - i.e. you won't benefit from any features that FASTBuild brings to the table.

**Comment by mikejack07** [comment]
Thanks for the help!
