### ISSUE TITLE
Using FastBuild with Makefile

### ISSUE THREAD

**Issue by mikejack07** [fastbuild/fastbuild#931]
I have started using FastBuild for distributed building of my projects. I have created a demo project that that has a directory dir and inside that directory I have these files: main.cpp, header.h, header.cpp, Makefile, fbuild.bff.

Makefile contains the following code:
output: main.o h1.o
	     g++ main.o h1.o -o output

main.o: main.cpp
	      g++ -c main.cpp

h1.o: h1.cpp h1.h
	g++ -c h1.cpp

clean:
	rm *.o output

What I want to do is that I want to go into the directory and run FBuild.exe in the command prompt. I want FastBuild to then follow the configurations written into the Makefile and execute accordingly. How should I configure fbuild.bff in that case?

**Comment by ffulin** [comment]
FASTBuild is a replacement for make. J just as make has its own custom config files (makefiles) FASTBuild has bff files.
To build a project using FASTBuild requires that you create bff files to replace the makefiles.

FASTBuild cannot parse or understand makefiles.

You could have FASTBuild invoke make, but that wouldn't really achieve anything: You benefit from any of FASTBuild's features.

**Comment by mikejack07** [comment]
Thanks for the help!
