### ISSUE TITLE
Does It allowed To Keep .Libraries Set Empty In Executable() Function?

### ISSUE THREAD

**Issue by sergegers** [fastbuild/fastbuild#935]
The folowing code compilation failed: 
`    Executable( '$ProjectName$-$ExeSuffix$-$Config$' )
    {
        .LinkerOutput              = "$CurrentPath$/Out/$Config$/$ProjectName$.exe"
        .CompilerOptions        = '%1 $CommonCompilerOptions$ /Fo"%2"'
	                                   + .BaseIncludePaths
                                           + .Definitions
        .Libraries                     = {}
   
}
`
`Empty string not allowed for property 'Libraries'.
    Executable( '$ProjectName$-$ExeSuffix$-$Config$' )
    ^
    \--here`

Does empty library  set forbidden for executable compilation?

**Comment by ffulin** [comment]
You cannot create an executable without specifying some object files or libraries. These are specified via the .Libraries option.

In your example above, the .CompilerOptions doesn't do anything as Executable doesn't accept .CompilerOptions. .CompilerOptions is a property of ObjectList or Library.

**Comment by sergegers** [comment]
Thank you for clarifying. "Libraries" is embarrassing name here. 

And probably the last question. .CompilerOptions property in the functions Library(), ObjectList() has no build time substitution PCHOutputFile as we have in .PCHOptions property. I review several bff scripts from github projects using precompiled headers and there are the same pattern here: 
`.CompilerOptions  = ... /Fp"$PCHOutputFile$" ...`
Why do not to add build time substitution PCHOutputFile to .CompilerOptions? It allows to decouple compiler options and library/executable generation.

**Comment by ffulin** [comment]
> Why do not to add build time substitution PCHOutputFile to .CompilerOptions? 

No particular reason. A % substitution for this could probably be added.

**Comment by sergegers** [comment]
Ok. Thank you.

**Comment by ffulin** [comment]
Closing this thread as questions seem to be answered.
