### ISSUE TITLE
fatal error C1014: too many include files: depth = 1024

### ISSUE THREAD

**Issue by sergegers** [fastbuild/fastbuild#939]
Looks like a bug. During jumbo build if continue a build after fixing code or build with key  **-clean** there is an error message:
> fatal error C1014: too many include files: depth = 1024

The cleaning intermediate and output files and full solution build is working fine.

**Comment by ffulin** [comment]
This is not a known general problem and is very likely something specific to your setup or codebase.

I can think of two possible reasons something like this might occur:
a) you have some cyclic dependencies, that for some reason are usually hidden but not when compiling a certain way
b) you are emitting the generated Unity files into the source folder of your code which is then feeding them back into themselves

To debug this issue, when you encounter the problem:
a) build from the command line with -showcmds
b) take the command shown and add /showIncludes (of if multiple passes are invoked and one has /showIncludes already, use that)

This should highlight where the bad include recursion is occurring.

**Comment by sergegers** [comment]
Yes, there was a unity file on the input path. Thank you for clarification.

**Comment by ffulin** [comment]
Conceivably something like this could be detected at bff parse time, but it could be tricky to allow for desirable edge-cases.

In any case, I'm glad you solved the problem. I'll close this issue as resolved in that case.
