### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by kovarex** [fastbuild/fastbuild#94]
Is there a plan to support modules?
It seems to be working in visual studio (I don't know about other platforms).

https://blogs.msdn.microsoft.com/vcblog/2015/12/03/c-modules-in-vs-2015-update-1/

**Comment by ffulin** [comment]
Hello

There are no specific plans to support modules at this time, though I'd certainly be interested to see how this space plays out and what potential impacts it might have on build performance.

Looking at the link you sent, it seems that it might be possible to use right now without any changes to FASTBuild, simply by specifying the correct command line options. Depending on how cumbersome that ends up being, in the future, it might be beneficial to have some of the work done automatically by FASTBuild. As the options appear somewhat experimental (and subject to change) it'd be worth waiting for that to stabilize before adding any dedicated functionality.

**Comment by claimred** [comment]
Looks like C++20 modules are here, shipped in VS2022.
https://devblogs.microsoft.com/cppblog/using-cpp-modules-in-msvc-from-the-command-line-part-1/

Wondering what could it mean for FASTBuild users. 🤔

**Comment by kovarex** [comment]
I meanly wonder what it means when it comes to build times. Potentially, this should be a dealbreaker, making the compilation times way faster, but the current implementations are not done properly, as they can be even slower, or faster just in specific scenarios.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1441r1.pdf

I wonder if they are approaching the order of magnitude compilation time speedup of modules we are expecting to have eventually.

**Comment by claimred** [comment]
Some discussion going on on C++ tooling study group mailing list about modules and build systems.

https://lists.isocpp.org/sg15/2022/03/1255.php
