### ISSUE TITLE
VCXProject .ProjectInputPaths always recursive

### ISSUE THREAD

**Issue by to01z** [fastbuild/fastbuild#948]
The current behavior of `.ProjectInputPaths` is to add files recursively to the generated project. While it is possible to exclude known files and subdirectories using the `.ProjectInputPathsExclude`/ `.ProjectPatternToExclude` properties, it isn't possible to add only files from the dir specified in `.ProjectInputPaths` and certain subdirectories thereof.

To narrow down what ends up in the project, it may be preferable to specify `.ProjectInputPaths` without recursion. This could be done using a new boolean property called `.ProjectInputPathsRecurse` in the VCXProject (similar behavior to the `.CompilerInputPathRecurse` property that exists for obj list, lib and unity targets).

 /to01z

**Comment by ffulin** [comment]
This seems like pretty reasonable addition of functionality and would make things consistent with other things that obtain directory listings.

Implementation would be pretty simple:
 - expose the boolean
 - utilize it when adding the directory listing dependency
 - update docs and add coverage test

**Comment by to01z** [comment]
I have an implementation of this work. PR incoming shortly.

**Comment by ffulin** [comment]
v1.09 has been released and includes this enhancement. Thanks for the improvement!
