### ISSUE TITLE
Performance regression in v1.08

### ISSUE THREAD

**Issue by stan680** [fastbuild/fastbuild#949]
Hi! Thanks for fastbuild!
I've noticed a regression in the speed of my no-op builds since upgrading to 1.08.
From about 0.008s to about 0.032s

My bff is structured very similarly to fastbuild's (just with fewer includes).
This isn't an issue for me as these numbers are so low but thought it might be worth flagging as 1.08's changelog suggests it should improve performance.

**Comment by ffulin** [comment]
The improvements for relatively simple build configs (like FASTBuilds) were negligible (saving only a millisecond or so), but for more complex setups, a hundred ms or so has been seen.

I'm a little surprised you've seen a regression in your case. As you noted, it's very small so nothing to be alarmed about, but it could be interesting to understand why this hapenned in case it's indicative of an increase that might grow to larger increases in more complex cases.

If you want to pursue this a bit further, you could built the Profile config from source and compare the profiling output between the two.

A couple of interesting notes:

Note that the optimizations in v1.08 were not OS but were mostly done on Windows.

**Comment by stan680** [comment]
Hey.

I was able to track this down in a profile build. Turns out `FBuildOptions::FBuildOptions()` was taking > 20ms. Which was all due to calls to `SHGetFileInfoA()` in `FileIO::NormalizeWindowsPathCasing()`- Looks like the call to `SHGetFileInfoA()` was removed in https://github.com/fastbuild/fastbuild/commit/b8378b4f9535960f78686c05eea60995c5e96139 and indeed I'm not seeing the slowdown when building latest on the dev branch.

So looks like this is already fixed in the next version :)

**Comment by ffulin** [comment]
Thanks for looking into it. I'm a little surprised that function could be so expensive, but then again not so surprised :)
In any case, as you say it was removed anyway (to fix an unrelated issue it caused) so the fix for your regression will be in the next release (v1.09)

I'll leave this issue open until that version is released.

**Comment by ffulin** [comment]
v1.09 has been released and includes the fix for this issue. Thanks for your help resolving it!
