### ISSUE TITLE
Scheduling Jobs On Local Host FBWorker 

### ISSUE THREAD

**Issue by sergegers** [fastbuild/fastbuild#954]
Under distributed compilation sometimes jobs are scheduling on local FBuildWorker. Below is the part of compilation output:
> >8> Uni: win32_user-Unity-ReleaseWithDebugInfo
1>8> Uni: parser_dll-Unity-ReleaseWithDebugInfo
1>8> Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_10.obj
1>-> Obj: D:\cht\source\ida\parser\rtti\out\ReleaseWithDebugInfo\Obj\rtti_unity_6.obj <REMOTE: 192.168.1.243>
1>28>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_1.obj
1>-> Obj: D:\cht\source\ida\parser\rtti\out\ReleaseWithDebugInfo\Obj\rtti_unity_5.obj <REMOTE: 192.168.1.243>
1>25>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_3.obj
1>24>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_9.obj
1>-> Obj: D:\cht\source\ida\parser\rtti\out\ReleaseWithDebugInfo\Obj\rtti_unity_1.obj <REMOTE: 192.168.1.50>
1>-> Obj: D:\cht\source\ida\dbg_shared\out\ReleaseWithDebugInfo\Obj\dbg_shared_unity_1.obj <REMOTE: 192.168.1.50>
1>9> Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_4.obj
1>31>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_2.obj
1>-> Obj: D:\cht\source\ida\test\rtti\out\ReleaseWithDebugInfo\Obj\test_rtti_test_main_unity.obj <REMOTE: 192.168.1.50>
1>1> Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_5.obj
1>-> Obj: D:\cht\source\ida\test\tutils\out\ReleaseWithDebugInfo\Obj\ida_tutils_unity_10.obj <REMOTE: 192.168.1.50>
1>-> Obj: D:\cht\source\ida\test\cmd\out\ReleaseWithDebugInfo\Obj\test_cmd_test_main_unity.obj <REMOTE: 192.168.1.50>
1>18>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_11.obj
1>-> Obj: D:\cht\source\ida\parser\cmd\out\ReleaseWithDebugInfo\Obj\cmd_unity_7.obj <REMOTE: 192.168.1.50>
1>7> Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_8.obj
1>-> Obj: D:\cht\source\ida\test\tutils\out\ReleaseWithDebugInfo\Obj\ida_tutils_unity_11.obj <REMOTE: 192.168.1.50>
1>23>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_7.obj
1>-> Obj: D:\cht\source\ida\model\log\out\ReleaseWithDebugInfo\Obj\log_unity_2.obj <REMOTE: 192.168.1.50>
1>29>Obj: D:\cht\source\ida\parser\dll\out\ReleaseWithDebugInfo\Obj\parser_dll_unity_6.obj
1>-> Obj: D:\cht\source\ida\parser\rtti\out\ReleaseWithDebugInfo\Obj\rtti_unity_7.obj <REMOTE: 192.168.1.243>
1>16>Obj: D:\cht\source\libs\other\idasdk\dbg\out\ReleaseWithDebugInfo\Obj\win32_user_unity_1.obj
1>-> Obj: D:\cht\source\cmn\shared\out\ReleaseWithDebugInfo\Obj\shared_unity_1.obj <REMOTE: 192.168.1.50>

where 192.168.1.243 is localhost IP.

**Comment by ffulin** [comment]
If using a network share as a brokerage location for worker discovery, any workers discovered that match the host IP will be ignored. This should avoid the case you mention unless there is some edge-case with multiple network interfaces perhaps.

Alternatively, if you are using the .Workers option in Environment() to explicitly list the workers, this is used as-is and allows a machine to connect to itself. The logic here is that if you have explicitly listed the worker, you've done so on purpose (and using the same machine can be useful for testing for example)

How have you setup your worker discovery?

**Comment by sergegers** [comment]
I'm using the network share on the remote host and the local FBuildWorker is started occasionally. It occurs rarely may be one build from 20. There is no distribution presets in the script.

**Comment by ffulin** [comment]
I've submitted a change which makes local addresses be filtered from the workers list retrieved from the brokerage: https://github.com/fastbuild/fastbuild/commit/8b49f87bda0044d1fd5d32805190d31f9ec39ab7

This fix will be in the next release (v1.09). I'll keep this issue open until that version is released.

Thanks for reporting this issue!

**Comment by sergegers** [comment]
Thank you.

**Comment by ffulin** [comment]
v1.09 has been released and includes the fix for this issue. Thanks again for reporting it!
