### ISSUE TITLE
Failed to build Object. error : 4294967295 (0xffffffff)

### ISSUE THREAD

**Issue by PeloGetan** [fastbuild/fastbuild#958]
Every time I build a UnrealEngine project I get this error at a random time:
```
1>EXEC : 8> Failed to build Object. error : 4294967295 (0xffffffff) Target: 'C:\work\MyUnrealProject\Intermediate\Build\Win64\UE4Editor\Development\MyUnrealProject\Module.MyUnrealProject.gen.14_of_19.cpp.obj'
1>8> PROBLEM: C:\work\MyUnrealProject\Intermediate\Build\Win64\UE4Editor\Development\MyUnrealProject\Module.MyUnrealProject.gen.14_of_19.cpp.obj
1>EXEC : warning : Unknown argument '@C:\Users\user\AppData\Local\Temp\.fbuild.tmp\0x6866f3b4\core_8\args.rsp'
1>EXEC : error : No output file name was specified! ("C:\work\ueditor\UnrealEngine\Engine\Build\Windows\cl-filter\cl-filter.exe" @"C:\Users\user\AppData\Local\Temp\.fbuild.tmp\0x6866f3b4\core_8\args.rsp")
1>Usage: cl-filter.exe -dependencies=<dependencies-file> -compiler=<compiler-file> [Optional Args] -- <child command line>
```
This happens both when building locally using FASTBuild and when building over a network with other computers.
Used different versions of the program, from 0.99 to 1.08. The error has always been.
There can be one or more such errors.

**Comment by ffulin** [comment]
It looks like whatever you are spawning (the Unreal compiler wrapper by the looks of things) doesn't support response files or at least is not command line compatible with MSVC cl.exe:
```
Unknown argument '@C:\Users\user\AppData\Local\Temp\.fbuild.tmp\0x6866f3b4\core_8\args.rsp'
```

Response files are used when the compiler command line length exceeds the OS limit for args. MVCS's cl.exe compiler supports these args and a wrapper around it should also.

You should be able to run your build with -verbose to see the command line length to see if the problems correlate with exceeding the OS limit of ~32KiB.

Assuming the above is correct, options for fixing or working around this problem include:
a) fixing/modifying filter-cl.exe to transparently accept response files
b) modifying FASTBuild to have explicit knowledge of the behavior of filter-cl.exe and baheving differently (passing some arg directly and only others through response files for example) if that's needed
c) reducing the amount of includes, defines and other parameters in your project that contribute to command line length
d) placing your project in a more shallow or shorter root path to shorten the contribution of include paths to the command line length
