### ISSUE TITLE
0 workers in payload

### ISSUE THREAD

**Issue by juaxix** [fastbuild/fastbuild#965]
Hello, I am trying to use FastBuild with Unreal 5.1. I did the modifications to work with the engine and everything seems to work, except for the workers connection.
I have a shared folder in the network, 3 machines, they create the machine-names files in the `FastBuild\Brokerage` directory, the coordinator is running in the server , the workers in the three machines, but 0 connections. when I start the build, this is the log:
```
2>BFF file 'X:\UDK\UE_5.1\Engine\Intermediate\Build\fbuild.bff' has changed (reparsing will occur).
2>Using coordinator
2>Connected to the coordinator
2>Requesting worker list
2>OnConnected 192.168.1.58
2>Process ( MsgWorkerList )
2>0 workers in payload
2>Disconnected from the coordinator
2>Worker list received: 0 workers
2>No workers received from coordinator
2>No workers available - Distributed compilation disabled
``` 
and in the machine , the coordinator receives this:
```
FBuildCoordinator - v0.99
Listening on port 31392
OnConnected 192.168.1.200
Process ( MsgRequestWorkerList )
```
that means that there is communication , the firewall are correctly configured but somehow the workers can't connect (windows titles of the workers shows 0 connections all the time). Maybe it's because the names used for the files generated in the shared Brokerage path are wrong? they are machine names, if I ping them, I get an IP so I don't know...
Thanks!

**Comment by ffulin** [comment]
FBuildCoordinator is not part of FASTBuild, so you'd need to ask the author of that for assistance.

Looking at your logs it seems the problem is that your FBuildCoordinator is saying there are no workers.

**Comment by juaxix** [comment]
Found out in the code that the FBuildCoordinator is looking for an environment variable named `FASTBUILD_COORDINATOR` with the network name (or IP) of the coordinator machine (the one running the _FBuildCoordinator.exe_). It connects now but I'm still having issues with the distribution as I don't see any objects being sent to the available workers even if I can see a connection in them.

**Comment by ffulin** [comment]
You may be able to use -distverbose and -profile to get an understanding of what's going on. Make sure you are running a recent version of FASTBuild if possible.

**Comment by juaxix** [comment]
Latest integration of unreal engine 5.1.1 fixes the issues, it distributes the build processes now, but it is taking a lot of time for the game part, any way I can tell to build more in the agents than in local?

**Comment by ffulin** [comment]
FASTBuild always prioritizes remote work when running in distributed mode so there is no command line option to do that.

The most common bottlenecks for distributed compilation include:
 - host PC not fast enough to feed workers
 - slow or unreliable network (at least 1Gbps wired network is recommended, esp for Unreal) 
 - undistributable work. Some command line options inhibit distribution (see https://fastbuild.org/docs/features/distribution.html) 
 
If you can use a recent version of FASTBuild, preferable v1.08, and run with -distverbose and -profile you can gather some information that might be helpful in understanding what your bottleneck is.

**Comment by juaxix** [comment]
if you have a good internal network speed, what would be better, having a shared folder for the cache or individual local folders?

**Comment by ffulin** [comment]
**> having a shared folder for the cache or individual local folders?**

The cache is primarily designed to share objects between machines, so putting the folder on a network share is the normal/expected use-case.

Having a local folder is not usually useful and would often make things slower.
