### ISSUE TITLE
How does the fastbuild continue when one target failed?

### ISSUE THREAD

**Issue by pkxpp** [fastbuild/fastbuild#967]
This is my fbuild.bff

```
Compiler('Compiler')
{
	.CompilerFamily = 'custom'
	.Executable = '$ClientDir$\Compiler.exe'
	.SimpleDistributionMode = true
}
ObjectList( 'List' )
{
	.Compiler='Compiler'
	.CompilerInputPath  = 'Input'
	.CompilerOutputPath = 'Output'
}
Compiler('CompilerPost')
{
	.CompilerFamily = 'custom'
	.Executable = '$ClientDir$\bin64\Compiler.exe'
}

ObjectList( 'ListPost' )
{
	.Compiler='CompilerPost'
	.CompilerInputPath  = 'Input'
	.CompilerOutputPath = 'Output'
	.CompilerOptions + ' -Post'
	.PreBuildDependencies = 'List'
}
Alias( 'all' ) {
	.Targets = { 'List', 'ListPost'}
}
```

when I do: FBuild.exe -clean -nostoponerror
ObjectList( 'List' ) will execute and process all files, even with errors.  Because used -nostoponerror
But ObjectList( 'ListPost' ) will not execute.Because .PreBuildDependencies = 'List'?
How can I make ObjectList( 'ListPost' ) execute when ObjectList( 'List' ) has erros?

**Comment by ffulin** [comment]
By default, FASTBuild will stop building as soon as any error is encountered. -nostoponerror allows it to instead continue to build as much as possible before stopping.

However, if task A depends on a task B that fails, then task A cannot be built no matter what.

In your example, you've made ListPost depend on List, so if List fails, ListPost cannot be executed.

**Comment by ffulin** [comment]
Closing as answered. Let me know if you have any followup questions.
