### ISSUE TITLE
FBuildWorker has MemoryLeak in macos,when link the large Library

### ISSUE THREAD

**Issue by leinlin** [fastbuild/fastbuild#969]
![image](https://user-images.githubusercontent.com/30318270/231643311-bb94c2cc-b7ac-408b-9580-6116b7e41c64.png)

**Comment by leinlin** [comment]
version is v1.07

**Comment by ffulin** [comment]
The FBuildWorker doesn't link libraries, only FBuild does that.  If there is a memory leak, it would have to be the result of something other that linking a large library.

Does this problem occur with the most recent version (v1.09)?

Are you able to provide any more information or a repro case? Does the leak happen slowly over time, or is it a large jump after performing a specific type of operation?

**Comment by ffulin** [comment]
There isn't enough information in this issue to investigate this problem, so I'm going to close it.

If you have some new information (such as information about requested previously) we can gladly re-open and try to investigate.
