### ISSUE TITLE
file_exists does not expand variables correctly

### ISSUE THREAD

**Issue by MikeO-8thLight** [fastbuild/fastbuild#974]
Using a variable within `file_exists` does not get expanded and returns FALSE when tested. Using plaintext works fine.

Test script as follows:

```
// Testing file_exists from an expanded variable
.TEST_VAR='./Folder'

Print("Searching for $TEST_VAR$/file.txt")
#if file_exists("$TEST_VAR$/file.txt")
  Print("Found it")
#else
  Print("Not found")
#endif

Print("Testing plain text for ./Folder/file.txt")
#if file_exists("./Folder/file.txt")
  Print("Found it")
#else
  Print("Not found")
#endif
```

## Versions
- FASTBuild: v1.09
- Affected OS: MacOS & Windows 11

**Comment by ffulin** [comment]
Variables cannot be used within preprocessor directives (just like C/C++ etc).

The preprocessor language in FASTBuild is quite rudimentary. In the future it's likely that either:
a) more functionality will be extended (allowing #define directives to define values that can then be used later in a similar way to how you've tried to use the TEST_VAR variable)
OR
b) functionality like file_exists will have an IfFileExists equivalent added so it can be used in the way you've attempted. (Conceivably this might eventually result in the removal of the preprocessor entirely)

The exact direction is undecided at this point..

**Comment by MikeO-8thLight** [comment]
Good to note - thank you.

**Comment by ffulin** [comment]
I'll close this as resolved, but please let me know if you have any followup questions.
