### ISSUE TITLE
PCH files and cache

### ISSUE THREAD

**Issue by zedmilner** [fastbuild/fastbuild#978]
When using the Fastbuild cache for PCH files with relative paths, it is possible to get a PCH from the cache that doesn't work, if there are .h files included that don't have the old style #ifndef include guards, only #pragma once.

This is because the compiled PCH file stores the full path of the .h files included, and if the PCH in the cache was built from let's say a different drive, it will still be a cache hit and we end up getting duplicate symbol declaration compile errors because #pragma once won't correctly prevent the same .h file from being included.

One idea we had to get around this was to set .AllowCaching to false for the ObjectList that generates the PCH file, but leave it default true for the other cpp files that are using the PCH. The expected outcome was that the PCH files would always be build locally (ie. never pulled from the cache), so the full paths of the included .h files would always match the local paths, and then the rest of the cpp files could come from the cache. 

But it seems that when the cache is turned off for the PCH file, it is also turned off for all other cpp files that depend on this PCH file. See
```

bool ObjectNode::ShouldUseCache() const
{
    bool useCache = IsCacheable() &&
                    m_AllowCaching &&
                    ( FBuild::Get().GetOptions().m_UseCacheRead ||
                     FBuild::Get().GetOptions().m_UseCacheWrite );
    if ( IsIsolatedFromUnity() )
    {
        // disable caching for locally modified files (since they will rarely if ever get a hit)
        useCache = false;
    }
    if ( IsMSVC() && IsUsingPCH() )
    {
        // If the PCH is not in the cache, then no point looking there
        // for objects and also no point storing them
        if ( GetPrecompiledHeader()->m_PCHCacheKey == 0 )
        {
            return false;
        }
    }
    return useCache;
}

```
I assume we never calculate the PCHCacheKey if the cache is disabled, which makes sense on its own, but prevents the above.

We could add another flag that could be set in the ObjectList that creates the PCH, to prevent the PCH from being pulled from the cache but still calculate its checksum (so .AllowCaching=true and eg. .CalculateCacheKey = true) which is a bit clunky. Or if we can query that any dependent node of the PCH does use cache, we could still calculate the PCH cache key. 

Do you think the above idea would be a good workaround to the problem, or is there a better way to solve this?
I'd be happy to implement & test any proposed code changes in our codebase, but wanted to make sure I go down a path that makes sense.

Thanks

**Comment by ffulin** [comment]
**> When using the Fastbuild cache for PCH files with relative paths,**

Some additional information about your setup would be helpful:
* What compiler are you using
* Have you opted into any experimental flags (like UseRelativePaths_Experimental)

Better still, a small repro bff would be ideal if you can provide one.

**> But it seems that when the cache is turned off for the PCH file, it is also turned off for all other cpp files that depend on this PCH file.**

PCH files using the MSVC compiler embed a guid that must match. It's not possible to build a PCH locally and then retrieve object files built against another PCH. This is why the behavior of the cache wrt PCH files and the pch key is the way it is (conceivably this behavior isn't necessary for non-Microsoft compilers)

**Do you think the above idea would be a good workaround to the problem, or is there a better way to solve this?**

I think i'd need to understand more about exactly how this problem can occur and investigate the behavior before suggesting any potential fixes.

**Comment by ffulin** [comment]
There isn't enough information in this issue to resolve the reported issue, so I'm going to close it for now. We can re-open or create a new issues as needed if/when more information is available.
