### ISSUE TITLE
Support for vcvarsall.bat?

### ISSUE THREAD

**Issue by cmdusr** [fastbuild/fastbuild#980]
My current build system on Windows runs vcvarsall.bat before issuing commands to cl.exe and link.exe

In fastbuild specifying .compiler = 'cl.exe' and .linker = ' link.exe' fails to work despite having the development environment setup by vcvarsall.bat before running fbuild.exe from cmd

Looking at the documentation and all examples of fastbuild you are required to specify the exact path to the compiler and system includes as well the windows sdk

This causes me a lot of friction when switching between computers and different versions of visual studio

How can I use fastbuild with my vcvarsall.bat environment?

If this is not presently possible could support for this please be added?

Thanks

**Comment by ffulin** [comment]
The vcvars batch files set some environment variables, one of which sets the base path to the toolchain:
```VCToolsInstallDir=C:\p4\depot\External\SDK\VisualStudio\2022\Community\VC\Tools\MSVC\14.31.31103\```

If you want to automatically use whichever version of the compiler has been set by these batch files, you can do so by importing the environment variable for the toolchain path and setting the compiler relative to that as follows:
```
#if exists( VCToolsInstallDir )
    #import VCToolsInstallDir
    .Compiler = '$VCToolsInstallDir$/bin/Hostx64/x64/cl.exe'
#else
    Error( 'VCToolsInstallDir is not set. Make sure vcvars.bat has been run' )
#endif
```

**Comment by cmdusr** [comment]
Thank you! Your code snippet solved my problem.
