### ISSUE TITLE
unable to run parallel on network shared system - used the guide but no luck

### ISSUE THREAD

**Issue by ronenya** [fastbuild/fastbuild#989]
unable to run parallel on network shared system - used the guide but no luck
we checked networking, access to shares, ...

if someone have any idea, please do share 

TX

**Comment by ffulin** [comment]
Unfortunately you haven't provided enough information here to be able to help you.

Some details such as the following would be helpful:
* the platform you are on (Windows, OSX or Linux)
* the compiler you are using (MSVC, Clang or other)
* the compiler version
* the FASTBuild version
* an example of your build configuration (your bff files)
* output and profile capture when running with -profile and -distverbose (-showcmds may also be helpful)
 
You can of course redact any sensitive information.

**Comment by ffulin** [comment]
There isn't enough information in this issue to assist any further, so I'm going to close it.

If you can provide some of the information above, we can happily re-open the ticket and try to help.
