### ISSUE TITLE
Create a target that always runs

### ISSUE THREAD

**Issue by olson-dan** [fastbuild/fastbuild#997]
Is there any way to create a target that always runs?

MSBuild can use Makefile projects to achieve this behavior.
CMake has `set_source_file_properties(targetame PROPERTIES SYMBOLIC TRUE)` to achieve it.

I'm wondering if fastbuild has a comparable way to always run a build command.

**Comment by ffulin** [comment]
Individual steps will normally only run when dependencies have changed, but Exec() (which allows for invocation of an arbitrary executable) has an ExecAlways option that can be set to force it to run every time.

If you have an entire build chain you'd like to execute whether inputs have changed or not, you can specify -clean on the command line which forces a build as if it was a "clean" build for the first time.
